/* 🌱 THE PLANT CART (v2.5) · a street vendor by Zach's house. Pick a plant, walk anywhere, plant it, water it every
   day, and watch it grow for real over the days: sprout → sapling → grown → fruit. Miss the water and it droops.
   Your plants are saved to you (profile when signed in, this device otherwise). Digital pets, but they photosynthesize. */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { M, glow, box, cyl, sph } from './aou-kit.js';
import { terrainY } from './aou-terrain.js';
const T = THREE;
const KINDS = { cactus: { n: 'Cactus', ic: '🌵', days: 4, thirst: 4, h: 1.6, col: 0x2f8f3a, fruit: 0xff4fd8, fruitN: 'pink blooms', say: 'Forgiving. Water every few days.' }, money: { n: 'Money tree', ic: '💰', days: 6, thirst: 2, h: 2.4, col: 0x3fa34d, fruit: 0xffd23f, fruitN: 'gold coins', say: 'Braided trunk, round leaves. Shakes coins when grown.' }, orange: { n: 'Orange tree', ic: '🍊', days: 7, thirst: 2, h: 3.4, col: 0x2e7d32, fruit: 0xff8a3d, fruitN: 'oranges', say: 'Fragrant. Oranges you can pick.' }, apple: { n: 'Apple tree', ic: '🍎', days: 7, thirst: 2, h: 3.6, col: 0x3b8f3f, fruit: 0xe53935, fruitN: 'apples', say: 'The classic. Pick when red.' }, lemon: { n: 'Lemon tree', ic: '🍋', days: 6, thirst: 2, h: 3.0, col: 0x43a047, fruit: 0xffeb3b, fruitN: 'lemons', say: 'Sunshine on a branch.' }, sunflower: { n: 'Sunflower', ic: '🌻', days: 3, thirst: 1, h: 2.2, col: 0x558b2f, fruit: 0xffd23f, fruitN: 'a giant bloom', say: 'Fast and tall. Turns to face the sun.' }, rose: { n: 'Rose bush', ic: '🌹', days: 4, thirst: 1, h: 1.2, col: 0x2f7a3a, fruit: 0xe91e63, fruitN: 'roses', say: 'Water daily. Worth it.' }, bamboo: { n: 'Lucky bamboo', ic: '🎋', days: 5, thirst: 3, h: 2.8, col: 0x66bb6a, fruit: 0x9ccc65, fruitN: 'new shoots', say: 'Grows a little every single day.' }, pine: { n: 'Blue spruce', ic: '🌲', days: 9, thirst: 3, h: 4.5, col: 0x3d6b6b, fruit: 0x8d6e63, fruitN: 'pinecones', say: 'Colorado\'s own. Slow and strong.' }, cherry: { n: 'Cherry blossom', ic: '🌸', days: 7, thirst: 2, h: 3.2, col: 0x5d8c3a, fruit: 0xffb7d5, fruitN: 'blossoms', say: 'Pink clouds in spring.' } };
const DAY = 86400000;
export function buildPlantCart(app, W, X, Z, ctx) {
  const S = app.scene; const toast = (m, ms) => app.toast(m, ms); const gy = (x, z) => terrainY(x, z); const sb = ctx && ctx.sb; const getMe = ctx && ctx.getMe;
  const KEY = 'aou_plants'; let plants = []; const load = () => { try { const me = getMe && getMe(); if (me && me.home && me.home.plants) return me.home.plants; return JSON.parse(localStorage.getItem(KEY) || '[]'); } catch (e) { return []; } }; const save = () => { try { localStorage.setItem(KEY, JSON.stringify(plants)); } catch (e) { } const me = getMe && getMe(); if (sb && me && me.id !== 'local') { clearTimeout(save._t); save._t = setTimeout(async () => { try { me.home = Object.assign({}, me.home || {}, { plants }); await sb.from('profiles').update({ home: me.home }).eq('id', me.id); } catch (e) { } }, 1000); } };
  /* ---- the cart ---- */
  const CX = X - 48, CZ = Z + 4; const cart = new T.Group(); cart.position.set(CX, gy(CX, CZ), CZ); cart.rotation.y = 0.3; S.add(cart); const wood = M(0x8a5a2b, { roughness: 0.9 }), green = M(0x2e7d32); box(3.2, 0.12, 1.6, wood, 0, 0.9, 0, cart); for (const [x, z] of [[-1.4, -0.6], [1.4, -0.6], [-1.4, 0.6], [1.4, 0.6]]) cyl(0.05, 0.05, 0.9, wood, x, 0.45, z, cart, 6); for (const x of [-1.2, 1.2]) { const wh = new T.Mesh(new T.TorusGeometry(0.32, 0.08, 8, 20), M(0x3b2a1a)); wh.position.set(x, 0.35, -0.9); wh.rotation.y = 0; cart.add(wh); } cyl(0.04, 0.04, 2.2, wood, -1.5, 2.0, 0, cart, 6); cyl(0.04, 0.04, 2.2, wood, 1.5, 2.0, 0, cart, 6); const awn = new T.Mesh(new T.BoxGeometry(3.6, 0.06, 2.0), new T.MeshStandardMaterial({ color: 0xffffff })); awn.position.set(0, 3.1, 0); cart.add(awn); for (let i = -1; i <= 1; i += 2) { const st = box(3.6, 0.07, 0.4, green, 0, 3.12, i * 0.7, cart); } const pots = Object.keys(KINDS); pots.forEach((k, i) => { const p = cyl(0.14, 0.11, 0.26, M(0xc2733a), -1.35 + (i % 5) * 0.68, 1.09, i < 5 ? -0.4 : 0.4, cart, 8); const d = KINDS[k]; const s = sph(0.16, M(d.col), -1.35 + (i % 5) * 0.68, 1.36, i < 5 ? -0.4 : 0.4, cart, 8); s.scale.y = 1.4; }); const sign = makeSprite('🌱 THE PLANT CART · buy a plant · grow it for real', { scale: 5, accent: '#7cff6b' }); sign.position.set(0, 4.3, 0); cart.add(sign); const vendor = new T.Group(); vendor.position.set(0, 0, 1.6); cart.add(vendor); cyl(0.26, 0.3, 1.2, M(0x2e7d32), 0, 0.6, 0, vendor, 10); sph(0.22, M(0xf1c27d), 0, 1.45, 0, vendor, 12); const hat = cyl(0.42, 0.42, 0.06, M(0xd7b377), 0, 1.66, 0, vendor, 12); cyl(0.2, 0.2, 0.16, M(0xd7b377), 0, 1.74, 0, vendor, 12); app.addObstacle && app.addObstacle(CX, CZ, 2.2);
  app.addPlace && app.addPlace({ id: 'plant-cart', name: '🌱 The Plant Cart · buy + grow real plants', icon: '🌱', x: CX, z: CZ + 3, cat: 'Fun', keys: 'plant cart cactus money tree orange apple garden grow nursery', say: 'Pick one. Water it every day. It grows while you live your life.' });
  let carrying = null; const shop = () => { const html = `<p>Pick a plant. Then walk anywhere you like and tap <b>🌱 Plant it here</b>. Water it once a day (tap it). It grows over real days, even when you are away. Forget the water and it droops; water it and it bounces back.</p><div class="aou-styles">${Object.entries(KINDS).map(([k, d]) => `<button data-plant="${k}"><span>${d.ic}</span><b>${d.n}</b><small>${d.days} days to grow · ${d.say}</small></button>`).join('')}</div><p class="aou-note">Free, courtesy of the house. You can have up to 12 plants.</p>`; const m = ctx && ctx.modal ? ctx.modal('🌱 The Plant Cart', html) : null; const root = m || document; root.querySelectorAll('[data-plant]').forEach(b => b.onclick = () => { if (plants.length >= 12) { toast('🌱 Twelve plants is the limit for now. Give one away by removing it.'); return; } carrying = b.dataset.plant; if (ctx && ctx.close) ctx.close(); else if (m && m.remove) m.remove(); toast(`${KINDS[carrying].ic} Carrying a ${KINDS[carrying].n}. Walk to a spot and tap 🌱 Plant it here.`, 5000); plantIt.label = `🌱 Plant the ${KINDS[carrying].n} here`; }); };
  app.addInteractable && app.addInteractable(CX, CZ + 3, 3.5, '🌱 The Plant Cart: pick a plant', shop); app.addHotspot && app.addHotspot(cart, { fn: shop });
  const plantIt = { x: 0, z: 0, r: 1e9, label: '🌱 Plant it here', fn: () => { if (!carrying) return; const P = app.player.position; const x = P.x - Math.sin(app.yaw) * 2, z = P.z - Math.cos(app.yaw) * 2; if (app._waterAt && app._waterAt(x, z) !== null) { toast('🌊 Not in the water. Find dry ground.'); return; } const rec = { id: 'p' + Date.now().toString(36), k: carrying, x: Math.round(x * 10) / 10, z: Math.round(z * 10) / 10, planted: Date.now(), watered: Date.now(), name: '' }; plants.push(rec); save(); grow(rec); carrying = null; (app.interactables || []).splice(app.interactables.indexOf(plantIt), 1); toast(`${KINDS[rec.k].ic} Planted! Water it tomorrow. It will be a sprout by morning.`, 4000); app.celebrate && app.celebrate('🌱'); } };
  app.onUpdate(() => { const it = app.interactables || []; const has = it.includes(plantIt); if (carrying && !has) it.push(plantIt); if (!carrying && has) it.splice(it.indexOf(plantIt), 1); });
  /* ---- growing ---- */
  const live = new Map(); const stageOf = (rec) => { const d = KINDS[rec.k]; const age = (Date.now() - rec.planted) / DAY; const dry = (Date.now() - rec.watered) / DAY; const thirsty = dry > d.thirst; const k = Math.min(1, age / d.days); return { k, thirsty, dry, fruit: k >= 1 && !thirsty }; };
  const grow = (rec) => { const old = live.get(rec.id); if (old) S.remove(old.g); const d = KINDS[rec.k]; const { k, thirsty, fruit } = stageOf(rec); const g = new T.Group(); g.position.set(rec.x, gy(rec.x, rec.z), rec.z); S.add(g); const h = 0.2 + d.h * k; const leafM = new T.MeshStandardMaterial({ color: thirsty ? 0x8d8d3a : d.col, roughness: 0.9 }); const mound = cyl(0.5, 0.6, 0.12, M(0x5b3d24), 0, 0.06, 0, g, 12);
    if (rec.k === 'cactus') { const body = new T.Mesh(new T.CapsuleGeometry(0.22 * (0.4 + k), h * 0.5, 4, 8), leafM); body.position.y = h * 0.5 + 0.1; g.add(body); if (k > 0.5) for (const sx of [-1, 1]) { const arm = new T.Mesh(new T.CapsuleGeometry(0.12, h * 0.25, 4, 8), leafM); arm.position.set(sx * 0.35, h * 0.55, 0); arm.rotation.z = sx * -0.5; g.add(arm); } if (fruit) for (let i = 0; i < 4; i++) sph(0.07, M(d.fruit), (Math.random() - 0.5) * 0.3, h + 0.05, (Math.random() - 0.5) * 0.3, g, 6); }
    else if (rec.k === 'sunflower') { cyl(0.03, 0.04, h, leafM, 0, h / 2, 0, g, 6); if (k > 0.3) { const head = cyl(0.25 * k, 0.25 * k, 0.06, M(0x5d4037), 0, h, 0.05, g, 16); head.rotation.x = Math.PI / 2; for (let i = 0; i < 14; i++) { const pet = box(0.08, 0.22 * k, 0.02, M(d.fruit), 0, h, 0.08, g); pet.position.x = Math.cos(i / 14 * 6.283) * 0.3 * k; pet.position.y = h + Math.sin(i / 14 * 6.283) * 0.3 * k; pet.rotation.z = i / 14 * 6.283; } } }
    else if (rec.k === 'bamboo') { for (let i = 0; i < 1 + Math.floor(k * 4); i++) { const st = cyl(0.03, 0.035, h * (0.6 + i * 0.1), leafM, (i - 2) * 0.1, h * (0.3 + i * 0.05), (i % 2) * 0.1, g, 6); } }
    else if (rec.k === 'rose') { for (let i = 0; i < 3 + Math.floor(k * 5); i++) { const st = cyl(0.015, 0.02, h * 0.8, leafM, (Math.random() - 0.5) * 0.4, h * 0.4, (Math.random() - 0.5) * 0.4, g, 5); st.rotation.z = (Math.random() - 0.5) * 0.5; if (fruit) sph(0.07, M(d.fruit), st.position.x, h * 0.8, st.position.z, g, 8); } }
    else { const trunk = cyl(0.05 + 0.08 * k, 0.07 + 0.1 * k, h * 0.55, M(rec.k === 'money' ? 0x9c7b4a : 0x6b4a2a), 0, h * 0.28, 0, g, 8); if (rec.k === 'money' && k > 0.4) trunk.rotation.y = 0.3; const crownR = 0.25 + 0.8 * k * (d.h / 3); if (rec.k === 'pine') { for (let i = 0; i < 3; i++) { const c = new T.Mesh(new T.ConeGeometry(crownR * (1 - i * 0.25), h * 0.35, 8), leafM); c.position.y = h * 0.45 + i * h * 0.2; g.add(c); } } else { sph(crownR, leafM, 0, h * 0.7, 0, g, 12); sph(crownR * 0.7, leafM, crownR * 0.5, h * 0.75, 0.2, g, 10); sph(crownR * 0.7, leafM, -crownR * 0.5, h * 0.8, -0.1, g, 10); } if (fruit) { const n = rec.k === 'cherry' ? 14 : 7; for (let i = 0; i < n; i++) { const f = sph(rec.k === 'money' ? 0.09 : 0.1, new T.MeshStandardMaterial({ color: d.fruit, metalness: rec.k === 'money' ? 0.9 : 0.1, roughness: 0.3 }), (Math.random() - 0.5) * crownR * 1.6, h * 0.7 + (Math.random() - 0.5) * crownR, (Math.random() - 0.5) * crownR * 1.6, g, 8); if (rec.k === 'money') { f.scale.z = 0.3; f.userData.coin = true; } } } }
    if (thirsty) g.rotation.z = 0.25; const lbl = makeSprite(`${d.ic} ${rec.name || d.n}${k < 1 ? ' · ' + Math.round(k * 100) + '%' : ' · grown'}${thirsty ? ' · 💧 thirsty!' : ''}`, { scale: 2.4, accent: thirsty ? '#ffd23f' : '#7cff6b', far: 90 }); lbl.position.y = h + 0.9; g.add(lbl); live.set(rec.id, { g, rec });
    const it = { x: rec.x, z: rec.z, r: 2.6, label: `💧 ${rec.name || d.n}: water · check`, fn: () => care(rec) }; (app.interactables = app.interactables || []).push(it); live.get(rec.id).it = it; app.addHotspot && app.addHotspot(g, { fn: () => care(rec) }); };
  const care = (rec) => { const d = KINDS[rec.k]; const st = stageOf(rec); const since = Math.floor(st.dry * 24); const html = `<p>${d.ic} <b>${rec.name || d.n}</b> · planted ${Math.floor((Date.now() - rec.planted) / DAY)} day(s) ago · <b>${Math.round(st.k * 100)}%</b> grown${st.fruit ? ' · ' + d.fruitN + ' ready!' : ''}</p><p>${st.thirsty ? '💧 <b>Thirsty!</b> It has been ' + since + ' hours. Water it and it perks right up.' : 'Watered ' + since + ' hour(s) ago. Happy.'} Needs water every ${d.thirst} day(s). Grows for ${d.days} days.</p>`; const acts = [{ label: '💧 Water it', fn: () => { rec.watered = Date.now(); save(); grow(rec); toast('💧 Glug glug. ' + d.n + ' says thanks.'); splash(rec); } }]; if (st.fruit) acts.push({ label: `${d.ic} Pick the ${d.fruitN}`, fn: () => { rec.picked = (rec.picked || 0) + 1; rec.planted = Date.now() - (d.days - 1) * DAY; save(); grow(rec); toast(rec.k === 'money' ? '💰 Coins! (Pretend ones. The real money tree is MONEYblocks.)' : `${d.ic} Picked! Sweet. More in a day or two.`, 3500); app.celebrate && app.celebrate(d.ic); } }); acts.push({ label: '✏️ Name it', fn: () => { const n = prompt('Name this plant:', rec.name || ''); if (n !== null) { rec.name = n.slice(0, 24); save(); grow(rec); } } }, { label: '🚚 Move it here', fn: () => { const P = app.player.position; rec.x = Math.round((P.x - Math.sin(app.yaw) * 2) * 10) / 10; rec.z = Math.round((P.z - Math.cos(app.yaw) * 2) * 10) / 10; removeLive(rec); save(); grow(rec); toast('🚚 Moved.'); } }, { label: '🗑️ Remove', fn: () => { if (!confirm('Remove this plant?')) return; removeLive(rec); plants = plants.filter(p => p !== rec); save(); toast('Gone. Compost happens.'); } }); if (ctx && ctx.modal) { const m = ctx.modal(d.ic + ' ' + (rec.name || d.n), html + '<div class="aou-chips">' + acts.map((a, i) => `<button class="lt-btn ${i === 0 ? 'holo' : ''}" data-pa="${i}">${a.label}</button>`).join('') + '</div>'); (m || document).querySelectorAll('[data-pa]').forEach(b => b.onclick = () => { ctx.close && ctx.close(); acts[+b.dataset.pa].fn(); }); } else { acts[0].fn(); } };
  const removeLive = (rec) => { const L = live.get(rec.id); if (!L) return; S.remove(L.g); if (L.it) { const i = (app.interactables || []).indexOf(L.it); if (i >= 0) app.interactables.splice(i, 1); } live.delete(rec.id); };
  const drops = []; const splash = (rec) => { for (let i = 0; i < 10; i++) { const dr = sph(0.04, new T.MeshStandardMaterial({ color: 0x9fe3ff, transparent: true, opacity: 0.9 }), 0, 0, 0, S, 6); dr.position.set(rec.x + (Math.random() - 0.5) * 0.6, gy(rec.x, rec.z) + 1.6, rec.z + (Math.random() - 0.5) * 0.6); dr.userData.v = new T.Vector3((Math.random() - 0.5) * 0.6, -0.5, (Math.random() - 0.5) * 0.6); dr.userData.t = 0; drops.push(dr); } };
  plants = load(); plants.forEach(grow); let last = Date.now(); app.onUpdate((dt, t) => { for (const dr of drops) { dr.userData.t += dt; dr.userData.v.y -= 6 * dt; dr.position.addScaledVector(dr.userData.v, dt); if (dr.userData.t > 0.9) S.remove(dr); } for (let i = drops.length - 1; i >= 0; i--) if (drops[i].userData.t > 0.9) drops.splice(i, 1); live.forEach(({ g, rec }) => { if (rec.k === 'sunflower') g.rotation.y = Math.sin(t * 0.2) * 0.4; g.children.forEach(c => { if (c.userData.coin) c.rotation.y = t * 2; }); }); if (Date.now() - last > 600000) { last = Date.now(); plants.forEach(grow); } });
  W.plants = { list: () => plants, water: (id) => { const r = plants.find(p => p.id === id); if (r) { r.watered = Date.now(); save(); grow(r); } } };
  return { shop };
}
