/* 🎉 Zach's 49th birthday party (Oct 3, 2026) · No. 1 Unity Road: metallic balloons in neon + pastel, streamers,
   the banner out front, the feast out back with real recipes, confetti favors, candles to blow out, a party game. */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { M, glow, box, cyl, sph, textPlane } from './aou-kit.js';
import { terrainY } from './aou-terrain.js';
const T = THREE; const MOB = isMobile();
export function buildParty(app, W, X, Z) {
  const S = app.scene; const y0 = terrainY(X, Z) + 0.05; const toast = (m, ms) => app.toast(m, ms); const G = new T.Group(); G.position.set(X, y0, Z); G.userData.noCollide = true; S.add(G);
  const COLS = [0xff2d95, 0x38f0ff, 0xffe600, 0x7cff6b, 0xb388ff, 0xff8a3d, 0xffc3e6, 0xbdf7ff, 0xfff3b0, 0xd7ffd0, 0xe4d4ff];
  // all balloons in ONE instanced mesh (3 draw calls total instead of 270)
  const balloons = []; const MAXB = 140; const bIM = new T.InstancedMesh(new T.SphereGeometry(0.42, 18, 12), new T.MeshStandardMaterial({ color: 0xffffff, metalness: 0.9, roughness: 0.12 }), MAXB); bIM.count = 0; bIM.frustumCulled = false; G.add(bIM); const kIM = new T.InstancedMesh(new T.ConeGeometry(0.07, 0.12, 6), bIM.material, MAXB); kIM.count = 0; kIM.frustumCulled = false; G.add(kIM); const strPos = new Float32Array(MAXB * 6); const strGeo = new T.BufferGeometry(); strGeo.setAttribute('position', new T.BufferAttribute(strPos, 3)); const strings = new T.LineSegments(strGeo, new T.LineBasicMaterial({ color: 0xdddddd })); strings.frustumCulled = false; G.add(strings); const _m = new T.Matrix4(), _q = new T.Quaternion(), _p = new T.Vector3(), _s = new T.Vector3(), _c = new T.Color();
  const balloon = (x, y, z, c, s = 1) => { if (bIM.count >= MAXB) return { userData: {} }; const i = bIM.count++; kIM.count = bIM.count; bIM.setColorAt(i, _c.setHex(c)); kIM.setColorAt(i, _c); const rec = { i, x, y, z, s, ph: Math.random() * 6, userData: {} }; balloons.push(rec); return rec; };
  const placeBalloon = (b, t) => { const yy = b.y + Math.sin(t * 0.9 + b.ph) * 0.12; const ry = Math.sin(t * 0.5 + b.ph) * 0.3; _q.setFromAxisAngle(_p.set(0, 1, 0), ry); _m.compose(_p.set(b.x, yy, b.z), _q, _s.set(b.s, b.s * 1.2, b.s)); bIM.setMatrixAt(b.i, _m); _q.setFromAxisAngle(_p.set(1, 0, 0), Math.PI); _m.compose(_p.set(b.x, yy - 0.52 * b.s, b.z), _q, _s.set(b.s, b.s, b.s)); kIM.setMatrixAt(b.i, _m); strPos[b.i * 6] = b.x; strPos[b.i * 6 + 1] = yy - 0.55 * b.s; strPos[b.i * 6 + 2] = b.z; strPos[b.i * 6 + 3] = b.x; strPos[b.i * 6 + 4] = yy - 2.1 * b.s; strPos[b.i * 6 + 5] = b.z; };
  // bunches: by the front door, both corners, the roof deck, the pool and the backyard
  const bunch = (x, y, z, n = 7, s = 1) => { for (let i = 0; i < n; i++) balloon(x + Math.cos(i * 2.4) * 0.5 * s, y + 0.9 + (i % 3) * 0.35, z + Math.sin(i * 2.4) * 0.5 * s, COLS[(i + Math.floor(x)) % COLS.length], s); };
  bunch(-23, 0, -6, 8); bunch(-23, 0, 6, 8); bunch(-22, 13.6, -12, 6); bunch(-22, 13.6, 12, 6); bunch(14, 0, -12, 7); bunch(14, 0, 12, 7); bunch(20, 0, 3, 9, 1.2); bunch(-4, 0, 20, 6); bunch(-2, 0, -27, 6);
  for (let i = 0; i < (MOB ? 14 : 30); i++) balloon(-40 + Math.random() * 90, 6 + Math.random() * 12, -40 + Math.random() * 70, COLS[i % COLS.length], 0.9).userData.drift = true;
  // the banner out front: HAPPY 49TH YOU OL' FART!!
  const banner = textPlane(["🎉 HAPPY 49TH, YOU OL' FART!! 🎉", 'Oct 3 · party at No. 1 Unity Road · everyone welcome'], 15, 3.2, { bg: '#ff2d95', fg: '#fff', accent: '#ffe600', font: 'bold 64px Poppins, Arial' }); banner.position.set(-23.2, 10.5, 0); banner.rotation.y = -Math.PI / 2; G.add(banner); for (const dz of [-7.6, 7.6]) cyl(0.08, 0.08, 1.4, M(0xdddddd), -23.2, 9, dz, G, 6);
  // streamers: twisted ribbons from the roofline to the yard
  const streamers = []; for (let i = 0; i < 14; i++) { const c = COLS[i % COLS.length]; const pts = []; const x0 = -21.3, z0 = -12 + i * 1.85; for (let k = 0; k <= 12; k++) { const t = k / 12; pts.push(new T.Vector3(x0 - t * 6 + Math.sin(t * 9 + i) * 0.5, 12.5 - t * 9, z0 + Math.sin(t * 6) * 0.8)); } const geo = new T.TubeGeometry(new T.CatmullRomCurve3(pts), 24, 0.045, 5, false); const m = new T.Mesh(geo, new T.MeshStandardMaterial({ color: c, metalness: 0.7, roughness: 0.25, side: T.DoubleSide })); G.add(m); streamers.push(m); }
  // the feast out back (with real recipes)
  const TX = 19, TZ = 4; const tb = new T.Group(); tb.position.set(TX, 0, TZ); G.add(tb); box(6, 0.12, 2.2, M(0xffffff, { roughness: 0.6 }), 0, 0.78, 0, tb); box(6.2, 0.06, 2.4, M(0xff2d95), 0, 0.84, 0, tb); for (const [x, z] of [[-2.8, -1], [2.8, -1], [-2.8, 1], [2.8, 1]]) cyl(0.06, 0.06, 0.78, M(0x333333), x, 0.39, z, tb, 6); app.addObstacle && app.addObstacle(X + TX, Z + TZ, 3.2);
  const cake = new T.Group(); cake.position.set(0, 0.87, 0); tb.add(cake); [[0.75, 0.32, 0xfff3b0], [0.55, 0.3, 0xffc3e6], [0.38, 0.28, 0xbdf7ff]].forEach(([r, h, c], i) => { const l = cyl(r, r, h, M(c, { roughness: 0.7 }), 0, [0.16, 0.47, 0.76][i], 0, cake, 24); const ic = new T.Mesh(new T.TorusGeometry(r, 0.05, 8, 24), M(0xffffff)); ic.rotation.x = Math.PI / 2; ic.position.y = [0.32, 0.62, 0.9][i]; cake.add(ic); }); const candles = []; for (let i = 0; i < 9; i++) { const a = i / 9 * 6.283; const cd = cyl(0.02, 0.02, 0.18, M(COLS[i % COLS.length]), Math.cos(a) * 0.28, 1.0, Math.sin(a) * 0.28, cake, 6); const fl = new T.Mesh(new T.ConeGeometry(0.03, 0.09, 6), new T.MeshBasicMaterial({ color: 0xffd23f })); fl.position.set(Math.cos(a) * 0.28, 1.14, Math.sin(a) * 0.28); cake.add(fl); candles.push(fl); } const c49 = makeSprite('4️⃣9️⃣', { scale: 1.6, accent: '#ffe600' }); c49.position.y = 1.45; cake.add(c49);
  const FOOD = [['🍕 Pizza', -2.2, 0, 'https://www.allrecipes.com/recipe/20171/quick-and-easy-pizza-crust/'], ['🌮 Tacos', 2.2, 0, 'https://www.allrecipes.com/recipe/70935/taqueria-style-tacos-carne-asada/'], ['🥑 Guac', -1.3, 0.7, 'https://www.allrecipes.com/recipe/14231/guacamole/'], ['🍪 Cookies', 1.3, 0.7, 'https://www.allrecipes.com/recipe/10813/best-chocolate-chip-cookies/'], ['🍝 Lasagna', -1.3, -0.7, 'https://www.allrecipes.com/recipe/23600/worlds-best-lasagna/'], ['🍋 Lemonade', 1.3, -0.7, 'https://www.allrecipes.com/recipe/32385/old-fashioned-lemonade/']];
  FOOD.forEach(([n, x, z, url], i) => { const plate = cyl(0.42, 0.42, 0.03, M(0xffffff), x, 0.86, z, tb, 20); const food = sph(0.26, M([0xd97706, 0xf59e0b, 0x65a30d, 0xb45309, 0xdc2626, 0xfde047][i], { roughness: 0.7 }), x, 1.02, z, tb, 12); food.scale.y = 0.55; const tag = makeSprite(n, { scale: 1.3, accent: '#ff2d95' }); tag.position.set(x, 1.5, z); tb.add(tag); app.addHotspot && app.addHotspot(food, { title: n + ' · the real recipe', html: '<p>Tonight\'s menu is real. Make it at home and bring a photo to the feed.</p>', actions: [{ label: '📖 Open the recipe', href: url, newTab: true }, { label: '📰 Post a food pic', href: '/flat/' }] }); });
  const fsign = makeSprite('🎂 THE 49TH BIRTHDAY FEAST · tap a dish for the recipe', { scale: 4, accent: '#ffe600' }); fsign.position.set(0, 3.2, 0); tb.add(fsign);
  let lit = true; const blow = () => { if (!lit) { toast('🎂 Relit for the next person. Make a wish!'); candles.forEach(c => c.visible = true); lit = true; return; } lit = false; candles.forEach(c => c.visible = false); app.celebrate && app.celebrate('🎂'); toast('🎂 Whoosh! 49 wishes granted. (Okay, nine candles. He is 49, not made of wax.)', 4000); confetti(); };
  app.addInteractable && app.addInteractable(X + TX, Z + TZ - 2.2, 2.8, '🎂 Blow out the candles', blow); app.addHotspot && app.addHotspot(cake, { fn: blow });
  // confetti favors: a canvas burst over the whole screen
  const confetti = () => { const cv = document.createElement('canvas'); cv.width = innerWidth; cv.height = innerHeight; cv.style.cssText = 'position:fixed;inset:0;z-index:99986;pointer-events:none'; document.body.appendChild(cv); const q = cv.getContext('2d'); const P = []; for (let i = 0; i < 260; i++) P.push({ x: cv.width / 2, y: cv.height * 0.7, vx: (Math.random() - 0.5) * 18, vy: -8 - Math.random() * 14, c: '#' + new T.Color(COLS[i % COLS.length]).getHexString(), r: Math.random() * 6.28, w: 6 + Math.random() * 8 }); let t0 = performance.now(); const loop = (now) => { const k = (now - t0) / 1000; q.clearRect(0, 0, cv.width, cv.height); for (const p of P) { p.vy += 0.35; p.x += p.vx; p.y += p.vy; p.vx *= 0.99; p.r += 0.1; q.save(); q.translate(p.x, p.y); q.rotate(p.r); q.fillStyle = p.c; q.fillRect(-p.w / 2, -p.w / 4, p.w, p.w / 2); q.restore(); } if (k < 3.2) requestAnimationFrame(loop); else cv.remove(); }; requestAnimationFrame(loop); app.buzz && app.buzz(60); };
  const favor = (x, z) => { const g = new T.Group(); g.position.set(x, 0, z); G.add(g); box(0.6, 0.9, 0.6, M(0xb388ff, { metalness: 0.6 }), 0, 0.45, 0, g); const btn = new T.Mesh(new T.CylinderGeometry(0.16, 0.16, 0.1, 16), new T.MeshStandardMaterial({ color: 0xff2d95, emissive: 0xff2d95, emissiveIntensity: 0.8 })); btn.position.y = 0.95; g.add(btn); const t = makeSprite('🎊 PUSH FOR CONFETTI', { scale: 2, accent: '#ffe600' }); t.position.y = 1.7; g.add(t); const fire = () => { btn.position.y = 0.9; setTimeout(() => btn.position.y = 0.95, 200); confetti(); toast('🎊 POP!', 900); }; app.addInteractable && app.addInteractable(X + x, Z + z + 1.2, 2, '🎊 Party favor: push for confetti', fire); app.addHotspot && app.addHotspot(g, { fn: fire }); }; favor(-26, -3); favor(16, -6); favor(-6, 24);
  // the party game: Guess the balloons (chat-style trivia with a reward)
  const total = balloons.length; /* counted after all bunches */ const game = () => app.popup && app.popup('🎈 Party game: how many balloons?', `<p>Count fast. Metallic ones, pastel ones, the floaters, all of them. Closest guess wins bragging rights in the fire chat.</p><input id="pg-n" type="number" min="1" max="999" placeholder="Your guess" style="width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:10px;padding:10px;font:800 16px Poppins,Arial"><p class="muted">Trivia bonus: Zach was born in Fremont, Nebraska. True or false? (It's true. Say happy birthday in the feed: 📰)</p>`, [{ label: '🎈 Guess', fn: () => { const n = +((document.getElementById('pg-n') || {}).value || 0); const d = Math.abs(n - total); if (d === 0) { app.celebrate && app.celebrate('🏆'); confetti(); toast('🏆 EXACTLY ' + total + '! You are the balloon champion of the world.', 5000); } else toast((d <= 5 ? '🔥 So close! ' : d <= 15 ? '🙂 Not bad. ' : '😅 Way off. ') + 'There are ' + total + '. Try the confetti button to feel better.', 5000); } }, { label: '📰 Wish Zach happy birthday', href: '/flat/' }]);
  app.addInteractable && app.addInteractable(X - 26, Z + 3, 3, '🎈 Party game: guess the balloons', game);
  app.addPlace && app.addPlace({ id: 'party49', name: "🎉 Zach's 49th birthday party · No. 1 Unity Road", icon: '🎉', x: X - 28, z: Z, cat: 'Fun', top: true, keys: 'birthday party zach 49 balloons cake feast confetti game october 3', say: "The banner says it all. Cake's out back. Push the purple boxes." });
  balloons.forEach(b => placeBalloon(b, 0)); bIM.instanceMatrix.needsUpdate = kIM.instanceMatrix.needsUpdate = true; if (bIM.instanceColor) bIM.instanceColor.needsUpdate = true; if (kIM.instanceColor) kIM.instanceColor.needsUpdate = true; strGeo.attributes.position.needsUpdate = true;
  app.onUpdate((dt, t) => { const P = app.player.position; if (Math.hypot(P.x - X, P.z - Z) > 160) return; for (const b of balloons) { if (b.userData.drift) { b.x += Math.sin(t * 0.2 + b.ph) * dt * 0.4; b.z += Math.cos(t * 0.17 + b.ph) * dt * 0.4; } placeBalloon(b, t); } bIM.instanceMatrix.needsUpdate = kIM.instanceMatrix.needsUpdate = true; strGeo.attributes.position.needsUpdate = true; streamers.forEach((s, i) => { s.rotation.x = Math.sin(t * 1.2 + i) * 0.04; }); candles.forEach((c, i) => { c.scale.y = 0.9 + Math.sin(t * 14 + i) * 0.25; }); });
}
