/* ============================================================
   allofus.one · plus layer (v3, Oct 2026)
   ✨ More sheet · 🌐 Worlds globe directory · ⛅ weather control
   🤗 hugs (in-world + email hug cards) · 😇 halo sign
   📡 friend scan (teens only with teens, adults with adults)
   🛡️ admin console · 🚩 report / block · family-friendly filter
   👆 device fingerprint doors · © 2026 allofus.one
   ============================================================ */
import { THREE, makeSprite, SKIES, addExtras, applyBuild, buildCharacter, CHARACTERS, animatePerson } from './aou-engine.js';
import { initStudio } from './aou-studio.js';
import { openHub } from './aou-hub.js';
import { initSky } from './aou-sky.js';
import { MODES, LIFE_PATHS } from './aou-world.js';
import { makeTools, TOOL_TABS, LIFETOOLS_CSS, startReminders } from './aou-lifetools.js';
import { createVoice, supabaseTransport, ICE } from './aou-voice.js';
import { CONFIG } from './aou-config.js';
const T = THREE;
const $ = (s, r = document) => r.querySelector(s); const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const load = (k, d) => { try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : d; } catch (e) { return d; } };
const save = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)); } catch (e) { } };

export const WORLDS = [
  ['allofus.one', 'https://allofus.one/', '🌍', 'You are here: the hub world for all of us', 'Social', 40, -100],
  ['World VR Mall', 'https://worldvrmall.com/', '🛍️', 'Walk-in 3D mall with real stores', 'Shopping', 20, 10],
  ['Comics Come Alive', 'https://comicscomealive.com/', '💥', 'Animated comics, games + bedtime stories', 'Family', -10, 60],
  ['The VR Galaxy', 'https://thevrgalaxy.com/', '🪐', '15 never-seen-before planets', 'Explore', 60, 150],
  ['Another Dimension VR', 'https://anotherdimensionvr.com/', '🌀', 'A browser VR game world', 'Games', -30, 120],
  ['Virtual Reality Adventure', 'https://virtualrealityadventure.com/', '🧭', 'Adventures with Coburn', 'Games', 10, -150],
  ['VR Flying Simulator', 'https://vrflyingsimulator.com/', '✈️', 'Realistic 3D flight school', 'Learn', 50, 80],
  ['Sparkle Diner', 'https://advertisingforrestaurant.com/', '🍔', 'A walk-in 3D 50s diner', 'Fun', -45, -40],
  ['Phoenix\'s World', 'https://phoenixsworld.com/', '👑', 'Learning games for little ones', 'Family', -55, 30],
  ['USA Business Search', 'https://usabusinesssearch.com/', '🔎', 'Find any business in the USA', 'Business', 30, -60],
  ['CO Business List', 'https://cobusinesslist.com/', '🏔️', 'Colorado businesses, all in one place', 'Business', 15, -110],
  ['Action Global News', 'https://actionglobalnews.com/', '📰', 'Business + tech news', 'News', -20, -10],
  ['Press Release for Business', 'https://pressreleaseforbusiness.com/', '📣', 'Get your news published', 'Business', -5, -80],
  ['Zach\'s world', 'https://zacharytyewennstedt.com/', '🎨', 'Meet the founder: art, poetry, tools', 'People', 35, 40],
  ['Eye To Ad Media', 'https://eyetoad.com/', '🐸', 'The web + marketing studio behind it all', 'Business', 5, 170],
];
const BAD = /\b(f+u+c+k+\w*|sh[i1]+t+\w*|b[i1]+t+c+h+\w*|a+s+s+h+o+l+e+\w*|d[i1]+c+k+\w*|c+u+n+t+\w*|wh[o0]+r+e+\w*|sl+u+t+\w*|p[o0]+r+n+\w*|n+u+d+e+s?|b+a+s+t+a+r+d+\w*|d+a+m+n+\w*|p+u+s+s+y+|c+o+c+k+\w*|s+e+x+y?|k+i+l+l+ y+o+u+r+s+e+l+f+)\b/gi;
export const clean = (t) => String(t || '').replace(BAD, (w) => w[0] + '•'.repeat(Math.max(2, w.length - 1)));
export const isClean = (t) => !new RegExp(BAD.source, 'i').test(String(t || ''));

export function initPlus(app, W, UI, lumi, opts = {}) { globalThis.AOU_SB = UI.DB && UI.DB.sb; W.UI = UI;
  /* 📰 the feed board on the front of the house */
  setTimeout(async () => { try { const sb = UI.DB && UI.DB.sb; if (!sb || !W.feedBoard) return; const { data: oid } = await sb.rpc('estate_owner', { p_slug: 'founder' }); if (!oid) return; const { data: pr } = await sb.from('profiles').select('display_name,home').eq('id', oid).maybeSingle(); const f = (pr && pr.home && pr.home.flat) || {}; if (f.showOnHome === false) { W.feedBoard([{ text: 'Feed is private right now.', created_at: new Date().toISOString() }], pr && pr.display_name); return; } const { data } = await sb.from('feed_posts').select('text,kind,created_at').eq('user_id', oid).eq('public', true).order('created_at', { ascending: false }).limit(f.homeN || 3); W.feedBoard(data || [], (pr && pr.display_name) || 'Zach'); } catch (e) { } }, 4000);
  setTimeout(() => { try { const me = getMe && getMe(); initSky(app, { x: 44 - 40, z: 105 + 44, sb: UI.DB && UI.DB.sb, me: () => getMe && getMe(), toast: UI.toast, popup: (t, h, acts) => app.popup(t, h, acts), celebrate: (e) => app.celebrate && app.celebrate(e) }); } catch (e) { console.error('sky', e); } }, 2500);
  /* ⬡ the Global Communication Hub replaces the old mailbox */
  W.openHub = async (ownerIn) => { const sb = UI.DB && UI.DB.sb; const me = getMe && getMe(); let owner = ownerIn || null; if (!owner && sb) { try { const { data: oid } = await sb.rpc('estate_owner', { p_slug: 'founder' }); if (oid) { const { data } = await sb.from('profiles').select('*').eq('id', oid).maybeSingle(); if (data) owner = { id: data.id, name: data.display_name, username: data.username, home: data.home || {}, zach: true }; } } catch (e) { } } if (!owner) owner = { id: 'zach', name: 'Zach', username: 'zach', home: {}, zach: true }; app.paused = true; openHub({ sb, me, owner, toast: UI.toast, onClose: () => { app.paused = false; } }); };
  /* 🐞 report a bug (we are brand new and still polishing) */
  const reportBug = () => { const m = UI.modal('🐞 Report a bug or problem', `<p>We're brand new and still polishing. See something broken, weird or slow? Tell us. It goes straight to the team.</p><label>What happened?<textarea id="bg-t" maxlength="1200" placeholder="What were you doing, what went wrong?"></textarea></label><label>Your email (optional, if you want a reply)<input id="bg-e" type="email" maxlength="120"></label><input id="bg-hp" class="hp" tabindex="-1" autocomplete="off" aria-hidden="true"><div class="mp-row"><button class="mp-btn holo" id="bg-go">Send report</button></div><p class="muted">We attach your device type, screen size and where you were in the world, nothing else.</p><p class="mp-err" id="bg-err"></p>`); const t0 = Date.now();
    m.querySelector('#bg-go').onclick = async () => { const t = m.querySelector('#bg-t').value.trim(); const err = m.querySelector('#bg-err'); if (m.querySelector('#bg-hp').value) return; if (t.length < 5) { err.textContent = 'A few words helps a lot.'; return; } if (Date.now() - t0 < 1500) { err.textContent = 'One second…'; return; } const P = app.player.position; const details = { page: location.pathname, where: [Math.round(P.x), Math.round(P.z)], level: app.level || 0, ua: navigator.userAgent.slice(0, 120), screen: innerWidth + 'x' + innerHeight, character: (() => { try { return JSON.parse(localStorage.getItem('wvm_avatar') || '{}').character; } catch (e) { return ''; } })() }; let ok = false; try { const sb = (UI.DB && UI.DB.sb); if (sb) { const { error } = await sb.rpc('submit_lead', { p_kind: 'bug', p_name: 'Bug report', p_business: location.hostname, p_email: m.querySelector('#bg-e').value.trim() || 'anon@allofus.one', p_phone: '', p_website: location.href.slice(0, 200), p_details: JSON.stringify({ text: t, ...details }) }); ok = !error; } } catch (e) { } m.querySelector('.aou-body, .mp-body').innerHTML = ok ? '<div class="mp-won"><div class="big">🙏</div><b>Thank you! That really helps.</b></div><p>We read every one.</p>' : '<div class="mp-won"><div class="big">📞</div><b>Our form did not answer.</b></div><p>Please email <a href="mailto:info@eyetoad.com?subject=Bug%20report">info@eyetoad.com</a> or call 1-800-481-8638 with what happened.</p>'; }; };

  /* ✈️ flight: drones fly; super-admins fly anything, anywhere */
  { const isDrone = () => { try { return (JSON.parse(localStorage.getItem('wvm_avatar') || '{}').character) === 'drone'; } catch (e) { return false; } }; app.flyOK = () => !!app.superAdmin || isDrone();
    const fb = document.createElement('div'); fb.id = 'fly-btns'; fb.innerHTML = '<button data-f="1" aria-label="Fly up">⬆</button><button data-f="-1" aria-label="Fly down">⬇</button>'; fb.style.cssText = 'position:absolute;left:50%;bottom:150px;transform:translateX(-50%);z-index:31;display:none;gap:8px'; (document.getElementById('wvm-hud') || document.body).appendChild(fb); const st = document.createElement('style'); st.textContent = '#fly-btns button{width:54px;height:54px;border-radius:16px;border:0;background:rgba(56,240,255,.9);color:#04122a;font-size:24px;font-weight:900;cursor:pointer;touch-action:none;box-shadow:0 6px 18px rgba(0,0,0,.35)}@media (max-width:720px){#fly-btns{bottom:220px}}'; document.head.appendChild(st);
    fb.addEventListener('pointerdown', (e) => { const b = e.target.closest('[data-f]'); if (b) app.setFly(+b.dataset.f); }); addEventListener('pointerup', () => app.setFly(0));
    addEventListener('keydown', (e) => { if (!app.flyOK() || e.repeat || (e.target.closest && e.target.closest('input,textarea'))) return; if (app._waterAt && app._waterAt(app.player.position.x, app.player.position.z) !== null) return; if (e.key === 'q' || e.key === 'Q') app.setFly(1); if (e.key === 'e' || e.key === 'E') app.setFly(-1); }); addEventListener('keyup', (e) => { if (/^[qeQE]$/.test(e.key)) app.setFly(0); });
    const show = () => { fb.style.display = app.flyOK() ? 'flex' : 'none'; }; show(); addEventListener('aou-avatar', show); setInterval(show, 3000); }
 setTimeout(() => { try { initStudio(app, { THREE, buildCharacter, CHARACTERS, addExtras, applyBuild, animatePerson }); } catch (e) { console.error('studio', e); } }, 1500);
  injectCSS(); const DB = UI.DB; const getMe = () => UI.getMe && UI.getMe(); const owned = new Set();
  W.addExtras = addExtras; W.applyBuild = applyBuild; W.fetchProfile = DB.live && DB.profile ? (id) => DB.profile(id) : null;
  const notify = (title, body) => { try { if (typeof Notification !== 'undefined' && Notification.permission === 'granted') new Notification(title, { body, icon: '/images/favicon-192.png' }); } catch (e) { } };

  /* ---------- ownership + fingerprint doors ---------- */
  const refreshOwned = async () => { owned.clear(); if (!DB.live || !getMe()) return; try { const { data } = await DB.sb.rpc('my_estates'); for (const r of data || []) owned.add(typeof r === 'string' ? r : (r.slug || r.my_estates)); } catch (e) { } try { const { data } = await DB.sb.rpc('is_admin'); UI.isAdmin = !!data; } catch (e) { UI.isAdmin = false; } };
  const isOwner = (slug) => owned.has(slug);
  const b64 = (buf) => btoa(String.fromCharCode(...new Uint8Array(buf))); const unb64 = (s) => Uint8Array.from(atob(s), c => c.charCodeAt(0));
  const deviceUnlock = async (slug) => { if (!window.PublicKeyCredential || !window.isSecureContext) return false; const key = 'aou_pk_' + slug; const ch = crypto.getRandomValues(new Uint8Array(32)); const id = load(key, null);
    try { if (id) { await navigator.credentials.get({ publicKey: { challenge: ch, allowCredentials: [{ id: unb64(id), type: 'public-key' }], userVerification: 'required', timeout: 60000 } }); return true; }
      if (!confirm('Use this device\'s fingerprint or face to open your door? Your biometric never leaves your device.')) return false;
      const cred = await navigator.credentials.create({ publicKey: { challenge: ch, rp: { name: 'allofus.one' }, user: { id: crypto.getRandomValues(new Uint8Array(16)), name: slug + '@allofus.one', displayName: 'Door · ' + slug }, pubKeyCredParams: [{ type: 'public-key', alg: -7 }, { type: 'public-key', alg: -257 }], authenticatorSelection: { authenticatorAttachment: 'platform', userVerification: 'required', residentKey: 'discouraged' }, timeout: 60000 } });
      if (cred) { save(key, b64(cred.rawId)); return true; } } catch (e) { console.warn('device unlock', e); } return false; };

  /* ---------- halo sign above your head (synced to everyone) ---------- */
  let haloSprite = null; const getHalo = () => { const me = getMe(); return (me && me.avatar && me.avatar.halo) || load('aou_halo', null); };
  const drawHalo = (h) => { if (haloSprite) { app.player.remove(haloSprite); haloSprite = null; } if (!h || !h.t) return; haloSprite = makeSprite(h.t, { scale: 3.4, accent: h.c || '#ffd23f' }); haloSprite.position.y = 3.55; haloSprite.userData.noCollide = true; app.player.add(haloSprite); };
  const setHalo = (h) => { if (h && h.t) { h.t = clean(h.t).slice(0, 44); } save('aou_halo', h || null); const me = getMe(); if (me) { me.avatar = Object.assign({}, me.avatar || {}, { halo: h || null, v: Date.now() }); UI.syncAvatar && UI.syncAvatar(); } drawHalo(h); };
  drawHalo(getHalo());
  app.onUpdate((dt, t) => { if (haloSprite) { haloSprite.position.y = 3.55 + Math.sin(t * 2) * 0.06; haloSprite.visible = app.dist > 0.6; } });

  /* ---------- hugs: hearts fly, the other person gets a notice ---------- */
  const heartTex = (() => { const c = document.createElement('canvas'); c.width = c.height = 64; const g = c.getContext('2d'); g.font = '52px serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillText('💛', 32, 36); const t = new T.CanvasTexture(c); return t; })();
  const hearts = (from, to) => { const N = 14; for (let i = 0; i < N; i++) { const s = new T.Sprite(new T.SpriteMaterial({ map: heartTex, transparent: true, depthWrite: false })); s.scale.setScalar(0.6); s.position.copy(from).add(new T.Vector3((Math.random() - 0.5) * 0.6, 1.8, (Math.random() - 0.5) * 0.6)); app.scene.add(s); const st = { k: 0, d: 0.8 + Math.random() * 0.8, delay: i * 0.05 };
      const f = (dt) => { st.delay -= dt; if (st.delay > 0) return; st.k += dt / st.d; const k = Math.min(1, st.k); if (to) { s.position.lerpVectors(from.clone().setY(from.y + 1.8), to.clone().setY(to.y + 1.8 + Math.sin(k * Math.PI) * 2.4), k); s.position.x += Math.sin(k * 9 + i) * 0.2; } else { s.position.y += dt * 1.6; s.position.x += Math.sin(st.k * 8 + i) * dt; } s.material.opacity = 1 - Math.max(0, k - 0.75) * 4; if (k >= 1) { app.scene.remove(s); s.material.dispose(); app.updaters = app.updaters.filter(q => q !== f); } }; app.onUpdate(f); } };
  const hugOverlay = (fromName, style = '🤗', msg = '') => { const o = document.createElement('div'); o.className = 'aou-hug'; o.innerHTML = `<div class="hb"><div class="he">${esc(style)}</div><b>${esc(fromName)} sent you a hug!</b>${msg ? `<p>${esc(msg)}</p>` : ''}<div class="hr">${'💛💜💙💚🧡❤️'.split('').filter(x => x.trim()).map((h, i) => `<span style="--i:${i}">${h}</span>`).join('')}</div><button class="lt-btn holo">🤗 Hug back</button></div>`; document.body.appendChild(o); o.onclick = (e) => { if (e.target.closest('button')) { o.remove(); if (fromName && W.lastHugFrom) sendHug(W.lastHugFrom); return; } o.remove(); }; setTimeout(() => o.remove(), 9000); };
  const nearby = () => { const P = app.player.position; const me = getMe(); const all = [...W.residents.map(r => ({ id: r.prof.id, name: r.prof.name, g: r.g, prof: r.prof })), ...[...W.remote.values()].map(r => ({ id: r.id, name: r.prof.name, g: r.g, live: true, prof: r.prof }))].filter(p => !me || p.id !== me.id); all.forEach(a => a.d = Math.hypot(a.g.position.x - P.x, a.g.position.z - P.z)); return all.sort((a, b) => (b.live ? 1 : 0) - (a.live ? 1 : 0) || a.d - b.d); };
  const sendHug = (p) => { if (!p) return; const me = getMe(); const target = p.g ? p.g.position : null; hearts(app.player.position.clone(), target ? target.clone() : null); app.celebrate && app.celebrate('🤗'); app.toast('🤗 Hug sent to ' + (p.name || 'a friend') + '!'); if (DB.live && me && p.live !== false && DB.fx) DB.fx({ kind: 'hug', from: me.id, fromName: me.name, to: p.id }); const lb = UI.LB && UI.LB(); if (lb) { lb.hugs = lb.hugs || { sent: 0, got: 0 }; lb.hugs.sent++; UI.saveLB(lb); } };
  W.onFx = (pl) => { if (!pl || pl.kind !== 'hug') return; const me = getMe(); const fromR = W.remote.get(pl.from); const toR = W.remote.get(pl.to); if (me && pl.to === me.id) { W.lastHugFrom = { id: pl.from, name: pl.fromName, g: fromR && fromR.g, live: true }; hearts(fromR ? fromR.g.position.clone() : app.player.position.clone().add(new T.Vector3(3, 0, 3)), app.player.position.clone()); hugOverlay(pl.fromName || 'Someone'); notify('🤗 ' + (pl.fromName || 'Someone') + ' sent you a hug', 'allofus.one'); const lb = UI.LB && UI.LB(); if (lb) { lb.hugs = lb.hugs || { sent: 0, got: 0 }; lb.hugs.got++; UI.saveLB(lb); } } else if (fromR) hearts(fromR.g.position.clone(), toR ? toR.g.position.clone() : null); };
  // a hug link opened from an email / text
  try { const h = new URLSearchParams(location.search).get('hug'); if (h) { const d = JSON.parse(decodeURIComponent(escape(atob(h)))); const st = ['🤗', '🫂', '💛', '🌍', '🎉', '🌙'][d.s || 0]; setTimeout(() => { hugOverlay((d.f || 'A friend').slice(0, 40), st, (d.t ? 'For ' + d.t.slice(0, 40) + ': ' : '') + clean(d.m || '').slice(0, 240)); hearts(app.player.position.clone(), null); }, 2600); } } catch (e) { }

  /* ---------- Lifeboard tools ---------- */
  W.LB_EXTRA = { tabs: TOOL_TABS, make: (c) => makeTools(Object.assign({}, c, { toast: (m, ms) => app.toast(m, ms), celebrate: (e) => app.celebrate && app.celebrate(e), notify, halo: setHalo, getHalo, hug: sendHug, nearby, goPlace: (id) => { UI.close(); const p = (app.places || []).find(x => x.id === id); if (p) app.travel(p); }, allTabs: () => { const base = [['overview', '🧭', 'Overview', 'Me'], ['goals', '🎯', 'Goals', 'Plan'], ['vision', '🗺️', 'Vision', 'Plan'], ['work', '💼', 'Work', 'Plan'], ['wellness', '🌿', 'Wellness', 'Grow'], ['social', '🤝', 'Social', 'Connect'], ['giving', '❤️', 'Giving', 'Connect'], ['create', '🎨', 'Create', 'Make'], ['paths', '🛤️', 'Paths', 'Make'], ['home', '🏡', 'My home', 'Make'], ['buttons', '🔘', 'Buttons', 'Make']]; const order = ['Me', 'Plan', 'Grow', 'Money', 'Connect', 'Make']; return [...base, ...TOOL_TABS].sort((a, b) => order.indexOf(a[3]) - order.indexOf(b[3])); } })) };
  startReminders(() => UI.LB && UI.LB(), () => { const lb = UI.LB && UI.LB(); if (lb) UI.saveLB(lb); }, notify, (m, ms) => app.toast(m, ms));

  /* ---------- weather control (your view only) ---------- */
  const WX = { mode: 'clear', rain: null, snow: null, aurora: null, flash: 0 };
  const mkRain = () => { const N = window.innerWidth < 720 ? 900 : 2200; const g = new T.BufferGeometry(); const p = new Float32Array(N * 6); for (let i = 0; i < N; i++) { const x = (Math.random() - 0.5) * 60, y = Math.random() * 30, z = (Math.random() - 0.5) * 60; p.set([x, y, z, x + 0.05, y - 0.7, z], i * 6); } g.setAttribute('position', new T.BufferAttribute(p, 3)); const m = new T.LineSegments(g, new T.LineBasicMaterial({ color: 0xaecbe8, transparent: true, opacity: 0.55 })); m.frustumCulled = false; m.userData.noCollide = true; return m; };
  const mkSnow = () => { const N = window.innerWidth < 720 ? 900 : 2400; const g = new T.BufferGeometry(); const p = new Float32Array(N * 3); for (let i = 0; i < N; i++) p.set([(Math.random() - 0.5) * 70, Math.random() * 30, (Math.random() - 0.5) * 70], i * 3); g.setAttribute('position', new T.BufferAttribute(p, 3)); const m = new T.Points(g, new T.PointsMaterial({ color: 0xffffff, size: 0.18, transparent: true, opacity: 0.9, depthWrite: false })); m.frustumCulled = false; m.userData.noCollide = true; return m; };
  const mkAurora = () => { const grp = new T.Group(); for (let i = 0; i < 3; i++) { const geo = new T.PlaneGeometry(420, 70, 80, 1); const mat = new T.ShaderMaterial({ uniforms: { t: { value: 0 }, c: { value: new T.Color([0x3dff9a, 0x38f0ff, 0xb08cff][i]) } }, transparent: true, depthWrite: false, side: T.DoubleSide, blending: T.AdditiveBlending, fog: false, vertexShader: 'uniform float t; varying vec2 vUv; void main(){ vUv=uv; vec3 p=position; p.z+=sin(p.x*0.02+t*0.4)*18.0; p.y+=sin(p.x*0.035+t*0.6)*5.0; gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}', fragmentShader: 'uniform float t; uniform vec3 c; varying vec2 vUv; void main(){ float a=smoothstep(0.0,0.6,vUv.y)*smoothstep(1.0,0.5,vUv.y)*(0.5+0.5*sin(vUv.x*40.0+t)); gl_FragColor=vec4(c,a*0.55);}' }); const m = new T.Mesh(geo, mat); m.position.set(0, 120 + i * 14, -260 + i * 30); m.rotation.x = 0.2; m.frustumCulled = false; m.userData.noCollide = true; grp.add(m); } return grp; };
  const clearWx = () => { for (const k of ['rain', 'snow', 'aurora']) if (WX[k]) { app.scene.remove(WX[k]); WX[k] = null; } if (app.hemi) app.hemi.intensity = app.isNight ? 0.35 : 0.75; if (app.scene.fog && WX.fog0) { app.scene.fog.near = WX.fog0[0]; app.scene.fog.far = WX.fog0[1]; } };
  const setWeather = (mode) => { clearWx(); WX.mode = mode; globalThis.AOU_WEATHER = mode; WX.fog0 = WX.fog0 || (app.scene.fog ? [app.scene.fog.near, app.scene.fog.far] : null); const P = app.player.position;
    if (mode === 'rain' || mode === 'storm') { WX.rain = mkRain(); app.scene.add(WX.rain); if (app.scene.fog) { app.scene.fog.near = 30; app.scene.fog.far = mode === 'storm' ? 140 : 240; } }
    if (mode === 'snow') { WX.snow = mkSnow(); app.scene.add(WX.snow); if (app.scene.fog) { app.scene.fog.near = 40; app.scene.fog.far = 260; } }
    if (mode === 'fog' && app.scene.fog) { app.scene.fog.near = 6; app.scene.fog.far = 90; }
    if (mode === 'aurora') { if (!app.isNight) app.setSky(SKIES.night, { night: true }); WX.aurora = mkAurora(); app.scene.add(WX.aurora); }
    if (mode === 'sunset') app.setSky(SKIES.meadow, { night: false }); if (mode === 'clear') app.setSky(SKIES.day, { night: false }); if (mode === 'beach') app.setSky(SKIES.beach, { night: false });
    save('aou_wx', mode); UI.renderDock && setTimeout(UI.renderDock, 60); };
  app.onUpdate((dt, t) => { const P = app.player.position;
    if (WX.rain) { WX.rain.position.set(P.x, P.y, P.z); const a = WX.rain.geometry.attributes.position.array; const sp = WX.mode === 'storm' ? 34 : 24; for (let i = 0; i < a.length; i += 6) { a[i + 1] -= sp * dt; a[i + 4] -= sp * dt; if (a[i + 1] < -2) { a[i + 1] += 30; a[i + 4] += 30; } } WX.rain.geometry.attributes.position.needsUpdate = true; }
    if (WX.snow) { WX.snow.position.set(P.x, P.y, P.z); const a = WX.snow.geometry.attributes.position.array; for (let i = 0; i < a.length; i += 3) { a[i + 1] -= 2.2 * dt; a[i] += Math.sin(t + i) * 0.4 * dt; if (a[i + 1] < -2) a[i + 1] += 30; } WX.snow.geometry.attributes.position.needsUpdate = true; }
    if (WX.aurora) { WX.aurora.position.set(P.x, 0, P.z); WX.aurora.children.forEach(m => m.material.uniforms.t.value = t); }
    if (WX.mode === 'storm') { WX.flash -= dt; if (WX.flash < -2 - Math.random() * 6) WX.flash = 0.18; const on = WX.flash > 0; if (app.hemi) app.hemi.intensity = on ? 3.2 : (app.isNight ? 0.35 : 0.55); } });
  const openWeather = () => { const L = [['clear', '☀️ Clear'], ['sunset', '🌅 Golden hour'], ['rain', '🌧️ Rain'], ['storm', '⛈️ Thunderstorm'], ['snow', '❄️ Snow'], ['fog', '🌫️ Fog'], ['aurora', '🌌 Northern lights'], ['beach', '🏝️ Tropical sky'], ['night', app.isNight ? '☀️ Daytime' : '🌙 Night']];
    const m = UI.modal('⛅ Weather control', `<p class="muted2">Change the sky and weather. Only your view changes, so nobody gets rained on without asking.</p><div class="pl-grid">${L.map(([k, l]) => `<button class="pl-tile ${WX.mode === k ? 'on' : ''}" data-wx="${k}">${l}</button>`).join('')}</div>`);
    $$('[data-wx]', m).forEach(b => b.onclick = () => { const k = b.dataset.wx; if (k === 'night') { const n = !app.isNight; app.setSky(n ? SKIES.night : SKIES.day, { night: n }); if (WX.mode === 'aurora' && !n) setWeather('clear'); } else setWeather(k); UI.close(); app.toast('⛅ ' + b.textContent); }); };
  try { const w0 = load('aou_wx', 'clear'); if (w0 && w0 !== 'clear') setTimeout(() => setWeather(w0), 3000); } catch (e) { }

  /* ---------- 🌐 Worlds globe directory ---------- */
  const openWorlds = () => { const o = document.createElement('div'); o.className = 'pl-worlds'; o.innerHTML = `<div class="pw-card" role="dialog" aria-label="All our worlds"><div class="pw-head"><b>🌐 All our worlds</b><input id="pw-q" placeholder="Search worlds: shopping, comics, flight, business…" aria-label="Search worlds"><button class="aou-x" aria-label="Close">✕</button></div><div class="pw-body"><canvas id="pw-globe" width="560" height="560" aria-label="Spinning globe of worlds. Drag to spin, tap a pin."></canvas><div class="pw-list" id="pw-list"></div></div><p class="pw-foot">Drag the globe to spin it. Tap a glowing pin or a card to travel. Same login is coming to every world.</p></div>`; document.body.appendChild(o); app.paused = true;
    const close = () => { o.remove(); app.paused = false; cancelAnimationFrame(raf); }; o.querySelector('.aou-x').onclick = close; o.onclick = (e) => { if (e.target === o) close(); };
    const list = $('#pw-list', o); const draw = (q = '') => { const ql = q.toLowerCase(); list.innerHTML = WORLDS.filter(w => !ql || (w[0] + w[3] + w[4]).toLowerCase().includes(ql)).map((w, i) => `<a class="pw-item" href="${w[1]}" ${w[0] === 'allofus.one' ? '' : 'target="_blank" rel="noopener"'} data-i="${WORLDS.indexOf(w)}"><span>${w[2]}</span><div><b>${esc(w[0])}</b><small>${esc(w[3])} · ${w[4]}</small></div></a>`).join('') || '<p class="lt-empty">No world matches yet.</p>'; };
    draw(); $('#pw-q', o).oninput = (e) => draw(e.target.value); $('#pw-q', o).onkeydown = (e) => e.stopPropagation();
    const cv = $('#pw-globe', o); const g = cv.getContext('2d'); let rot = 0, tilt = 0.35, drag = null, vel = 0.004, raf = 0, hover = -1; const R = 230, C = 280; const pins = [];
    const proj = (lat, lon) => { const la = lat * Math.PI / 180, lo = lon * Math.PI / 180 + rot; let x = Math.cos(la) * Math.sin(lo), y = Math.sin(la), z = Math.cos(la) * Math.cos(lo); const y2 = y * Math.cos(tilt) - z * Math.sin(tilt), z2 = y * Math.sin(tilt) + z * Math.cos(tilt); return [C + x * R, C - y2 * R, z2]; };
    const frame = () => { if (!drag) rot += vel; g.clearRect(0, 0, 560, 560); const gr = g.createRadialGradient(C - 70, C - 80, 20, C, C, R); gr.addColorStop(0, '#7dd3fc'); gr.addColorStop(0.55, '#2563eb'); gr.addColorStop(1, '#0b1a4a'); g.fillStyle = gr; g.beginPath(); g.arc(C, C, R, 0, Math.PI * 2); g.fill();
      g.strokeStyle = 'rgba(255,255,255,.22)'; g.lineWidth = 1; for (let la = -60; la <= 60; la += 30) { g.beginPath(); let first = true; for (let lo = -180; lo <= 180; lo += 6) { const [x, y, z] = proj(la, lo); if (z < 0) { first = true; continue; } first ? g.moveTo(x, y) : g.lineTo(x, y); first = false; } g.stroke(); } for (let lo = -180; lo < 180; lo += 30) { g.beginPath(); let first = true; for (let la = -90; la <= 90; la += 6) { const [x, y, z] = proj(la, lo); if (z < 0) { first = true; continue; } first ? g.moveTo(x, y) : g.lineTo(x, y); first = false; } g.stroke(); }
      pins.length = 0; WORLDS.forEach((w, i) => { const [x, y, z] = proj(w[5], w[6]); if (z < 0.05) return; pins.push([x, y, i]); const s = 1 + z * 0.6; g.fillStyle = i === hover ? '#ffd23f' : '#ffffff'; g.shadowColor = '#38f0ff'; g.shadowBlur = 16; g.beginPath(); g.arc(x, y, 6 * s, 0, Math.PI * 2); g.fill(); g.shadowBlur = 0; g.font = `${Math.round(15 * s)}px serif`; g.textAlign = 'center'; g.fillText(w[2], x, y - 12 * s); if (i === hover || z > 0.85) { g.font = `bold ${Math.round(11 * s)}px Poppins, Arial`; g.fillStyle = '#fff'; g.fillText(w[0], x, y + 20 * s); } });
      const hl = g.createRadialGradient(C, C, R * 0.9, C, C, R * 1.12); hl.addColorStop(0, 'rgba(56,240,255,0)'); hl.addColorStop(1, 'rgba(56,240,255,.35)'); g.fillStyle = hl; g.beginPath(); g.arc(C, C, R * 1.12, 0, Math.PI * 2); g.fill(); raf = requestAnimationFrame(frame); };
    frame();
    const pt = (e) => { const r = cv.getBoundingClientRect(); return [(e.clientX - r.left) * 560 / r.width, (e.clientY - r.top) * 560 / r.height]; };
    cv.onpointerdown = (e) => { cv.setPointerCapture(e.pointerId); drag = { x: e.clientX, y: e.clientY, r: rot, t: tilt, moved: false }; };
    cv.onpointermove = (e) => { const [px, py] = pt(e); const h = pins.find(p => Math.hypot(p[0] - px, p[1] - py) < 16); hover = h ? h[2] : -1; cv.style.cursor = h ? 'pointer' : 'grab'; if (!drag) return; const dx = e.clientX - drag.x, dy = e.clientY - drag.y; if (Math.abs(dx) + Math.abs(dy) > 4) drag.moved = true; rot = drag.r + dx * 0.008; tilt = Math.max(-0.9, Math.min(0.9, drag.t + dy * 0.006)); vel = dx * 0.00005 || vel; };
    cv.onpointerup = (e) => { const moved = drag && drag.moved; drag = null; if (moved) return; const [px, py] = pt(e); const h = pins.find(p => Math.hypot(p[0] - px, p[1] - py) < 18); if (h) { const w = WORLDS[h[2]]; const it = list.querySelector(`[data-i="${h[2]}"]`); if (it) { it.scrollIntoView({ block: 'nearest', behavior: 'smooth' }); it.classList.add('hl'); setTimeout(() => it.classList.remove('hl'), 1400); } app.toast(w[2] + ' ' + w[0] + ': tap its card to travel'); } }; };

  /* ---------- 📡 friend scan ---------- */
  const band = () => { const me = getMe(); return (me && me.avatar && me.avatar.band) || load('aou_band', null); };
  const openScan = () => { const b = band(); if (!b) { const m = UI.modal('📡 Friend scan', `<p>Before we scan: which group are you in? Teens are only ever matched with teens, and adults with adults.</p><div class="pl-grid"><button class="pl-tile" data-b="teen">🧑‍🎓 13 to 17</button><button class="pl-tile" data-b="adult">🧑 18 or older</button></div><p class="muted2">Kids under 13 can explore with a grown-up but cannot use friend scan or chat.</p>`); $$('[data-b]', m).forEach(x => x.onclick = () => { save('aou_band', x.dataset.b); const me = getMe(); if (me) { me.avatar = Object.assign({}, me.avatar || {}, { band: x.dataset.b, v: Date.now() }); UI.syncAvatar && UI.syncAvatar(); } UI.close(); setTimeout(openScan, 120); }); return; }
    const me = getMe(); const myPaths = (me && me.paths) || []; const myCauses = (me && me.causes) || [];
    const m = UI.modal('📡 Friend scan', `<div class="pl-radar"><div class="sweep"></div>${'<i></i>'.repeat(6)}</div><p class="aou-lbl">Looking for</p><div class="aou-chips" id="fs-p">${LIFE_PATHS.map(p => `<button data-p="${p.id}" class="${myPaths.includes(p.id) ? 'on' : ''}">${p.icon} ${p.name}</button>`).join('')}</div><div class="lt-row"><label class="muted2"><input type="checkbox" id="fs-live" checked> Online now first</label><label class="muted2"><input type="checkbox" id="fs-c"> Same causes</label></div><div id="fs-out" class="lt-list"><p class="muted2">Scanning…</p></div>`, { wide: true });
    const want = new Set(myPaths); $$('#fs-p button', m).forEach(x => x.onclick = () => { want.has(x.dataset.p) ? want.delete(x.dataset.p) : want.add(x.dataset.p); x.classList.toggle('on'); run(); }); $('#fs-live', m).onchange = run; $('#fs-c', m).onchange = run;
    function run() { const liveFirst = $('#fs-live', m).checked, causes = $('#fs-c', m).checked; const all = nearby().filter(p => { const pb = (p.prof.avatar && p.prof.avatar.band) || (p.prof.demo ? 'adult' : null); if (b === 'teen' ? pb !== 'teen' : pb === 'teen') return false; if (p.prof.mode === 'dnd') return false; const paths = p.prof.paths || [p.prof.path]; if (want.size && !paths.some(x => want.has(x))) return false; if (causes && !(p.prof.causes || []).some(c => myCauses.includes(c))) return false; return true; });
      if (!liveFirst) all.sort((a, c) => a.d - c.d);
      $('#fs-out', m).innerHTML = all.length ? all.slice(0, 12).map(p => { const md = MODES[p.prof.mode] || MODES.hanging; const shared = (p.prof.paths || []).filter(x => want.has(x)).map(x => (LIFE_PATHS.find(q => q.id === x) || {}).icon).join(''); return `<div class="aou-li fs-row"><b><span class="dot" style="background:${md.css}"></span>${esc(p.name)}${p.live ? ' <span class="aou-tag">live</span>' : ''} ${shared}</b><small>${md.label} · ${p.d < 1000 ? Math.round(p.d) + ' m away' : 'far away'}</small><span class="fs-act"><button class="lt-btn sm" data-walk="${esc(p.id)}">📍 Walk to</button><button class="lt-btn sm" data-prof="${esc(p.id)}">👤 Profile</button><button class="lt-btn sm holo" data-hug2="${esc(p.id)}">🤗</button></span></div>`; }).join('') : '<p class="lt-empty">No matches nearby yet. Try more paths, or invite a friend.</p>';
      $$('[data-walk]', m).forEach(x => x.onclick = () => { const p = all.find(q => String(q.id) === x.dataset.walk); UI.close(); app.walkTo(p.g.position.x + 2, p.g.position.z + 2); });
      $$('[data-prof]', m).forEach(x => x.onclick = () => { const p = all.find(q => String(q.id) === x.dataset.prof); W.api.openProfile(p.prof); });
      $$('[data-hug2]', m).forEach(x => x.onclick = () => sendHug(all.find(q => String(q.id) === x.dataset.hug2))); }
    setTimeout(run, 900); };

  /* ---------- profile cards: hug, report, block ---------- */
  const blocked = new Set(load('aou_blocked', []));
  const op0 = W.api.openProfile; W.api.openProfile = (p) => { op0(p); const me = getMe(); if (me && p.id === me.id) return; setTimeout(() => { const card = UI.cur && UI.cur.querySelector('.aou-card'); if (!card || card.querySelector('.pl-prof')) return; const bar = document.createElement('div'); bar.className = 'pl-prof'; bar.innerHTML = `<button class="lt-btn holo" data-x="hug">🤗 Send a hug</button><button class="lt-btn" data-x="report">🚩 Report</button><button class="lt-btn" data-x="block">${blocked.has(p.id) ? '✅ Unblock' : '🚫 Block'}</button>`; (card.querySelector('.aou-body') || card).appendChild(bar);
      bar.onclick = async (e) => { const x = e.target.closest('[data-x]'); if (!x) return; const a = x.dataset.x; const r = [...W.remote.values()].find(q => q.id === p.id); const res = W.residents.find(q => q.prof.id === p.id);
        if (a === 'hug') sendHug({ id: p.id, name: p.name, g: (r || res || {}).g, live: !!r });
        if (a === 'block') { blocked.has(p.id) ? blocked.delete(p.id) : blocked.add(p.id); save('aou_blocked', [...blocked]); x.textContent = blocked.has(p.id) ? '✅ Unblock' : '🚫 Block'; if (r) r.g.visible = !blocked.has(p.id); app.toast(blocked.has(p.id) ? '🚫 Blocked. You will not see them or their messages.' : 'Unblocked.'); }
        if (a === 'report') { const why = prompt('What happened? (A real person reviews every report.)'); if (!why) return; try { if (DB.live && me) await DB.sb.from('reports').insert({ reporter: me.id, reported: p.id, reason: clean(why).slice(0, 500) }); app.toast('🚩 Thank you. Report sent for review.'); } catch (err) { app.toast('🚩 Could not send. Use the contact on allofus.one/privacy if it is urgent.'); } } }; }, 60); };
  app.onUpdate(() => { if (!blocked.size) return; for (const r of W.remote.values()) if (blocked.has(r.id)) r.g.visible = false; });

  /* ---------- family-friendly filter on everything people type ---------- */
  for (const k of ['send', 'sendRoom', 'post', 'wish', 'addMatch']) { const f = DB[k]; if (typeof f !== 'function') continue; DB[k] = function (...args) { const i = args.findIndex(a => typeof a === 'string'); if (i >= 0) args[i] = clean(args[i]); for (const a of args) if (a && typeof a === 'object' && !Array.isArray(a)) for (const kk of ['body', 'title', 'details']) if (typeof a[kk] === 'string') a[kk] = clean(a[kk]); return f.apply(this, args); }; }
  // rooms: drop messages from people you blocked
  if (DB.room) { const r0 = DB.room.bind(DB); DB.room = (id) => r0(id).filter(m => !m.sender || !blocked.has(m.sender)); }

  /* ---------- age + rules checkbox on Join ---------- */
  new MutationObserver(() => { const go = document.getElementById('j-go'); if (!go || go.dataset.age) return; go.dataset.age = '1'; const box = document.createElement('label'); box.className = 'pl-age'; box.innerHTML = `<input type="checkbox" id="j-age"><span>I am 13 or older and I agree to the <a href="/terms/" target="_blank">Terms</a> and <a href="/community-rules/" target="_blank">Community Rules</a> (kind, family friendly, no exceptions).</span>`; go.parentElement.parentElement.insertBefore(box, go.parentElement);
    go.addEventListener('click', (e) => { if (!document.getElementById('j-age').checked) { e.stopImmediatePropagation(); e.preventDefault(); const er = document.getElementById('j-err'); if (er) er.textContent = 'Please check the box to agree first.'; } }, true); }).observe(document.body, { childList: true, subtree: true });

  /* ---------- 🛡️ admin console (admin emails live only in the private SQL file) ---------- */
  const openAdmin = async () => { if (!UI.isAdmin) { app.toast('🛡️ Admins only.'); return; } const m = UI.modal('🛡️ Admin console', `<p class="muted2">Loading…</p>`, { wide: true }); const body = m.querySelector('.aou-body') || m.querySelector('.aou-card');
    try { const { data: users, error } = await DB.sb.rpc('admin_users'); if (error) throw error; const { data: reps } = await DB.sb.from('reports').select('*').order('created_at', { ascending: false }).limit(50); const last = load('aou_admin_seen', 0); const now = Date.now(); const d1 = users.filter(u => now - new Date(u.created_at) < 86400000).length, d7 = users.filter(u => now - new Date(u.created_at) < 7 * 86400000).length, fresh = users.filter(u => new Date(u.created_at) > last).length; save('aou_admin_seen', now);
      body.innerHTML = `<div class="lt-split"><div><b>${users.length}</b><small>accounts</small></div><div><b>${d1}</b><small>new today</small></div><div><b>${d7}</b><small>new this week</small></div><div><b>${fresh}</b><small>new since your last visit</small></div></div>
        <div class="lt-row"><input class="lt-in" id="ad-q" placeholder="Search name, username, email, city" style="max-width:320px"><button class="lt-btn" id="ad-csv">⬇️ Export CSV</button></div>
        <div class="pl-table"><table><thead><tr><th>Name</th><th>Email</th><th>City</th><th>Joined</th><th>Last in</th><th></th></tr></thead><tbody id="ad-rows"></tbody></table></div>
        <h3>🚩 Reports (${(reps || []).filter(r => !r.resolved).length} open)</h3>${(reps || []).map(r => `<div class="habit ${r.resolved ? 'lt-rem done' : ''}"><div><b>${esc(r.reason)}</b><small class="muted2">${new Date(r.created_at).toLocaleString()} · reported ${esc(String(r.reported).slice(0, 8))}</small></div><span><button class="lt-btn sm" data-ban="${r.reported}">🚫 Ban</button><button class="lt-btn sm" data-res="${r.id}">✓ Resolve</button></span></div>`).join('') || '<p class="lt-empty">No reports. 🌍</p>'}`;
      const rows = (q = '') => { const ql = q.toLowerCase(); $('#ad-rows', body).innerHTML = users.filter(u => !ql || [u.display_name, u.username, u.email, u.city].join(' ').toLowerCase().includes(ql)).map(u => `<tr class="${u.banned ? 'ban' : ''}"><td><b>${esc(u.display_name)}</b><br><small>@${esc(u.username || '')}</small></td><td>${esc(u.email)}</td><td>${esc(u.city || '')}</td><td>${new Date(u.created_at).toLocaleDateString()}</td><td>${u.last_sign_in_at ? new Date(u.last_sign_in_at).toLocaleDateString() : ''}</td><td><button class="lt-btn sm" data-ban="${u.id}" data-on="${u.banned ? 0 : 1}">${u.banned ? 'Unban' : 'Ban'}</button></td></tr>`).join(''); };
      rows(); $('#ad-q', body).oninput = (e) => rows(e.target.value); $('#ad-q', body).onkeydown = (e) => e.stopPropagation();
      $('#ad-csv', body).onclick = () => { const csv = ['name,username,email,city,joined,last_sign_in,banned', ...users.map(u => [u.display_name, u.username, u.email, u.city, u.created_at, u.last_sign_in_at, u.banned].map(v => '"' + String(v == null ? '' : v).replace(/"/g, '""') + '"').join(','))].join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'allofus-accounts.csv'; a.click(); };
      body.onclick = async (e) => { const bb = e.target.closest('[data-ban]'); const rr = e.target.closest('[data-res]'); if (bb) { const on = bb.dataset.on !== '0'; if (!confirm((on ? 'Ban' : 'Unban') + ' this account?')) return; await DB.sb.rpc('admin_set_ban', { p_user: bb.dataset.ban, p_on: on }); app.toast(on ? '🚫 Banned' : 'Unbanned'); UI.close(); openAdmin(); } if (rr) { await DB.sb.from('reports').update({ resolved: true }).eq('id', rr.dataset.res); UI.close(); openAdmin(); } };
    } catch (err) { body.innerHTML = `<p>Admin data is not set up yet. Run <b>allofus-admin-upgrade.sql</b> in Supabase → SQL Editor, then sign out and back in.</p><p class="muted2">${esc(err.message || err)}</p>`; } };

  /* ---------- 🎙️ voice chat (real WebRTC, rooms split teens / adults) ---------- */
  let voice = null; const vpill = document.createElement('div'); vpill.id = 'pl-voice'; vpill.style.display = 'none'; (document.getElementById('wvm-stage') || document.body).appendChild(vpill);
  const drawPill = (st) => { if (!st || !st.room) { vpill.style.display = 'none'; return; } vpill.style.display = ''; vpill.innerHTML = `<span class="vl" id="pv-l"></span><b>🎙️ ${esc(st.room.replace(/-(teen|adult)$/, ''))}</b><small>${st.peers.filter(p => p.state === 'connected').length + 1} here</small><button data-v="mute">${st.muted ? '🔇 Unmute' : '🎤 Mute'}</button><button data-v="who">👥</button><button data-v="leave">✕ Leave</button>`; };
  vpill.onclick = (e) => { const b = e.target.closest('[data-v]'); if (!b || !voice) return; const a = b.dataset.v; if (a === 'mute') voice.mute(); if (a === 'leave') voice.leave(); if (a === 'who') { const st = voice.status(); UI.modal('🎙️ In this voice room', `<div class="lt-list">${st.peers.map(p => `<div class="aou-li"><b>${esc(p.name)}</b><small>${p.state}</small></div>`).join('') || '<p class="lt-empty">Just you so far. Invite someone!</p>'}</div><p class="muted2">Voice goes directly between browsers and is never recorded. Report anyone who breaks the Community Rules.</p>`); } };
  setInterval(() => { if (!voice || !voice.status().room) return; const l = document.getElementById('pv-l'); if (l) l.style.transform = 'scale(' + (1 + Math.min(1, voice.level('me') * 4)) + ')'; }, 120);
  const joinVoice = async (base = 'nearby') => { const me = getMe(); if (!me) { app.toast('✨ Join first to use voice chat.'); window.AOU.join && window.AOU.join('Join to talk with people.'); return; } if (!DB.live) { app.toast('🎙️ Voice needs the live server (accounts on).'); return; } const b = band(); if (!b) { openScan(); app.toast('Pick your age group first: voice rooms keep teens with teens and adults with adults.', 4200); return; }
    if (!navigator.mediaDevices || !window.RTCPeerConnection) { app.toast('🎙️ This browser does not support voice chat.'); return; }
    let room = base; if (base === 'nearby') { const P = app.player.position; room = 'area-' + Math.round(P.x / 150) + '_' + Math.round(P.z / 150); }
    room += '-' + b; const ice = (CONFIG.TURN ? [...ICE, CONFIG.TURN] : ICE);
    if (!voice) voice = createVoice({ transport: supabaseTransport(DB.sb, me.id), myId: me.id, myName: me.name, iceServers: ice, onChange: drawPill, getVolume: (id) => { if (/^conference/.test(voice.status().room || '')) return 1; const r = W.remote.get(id); if (!r) return 0.8; const d = Math.hypot(r.g.position.x - app.player.position.x, r.g.position.z - app.player.position.z); return d < 8 ? 1 : Math.max(0.12, 1 - (d - 8) / 70); } });
    try { await voice.join(room); app.toast('🎙️ Voice on. People in this room can hear you. Tap 🎤 Mute anytime.', 3800); } catch (e) { app.toast('🎙️ Microphone blocked or unavailable: ' + (e.message || e), 4200); } };
  const openVoice = () => { const st = voice && voice.status(); const m = UI.modal('🎙️ Voice chat', `<p>Talk out loud with people in the world. Real peer-to-peer audio, never recorded. Teens only hear teens, adults only hear adults.</p>${st && st.room ? `<p class="lt-good">You are in <b>${esc(st.room)}</b>.</p>` : ''}<div class="pl-grid">${[['nearby', '📍 People near me'], ['plaza', '🌍 Central Plaza'], ['conference', '🎤 Conference hall'], ['office-zach', '💼 Zach\'s office'], ['town-square', '💬 Town Square'], ['coburn', '🏔️ Coburn\'s Place']].map(([k, l]) => `<button class="pl-tile" data-r="${k}">${l}</button>`).join('')}</div>${st && st.room ? '<p><button class="lt-btn" id="vc-leave">✕ Leave voice</button></p>' : ''}<p class="muted2">Tip: headphones stop echo. Some strict office or school networks block peer-to-peer audio.</p>`); $$('[data-r]', m).forEach(b => b.onclick = () => { UI.close(); joinVoice(b.dataset.r); }); const lv = $('#vc-leave', m); if (lv) lv.onclick = () => { UI.close(); voice.leave(); }; };
  // event invite links: ?event=…
  try { const ev = new URLSearchParams(location.search).get('event'); if (ev) { const d = JSON.parse(decodeURIComponent(escape(atob(ev)))); setTimeout(() => app.popup('🎤 ' + clean(d.t || 'Event').slice(0, 60), `<p><b>${new Date(d.at).toLocaleString('en-US', { weekday: 'long', month: 'long', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</b></p>${d.d ? '<p>' + esc(clean(d.d).slice(0, 400)) + '</p>' : ''}<p>You are here. When it starts, join the voice room and grab a seat.</p>`, [{ label: '🎙️ Join voice', primary: true, fn: () => joinVoice('conference') }]), 6000); } } catch (e) { }

  /* ---------- ✨ More sheet (the second half of the dock) ---------- */
  const moreAction = (a) => { const acts = { directory: () => opts.build && opts.build.openDirectory(), builder: () => opts.build && opts.build.openBuilder(), voice: openVoice, conference: () => { const p = (app.places || []).find(x => x.id === 'conference'); if (p) app.travel(p); }, ski: () => { const p = (app.places || []).find(x => x.id === 'ski'); if (p) app.travel(p); }, worlds: openWorlds, weather: openWeather, scan: openScan, hug: () => { const n = nearby(); if (n[0] && n[0].d < 40) sendHug(n[0]); else W.api.openLifeboard && W.api.openLifeboard('hugs'); }, halo: () => W.api.openLifeboard && W.api.openLifeboard('halo'), admin: openAdmin }; (acts[a] || (() => { }))(); };
  W.api.moreAction = moreAction;
  W.api.openMore = () => { const me = getMe(); const tiles = [
      ['directory', '📒', 'Directory', 'Every place + home address'], ['builder', '🏗️', 'Home builder', 'Walls, roofs, pools, blocks'], ['voice', '🎙️', 'Voice chat', 'Talk out loud, live'], ['conference', '🎤', 'Conference', 'Present on a 26 m screen'], ['ski', '⛷️', 'Ski + Coburn\'s', 'Lift, ski run, summit'], ['tour', '🎬', 'Take the tour', 'Both worlds in 2 min'], ['shrink', '🐜', 'Shrink to ant size', 'Everything becomes giant'], ['golf', '⛳', 'Unity Links golf', 'Sky Range · 6 clubs'], ['mall', '🛍️', 'World VR Mall', 'Shop small + prize hunt'],
      ['worlds', '🌐', 'All worlds', 'Mall, comics, galaxy, flight + more'], ['scan', '📡', 'Friend scan', 'Find your people nearby'], ['hug', '🤗', 'Send a hug', 'Free, unlimited'], ['halo', '😇', 'Halo sign', 'Float your vibe overhead'],
      ['weather', '⛅', 'Weather', 'Rain, snow, aurora, storms'], ['match', '🤝', 'Global Match', 'I have ↔ I need'], ['invite', '✉️', 'Invite', 'Bring a friend'], ['map', '🗺️', 'Map', 'Every place, searchable'],
      ['find', '🔍', 'Find a place', 'Search + teleport'], ['me', '🧑', 'My character', 'Body, face, clothes'], ['lumi3d', '💡', W.lumi && W.lumi.visible ? 'Hide Lumi orb' : 'Show Lumi orb', 'Your floating guide'], ['hub', '⬡', 'My Comm Hub', 'Inbox, requests, configurator'], ['arcade', '🎮', 'Arcade screen', 'Play games right here'], ['flat', '📰', 'FLAT · feed + my page', 'The flat side, your way'], ['groups', '🛍️', 'Buy · sell · trade', 'National groups'], ['mission', '✌️', 'Our mission', 'Why this exists'], ['ailb', '🤖', 'AI Lifeboard', 'ailifeboard.com · the app'], ['rules', '📜', 'Rules + safety', 'Kind, family friendly'], ['bug', '🐞', 'Report a bug', 'Still polishing, tell us'],
      ...(UI.isAdmin ? [['admin', '🛡️', 'Admin', 'Accounts, reports, bans'], ['super', '🦸', app.superAdmin ? 'Super admin: ON' : 'Super admin mode', 'Fly anywhere, 3× speed']] : [])];
    const m = UI.modal('✨ More', `<div class="pl-more">${tiles.map(([k, ic, n, s]) => `<button class="lt-holo" data-mo="${k}"><span class="ic">${ic}</span><b>${n}</b><small>${s}</small></button>`).join('')}</div><p class="pl-legal">© 2026 allofus.one · <a href="/terms/">Terms</a> · <a href="/privacy/">Privacy</a> · <a href="/community-rules/">Community Rules</a> · <a href="/accessibility/">Accessibility</a></p>`, { wide: true });
    $$('[data-mo]', m).forEach(b => b.onclick = () => { const k = b.dataset.mo; UI.close(); setTimeout(() => {
      if (k === 'arcade') { const G = [['🪐 The VR Galaxy', 'https://thevrgalaxy.com/'], ['🌀 Another Dimension', 'https://anotherdimensionvr.com/'], ['✈️ VR Flying Simulator', 'https://vrflyingsimulator.com/'], ['🧭 VR Adventure', 'https://virtualrealityadventure.com/'], ['💥 Comics Come Alive', 'https://comicscomealive.com/']]; const m = UI.modal('🎮 Arcade screen', `<div class="aou-chips">${G.map(([n, u], i) => `<button class="${i ? '' : 'on'}" data-g="${u}">${n}</button>`).join('')}</div><iframe id="ar-f" src="${G[0][1]}" style="width:100%;height:62vh;border:1px solid #e2e8f0;border-radius:12px;margin-top:8px" title="Game" allow="fullscreen; gamepad"></iframe><p class="muted2">Full screen for the best game: open it in its own tab with the link above the game.</p>`, { wide: true }); m.querySelectorAll('[data-g]').forEach(b => b.onclick = () => { m.querySelectorAll('[data-g]').forEach(q => q.classList.toggle('on', q === b)); m.querySelector('#ar-f').src = b.dataset.g; }); } else if (k === 'hub') { const me = getMe && getMe(); W.openHub(me ? { id: me.id, name: me.name, username: me.username, home: me.home || {} } : null); } else if (k === 'flat') location.href = '/flat/'; else if (k === 'groups') location.href = '/flat/?g=general'; else if (k === 'mission') location.href = '/mission/'; else if (k === 'ailb') location.href = 'https://www.ailifeboard.com/'; else if (k === 'bug') reportBug(); else if (k === 'super') { app.superAdmin = !app.superAdmin; app.speedMul = app.superAdmin ? 3 : 1; UI.toast(app.superAdmin ? '🦸 Super admin ON: fly with ⬆⬇ or Q/E, 3× speed, any height.' : '🦸 Super admin off.'); } else if (k === 'shrink') app.setShrink && app.setShrink(!(app.shrink && app.shrink < 1)); else if (k === 'golf') { const p = (app.places || []).find(q => q.id === 'skyrange'); if (p) app.travel(p); } else if (k === 'tour') location.href = 'https://worldvrmall.com/tour/'; else if (k === 'mall') location.href = 'https://worldvrmall.com/'; else if (k === 'match') W.api.openMatch(); else if (k === 'invite') window.AOU.openInvite(); else if (k === 'map') document.getElementById('wvm-map') && document.getElementById('wvm-map').click(); else if (k === 'find') document.getElementById('wvm-find') && document.getElementById('wvm-find').click(); else if (k === 'me') app.openSelfie(); else if (k === 'rules') window.open('/community-rules/', '_blank'); else if (k === 'lumi3d') { if (W.lumi) { W.lumi.visible = !W.lumi.visible; save('aou_lumi3d', W.lumi.visible); app.toast(W.lumi.visible ? '💡 Lumi orb on' : 'Lumi orb hidden'); } } else moreAction(k); }, 80); }); };

  /* ---------- Lumi: the floating 3D orb stays home unless you ask for it ---------- */
  if (W.lumi) W.lumi.visible = !!load('aou_lumi3d', false);

  /* ---------- legal + copyright strip in the HUD ---------- */
  const lg = document.createElement('div'); lg.id = 'pl-copy'; lg.innerHTML = '© 2026 allofus.one · <a href="/terms/">Terms</a> · <a href="/privacy/">Privacy</a> · <a href="/community-rules/">Rules</a>'; (document.getElementById('wvm-stage') || document.body).appendChild(lg);

  /* ---------- sign-in → ownership, admin, mansion sign ---------- */
  const after = async () => { await refreshOwned(); const ms = opts.estates && opts.estates.mansion; if (!ms || !DB.live) return; try { const { data: oid } = await DB.sb.rpc('estate_owner', { p_slug: 'founder' }); const op = oid && (W.profileCache.get(oid) || await DB.profile(oid)); const n = op && op.home && op.home.notice; if (n && n.t) ms.setNotice(clean(n.t), n.c); } catch (e) { } };
  after(); if (DB.sb) DB.sb.auth.onAuthStateChange(() => setTimeout(after, 400));
  window.AOU = Object.assign(window.AOU || {}, { clean });
  return { joinVoice, openVoice, isOwner, deviceUnlock, openWorlds, openWeather, openScan, sendHug, setHalo, openAdmin, refreshOwned, setNotice: async (t, c) => { const me = getMe(); const ms = opts.estates && opts.estates.mansion; if (!ms) return; ms.setNotice(clean(t), c); if (me && isOwner('founder')) { me.home = Object.assign({}, me.home || {}, { notice: { t: clean(t).slice(0, 40), c } }); try { await DB.saveMe(me); } catch (e) { } } } };
}

function injectCSS() { if (document.getElementById('pl-css')) return; const s = document.createElement('style'); s.id = 'pl-css'; s.textContent = LIFETOOLS_CSS + `
#aou-dock button.more{background:linear-gradient(135deg,#0ea5e9,#6366f1 55%,#a855f7);color:#fff;border-color:transparent}#aou-dock button.more small{color:#fff}
.pl-more{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}@media (max-width:720px){.pl-more{grid-template-columns:1fr 1fr}}
.pl-legal{margin:12px 0 0;font-size:12px;color:#64748b;text-align:center}.pl-legal a{color:#2563eb}
.pl-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}@media (max-width:520px){.pl-grid{grid-template-columns:1fr 1fr}}
.pl-tile{border:1px solid #e2e8f0;background:#f8fafc;border-radius:14px;padding:14px 8px;font:800 14px Poppins,Arial;color:#0f172a;cursor:pointer}.pl-tile.on,.pl-tile:hover{background:#eef2ff;border-color:#818cf8}
.pl-prof{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px;padding-top:10px;border-top:1px solid #e2e8f0}
.pl-age{display:flex;gap:8px;align-items:flex-start;font-size:13px;color:#334155;margin:8px 0;line-height:1.4}.pl-age input{width:20px;height:20px;flex:none;accent-color:#16a34a}.pl-age a{color:#2563eb;font-weight:700}
.pl-worlds{position:fixed;inset:0;z-index:99990;background:rgba(2,6,23,.62);backdrop-filter:blur(6px);display:flex;align-items:center;justify-content:center;padding:12px}
.pw-card{background:#fff;color:#0f172a;border-radius:22px;width:min(1040px,100%);max-height:94vh;display:flex;flex-direction:column;overflow:hidden;box-shadow:0 30px 90px rgba(2,6,23,.5)}
.pw-head{display:flex;gap:10px;align-items:center;padding:12px 14px;border-bottom:1px solid #e2e8f0;background:linear-gradient(90deg,#ecfeff,#eef2ff)}.pw-head b{font:900 18px Poppins,Arial;white-space:nowrap}.pw-head input{flex:1;min-width:0;border:1px solid #cbd5e1;border-radius:999px;padding:9px 14px;font:600 14px Poppins,Arial}
.pw-head .aou-x{border:1px solid #e2e8f0;background:#fff;border-radius:10px;width:36px;height:36px;cursor:pointer;font-size:16px;color:#0f172a}
.pw-body{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:10px;padding:12px;overflow:auto;background:radial-gradient(circle at 30% 40%,#0b1a4a,#020617 70%)}
.pw-body canvas{width:100%;height:auto;max-width:520px;margin:auto;touch-action:none;cursor:grab}
.pw-list{display:flex;flex-direction:column;gap:8px;max-height:62vh;overflow:auto;padding-right:4px}
.pw-item{display:flex;gap:12px;align-items:center;text-decoration:none;color:#0f172a;background:#fff;border-radius:14px;padding:10px 12px;border:1px solid #e2e8f0;transition:.15s}.pw-item span{font-size:26px}.pw-item b{display:block;font:900 14.5px Poppins,Arial}.pw-item small{color:#475569}.pw-item:hover,.pw-item.hl{transform:translateX(4px);border-color:#38bdf8;box-shadow:0 0 0 3px rgba(56,189,248,.35)}
.pw-foot{margin:0;padding:8px 14px;font-size:12.5px;color:#475569;border-top:1px solid #e2e8f0}
@media (max-width:760px){.pw-body{grid-template-columns:1fr}.pw-body canvas{max-width:300px}.pw-list{max-height:none}}
.aou-hug{position:fixed;inset:0;z-index:99991;display:flex;align-items:center;justify-content:center;background:rgba(255,236,245,.55);backdrop-filter:blur(3px);animation:plIn .3s}
.aou-hug .hb{background:#fff;border-radius:26px;padding:24px 26px;text-align:center;max-width:min(420px,90vw);box-shadow:0 30px 80px rgba(236,72,153,.35);border:2px solid #fbcfe8}.aou-hug .he{font-size:84px;animation:plHug 1.2s ease-in-out infinite}.aou-hug b{display:block;font:900 22px Poppins,Arial;color:#831843;margin:6px 0}.aou-hug p{color:#475569}
.aou-hug .hr span{display:inline-block;font-size:24px;animation:plFloat 1.6s ease-in-out infinite;animation-delay:calc(var(--i)*.15s)}
@keyframes plHug{0%,100%{transform:scale(1)}50%{transform:scale(1.18) rotate(-4deg)}}@keyframes plFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}@keyframes plIn{from{opacity:0}to{opacity:1}}
.pl-radar{position:relative;width:170px;height:170px;margin:4px auto 10px;border-radius:50%;background:radial-gradient(circle,#052e2b 0,#064e3b 60%,#022c22 100%);box-shadow:0 0 0 2px #10b981 inset,0 0 30px rgba(16,185,129,.4);overflow:hidden}
.pl-radar:before,.pl-radar:after{content:"";position:absolute;inset:25%;border-radius:50%;border:1px solid rgba(16,185,129,.5)}.pl-radar:after{inset:45%}
.pl-radar .sweep{position:absolute;inset:0;border-radius:50%;background:conic-gradient(rgba(52,211,153,.55),transparent 25%);animation:plSpin 2s linear infinite}
.pl-radar i{position:absolute;width:8px;height:8px;border-radius:50%;background:#a7f3d0;box-shadow:0 0 10px #34d399;animation:plBlip 2s ease-in-out infinite}.pl-radar i:nth-child(2){left:30%;top:28%}.pl-radar i:nth-child(3){left:66%;top:40%;animation-delay:.4s}.pl-radar i:nth-child(4){left:40%;top:70%;animation-delay:.8s}.pl-radar i:nth-child(5){left:72%;top:72%;animation-delay:1.2s}.pl-radar i:nth-child(6){left:20%;top:55%;animation-delay:1.6s}.pl-radar i:nth-child(7){left:55%;top:18%;animation-delay:.2s}
@keyframes plSpin{to{transform:rotate(360deg)}}@keyframes plBlip{0%,100%{opacity:.15}50%{opacity:1}}
.fs-row{display:grid!important;grid-template-columns:1fr auto;gap:2px 8px;align-items:center}.fs-row small{grid-column:1}.fs-act{grid-row:1/3;grid-column:2;display:flex;gap:4px}
.pl-table{overflow:auto;max-height:46vh;border:1px solid #e2e8f0;border-radius:12px}.pl-table table{border-collapse:collapse;width:100%;font-size:13px}.pl-table th,.pl-table td{padding:8px 10px;border-bottom:1px solid #f1f5f9;text-align:left;vertical-align:top}.pl-table th{position:sticky;top:0;background:#f8fafc}.pl-table tr.ban{background:#fef2f2}
#pl-voice{position:absolute;left:50%;top:62px;transform:translateX(-50%);z-index:33;display:flex;align-items:center;gap:8px;background:rgba(255,255,255,.96);border-radius:999px;padding:6px 8px 6px 12px;box-shadow:0 8px 26px rgba(2,6,23,.3);font:700 13px Poppins,Arial;color:#0f172a;white-space:nowrap}#pl-voice small{color:#64748b}#pl-voice button{border:1px solid #e2e8f0;background:#fff;border-radius:999px;padding:6px 10px;font:800 12px Poppins,Arial;cursor:pointer}#pl-voice .vl{width:10px;height:10px;border-radius:50%;background:#22c55e;box-shadow:0 0 10px #22c55e;transition:transform .1s}
#pl-copy{position:absolute;right:10px;bottom:6px;z-index:28;font:600 11px Poppins,Arial;color:#fff;text-shadow:0 1px 3px rgba(0,0,0,.6);opacity:.85}#pl-copy a{color:#fff}
body.wvm-modal-open #pl-copy{display:none}@media (max-width:720px){#pl-copy{display:none}}
.wvm-char .fbadge{display:inline-block;margin-top:4px;font-style:normal;font-size:10.5px;font-weight:800;color:#065f46;background:#d1fae5;border-radius:999px;padding:2px 7px}.wvm-char .fbadge.no{color:#7c2d12;background:#ffedd5}
#wvm-list,#wvm-bag{display:none!important}
`; document.head.appendChild(s); }
