/* ============================================================
   No. 1 Unity Road · v5 (Oct 2026)
   Layered, angled architecture (not a box): a twisted terracotta
   wing with the DISCO ROOM inside, a charcoal cantilever, stepped
   glass terraces and a LIVING GREEN WALL.
   Rain → copper gutters → rain chains → RO + UV system → drinking
   water, showers and the organic garden, with a teaching demo that
   lights the pipes up blue. Organic rain pond with koi.
   Front-yard LAUNCH console for the backyard rocket.
   ⛳ UNITY LINKS · the Sky Range: a floating driving range with
   six clubs, power meter, wind, glowing trails, five floating
   target greens, a 3D scoreboard, ball-cam, and VR trigger swings.
   ============================================================ */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { M, glow, box, cyl, sph, textPlane, waterMaterial } from './aou-kit.js';
import { terrainY, addDeck } from './aou-terrain.js';
import { makeFlower } from './aou-garden.js';
const T = THREE; const MOB = isMobile();

export function buildUnityV5(app, W, X, Z) {
  const S = app.scene; const y0 = terrainY(X, Z) + 0.05; const toast = (m, ms) => app.toast(m, ms);
  const G = new T.Group(); G.position.set(X, y0, Z); G.userData.noCollide = true; S.add(G);
  const L = (lx, lz) => [X + lx, Z + lz];
  const terracotta = M(0xc2603a, { roughness: 0.8 }), charcoal = M(0x2b2f36, { roughness: 0.6, metalness: 0.2 }), sand = M(0xe9dcc4, { roughness: 0.85 }), copper = M(0xb87333, { metalness: 0.85, roughness: 0.3 }), glassM = new T.MeshPhysicalMaterial({ color: 0xcfefff, transparent: true, opacity: 0.28, roughness: 0.04, metalness: 0.2, depthWrite: false, side: T.DoubleSide }), strip = (c) => glow(c, 1.6);

  /* ---------- 1) the twisted wing: the DISCO ROOM (walk in) ---------- */
  const wing = new T.Group(); wing.position.set(4, 0, 20.5); wing.rotation.y = 0.48; G.add(wing);
  const WW = 13, WD = 9, WH = 5.2; box(WW, 0.3, WD, sand, 0, 0.15, 0, wing); box(WW, 0.35, WD, terracotta, 0, WH, 0, wing); box(0.35, WH, WD, terracotta, -WW / 2, WH / 2, 0, wing); box(0.35, WH, WD, terracotta, WW / 2, WH / 2, 0, wing); box(WW, WH, 0.35, terracotta, 0, WH / 2, WD / 2, wing); for (const sx of [-1, 1]) box(WW / 2 - 1.8, WH, 0.35, terracotta, sx * (WW / 4 + 0.9), WH / 2, -WD / 2, wing); box(3.6, 1.2, 0.35, terracotta, 0, WH - 0.6, -WD / 2, wing);
  box(WW + 0.4, 0.12, 0.12, strip(0xff4fd8), 0, WH + 0.2, -WD / 2 - 0.1, wing); box(0.12, 0.12, WD + 0.4, strip(0x38f0ff), WW / 2 + 0.1, WH + 0.2, 0, wing);
  const wingObs = []; const wp = (lx, lz) => { const c = Math.cos(0.48), s = Math.sin(0.48); return L(4 + lx * c + lz * s, 20.5 - lx * s + lz * c); }; for (let i = -6; i <= 6; i += 1.5) { wingObs.push(wp(i, WD / 2)); if (Math.abs(i) > 2) wingObs.push(wp(i, -WD / 2)); } for (let j = -4; j <= 4; j += 1.5) { wingObs.push(wp(-WW / 2, j)); wingObs.push(wp(WW / 2, j)); } wingObs.forEach(([x, z]) => app.addObstacle && app.addObstacle(x, z, 0.9));
  // LED dance floor: 10 x 7 tiles that change color to the beat
  const TX = 10, TZ = 7, tile = new T.InstancedMesh(new T.BoxGeometry(1.15, 0.08, 1.15), new T.MeshBasicMaterial({ color: 0xffffff }), TX * TZ); const m4 = new T.Matrix4(), col = new T.Color(); let k = 0; for (let i = 0; i < TX; i++) for (let j = 0; j < TZ; j++) { m4.makeTranslation(-5.4 + i * 1.2, 0.36, -3.6 + j * 1.2); tile.setMatrixAt(k, m4); tile.setColorAt(k++, col.setHSL(0, 1, 0.5)); } tile.instanceColor.needsUpdate = true; wing.add(tile);
  const ball = new T.Mesh(new T.IcosahedronGeometry(0.7, 2), new T.MeshStandardMaterial({ color: 0xffffff, metalness: 1, roughness: 0.1, flatShading: true, emissive: 0x333344 })); ball.position.y = WH - 1.2; wing.add(ball); cyl(0.02, 0.02, 0.9, M(0xcccccc), 0, WH - 0.45, 0, wing, 6);
  const beams = []; for (let i = 0; i < 6; i++) { const b = new T.Mesh(new T.ConeGeometry(0.9, WH - 1.2, 16, 1, true), new T.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.12, blending: T.AdditiveBlending, depthWrite: false, side: T.DoubleSide })); b.position.y = (WH - 1.2) / 2; const pv = new T.Group(); pv.position.y = WH - 1.2; pv.add(b); b.position.y = -(WH - 1.2) / 2; wing.add(pv); beams.push(pv); }
  const dsign = makeSprite('🪩 THE DISCO ROOM', { scale: 3.4, accent: '#ff4fd8' }); dsign.position.set(0, WH + 1.4, -WD / 2); wing.add(dsign);
  let beat = null, beatOn = false; const music = () => { beatOn = !beatOn; if (beatOn) { try { const AC = window.AudioContext || window.webkitAudioContext; const ac = new AC(); let n = 0; beat = setInterval(() => { const tt = ac.currentTime; const o = ac.createOscillator(), g2 = ac.createGain(); o.frequency.setValueAtTime(n % 2 ? 180 : 60, tt); o.frequency.exponentialRampToValueAtTime(40, tt + 0.12); g2.gain.setValueAtTime(0.2, tt); g2.gain.exponentialRampToValueAtTime(0.001, tt + 0.15); o.connect(g2); g2.connect(ac.destination); o.start(tt); o.stop(tt + 0.16); if (n % 2) { const h = ac.createOscillator(), hg = ac.createGain(); h.type = 'square'; h.frequency.value = 2400; hg.gain.setValueAtTime(0.02, tt); hg.gain.exponentialRampToValueAtTime(0.0001, tt + 0.04); h.connect(hg); hg.connect(ac.destination); h.start(tt); h.stop(tt + 0.05); } n++; }, 250); beat.ac = ac; } catch (e) { } toast('🪩 Music on. Dance!'); } else { if (beat) { clearInterval(beat); try { beat.ac.close(); } catch (e) { } } beat = null; toast('🪩 Music off.'); } };
  const [dx, dz] = wp(0, -WD / 2 - 1.5); app.addInteractable && app.addInteractable(dx, dz, 3, '🪩 Disco Room · music on/off', music); { const [cx, cz] = wp(0, 0); app.addInteractable && app.addInteractable(cx, cz, 4, '🪩 Dance! (music on/off)', music); }
  // charcoal cantilever floating over the wing, plus stepped glass terraces on the south side
  const cant = new T.Group(); cant.position.set(9, 8.3, 19); cant.rotation.y = -0.32; G.add(cant); box(12, 3.2, 7.5, charcoal, 0, 0, 0, cant); box(11.6, 1.2, 0.06, strip(0xffe9a8), 0, 0.2, 3.78, cant); box(11.6, 1.2, 0.06, strip(0xffe9a8), 0, 0.2, -3.78, cant); const greenRoof = new T.Mesh(new T.BoxGeometry(11.6, 0.25, 7.2), M(0x3f8f3a, { roughness: 1 })); greenRoof.position.y = 1.72; cant.add(greenRoof);
  [[-8, 2.4, -17, 9, 4.8, 0xf4f1ea], [-2, 4.2, -18.2, 8, 8.4, 0xd6d0c4], [4, 6.0, -19.4, 7, 12, 0xa8b5a2]].forEach(([x, h, z, w, yTop, c], i) => { const tg = new T.Group(); tg.position.set(x, 0, z); tg.rotation.y = -0.12 * i; G.add(tg); box(w, h, 5, M(c, { roughness: 0.7 }), 0, yTop - h / 2, 0, tg); box(w, 1.1, 0.06, glassM, 0, yTop + 0.55, -2.5, tg); for (let p = 0; p < 4; p++) { const pl = makeFlower(['lupine', 'tulip', 'allium', 'sunflower'][p], 0.9, i * 7 + p); pl.position.set(-w / 2 + 1 + p * (w - 2) / 3, yTop, 1.6); tg.add(pl); } });

  /* ---------- 2) the LIVING GREEN WALL on the front ---------- */
  const gw = new T.Group(); gw.position.set(-21.4, 0, 0); G.add(gw); const gwTex = (() => { const c = document.createElement('canvas'); c.width = 256; c.height = 512; const q = c.getContext('2d'); q.fillStyle = '#20462a'; q.fillRect(0, 0, 256, 512); for (let i = 0; i < 1400; i++) { q.fillStyle = `hsl(${85 + Math.random() * 60},${45 + Math.random() * 35}%,${22 + Math.random() * 30}%)`; q.beginPath(); q.ellipse(Math.random() * 256, Math.random() * 512, 4 + Math.random() * 9, 2 + Math.random() * 5, Math.random() * 3, 0, 6.28); q.fill(); } for (let i = 0; i < 90; i++) { q.fillStyle = ['#ff6f91', '#ffd23f', '#ffffff', '#b08cff'][i % 4]; q.beginPath(); q.arc(Math.random() * 256, Math.random() * 512, 2.5, 0, 6.28); q.fill(); } const t2 = new T.CanvasTexture(c); t2.colorSpace = T.SRGBColorSpace; t2.wrapS = t2.wrapT = T.RepeatWrapping; t2.repeat.set(3, 2); return t2; })();
  const gwm = new T.Mesh(new T.PlaneGeometry(14, 11), new T.MeshStandardMaterial({ map: gwTex, roughness: 1 })); gwm.rotation.y = -Math.PI / 2; gwm.position.set(0, 5.6, 0); gw.add(gwm); const leafM = M(0x3fa34d, { roughness: 0.9, side: T.DoubleSide }); const leaves = new T.InstancedMesh(new T.PlaneGeometry(0.5, 0.28), leafM, MOB ? 160 : 420); const d0 = new T.Object3D(); for (let i = 0; i < leaves.count; i++) { d0.position.set(-0.12 - Math.random() * 0.25, 0.4 + Math.random() * 10.6, -6.8 + Math.random() * 13.6); d0.rotation.set(Math.random() * 3, Math.random() * 3, Math.random() * 3); d0.scale.setScalar(0.6 + Math.random() * 0.9); d0.updateMatrix(); leaves.setMatrixAt(i, d0.matrix); } gw.add(leaves);
  for (let r = 0; r < 4; r++) { const drip = cyl(0.02, 0.02, 13.8, M(0x222222), -0.2, 2.2 + r * 2.7, 0, gw, 6); drip.rotation.x = Math.PI / 2; } const gwSign = makeSprite('🌿 Living wall · 3,000 plants on drip irrigation', { scale: 3.6, accent: '#7cff6b' }); gwSign.position.set(-1.2, 12, 0); gw.add(gwSign);
  app.addHotspot && app.addHotspot(gwm, { title: '🌿 The living wall', html: '<p>Thousands of plants growing straight up the front of the house, watered by the same rainwater system that feeds the garden. Green walls cool a building by several degrees in summer, clean the air and quiet street noise.</p>' });

  /* ---------- 3) RAIN → GUTTERS → RO + UV → TAPS, SHOWERS, POND + GARDEN (with the blue-water demo) ---------- */
  const RY = 13.4; const pipeM = M(0x6b7280, { metalness: 0.6, roughness: 0.4 }); const flowM = new T.ShaderMaterial({ uniforms: { t: { value: 0 }, on: { value: 0 } }, transparent: true, depthWrite: false, vertexShader: 'varying vec2 vUv; void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}', fragmentShader: 'uniform float t; uniform float on; varying vec2 vUv; void main(){ float s=fract(vUv.x*14.0-t*2.2); float w=smoothstep(0.0,0.25,s)*smoothstep(1.0,0.55,s); vec3 c=mix(vec3(0.1,0.45,1.0),vec3(0.75,0.95,1.0),w); gl_FragColor=vec4(c,on*(0.55+w*0.45)); }' });
  const pipe = (pts, r = 0.12) => { const cv = new T.CatmullRomCurve3(pts.map(p => new T.Vector3(...p)), false, 'catmullrom', 0.05); const p1 = new T.Mesh(new T.TubeGeometry(cv, Math.max(16, pts.length * 10), r, 8, false), pipeM); G.add(p1); const p2 = new T.Mesh(new T.TubeGeometry(cv, Math.max(16, pts.length * 10), r * 1.25, 8, false), flowM); p2.renderOrder = 4; G.add(p2); return cv; };
  // copper half-pipe gutters around the roofline + downspouts with rain chains
  const gutter = (x1, z1, x2, z2) => { const len = Math.hypot(x2 - x1, z2 - z1); const gm = new T.Mesh(new T.CylinderGeometry(0.22, 0.22, len, 12, 1, true, 0, Math.PI), new T.MeshStandardMaterial({ color: 0xb87333, metalness: 0.85, roughness: 0.3, side: T.DoubleSide })); gm.rotation.z = Math.PI / 2; gm.rotation.y = -Math.atan2(z2 - z1, x2 - x1); gm.rotation.order = 'YXZ'; gm.position.set((x1 + x2) / 2, RY, (z1 + z2) / 2); gm.rotateX(Math.PI); G.add(gm); };
  gutter(-21.2, -13.3, 13.2, -13.3); gutter(-21.2, 13.3, 13.2, 13.3); gutter(13.3, -13.3, 13.3, 13.3);
  const chains = []; for (const [x, z] of [[13.3, -13.3], [13.3, 13.3]]) { for (let i = 0; i < 18; i++) { const cup = cyl(0.12, 0.06, 0.18, copper, x, RY - 0.5 - i * 0.7, z, G, 10); chains.push(cup); } }
  const tankX = 20, tankZ = -10; const tank = new T.Group(); tank.position.set(tankX, 0, tankZ); G.add(tank); cyl(1.6, 1.6, 4.2, M(0x9ec5d8, { roughness: 0.4, metalness: 0.3 }), 0, 2.1, 0, tank, 28); const tankLvl = cyl(1.62, 1.62, 0.1, new T.MeshBasicMaterial({ color: 0x38bdf8, transparent: true, opacity: 0.6 }), 0, 0.6, 0, tank, 28); const tl = textPlane(['RAIN TANK', '2,500 gal'], 2.6, 1, { bg: '#0b2a4a', fg: '#fff', accent: '#38bdf8' }); tl.position.set(0, 2.6, 1.62); tank.add(tl);
  const ro = new T.Group(); ro.position.set(24.5, 0, -10); G.add(ro); const ST = [['Sediment', 0xe5e7eb], ['Carbon', 0x374151], ['RO membrane', 0x0ea5e9], ['UV light', 0xa855f7]]; ST.forEach(([n, c], i) => { const can = cyl(0.36, 0.36, 1.6, M(c, { roughness: 0.4, metalness: 0.2 }), -1.5 + i * 1, 1.3, 0, ro, 18); const lb = makeSprite(n, { scale: 1.6, accent: '#38bdf8' }); lb.position.set(-1.5 + i * 1, 2.6, 0); ro.add(lb); }); box(4.6, 0.3, 1.2, M(0x334155), 0, 0.3, 0, ro); const uvGlow = cyl(0.38, 0.38, 1.62, new T.MeshBasicMaterial({ color: 0xb388ff, transparent: true, opacity: 0, blending: T.AdditiveBlending, depthWrite: false }), 1.5, 1.3, 0, ro, 18);
  [[tankX, -10], [24.5, -10]].forEach(([x, z]) => app.addObstacle && app.addObstacle(...L(x, z), 2.1));
  const P1 = pipe([[13.3, 0.4, -13.3], [16, 0.35, -12], [tankX - 1.6, 0.6, tankZ]]); const P2 = pipe([[13.3, 0.4, 13.3], [17, 0.35, 6], [18.6, 0.35, -6], [tankX, 0.6, tankZ + 1.6]]);
  const P3 = pipe([[tankX + 1.6, 0.6, tankZ], [22.6, 0.6, -10], [23.0, 1.3, -10.6]], 0.1); const P4 = pipe([[26.4, 1.3, -10.4], [27.5, 0.5, -8], [24, 0.4, -2], [14, 0.4, -2], [12.2, 1.4, -2], [12.2, 4.5, -2], [12.2, 9.0, -2]], 0.1);
  const P5 = pipe([[26.6, 0.4, -9.4], [28, 0.3, -3], [26, 0.3, 4], [24.6, 0.3, 8]], 0.08); const P6 = pipe([[tankX, 0.3, tankZ + 1.6], [20, 0.25, -4], [21, 0.25, 4], [21.6, 0.25, 7]], 0.1);
  // the organic rain pond (no circles here) with koi, lilies and a boulder spillway
  const PX = 21, PZ = 9; const outline = []; for (let i = 0; i < 48; i++) { const a = i / 48 * Math.PI * 2; const r = 5.2 * (1 + 0.22 * Math.sin(3 * a + 0.7) + 0.12 * Math.cos(5 * a) + 0.08 * Math.sin(7 * a + 2)); outline.push(new T.Vector2(Math.cos(a) * r * 1.25, Math.sin(a) * r)); }
  const pshape = new T.Shape(outline); const pw = new T.Mesh(new T.ShapeGeometry(pshape, 6), waterMaterial(0x2a9ad8, 0x0b3f6e)); pw.rotation.x = -Math.PI / 2; pw.position.set(PX, 0.12, PZ); G.add(pw); const rim = new T.Shape(outline.map(v => v.clone().multiplyScalar(1.12))); rim.holes.push(new T.Path(outline)); const rm = new T.Mesh(new T.ShapeGeometry(rim, 6), M(0x9a8f7a, { roughness: 1 })); rm.rotation.x = -Math.PI / 2; rm.position.set(PX, 0.1, PZ); G.add(rm);
  for (let i = 0; i < 12; i++) { const a = i / 12 * 6.283; const v = outline[Math.floor(i * 4)]; const st = new T.Mesh(new T.DodecahedronGeometry(0.4 + (i % 3) * 0.25, 0), M(0x8d8f92, { flatShading: true, roughness: 1 })); st.position.set(PX + v.x * 1.06, 0.25, PZ - v.y * 1.06); st.rotation.set(i, i * 2, i); G.add(st); }
  const koi = []; for (let i = 0; i < 9; i++) { const f = new T.Group(); const b = sph(0.22, M([0xff6a1f, 0xffffff, 0xffd23f][i % 3], { roughness: 0.35 }), 0, 0, 0, f, 10); b.scale.set(0.5, 0.45, 1.3); const tl2 = new T.Mesh(new T.ConeGeometry(0.16, 0.3, 4), b.material); tl2.rotation.x = -Math.PI / 2; tl2.position.z = -0.38; f.add(tl2); f.position.y = 0.02; G.add(f); koi.push({ f, a: i, r: 1.5 + (i % 4) * 0.8, sp: 0.3 + (i % 3) * 0.1 }); }
  for (let i = 0; i < 7; i++) { const lp = new T.Mesh(new T.CircleGeometry(0.42, 16, 0.3, 6), M(0x2f8f3a, { side: T.DoubleSide })); lp.rotation.x = -Math.PI / 2; lp.position.set(PX - 3 + i * 1.1, 0.16, PZ + Math.sin(i * 2) * 2.4); G.add(lp); if (i % 2) { const fl = sph(0.12, M(0xffb3d1), lp.position.x, 0.25, lp.position.z, G, 8); fl.scale.y = 0.6; } }
  app.addObstacle && app.addObstacle(...L(PX, PZ), 5.2);
  // the organic garden: curved raised beds with drip lines, growing flowers and veg
  const GX = 27.5, GZ = 13; for (let b = 0; b < 3; b++) { const bed = new T.Mesh(new T.TorusGeometry(3.2 + b * 1.6, 0.42, 8, 32, Math.PI * 0.9), M(0x7a5232, { roughness: 1 })); bed.rotation.x = Math.PI / 2; bed.rotation.z = 0.3; bed.position.set(GX, 0.35, GZ); G.add(bed); const soil = new T.Mesh(new T.TorusGeometry(3.2 + b * 1.6, 0.34, 6, 32, Math.PI * 0.9), M(0x3b2a1a, { roughness: 1 })); soil.rotation.x = Math.PI / 2; soil.rotation.z = 0.3; soil.position.set(GX, 0.55, GZ); G.add(soil); for (let i = 0; i < (MOB ? 5 : 8); i++) { const a = 0.3 + i / 8 * Math.PI * 0.9; const pl = makeFlower(['sunflower', 'tulip', 'lupine', 'columbine', 'allium'][(i + b) % 5], 0.7, b * 11 + i); pl.position.set(GX + Math.cos(a) * (3.2 + b * 1.6), 0.6, GZ - Math.sin(a) * (3.2 + b * 1.6)); G.add(pl); } }
  const gsign = makeSprite('🥕 Organic garden · fed by rain', { scale: 3, accent: '#7cff6b' }); gsign.position.set(GX, 3.4, GZ); G.add(gsign);
  // the demo: blue water lights up stage by stage, with a teaching card for each step
  const STEPS = [['🌧️ Rain hits the roof', 'Every inch of rain on this roof is about 600 gallons per 1,000 square feet. The copper gutters catch all of it.', [P1, P2], 'chain'], ['🫙 Into the rain tank', 'Downspouts and rain chains carry it to a sealed 2,500-gallon tank. A first-flush diverter dumps the dirtiest first few gallons.', [P1, P2], 'tank'], ['🧪 Filtered four ways', 'Sediment filter (dirt) → carbon (taste, chlorine, chemicals) → reverse-osmosis membrane (pores about 0.0001 micron) → UV light (kills bacteria and viruses).', [P3], 'ro'], ['🚰 Drinkable, all through the house', 'Clean water is pumped to every tap, the kitchen, both showers and the ice maker. It tests cleaner than most city water.', [P4], ''], ['🥕 The garden gets fed', 'RO leftover water and tank overflow go to drip lines in the organic garden: water at the roots, nothing wasted.', [P5], 'garden'], ['🐟 The pond tops itself up', 'Overflow keeps the koi pond full, and the pond feeds the living wall. Rain in, life out. Nothing goes to the sewer.', [P6], 'pond']];
  let demo = -1, dT = 0; const card = (i) => app.popup ? app.popup(STEPS[i][0], '<p>' + STEPS[i][1] + '</p><p class="muted">Step ' + (i + 1) + ' of ' + STEPS.length + ' · the blue water shows where it goes</p>', [{ label: i < STEPS.length - 1 ? 'Next step ▶' : '✅ Done', fn: () => { if (i < STEPS.length - 1) { demo = i + 1; dT = 0; setTimeout(() => card(demo), 150); } else demo = -1; } }]) : toast(STEPS[i][0]);
  const startDemo = () => { demo = 0; dT = 0; card(0); };
  const kioskG = new T.Group(); kioskG.position.set(17.5, 0, -6); G.add(kioskG); box(0.9, 1.2, 0.5, M(0x0b2a4a), 0, 0.6, 0, kioskG); const ks = textPlane(['💧 WATER DEMO', 'rain → tap → garden'], 1.8, 0.8, { bg: '#0b2a4a', fg: '#fff', accent: '#38bdf8' }); ks.position.set(0, 1.7, 0.27); kioskG.add(ks);
  app.addInteractable && app.addInteractable(...L(17.5, -4.6), 2.6, '💧 Run the rain-to-tap water demo', startDemo); app.addHotspot && app.addHotspot(kioskG, { fn: startDemo });
  // when it rains for real, the gutters and tank run on their own
  let rainT = 0;

  /* ---------- 4) the LAUNCH console in the front yard ---------- */
  const lc = new T.Group(); lc.position.set(-27, 0, -6.5); lc.rotation.y = Math.PI / 2; G.add(lc); box(1.3, 1.0, 0.8, M(0x1f2937, { metalness: 0.5 }), 0, 0.5, 0, lc); const lbtn = new T.Mesh(new T.SphereGeometry(0.22, 18, 12, 0, Math.PI * 2, 0, Math.PI / 2), new T.MeshStandardMaterial({ color: 0xe11d2a, emissive: 0xe11d2a, emissiveIntensity: 0.9 })); lbtn.position.y = 1.02; lc.add(lbtn); const lsg = makeSprite('🚀 LAUNCH THE ROCKET', { scale: 2.8, accent: '#ff4f79' }); lsg.position.y = 2.2; lc.add(lsg);
  const launch = () => { if (W.launchRocket) W.launchRocket(); else toast('🚀 The rocket is in the backyard. Walk onto the pad!'); lbtn.position.y = 0.96; setTimeout(() => { lbtn.position.y = 1.02; }, 300); };
  app.addInteractable && app.addInteractable(...L(-27, -5), 2.4, '🚀 Launch the backyard rocket', launch); app.addHotspot && app.addHotspot(lc, { fn: launch });

  /* ---------- 4b) the BOBBLEHEAD MAILBOX: giant, glowing, Zach's head on a spring ---------- */
  { const MB0 = globalThis.AOU_MAILBOX; const mbx = X - 34, mbz = Z - 8; if (MB0 && MB0.g) MB0.g.visible = false; const bm = new T.Group(); bm.position.set(mbx, terrainY(mbx, mbz), mbz); bm.rotation.y = Math.PI / 2; S.add(bm); cyl(0.35, 0.45, 2.2, M(0x2a1a10), 0, 1.1, 0, bm, 10); const body = box(2.2, 2.0, 3.6, M(0x2f6bff, { metalness: 0.7, roughness: 0.25 }), 0, 3.2, 0, bm); const lidm = new T.Mesh(new T.CylinderGeometry(1.1, 1.1, 3.6, 24, 1, false, 0, Math.PI), M(0x2f6bff, { metalness: 0.7, roughness: 0.25 })); lidm.rotation.z = Math.PI / 2; lidm.rotation.y = Math.PI / 2; lidm.position.set(0, 4.2, 0); bm.add(lidm); const door = box(2.0, 1.8, 0.1, M(0x1e40af, { metalness: 0.6 }), 0, 3.2, 1.86, bm); box(0.5, 0.1, 0.1, M(0xffd23f, { metalness: 0.9 }), 0, 3.4, 1.95, bm); const flag = box(0.1, 1.4, 0.5, M(0xff4f79), 1.2, 4.4, -0.8, bm); const lb = textPlane(['ZACH', 'No. 1 Unity Road'], 2.4, 0.9, { bg: '#ffffff', fg: '#1e1b4b', accent: '#2f6bff' }); lb.position.set(0, 2.9, 1.92); bm.add(lb); const strip = box(2.3, 0.08, 3.7, glow(0x38f0ff, 1.6), 0, 2.2, 0, bm);
    const spring = new T.Group(); spring.position.set(0, 5.3, 0); bm.add(spring); for (let i = 0; i < 6; i++) { const r = new T.Mesh(new T.TorusGeometry(0.42, 0.06, 8, 24), M(0xdfe6f2, { metalness: 0.95, roughness: 0.1 })); r.rotation.x = Math.PI / 2; r.position.y = i * 0.16; spring.add(r); } const headG = new T.Group(); headG.position.y = 1.2; spring.add(headG); const faceTex = new T.TextureLoader().load('/images/zach-face-shades.webp'); faceTex.colorSpace = T.SRGBColorSpace; const head = new T.Mesh(new T.SphereGeometry(1.7, 32, 24), new T.MeshStandardMaterial({ color: 0xf1c9a5, roughness: 0.6 })); head.scale.set(1, 1.15, 0.95); headG.add(head); const face = new T.Mesh(new T.PlaneGeometry(2.6, 3.2), new T.MeshBasicMaterial({ map: faceTex, transparent: true })); face.position.set(0, 0.1, 1.55); headG.add(face); const hair = new T.Mesh(new T.SphereGeometry(1.75, 24, 16, 0, Math.PI * 2, 0, Math.PI * 0.45), M(0xd9b56a, { roughness: 0.9 })); hair.position.y = 0.3; headG.add(hair); const halo = new T.Mesh(new T.TorusGeometry(1.5, 0.12, 8, 40), glow(0xffd23f, 1.8)); halo.rotation.x = Math.PI / 2; halo.position.y = 2.4; headG.add(halo); const sg = makeSprite("📬 ZACH'S BOBBLEHEAD MAILBOX · tap to open the Comm Hub", { scale: 5, accent: '#38f0ff' }); sg.position.y = 10.5; bm.add(sg);
    app.addObstacle && app.addObstacle(mbx, mbz, 2.4); const openIt = () => { if (W.openHub) W.openHub(); else if (MB0) MB0.open(); }; app.addHotspot && app.addHotspot(bm, { fn: openIt }); app.addInteractable && app.addInteractable(mbx + 3.2, mbz, 3.6, "📬 Zach's bobblehead mailbox · the Comm Hub", openIt);
    let bob = 0, bobV = 0; app.onUpdate((dt, t) => { const P = app.player.position; const d = Math.hypot(P.x - mbx, P.z - mbz); if (d > 60) return; if (d < 6 && Math.abs(bobV) < 0.2 && app.moving) bobV = 2.5; bobV -= bob * 18 * dt; bobV *= 1 - 2.5 * dt; bob += bobV * dt; headG.rotation.z = bob * 0.6 + Math.sin(t * 1.7) * 0.05; headG.rotation.x = Math.sin(t * 1.1) * 0.08 + bob * 0.3; headG.position.y = 1.2 + Math.abs(bob) * 0.15; spring.scale.y = 1 + bob * 0.2; halo.rotation.z = t; flag.rotation.x = d < 8 ? Math.min(0, flag.rotation.x - dt * 3) : Math.min(0, flag.rotation.x + dt * 3) * 1; door.rotation.x = d < 4 ? Math.min(1.3, door.rotation.x + dt * 3) : Math.max(0, door.rotation.x - dt * 3); }); }
  /* ---------- 5) ⛳ UNITY LINKS · the Sky Range ---------- */
  const golf = buildSkyRange(app, W, X, Z, y0, toast);
  const tee = new T.Group(); tee.position.set(24, 0, -18); G.add(tee); const tring = new T.Mesh(new T.TorusGeometry(1.5, 0.12, 10, 40), new T.MeshBasicMaterial({ color: 0x7cff6b })); tring.rotation.x = Math.PI / 2; tring.position.y = 0.1; tee.add(tring); const flag = cyl(0.04, 0.04, 3.2, M(0xffffff), 0, 1.6, 0, tee, 6); const fl2 = new T.Mesh(new T.PlaneGeometry(0.9, 0.55), new T.MeshBasicMaterial({ color: 0xff4f79, side: T.DoubleSide })); fl2.position.set(0.45, 2.9, 0); tee.add(fl2); const tsg = makeSprite('⛳ UNITY LINKS · Sky Range', { scale: 3.2, accent: '#7cff6b' }); tsg.position.y = 4; tee.add(tsg);
  app.addInteractable && app.addInteractable(...L(24, -16.5), 2.6, '⛳ Go up to the Sky Range (golf)', golf.enter); app.addHotspot && app.addHotspot(tee, { fn: golf.enter });
  app.addPlace && app.addPlace({ id: 'skyrange', name: '⛳ Unity Links · Sky Range golf', icon: '⛳', x: X + 24, z: Z - 14, cat: 'Fun', top: true, keys: 'golf driving range targets clubs sky range unity links game vr', say: 'Step on the green ring to go up to the floating driving range.' });
  app.addPlace && app.addPlace({ id: 'disco', name: '🪩 The Disco Room · No. 1 Unity Road', icon: '🪩', x: wp(0, -WD / 2 - 2)[0], z: wp(0, -WD / 2 - 2)[1], cat: 'Fun', keys: 'disco dance floor music party lights', say: 'Walk in and press the dance button.' });
  app.addPlace && app.addPlace({ id: 'water', name: '💧 Rain-to-tap water demo', icon: '💧', x: X + 17.5, z: Z - 3.5, cat: 'Learn', keys: 'water rain gutters ro reverse osmosis filter drinkable garden pond demo plumbing', say: 'Tap the kiosk to watch rain become drinking water.' });

  app.onUpdate((dt, t) => { const P = app.player.position; const near = Math.hypot(P.x - X, P.z - Z) < 110; flowM.uniforms.t.value = t; if (!near && !golf.active()) return;
    // disco floor + ball + beams
    let q = 0; const bpm = beatOn ? 4 : 1.2; for (let i = 0; i < TX; i++) for (let j = 0; j < TZ; j++) { const h = ((i * 0.08 + j * 0.13 + Math.floor(t * bpm) * 0.17) % 1); const pulse = ((i + j + Math.floor(t * bpm)) % 3 === 0) ? 0.65 : 0.4; tile.setColorAt(q++, col.setHSL(h, 1, pulse)); } tile.instanceColor.needsUpdate = true; ball.rotation.y += dt * 0.8; beams.forEach((b, i) => { b.rotation.z = Math.sin(t * 1.3 + i) * 0.6; b.rotation.x = Math.cos(t * 1.1 + i * 2) * 0.6; b.children[0].material.color.setHSL((t * 0.2 + i / 6) % 1, 1, 0.6); });
    for (const kf of koi) { kf.a += dt * kf.sp; kf.f.position.set(PX + Math.cos(kf.a) * kf.r * 1.2, 0.06, PZ + Math.sin(kf.a) * kf.r * 0.8); kf.f.rotation.y = -kf.a; }
    // weather: when it is raining, the system runs on its own
    const raining = (globalThis.AOU_WEATHER || '') === 'rain' || (globalThis.AOU_WEATHER || '') === 'storm'; if (raining) rainT = Math.min(1, rainT + dt * 0.5); else rainT = Math.max(0, rainT - dt * 0.3);
    if (demo >= 0) dT += dt; const lit = (i) => demo >= i;
    flowM.uniforms.on.value = Math.max(demo >= 0 ? 1 : 0, rainT);
    chains.forEach((c, i) => { c.material.emissive = c.material.emissive || new T.Color(); }); tankLvl.position.y = 0.6 + (lit(1) || rainT > 0.3 ? 3.0 : 1.2) * (0.6 + Math.sin(t * 0.5) * 0.02); uvGlow.material.opacity = (lit(2) || rainT > 0.3) ? 0.45 + Math.sin(t * 9) * 0.15 : 0; });
  return { golf };
}

/* ⛳ the Sky Range: a floating tee deck with five floating target greens out in the sky */
function buildSkyRange(app, W, X, Z, y0, toast) {
  const S = app.scene; const LV = 7; const DY = y0 + 52, TX0 = X + 40, TZ0 = Z - 60; let built = false, active = false; const G = new T.Group(); G.position.set(TX0, DY, TZ0); G.userData.noCull = true; G.visible = false; S.add(G);
  const deck = { level: LV, y: DY, x1: TX0 - 9, x2: TX0 + 9, z1: TZ0 - 6, z2: TZ0 + 6 }; addDeck(deck);
  const CLUBS = [['🏌️ Driver', 72, 11], ['🪵 3-Wood', 64, 14], ['⛓️ 5-Iron', 52, 20], ['🔩 9-Iron', 40, 34], ['🥄 Wedge', 28, 48], ['🚀 Rocket Club', 120, 16]];
  const TARGETS = [[60, 6, 0, 7, 10, 0x7cff6b, 'GREEN 60'], [110, 12, -18, 8, 25, 0x38f0ff, 'BLUE 110'], [165, 3, 22, 9, 50, 0xffd23f, 'GOLD 165'], [230, 18, -6, 10, 100, 0xff4fd8, 'PINK 230'], [320, 30, 30, 12, 250, 0xff8a3d, 'MOON 320']];
  const tgts = []; let board, bctx, btex; const ballM = new T.MeshStandardMaterial({ color: 0xffffff, roughness: 0.3, emissive: 0x334455, emissiveIntensity: 0.3 }); let ballObj, trail, trailPos, burstPts;
  const build = () => { if (built) return; built = true;
    const turf = (() => { const c = document.createElement('canvas'); c.width = c.height = 256; const q = c.getContext('2d'); for (let i = 0; i < 16; i++) { q.fillStyle = i % 2 ? '#3f9a3a' : '#4aab44'; q.fillRect(0, i * 16, 256, 16); } for (let i = 0; i < 4000; i++) { q.fillStyle = `rgba(20,60,20,${Math.random() * 0.25})`; q.fillRect(Math.random() * 256, Math.random() * 256, 1, 3); } const t2 = new T.CanvasTexture(c); t2.colorSpace = T.SRGBColorSpace; t2.wrapS = t2.wrapT = T.RepeatWrapping; t2.repeat.set(3, 2); return t2; })();
    box(18, 0.6, 12, new T.MeshStandardMaterial({ map: turf, roughness: 1 }), 0, -0.3, 0, G); const under = new T.Mesh(new T.ConeGeometry(9, 14, 8), M(0x6b4a2a, { roughness: 1, flatShading: true })); under.rotation.x = Math.PI; under.position.y = -7.6; under.scale.z = 0.7; G.add(under);
    for (let i = 0; i < 4; i++) { const mat = box(1.6, 0.06, 1.6, M(0x2f6b2a), -6 + i * 4, 0.04, 2.5, G); const teeP = cyl(0.03, 0.02, 0.12, M(0xffd23f), -6 + i * 4, 0.1, 2.5, G, 8); }
    for (const sz of [-6, 6]) box(18, 1.0, 0.06, new T.MeshPhysicalMaterial({ color: 0xcfefff, transparent: true, opacity: 0.25, depthWrite: false }), 0, 0.5, sz, G); box(0.06, 1.0, 12, new T.MeshPhysicalMaterial({ color: 0xcfefff, transparent: true, opacity: 0.25, depthWrite: false }), -9, 0.5, 0, G);
    // floating target greens with rings, bullseyes, flags and point values
    TARGETS.forEach(([dx, dy, dz, r, pts, c, name]) => { const g = new T.Group(); g.position.set(dx, dy, dz); G.add(g); const grn = new T.Mesh(new T.CylinderGeometry(r, r * 0.92, 0.8, 40), new T.MeshStandardMaterial({ map: turf, roughness: 1 })); g.add(grn); const rock = new T.Mesh(new T.ConeGeometry(r * 0.95, r * 1.6, 9), M(0x6b4a2a, { roughness: 1, flatShading: true })); rock.rotation.x = Math.PI; rock.position.y = -r * 0.8 - 0.4; g.add(rock); for (let k = 0; k < 3; k++) { const ring = new T.Mesh(new T.RingGeometry(r * (0.95 - k * 0.3) - 0.35, r * (0.95 - k * 0.3), 40), new T.MeshBasicMaterial({ color: k === 2 ? 0xffffff : c, side: T.DoubleSide })); ring.rotation.x = -Math.PI / 2; ring.position.y = 0.42; g.add(ring); } const bull = new T.Mesh(new T.CircleGeometry(r * 0.12, 24), new T.MeshBasicMaterial({ color: 0xff2d55 })); bull.rotation.x = -Math.PI / 2; bull.position.y = 0.43; g.add(bull);
      const pole = cyl(0.06, 0.06, 4, M(0xffffff), 0, 2.4, 0, g, 6); const fl = new T.Mesh(new T.PlaneGeometry(1.6, 1), new T.MeshBasicMaterial({ color: c, side: T.DoubleSide })); fl.position.set(0.8, 4, 0); g.add(fl); const lab = makeSprite(name + ' · ' + pts + ' pts', { scale: 5 + r * 0.3, accent: '#' + new T.Color(c).getHexString() }); lab.position.y = 6.5; g.add(lab); const halo = new T.Mesh(new T.TorusGeometry(r + 0.6, 0.14, 8, 48), new T.MeshBasicMaterial({ color: c, transparent: true, opacity: 0.6 })); halo.rotation.x = Math.PI / 2; halo.position.y = 0.6; g.add(halo); tgts.push({ g, r, pts, c, name, fl, halo, hit: 0 }); });
    // the scoreboard
    const bc = document.createElement('canvas'); bc.width = 1024; bc.height = 512; bctx = bc.getContext('2d'); btex = new T.CanvasTexture(bc); btex.colorSpace = T.SRGBColorSpace; const bf = new T.Group(); bf.position.set(-2, 0, -8.5); G.add(bf); box(10.4, 5.4, 0.3, M(0x111827, { metalness: 0.4 }), 0, 4.2, 0, bf); board = new T.Mesh(new T.PlaneGeometry(10, 5), new T.MeshBasicMaterial({ map: btex })); board.position.set(0, 4.2, 0.17); bf.add(board); for (const sx of [-4.6, 4.6]) cyl(0.12, 0.12, 2, M(0x6b7280), sx, 0.8, 0, bf, 8);
    ballObj = new T.Mesh(new T.SphereGeometry(0.12, 16, 12), ballM); ballObj.visible = false; G.add(ballObj); trailPos = new Float32Array(120 * 3); const tg = new T.BufferGeometry(); tg.setAttribute('position', new T.BufferAttribute(trailPos, 3)); trail = new T.Line(tg, new T.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.85 })); trail.frustumCulled = false; G.add(trail);
    const bp = new Float32Array(90 * 3); const bg = new T.BufferGeometry(); bg.setAttribute('position', new T.BufferAttribute(bp, 3)); burstPts = new T.Points(bg, new T.PointsMaterial({ color: 0xffd23f, size: 0.5, transparent: true, depthWrite: false, blending: T.AdditiveBlending })); burstPts.visible = false; burstPts.frustumCulled = false; burstPts.userData.v = new Float32Array(90 * 3); G.add(burstPts);
    const keep = [[TX0 - 8.6, TZ0 - 5.6], [TX0 + 8.6, TZ0 - 5.6], [TX0 + 8.6, TZ0 + 5.6], [TX0 - 8.6, TZ0 + 5.6]]; const n0 = app.obstacles.length; app.addPoly(keep, { keepIn: true }); for (let i = n0; i < app.obstacles.length; i++) app.obstacles[i].level = LV;
    const exitIt = app.interactables.length; app.addInteractable(TX0 - 7, TZ0 + 4, 2.4, '⬇️ Back down to No. 1 Unity Road', leave); app.addInteractable(TX0 + 1, TZ0 + 2.5, 3, '🏌️ Tee up (start a round)', () => startRound()); for (let i = exitIt; i < app.interactables.length; i++) app.interactables[i].level = LV;
    drawBoard(); };
  // game state
  const ST = { club: 0, shots: 10, score: 0, best: +(localStorage.getItem('aou_golf_best') || 0), wind: 0, flying: false, power: 0, charging: false, last: '' };
  const drawBoard = () => { if (!bctx) return; const q = bctx; const g = q.createLinearGradient(0, 0, 0, 512); g.addColorStop(0, '#0b1a3a'); g.addColorStop(1, '#13294f'); q.fillStyle = g; q.fillRect(0, 0, 1024, 512); q.strokeStyle = '#7cff6b'; q.lineWidth = 8; q.strokeRect(12, 12, 1000, 488); q.fillStyle = '#7cff6b'; q.font = '900 64px Poppins, Arial'; q.textAlign = 'center'; q.fillText('⛳ UNITY LINKS', 512, 92); q.font = '800 46px Poppins, Arial'; q.fillStyle = '#fff'; q.fillText('SCORE ' + ST.score + '    SHOTS ' + ST.shots + '/10', 512, 175); q.fillStyle = '#ffd23f'; q.fillText('BEST ' + ST.best, 512, 240); q.fillStyle = '#9fd3ff'; q.font = '700 38px Poppins, Arial'; q.fillText(CLUBS[ST.club][0] + '   ·   wind ' + (ST.wind >= 0 ? '→ ' : '← ') + Math.abs(ST.wind).toFixed(1) + ' m/s', 512, 310); q.fillStyle = '#ff9ad5'; q.font = '800 44px Poppins, Arial'; q.fillText(ST.last || 'Pick a club, hold to power up, release to swing', 512, 400); q.font = '600 30px Poppins, Arial'; q.fillStyle = '#cbd5e1'; TARGETS.forEach(([d, , , , p, c, n], i) => { q.fillStyle = '#' + new T.Color(c).getHexString(); q.fillText(n.split(' ')[0] + ' ' + p, 120 + i * 196, 470); }); btex.needsUpdate = true; };
  // HUD
  let hud = null; const showHud = () => { if (hud) return; hud = document.createElement('div'); hud.id = 'golf-hud'; hud.innerHTML = `<style>#golf-hud{position:fixed;left:50%;bottom:16px;transform:translateX(-50%);z-index:9500;display:flex;flex-direction:column;align-items:center;gap:8px;font-family:Poppins,Arial;pointer-events:none}#golf-hud *{pointer-events:auto}#golf-hud .clubs{display:flex;gap:6px;flex-wrap:wrap;justify-content:center}#golf-hud .clubs button{border:0;border-radius:999px;padding:8px 12px;font:800 13px Poppins,Arial;background:rgba(255,255,255,.92);color:#0f172a;cursor:pointer}#golf-hud .clubs button.on{background:#16a34a;color:#fff}#golf-hud .meter{width:min(420px,86vw);height:18px;border-radius:999px;background:rgba(15,23,42,.75);overflow:hidden;border:2px solid #fff}#golf-hud .meter i{display:block;height:100%;width:0;background:linear-gradient(90deg,#7cff6b,#ffd23f 70%,#ff2d55)}#golf-hud .swing{border:0;border-radius:18px;padding:16px 30px;font:900 18px Poppins,Arial;color:#fff;background:linear-gradient(135deg,#16a34a,#0ea5e9);box-shadow:0 10px 30px rgba(0,0,0,.35);cursor:pointer;touch-action:none;user-select:none}#golf-hud .info{background:rgba(15,23,42,.8);color:#fff;border-radius:999px;padding:6px 14px;font:700 13px Poppins,Arial}</style><div class="info" id="gh-i"></div><div class="clubs">${CLUBS.map((c, i) => `<button data-c="${i}">${c[0]}</button>`).join('')}</div><div class="meter"><i id="gh-m"></i></div><button class="swing" id="gh-s">⛳ HOLD TO SWING</button>`; document.body.appendChild(hud);
    hud.querySelectorAll('[data-c]').forEach(b => b.onclick = () => { ST.club = +b.dataset.c; upd(); drawBoard(); }); const sb = hud.querySelector('#gh-s'); sb.onpointerdown = (e) => { e.preventDefault(); charge(); }; sb.onpointerup = sb.onpointerleave = () => release(); upd(); };
  const upd = () => { if (!hud) return; hud.querySelectorAll('[data-c]').forEach(b => b.classList.toggle('on', +b.dataset.c === ST.club)); hud.querySelector('#gh-i').textContent = `Score ${ST.score} · Shots ${ST.shots}/10 · Best ${ST.best} · aim with the camera · Space or VR trigger works too`; };
  const hideHud = () => { if (hud) { hud.remove(); hud = null; } };
  const charge = () => { if (ST.flying || ST.shots <= 0 || !active) { if (ST.shots <= 0) startRound(); return; } ST.charging = true; ST.power = 0; };
  const release = () => { if (!ST.charging) return; ST.charging = false; swing(Math.min(1, ST.power)); };
  const key = (e) => { if (!active || (e.target.closest && e.target.closest('input,textarea'))) return; if (e.code === 'Space') { e.preventDefault(); if (e.type === 'keydown' && !e.repeat) charge(); if (e.type === 'keyup') release(); } if (e.type === 'keydown' && /^[1-6]$/.test(e.key)) { ST.club = +e.key - 1; upd(); drawBoard(); } };
  addEventListener('keydown', key); addEventListener('keyup', key);
  // VR: hold the trigger, release to swing
  try { const xr = app.renderer && app.renderer.xr; if (xr) for (const i of [0, 1]) { const c = xr.getController(i); c.addEventListener('selectstart', () => { if (active) charge(); }); c.addEventListener('selectend', () => { if (active) release(); }); } } catch (e) { }
  // flight
  const FL = { p: new T.Vector3(), v: new T.Vector3(), t: 0, n: 0, landed: false, cam0: null };
  const swing = (pw) => { const [name, sp, loft] = CLUBS[ST.club]; const yaw = app.yaw; const dir = new T.Vector3(-Math.sin(yaw), 0, -Math.cos(yaw)); const speed = sp * (0.35 + 0.65 * pw) * (0.96 + Math.random() * 0.08); const la = loft * Math.PI / 180 * (0.85 + pw * 0.3); FL.v.copy(dir).multiplyScalar(Math.cos(la) * speed); FL.v.y = Math.sin(la) * speed; FL.p.set(app.player.position.x - TX0 + dir.x * 0.8, 0.3, app.player.position.z - TZ0 + dir.z * 0.8); FL.t = 0; FL.n = 0; FL.landed = false; ST.flying = true; ST.shots--; ballObj.visible = true; ballObj.position.copy(FL.p); trailPos.fill(0); for (let i = 0; i < 120; i++) { trailPos[i * 3] = FL.p.x; trailPos[i * 3 + 1] = FL.p.y; trailPos[i * 3 + 2] = FL.p.z; } trail.geometry.attributes.position.needsUpdate = true; trail.material.color.setHSL(Math.random(), 0.9, 0.7); if (app.avatar) { const av = app.avatar; const r0 = av.rotation.y; let k = 0; const sw = (dt) => { k += dt * 5; av.rotation.y = r0 + Math.sin(Math.min(1, k) * Math.PI) * 1.4; if (k >= 1) { av.rotation.y = r0; app.updaters = app.updaters.filter(z => z !== sw); } }; app.onUpdate(sw); } app.buzz && app.buzz(40); toast(`${name} · ${Math.round(pw * 100)}% power 🏌️`, 1400); FL.cam0 = app.targetDist; app.targetDist = Math.max(app.targetDist, 9); upd(); };
  const burst = (p, c) => { const a = burstPts.geometry.attributes.position.array, v = burstPts.userData.v; for (let i = 0; i < 90; i++) { a[i * 3] = p.x; a[i * 3 + 1] = p.y + 0.5; a[i * 3 + 2] = p.z; const th = Math.random() * 6.283, ph = Math.random() * 1.4; v[i * 3] = Math.cos(th) * Math.sin(ph) * 9; v[i * 3 + 1] = Math.cos(ph) * 12; v[i * 3 + 2] = Math.sin(th) * Math.sin(ph) * 9; } burstPts.material.color.set(c); burstPts.material.opacity = 1; burstPts.visible = true; burstPts.userData.life = 1.6; burstPts.geometry.attributes.position.needsUpdate = true; };
  const land = (msg) => { ST.flying = false; ST.last = msg; drawBoard(); upd(); setTimeout(() => { ballObj.visible = false; app.targetDist = FL.cam0 || 7; if (ST.shots <= 0) { if (ST.score > ST.best) { ST.best = ST.score; localStorage.setItem('aou_golf_best', ST.best); ST.last = '🏆 NEW BEST: ' + ST.score + '!'; app.celebrate && app.celebrate('🏆'); } else ST.last = 'Round over · ' + ST.score + ' pts · tap SWING for a new round'; drawBoard(); } ST.wind = Math.round((Math.random() * 8 - 4) * 10) / 10; drawBoard(); }, 1400); };
  app.onUpdate((dt, t) => { if (!active) return; if (ST.charging) { ST.power += dt * 0.9; if (ST.power > 1.15) ST.power = 0; const m = hud && hud.querySelector('#gh-m'); if (m) m.style.width = Math.min(100, ST.power * 100) + '%'; }
    tgts.forEach((tg, i) => { tg.fl.rotation.y = Math.sin(t * 2 + i) * 0.4; tg.halo.material.opacity = 0.35 + Math.sin(t * 2 + i) * 0.25 + (tg.hit > 0 ? 0.5 : 0); if (tg.hit > 0) { tg.hit -= dt; tg.g.position.y = TARGETS[i][1] + Math.sin(tg.hit * 20) * 0.15; } });
    if (burstPts && burstPts.visible) { const a = burstPts.geometry.attributes.position.array, v = burstPts.userData.v; burstPts.userData.life -= dt; for (let i = 0; i < 90; i++) { v[i * 3 + 1] -= 14 * dt; a[i * 3] += v[i * 3] * dt; a[i * 3 + 1] += v[i * 3 + 1] * dt; a[i * 3 + 2] += v[i * 3 + 2] * dt; } burstPts.geometry.attributes.position.needsUpdate = true; burstPts.material.opacity = Math.max(0, burstPts.userData.life / 1.6); if (burstPts.userData.life <= 0) burstPts.visible = false; }
    if (!ST.flying) return; const steps = 3; for (let s = 0; s < steps; s++) { const h = dt / steps; FL.v.y -= 9.81 * h; FL.v.x += ST.wind * 0.12 * h; FL.v.multiplyScalar(1 - 0.06 * h); FL.p.addScaledVector(FL.v, h); FL.t += h;
      for (const tg of tgts) { const gp = tg.g.position; const dx = FL.p.x - gp.x, dz = FL.p.z - gp.z, top = gp.y + 0.45; if (FL.v.y < 0 && FL.p.y <= top && FL.p.y > top - 1.2 && dx * dx + dz * dz < tg.r * tg.r) { const dd = Math.sqrt(dx * dx + dz * dz) / tg.r; const mult = dd < 0.12 ? 5 : dd < 0.35 ? 3 : dd < 0.65 ? 2 : 1; const pts = tg.pts * mult; ST.score += pts; tg.hit = 1.2; FL.p.y = top; ballObj.position.copy(FL.p); burst(FL.p, tg.c); app.celebrate && app.celebrate(mult >= 5 ? '🎯' : '⛳'); toast((mult >= 5 ? '🎯 BULLSEYE! ' : mult >= 3 ? '🔥 Inner ring! ' : '⛳ On the green! ') + tg.name + ' · +' + pts, 2600); land((mult >= 5 ? '🎯 BULLSEYE ' : '⛳ ') + tg.name + ' +' + pts); return; } }
      if (FL.p.y < -60 || FL.t > 14) { const dist = Math.round(Math.hypot(FL.p.x, FL.p.z)); toast('☁️ Into the clouds · ' + dist + ' m', 1800); land('☁️ ' + dist + ' m · into the clouds'); return; } }
    ballObj.position.copy(FL.p); FL.n++; if (FL.n % 2 === 0) { trailPos.copyWithin(3, 0, 117 * 3); trailPos[0] = FL.p.x; trailPos[1] = FL.p.y; trailPos[2] = FL.p.z; trail.geometry.attributes.position.needsUpdate = true; }
    // ball-cam: the camera swings to watch the ball
    const wpx = TX0 + FL.p.x, wpz = TZ0 + FL.p.z; const want = Math.atan2(-(wpx - app.player.position.x), -(wpz - app.player.position.z)); let da = want - app.yaw; while (da > Math.PI) da -= Math.PI * 2; while (da < -Math.PI) da += Math.PI * 2; app.yaw += da * Math.min(1, dt * 2); app.pitch += ((Math.atan2(FL.p.y - 2, Math.hypot(FL.p.x, FL.p.z) + 4) * 0.6) - app.pitch) * Math.min(1, dt * 2); });
  const startRound = () => { ST.shots = 10; ST.score = 0; ST.last = 'New round! 10 shots. Go far.'; ST.wind = Math.round((Math.random() * 6 - 3) * 10) / 10; drawBoard(); upd(); };
  const enter = () => { build(); active = true; G.visible = true; app.fade && app.fade.classList.add('on'); setTimeout(() => { app.level = LV; app.player.position.set(TX0 + 1, DY, TZ0 + 2.5); app.yaw = -Math.PI / 2; app.pitch = -0.05; if (app.avatar) app.avatar.rotation.y = app.yaw + Math.PI; app.targetDist = 6; app.dist = 6; showHud(); startRound(); app.fade && app.fade.classList.remove('on'); toast('⛳ Welcome to the Sky Range! Pick a club, hold SWING (or Space / VR trigger), release. Aim with the camera.', 6000); }, 400); };
  function leave() { active = false; hideHud(); app.fade && app.fade.classList.add('on'); setTimeout(() => { app.level = 0; app.player.position.set(X + 24, terrainY(X + 24, Z - 15), Z - 15); G.visible = false; app.fade && app.fade.classList.remove('on'); }, 400); }
  W.golfLeave = leave; return { enter, leave, active: () => active };
}

/* ============================================================
   v6 · the shape: a huge L with an O-shaped wing around a center
   garden and the TREE OF LIFE. Sections at 2, 3 and 4 levels, each a
   different material (brick, stone, cedar, stucco, copper). Inside the
   O: the kitchen, the big bathroom with a rain shower, the dirt-floor
   grounding room. On top of the 4-level tower: the OBSERVATORY.
   ============================================================ */
import { TEX } from './aou-build.js';
import { makeHummingbird } from './aou-garden.js';
export function buildUnityV6(app, W, X, Z) {
  const S = app.scene; const y0 = terrainY(X, Z) + 0.05; const toast = (m, ms) => app.toast(m, ms); const G = new T.Group(); G.position.set(X, y0, Z); G.userData.noCollide = true; S.add(G); const L = (lx, lz) => [X + lx, Z + lz];
  const tex = (k, rx = 2, ry = 2, o = {}) => { try { const t = TEX[k](); const t2 = t.clone(); t2.needsUpdate = true; t2.repeat.set(rx, ry); return new T.MeshStandardMaterial({ map: t2, roughness: 0.8, ...o }); } catch (e) { return M(0xcccccc); } };
  const brick = tex('brick', 4, 2), stone = tex('stone', 3, 2), cedar = tex('cedar', 3, 3), stucco = tex('stucco', 2, 2), copper = tex('copper', 2, 2, { metalness: 0.7, roughness: 0.35 }), slate = tex('slate', 3, 3), glassM = new T.MeshPhysicalMaterial({ color: 0xcfefff, transparent: true, opacity: 0.3, roughness: 0.04, metalness: 0.2, depthWrite: false, side: T.DoubleSide }), band = (c) => glow(c, 1.5);
  const solid = (x1, z1, x2, z2) => app.addPoly && app.addPoly([L(x1, z1), L(x2, z1), L(x2, z2), L(x1, z2)]);
  /* ---- the long leg of the L: a 4-level stone tower, a 3-level brick block, a 2-level cedar block, all along the north side ---- */
  const tower = new T.Group(); tower.position.set(-26, 0, 24); G.add(tower); for (let f = 0; f < 4; f++) { const w = 11 - f * 0.6; box(w, 3.4, w, f % 2 ? stone : brick, 0, f * 3.5 + 1.7, 0, tower); box(w + 0.3, 0.14, w + 0.3, band([0x38f0ff, 0xff4fd8, 0xffd23f, 0x7cff6b][f]), 0, f * 3.5 + 3.45, 0, tower); for (const sx of [-1, 1]) box(0.06, 1.3, w * 0.7, glassM, sx * (w / 2 + 0.04), f * 3.5 + 1.8, 0, tower); } solid(-31.5, 18.5, -20.5, 29.5);
  // the observatory on top of the tower
  const obs = new T.Group(); obs.position.set(0, 14.1, 0); tower.add(obs); cyl(4.6, 5, 1.2, copper, 0, 0.6, 0, obs, 32); const dome = new T.Mesh(new T.SphereGeometry(5.4, 32, 16, 0, Math.PI * 2, 0, Math.PI / 2), M(0xdfe6f2, { metalness: 0.6, roughness: 0.25 })); dome.position.y = 1.2; obs.add(dome); const domeIn = new T.Mesh(new T.SphereGeometry(5.3, 32, 16, 0, Math.PI * 2, 0, Math.PI / 2), new T.MeshStandardMaterial({ color: 0x0b1a3a, side: T.BackSide, roughness: 1, emissive: 0x05102a, emissiveIntensity: 0.6 })); domeIn.position.y = 1.2; obs.add(domeIn); const stars = (() => { const n = 300, pos = new Float32Array(n * 3); for (let i = 0; i < n; i++) { const th = Math.random() * 6.283, ph = Math.random() * 1.4; pos[i * 3] = Math.cos(th) * Math.sin(ph) * 5.1; pos[i * 3 + 1] = 1.2 + Math.cos(ph) * 5.1; pos[i * 3 + 2] = Math.sin(th) * Math.sin(ph) * 5.1; } const g2 = new T.BufferGeometry(); g2.setAttribute('position', new T.BufferAttribute(pos, 3)); const pts = new T.Points(g2, new T.PointsMaterial({ color: 0xffffff, size: 0.06 })); obs.add(pts); return pts; })(); const slit = box(1.6, 4.6, 0.5, M(0x0b1a3a), 0, 3.4, 5.0, obs); slit.rotation.x = -0.6; const scope = new T.Group(); scope.position.y = 1.4; obs.add(scope); const tube = cyl(0.5, 0.65, 5, M(0x1e2a4a, { metalness: 0.7, roughness: 0.3 }), 0, 2, 1.2, scope, 16); tube.rotation.x = -0.8; const lens = cyl(0.66, 0.66, 0.15, glow(0x38f0ff, 1.5), 0, 2 + Math.sin(0.8) * 2.5, 1.2 + Math.cos(0.8) * 2.5, scope, 16); lens.rotation.x = -0.8; const osign = makeSprite('🔭 THE OBSERVATORY · top of the tower', { scale: 4, accent: '#b08cff' }); osign.position.y = 9; obs.add(osign);
  const DY = y0 + 14.1 + 1.2; addDeck({ level: 8, y: DY, x1: X - 30.4, x2: X - 21.6, z1: Z + 19.6, z2: Z + 28.4 }); const n0 = app.obstacles.length; app.addPoly && app.addPoly([L(-30.2, 19.8), L(-21.8, 19.8), L(-21.8, 28.2), L(-30.2, 28.2)], { keepIn: true }); for (let i = n0; i < app.obstacles.length; i++) app.obstacles[i].level = 8;
  const upObs = () => { app.fade && app.fade.classList.add('on'); setTimeout(() => { app.level = 8; app.player.position.set(X - 26, DY, Z + 26.5); app.yaw = Math.PI; app.targetDist = 2.6; app.pitch = -0.08; app.fade && app.fade.classList.remove('on'); toast('🔭 The observatory. Drag to look: the whole world, the mountain, the stars after 6 pm. Tap ⬇ when you are done.', 6000); }, 400); }; const downObs = () => { app.fade && app.fade.classList.add('on'); setTimeout(() => { app.level = 0; app.player.position.set(X - 26, terrainY(X - 26, Z + 31), Z + 31); app.targetDist = 6; app.pitch = -0.05; app.fade && app.fade.classList.remove('on'); }, 400); };
  app.addInteractable && app.addInteractable(...L(-26, 31), 3.2, '🔭 Elevator up to the observatory', upObs); { const i0 = app.interactables.length; app.addInteractable(X - 26, Z + 22.5, 2.6, '⬇️ Back down', downObs); app.addInteractable(X - 26, Z + 26.5, 2.2, '🔭 Look through the telescope', () => { app.targetDist = 0.01; app.pitch = 0.5; toast('🔭 Pinch or scroll to zoom. Mount Peace is that way, the mall is the other way. 🌙 Night sky after 6 pm.', 4500); }); for (let i = i0; i < app.interactables.length; i++) app.interactables[i].level = 8; }
  const pod = cyl(1.3, 1.3, 14.4, glassM, -26, 7.2, 31, G, 20); for (const y of [0.1, 14.3]) { const r = new T.Mesh(new T.TorusGeometry(1.3, 0.08, 8, 28), band(0xffd23f)); r.rotation.x = Math.PI / 2; r.position.set(-26, y, 31); G.add(r); }
  const blk3 = new T.Group(); blk3.position.set(-13, 0, 22); G.add(blk3); for (let f = 0; f < 3; f++) { box(12 - f * 1.4, 3.3, 9 - f * 0.5, f === 1 ? cedar : brick, f * 0.7, f * 3.4 + 1.65, 0, blk3); box(12.2 - f * 1.4, 0.12, 0.06, band(0xffe9a8), f * 0.7, f * 3.4 + 2.2, (9 - f * 0.5) / 2 + 0.04, blk3); } const g3 = new T.Mesh(new T.BoxGeometry(9.2, 0.2, 7.8), M(0x3f8f3a, { roughness: 1 })); g3.position.set(1.4, 10.3, 0); blk3.add(g3); solid(-19, 17.5, -7, 26.5);
  const blk2 = new T.Group(); blk2.position.set(-4, 0, 23); G.add(blk2); for (let f = 0; f < 2; f++) { box(7, 3.2, 8, f ? stucco : cedar, 0, f * 3.3 + 1.6, 0, blk2); } box(7.3, 0.4, 8.3, slate, 0, 6.8, 0, blk2); solid(-7.5, 19, -0.5, 27);
  /* ---- the O wing: a ring of rooms around the Tree of Life garden ---- */
  const OX = -2, OZ = -44, RO = 17, RI = 10, H = 6.2; const O = new T.Group(); O.position.set(OX, 0, OZ); G.add(O);
  const ringWall = (r, mat, h, y) => { const m = new T.Mesh(new T.CylinderGeometry(r, r, h, 72, 1, true), mat); m.position.y = y + h / 2; m.material.side = T.DoubleSide; O.add(m); return m; };
  ringWall(RO, stucco, H, 0); ringWall(RI, stone, H, 0); const roofO = new T.Mesh(new T.RingGeometry(RI - 0.3, RO + 0.6, 72), slate); roofO.rotation.x = -Math.PI / 2; roofO.position.y = H + 0.3; roofO.material.side = T.DoubleSide; O.add(roofO); const floorO = new T.Mesh(new T.RingGeometry(RI, RO, 72), M(0xe9e4da, { roughness: 0.8 })); floorO.rotation.x = -Math.PI / 2; floorO.position.y = 0.04; O.add(floorO); const gb = new T.Mesh(new T.TorusGeometry(RO + 0.3, 0.1, 8, 96), band(0x38f0ff)); gb.rotation.x = Math.PI / 2; gb.position.y = H + 0.4; O.add(gb);
  for (let i = 0; i < 12; i++) { const a = i / 12 * Math.PI * 2; const w = box(0.08, 2.2, 3.4, glassM, 0, 3.4, 0, O); w.position.set(Math.cos(a) * (RO + 0.02), 3.4, Math.sin(a) * (RO + 0.02)); w.rotation.y = -a; }
  // doors: outer door on the north (toward the house) and a garden door on the inner ring, both open
  const doorA = Math.PI / 2; const inner = []; for (let i = 0; i < 72; i++) { const a = i / 72 * Math.PI * 2; if (Math.abs(a - doorA) < 0.14) continue; app.addObstacle && app.addObstacle(...L(OX + Math.cos(a) * RO, OZ + Math.sin(a) * RO), 0.8); } for (let i = 0; i < 48; i++) { const a = i / 48 * Math.PI * 2; if (Math.abs(a - doorA) < 0.22 || Math.abs(a - doorA - Math.PI) < 0.22) continue; app.addObstacle && app.addObstacle(...L(OX + Math.cos(a) * RI, OZ + Math.sin(a) * RI), 0.7); }
  const cutDoor = (r, a, w) => { const d = box(w, 3.2, 0.7, M(0x1e1b4b), 0, 1.6, 0, O); d.position.set(Math.cos(a) * r, 1.6, Math.sin(a) * r); d.rotation.y = -a; d.visible = false; const arch = new T.Mesh(new T.TorusGeometry(w / 2, 0.12, 8, 24, Math.PI), band(0xffd23f)); arch.position.set(Math.cos(a) * r, 3.2, Math.sin(a) * r); arch.rotation.y = -a; O.add(arch); }; cutDoor(RO, doorA, 3.4); cutDoor(RI, doorA, 3); cutDoor(RI, doorA + Math.PI, 3);
  // three rooms inside the ring: kitchen (east), bathroom (south), grounding room (west), with partitions
  const part = (a) => { const p = box(0.25, H, RO - RI, stone, 0, H / 2, 0, O); p.position.set(Math.cos(a) * (RI + RO) / 2, H / 2, Math.sin(a) * (RI + RO) / 2); p.rotation.y = -a + Math.PI / 2; for (let k = 0; k < 5; k++) { const rr = RI + 0.8 + k * 1.5; app.addObstacle && app.addObstacle(...L(OX + Math.cos(a) * rr, OZ + Math.sin(a) * rr), 0.5); } }; [Math.PI / 2 + 0.6, Math.PI + 0.9, Math.PI * 1.5 + 0.9, 0.3].forEach(part);
  const room = (a0, build) => { const r = (RI + RO) / 2; const g = new T.Group(); g.position.set(Math.cos(a0) * r, 0, Math.sin(a0) * r); g.rotation.y = -a0 + Math.PI / 2; O.add(g); build(g, a0); };
  // kitchen
  room(-0.25, (g) => { const stoneTop = M(0x2a2d33, { roughness: 0.25, metalness: 0.3 }); box(4.2, 1.0, 1.2, cedar, 0, 0.5, 0, g); box(4.4, 0.12, 1.4, stoneTop, 0, 1.06, 0, g); box(3.5, 1.0, 0.7, cedar, 0, 0.5, 2.6, g); box(3.6, 0.12, 0.9, stoneTop, 0, 1.06, 2.6, g); for (let i = 0; i < 4; i++) cyl(0.11, 0.11, 0.02, M(0x111111), -1.2 + i * 0.8, 1.13, 2.6, g, 16); box(0.9, 1.9, 0.9, M(0xdfe6f2, { metalness: 0.8, roughness: 0.2 }), 2.4, 0.95, 2.6, g); for (let i = 0; i < 3; i++) { const st = cyl(0.3, 0.3, 0.08, M(0x8a5a2b), -1.2 + i * 1.2, 0.76, -1.1, g, 12); cyl(0.04, 0.04, 0.7, M(0x333333), -1.2 + i * 1.2, 0.36, -1.1, g, 6); const pd = sph(0.22, glow(0xffe9a8, 1.6), -1.2 + i * 1.2, 3.1, 0, g, 10); } const sg = makeSprite('🍳 Kitchen · rainwater on tap', { scale: 2.8, accent: '#ffd23f' }); sg.position.set(0, 4.6, 0); g.add(sg); });
  // the big bathroom: walk-in rain shower, soaking tub
  room(Math.PI * 0.75 + 0.2, (g) => { const chrome = M(0xe9eef7, { metalness: 1, roughness: 0.12 }); const gl = new T.MeshPhysicalMaterial({ color: 0xcfefff, transparent: true, opacity: 0.22, roughness: 0.03, side: T.DoubleSide, depthWrite: false }); for (const [w, d, x, z] of [[4, 0.06, 0, -1.6], [0.06, 3.2, -2, 0], [0.06, 3.2, 2, 0]]) box(w, 3.4, d, gl, x, 1.7, z, g); box(4, 0.12, 3.2, M(0xdfe6f2, { roughness: 0.4 }), 0, 0.06, 0, g); const head = cyl(0.55, 0.55, 0.08, chrome, 0, 3.4, -0.5, g, 20); box(0.08, 0.08, 1.4, chrome, 0, 3.44, -1.2, g); const RN = 70; const rp = new Float32Array(RN * 3); const rs = []; for (let i = 0; i < RN; i++) rs.push([(Math.random() - 0.5), Math.random(), (Math.random() - 0.5)]); const rg = new T.BufferGeometry(); rg.setAttribute('position', new T.BufferAttribute(rp, 3)); const rain = new T.Points(rg, new T.PointsMaterial({ color: 0xcfefff, size: 0.06, transparent: true, opacity: 0.85, depthWrite: false })); rain.frustumCulled = false; rain.visible = false; g.add(rain); let on = false; app.onUpdate((dt) => { if (!on) return; for (let i = 0; i < RN; i++) { const r = rs[i]; r[1] = (r[1] + dt * 1.5) % 1; rp[i * 3] = r[0]; rp[i * 3 + 1] = 3.3 - r[1] * 3.2; rp[i * 3 + 2] = -0.5 + r[2]; } rg.attributes.position.needsUpdate = true; }); const tub = new T.Mesh(new T.CapsuleGeometry(0.7, 1.4, 6, 14), M(0xffffff, { roughness: 0.2 })); tub.rotation.z = Math.PI / 2; tub.scale.set(1, 1, 0.55); tub.position.set(0, 0.5, 3.2); g.add(tub); const sg = makeSprite('🚿 The big bathroom · rain shower + tub', { scale: 3, accent: '#38f0ff' }); sg.position.set(0, 4.6, 1); g.add(sg); const wp = new T.Vector3(); g.getWorldPosition(wp); app.addInteractable && app.addInteractable(wp.x, wp.z, 3, '🚿 Turn on the rain shower', () => { on = !on; rain.visible = on; toast(on ? '🚿 Filtered rainwater, warm. 🎤 Sing it.' : '🚿 Off. Towel is on the warmer.', 3000); }); });
  // the dirt-floor grounding room
  room(Math.PI * 1.25 + 0.2, (g) => { const dirt = (() => { const c = document.createElement('canvas'); c.width = c.height = 256; const q = c.getContext('2d'); q.fillStyle = '#5a3d22'; q.fillRect(0, 0, 256, 256); for (let i = 0; i < 5000; i++) { q.fillStyle = `hsl(${22 + Math.random() * 14},${30 + Math.random() * 25}%,${16 + Math.random() * 22}%)`; q.fillRect(Math.random() * 256, Math.random() * 256, 2, 2); } const t = new T.CanvasTexture(c); t.wrapS = t.wrapT = T.RepeatWrapping; t.repeat.set(2, 2); t.colorSpace = T.SRGBColorSpace; return t; })(); const fl = new T.Mesh(new T.PlaneGeometry(6, 5), new T.MeshStandardMaterial({ map: dirt, roughness: 1 })); fl.rotation.x = -Math.PI / 2; fl.position.y = 0.08; g.add(fl); for (let i = 0; i < 4; i++) { const cu = new T.Mesh(new T.CylinderGeometry(0.42, 0.45, 0.18, 16), M([0xb5432b, 0xc9a24a, 0x3f8f3a, 0x6366f1][i], { roughness: 1 })); cu.position.set(-1.5 + i * 1, 0.17, 1.2 - (i % 2) * 2.4); g.add(cu); } for (let i = 0; i < 6; i++) { const st = new T.Mesh(new T.DodecahedronGeometry(0.2 + (i % 3) * 0.1, 0), M(0x8d8f92, { flatShading: true })); st.position.set(-2.2 + i * 0.9, 0.2, -1.8); g.add(st); } const pl = new T.Mesh(new T.CylinderGeometry(0.5, 0.4, 0.5, 10), M(0xc9661a)); pl.position.set(2.3, 0.25, 1.8); g.add(pl); const sg = makeSprite('🌱 Grounding room · real dirt floor', { scale: 3, accent: '#7cff6b' }); sg.position.set(0, 4.6, 0); g.add(sg); const wp = new T.Vector3(); g.getWorldPosition(wp); app.addHotspot && app.addHotspot(fl, { title: '🌱 The grounding room', html: '<p>Bare feet on real earth. Grounding (earthing) is simply skin-to-soil contact; people use it to slow down, breathe and feel steady. The floor is packed clay and river sand, swept daily, cool in summer.</p>' }); app.addInteractable && app.addInteractable(wp.x, wp.z, 3, '🌱 Sit on the earth', () => toast('🌱 Shoes off. Breathe in for 4, hold 4, out for 6. The floor is cool. Nothing is urgent.', 5200)); });
  /* ---- the garden and the TREE OF LIFE ---- */
  const gar = new T.Mesh(new T.CircleGeometry(RI - 0.4, 48), M(0x3f8f3a, { roughness: 1 })); gar.rotation.x = -Math.PI / 2; gar.position.y = 0.05; O.add(gar); const path = new T.Mesh(new T.RingGeometry(3.2, 4.4, 48), M(0xc9b48a, { roughness: 1 })); path.rotation.x = -Math.PI / 2; path.position.y = 0.07; O.add(path);
  const tree = new T.Group(); O.add(tree); const bark = M(0x5a3d22, { roughness: 1 }); const trunk = new T.Mesh(new T.LatheGeometry([[2.2, 0], [1.3, 1.2], [1.0, 3.5], [0.9, 6], [0.7, 8], [0.5, 10]].map(([r, y]) => new T.Vector2(r, y)), 14), bark); trunk.castShadow = true; tree.add(trunk); for (let i = 0; i < 7; i++) { const a = i / 7 * Math.PI * 2; const br = cyl(0.14, 0.32, 5.5, bark, Math.cos(a) * 2.4, 9.6, Math.sin(a) * 2.4, tree, 8); br.rotation.set(Math.sin(a) * 0.9, 0, -Math.cos(a) * 0.9); }
  const leafM = new T.MeshStandardMaterial({ color: 0x3fa34d, roughness: 0.9, emissive: 0x0a3a1a, emissiveIntensity: 0.3 }); const can = [[0, 12.5, 0, 5.2], [3.6, 11, 1.4, 3.4], [-3.4, 11.4, -1.2, 3.2], [1.2, 10.6, -3.8, 3], [-1.6, 10.8, 3.8, 3.1], [0, 15.5, 0, 3.2]]; for (const [x, y, z, r] of can) { const c = new T.Mesh(new T.IcosahedronGeometry(r, 2), leafM); c.position.set(x, y, z); tree.add(c); }
  const FN = MOB ? 140 : 320; const flowers = new T.InstancedMesh(new T.SphereGeometry(0.22, 8, 6), new T.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: 1.4, roughness: 0.3 }), FN); const fd = []; const m4 = new T.Matrix4(), col = new T.Color(); for (let i = 0; i < FN; i++) { const [x, y, z, r] = can[i % can.length]; const th = Math.random() * 6.283, ph = Math.acos(2 * Math.random() - 1); fd.push({ p: new T.Vector3(x + Math.sin(ph) * Math.cos(th) * r * 0.98, y + Math.cos(ph) * r * 0.98, z + Math.sin(ph) * Math.sin(th) * r * 0.98), ph: Math.random() * 6.283, pink: Math.random() < 0.5 }); flowers.setColorAt(i, col.setHex(fd[i].pink ? 0xff6fd8 : 0xb388ff)); } flowers.instanceColor.needsUpdate = true; tree.add(flowers);
  const glowSp = (() => { const c = document.createElement('canvas'); c.width = c.height = 128; const q = c.getContext('2d'); const gr = q.createRadialGradient(64, 64, 4, 64, 64, 64); gr.addColorStop(0, 'rgba(255,255,255,.9)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); q.fillStyle = gr; q.fillRect(0, 0, 128, 128); return new T.CanvasTexture(c); })(); for (let i = 0; i < 5; i++) { const sp = new T.Sprite(new T.SpriteMaterial({ map: glowSp, color: i % 2 ? 0xff6fd8 : 0xb388ff, transparent: true, opacity: 0.35, depthWrite: false, blending: T.AdditiveBlending })); const [x, y, z, r] = can[i]; sp.position.set(x, y, z); sp.scale.setScalar(r * 3); tree.add(sp); }
  const bflies = []; for (let i = 0; i < (MOB ? 8 : 16); i++) { const b = new T.Group(); const wm = M([0xff6fd8, 0xb388ff, 0xffd23f, 0x38f0ff][i % 4], { side: T.DoubleSide, emissive: [0xff6fd8, 0xb388ff, 0xffd23f, 0x38f0ff][i % 4], emissiveIntensity: 0.4 }); for (const sx of [-1, 1]) { const w = new T.Mesh(new T.CircleGeometry(0.22, 10, 0, Math.PI), wm); w.position.x = sx * 0.02; w.rotation.y = sx * Math.PI / 2; w.userData.sx = sx; b.add(w); } tree.add(b); bflies.push({ b, a: Math.random() * 6.283, r: 3 + Math.random() * 6, y: 7 + Math.random() * 9, sp: 0.3 + Math.random() * 0.4 }); }
  const hums = []; for (let i = 0; i < 4; i++) { try { const h = makeHummingbird(); tree.add(h); hums.push({ h, a: i * 1.6, r: 5 + i, y: 9 + i * 1.5 }); } catch (e) { } }
  const tsign = makeSprite('🌳 THE TREE OF LIFE', { scale: 5, accent: '#ff6fd8' }); tsign.position.y = 19.5; tree.add(tsign); app.addObstacle && app.addObstacle(...L(OX, OZ), 2.4);
  const pets = []; const takeButterflies = () => { if (pets.length) { pets.forEach(p => S.remove(p.b)); pets.length = 0; toast('🦋 They flew home.'); return; } for (let i = 0; i < 6; i++) { const b = new T.Group(); const wm = M([0xff6fd8, 0xb388ff, 0xffd23f, 0x38f0ff][i % 4], { side: T.DoubleSide, emissive: [0xff6fd8, 0xb388ff, 0xffd23f, 0x38f0ff][i % 4], emissiveIntensity: 0.5 }); for (const sx of [-1, 1]) { const w = new T.Mesh(new T.CircleGeometry(0.16, 8, 0, Math.PI), wm); w.position.x = sx * 0.02; w.rotation.y = sx * Math.PI / 2; w.userData.sx = sx; b.add(w); } b.userData.noCollide = true; S.add(b); pets.push({ b, a: i, r: 0.8 + i * 0.25, y: 1.4 + (i % 3) * 0.3, t0: app.t }); } toast('🦋 Six butterflies are coming with you (tap the tree again to send them home). ✌️', 4500); app.celebrate && app.celebrate('🦋'); };
  app.addHotspot && app.addHotspot(trunk, { title: '🌳 The Tree of Life', html: '<p>Planted for Stephanie, who threw the peace sign everywhere she went. The flowers glow pink and purple and never stop growing. Butterflies and hummingbirds live in it. Sit under it any time; it is the quietest spot on the property.</p>', actions: [{ label: '🦋 Take butterflies with you', fn: takeButterflies }, { label: '✌️ Our mission', href: '/mission/' }] });
  app.onUpdate((dt, t) => { if (!pets.length) return; const P = app.player.position; for (const p of pets) { p.a += dt * 1.6; p.b.position.set(P.x + Math.cos(p.a) * p.r, P.y + p.y + Math.sin(t * 2.5 + p.a) * 0.25, P.z + Math.sin(p.a) * p.r); p.b.rotation.y = -p.a; p.b.children.forEach(w => { w.rotation.y = w.userData.sx * (Math.PI / 2 - 0.9 + Math.sin(t * 20 + p.a) * 0.8); }); } });
  /* ---- the FEED BOARD on the front of the house: your latest public posts, for anyone walking by ---- */
  const fb = new T.Group(); fb.position.set(-37, 0, 7); fb.rotation.y = -Math.PI / 2; G.add(fb); fb.traverse(o => { o.frustumCulled = false; }); box(6.4, 4.2, 0.2, M(0x111827, { metalness: 0.4 }), 0, 3.1, 0, fb); for (const sx of [-2.9, 2.9]) cyl(0.1, 0.12, 1.2, M(0x6b7280), sx, 0.6, 0, fb, 8); const fc = document.createElement('canvas'); fc.width = 1024; fc.height = 672; const fq = fc.getContext('2d'); const ft = new T.CanvasTexture(fc); ft.colorSpace = T.SRGBColorSpace; const fm = new T.Mesh(new T.PlaneGeometry(6, 3.9), new T.MeshBasicMaterial({ map: ft })); fm.position.set(0, 3.1, 0.11); fm.frustumCulled = false; fb.add(fm);
  const drawFeed = (posts, name) => { const q = fq; const g2 = q.createLinearGradient(0, 0, 1024, 672); g2.addColorStop(0, '#0ea5e9'); g2.addColorStop(1, '#6366f1'); q.fillStyle = g2; q.fillRect(0, 0, 1024, 672); q.fillStyle = '#fff'; q.font = '900 44px Poppins, Arial'; q.textAlign = 'left'; q.fillText('📰 ' + (name || 'Zach') + "'s feed", 36, 70); q.font = '600 24px Poppins, Arial'; q.fillStyle = '#e0f2fe'; q.fillText('live from allofus.one/flat · tap the board to read + post', 36, 108); let y = 160; (posts && posts.length ? posts : [{ text: 'Nothing posted yet. Tap the board to write the first one!', created_at: new Date().toISOString() }]).slice(0, 3).forEach(p => { q.fillStyle = 'rgba(255,255,255,.14)'; q.beginPath(); q.roundRect(36, y, 952, 150, 20); q.fill(); q.fillStyle = '#fff'; q.font = '700 30px Poppins, Arial'; const words = String(p.text || (p.kind === 'sale' ? '🏷️ Something for sale' : p.kind)).split(' '); let line = '', ly = y + 48, lines = 0; for (const w of words) { const test = line + w + ' '; if (q.measureText(test).width > 900 && line) { q.fillText(line, 60, ly); line = w + ' '; ly += 38; if (++lines === 2) break; } else line = test; } if (lines < 2) q.fillText(line.slice(0, 60), 60, ly); q.fillStyle = '#c7d2fe'; q.font = '600 20px Poppins, Arial'; q.fillText(new Date(p.created_at).toLocaleDateString(), 60, y + 132); y += 166; }); ft.needsUpdate = true; }; drawFeed([], 'Zach'); W.feedBoard = drawFeed;
  app.addHotspot && app.addHotspot(fm, { fn: () => { location.href = '/flat/?u=zach'; } }); app.addInteractable && app.addInteractable(...L(-39.5, 7), 3, "📰 Zach's feed board · read + post", () => { location.href = '/flat/'; });
  app.addPlace && app.addPlace({ id: 'treeoflife', name: '🌳 The Tree of Life · No. 1 Unity Road garden', icon: '🌳', x: X + OX, z: Z + OZ + 7, cat: 'Places', top: true, keys: 'tree of life garden flowers glowing butterflies hummingbirds stephanie peace', say: 'Inside the O wing. Walk through the gold arch.' });
  app.addPlace && app.addPlace({ id: 'observatory', name: '🔭 The Observatory · No. 1 Unity Road', icon: '🔭', x: X - 26, z: Z + 31, cat: 'Places', keys: 'observatory telescope stars tower', say: 'Take the glass elevator up the 4-level tower.' });
  app.onUpdate((dt, t) => { const P = app.player.position; if (Math.hypot(P.x - (X + OX), P.z - (Z + OZ)) > 120) return; for (let i = 0; i < FN; i++) { const f = fd[i]; const grow = 0.55 + 0.45 * (0.5 + 0.5 * Math.sin(t * 0.35 + f.ph)); m4.makeScale(grow, grow, grow); m4.setPosition(f.p.x, f.p.y + Math.sin(t * 1.5 + f.ph) * 0.06, f.p.z); flowers.setMatrixAt(i, m4); } flowers.instanceMatrix.needsUpdate = true; flowers.material.emissiveIntensity = 1.1 + Math.sin(t * 1.3) * 0.4; for (const bf of bflies) { bf.a += dt * bf.sp; bf.b.position.set(Math.cos(bf.a) * bf.r, bf.y + Math.sin(t * 2 + bf.a) * 0.8, Math.sin(bf.a) * bf.r); bf.b.rotation.y = -bf.a; bf.b.children.forEach(w => { w.rotation.y = w.userData.sx * (Math.PI / 2 - 0.9 + Math.sin(t * 18 + bf.a) * 0.8); }); } hums.forEach((hm, i) => { hm.a += dt * 0.5; hm.h.position.set(Math.cos(hm.a) * hm.r, hm.y + Math.sin(t * 3 + i) * 0.4, Math.sin(hm.a) * hm.r); hm.h.rotation.y = -hm.a + Math.PI / 2; if (hm.h.userData.tick) hm.h.userData.tick(dt, t); }); obs.rotation.y = Math.sin(t * 0.1) * 0.5; });
}
