/* 🧭 allofus LIFEboard · the flat version (Oct 2026). Same `lifeboards.data` the 3D board uses, so both stay in sync.
   Tabs: Today · Goals · Habits · Wheel · Vision · Projects · Money · Generators. Everything saves on change. */
export const BOARD_CSS = `.lb{display:grid;grid-template-columns:200px minmax(0,1fr);gap:14px}@media(max-width:900px){.lb{grid-template-columns:1fr}}.lb-tabs{display:flex;flex-direction:column;gap:4px}@media(max-width:900px){.lb-tabs{flex-direction:row;overflow:auto;padding-bottom:4px}}.lb-tabs button{display:flex;align-items:center;gap:8px;border:1.5px solid transparent;background:#fff;border-radius:10px;padding:9px 10px;font:700 13px var(--ff);color:#14183a;cursor:pointer;white-space:nowrap}.lb-tabs button .dot{width:9px;height:9px;border-radius:50%}.lb-tabs button.on{border-color:var(--tc);background:color-mix(in srgb,var(--tc) 8%,#fff)}
.lb h3{display:flex;align-items:center;gap:8px;margin:0 0 8px}.lb .muted{color:#64748b;font-size:13px}.lb input,.lb textarea,.lb select{border:1.5px solid #cbd5e1;border-radius:10px;padding:8px 10px;font:600 13px var(--ff);background:#fff;color:#14183a}.lb textarea{width:100%;min-height:70px}
.kan{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}@media(max-width:700px){.kan{grid-template-columns:1fr}}.kan .col{background:#f1f5f9;border-radius:14px;padding:10px;min-height:160px}.kan .col h4{margin:0 0 8px;font:800 12px var(--ff);letter-spacing:.06em;text-transform:uppercase;color:#475569;display:flex;justify-content:space-between}.kan .col.over{outline:2px dashed #0ea5e9}.gc{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:9px 10px;margin-bottom:8px;cursor:grab;position:relative;font-size:14px}.gc .tag{display:inline-block;font:800 10px var(--ff);letter-spacing:.06em;text-transform:uppercase;color:#fff;border-radius:999px;padding:2px 7px;margin-right:6px;background:var(--tc,#6366f1)}.gc .x{position:absolute;right:8px;top:6px;border:0;background:transparent;color:#94a3b8;cursor:pointer;font-weight:800}.gc .mv{display:none;gap:4px;margin-top:6px}@media(max-width:700px){.gc .mv{display:flex}}.gc .mv button{border:1px solid #e2e8f0;background:#fff;border-radius:8px;padding:3px 8px;font:800 11px var(--ff);cursor:pointer}
.hab{width:100%;border-collapse:collapse;font-size:12px}.hab th{font:800 10px var(--ff);color:#64748b;text-align:center;padding:4px 2px}.hab td{padding:4px 2px;text-align:center;border-top:1px solid #f1f5f9}.hab td:first-child{text-align:left;font-weight:700;white-space:nowrap}.hab i{display:inline-block;width:22px;height:22px;border-radius:7px;border:1.5px solid #e2e8f0;background:#fff;cursor:pointer}.hab i.on{background:#22c55e;border-color:#22c55e}.hab .st{font:800 12px var(--ff);color:#f97316}
.wheel{display:grid;grid-template-columns:220px minmax(0,1fr);gap:14px;align-items:center}@media(max-width:700px){.wheel{grid-template-columns:1fr}}.wheel label{display:flex;align-items:center;gap:8px;font-size:13px;font-weight:700;margin:6px 0}.wheel input[type=range]{flex:1}
.vis{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));grid-auto-flow:dense;gap:10px}.vc{border-radius:14px;padding:12px;color:#fff;position:relative;min-height:90px;cursor:grab;font:700 14px var(--ff);display:flex;align-items:flex-end;box-shadow:0 6px 16px rgba(2,8,30,.1)}.vc.m{grid-column:span 2}.vc.l{grid-column:span 2;grid-row:span 2;font-size:18px}.vc .tools{position:absolute;right:6px;top:6px;display:flex;gap:4px;opacity:.9}.vc .tools button{border:0;background:rgba(255,255,255,.25);color:#fff;border-radius:7px;width:24px;height:24px;cursor:pointer;font:800 11px var(--ff)}.vc.over{outline:3px dashed #fff}.vc img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;border-radius:14px;opacity:.55}.vc span{position:relative}
.proj{display:flex;flex-direction:column;gap:8px}.pr{display:flex;gap:8px;align-items:center;background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:8px 10px}.pr b{flex:1}.pr select{padding:4px 6px}
.money{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:700px){.money{grid-template-columns:1fr}}.money .lst div{display:flex;justify-content:space-between;padding:5px 0;border-top:1px solid #f1f5f9;font-size:13px}.money .tot{font:900 20px var(--ff);margin-top:6px}
.gen{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.gen .g{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:12px}.gen .g h4{margin:0 0 4px;font:800 14px var(--ff)}.gen .out{background:#f8fafc;border-radius:10px;padding:10px;margin-top:8px;font-size:13px;white-space:pre-wrap}
.today{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.mood{display:flex;gap:6px}.mood button{border:1.5px solid #e2e8f0;background:#fff;border-radius:10px;padding:6px 10px;font-size:18px;cursor:pointer}.mood button.on{border-color:#0ea5e9;background:#e0f2fe}`;
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const uid = () => Math.random().toString(36).slice(2, 9);
const COLS = { dream: ['Dream', '#8b5cf6'], doing: ['Doing', '#0ea5e9'], done: ['Done', '#22c55e'] };
const PAL = ['#7c3aed', '#2563eb', '#0ea5e9', '#22c55e', '#f59e0b', '#ef4444', '#ec4899', '#0f172a'];
const dayKey = (d = new Date()) => d.toISOString().slice(0, 10);
const last14 = () => { const o = []; for (let i = 13; i >= 0; i--) { const d = new Date(); d.setDate(d.getDate() - i); o.push(dayKey(d)); } return o; };
const streak = (days) => { const set = new Set(days || []); let n = 0; const d = new Date(); if (!set.has(dayKey(d))) d.setDate(d.getDate() - 1); while (set.has(dayKey(d))) { n++; d.setDate(d.getDate() - 1); } return n; };
export async function boardView(body, { sb, me, toast, rightRail, wireRight, opts, defaultLB, post }) {
  if (!me) { body.innerHTML = '<div class="fl3"><div></div><div class="fl-card"><h3>allofus LIFEboard</h3><p>Your goals, habits, life wheel, vision board, projects, money and generators — one board, saved to your account, the same board you see in 3D.</p><div class="fl-chips"><button class="fl-btn p" data-join>Create my account</button><button class="fl-btn" data-signin>Sign in</button></div></div></div>'; return; }
  let L = null; try { const { data } = await sb.from('lifeboards').select('data').eq('id', me.id).maybeSingle(); L = Object.assign(defaultLB(), (data && data.data) || {}); } catch (e) { L = defaultLB(); }
  L.goals = L.goals || []; L.habits = L.habits || []; L.vision = L.vision || { nodes: [], links: [] }; L.vision.cards = L.vision.cards || L.vision.nodes.map(n => ({ id: n.id, t: n.t, c: n.c, s: 's' })); L.projects = L.projects || []; L.money = L.money || { inc: [], exp: [] }; L.moods = L.moods || []; L.gratitude = L.gratitude || []; L.wheel = L.wheel || {};
  let saveT = 0; const save = () => { clearTimeout(saveT); saveT = setTimeout(async () => { try { await sb.from('lifeboards').upsert({ id: me.id, data: L, updated_at: new Date().toISOString() }); } catch (e) { toast('Could not save — check your connection.'); } }, 500); };
  const TABS = [['today', 'Today', '#f59e0b'], ['goals', 'Goals', '#8b5cf6'], ['habits', 'Habits', '#22c55e'], ['wheel', 'Life wheel', '#0ea5e9'], ['vision', 'Vision board', '#ec4899'], ['projects', 'Projects', '#6366f1'], ['money', 'Money', '#16a34a'], ['gen', 'Generators', '#f97316']];
  let tab = (opts && opts.tab) || localStorage.getItem('lb_tab') || 'today';
  const $ = (s, r = body) => r.querySelector(s), $$ = (s, r = body) => [...r.querySelectorAll(s)];
  const draw = () => { localStorage.setItem('lb_tab', tab); body.innerHTML = `<div class="fl-card lb"><nav class="lb-tabs">${TABS.map(([k, n, c]) => `<button class="${k === tab ? 'on' : ''}" data-t="${k}" style="--tc:${c}"><i class="dot" style="background:${c}"></i>${n}</button>`).join('')}<a class="fl-btn sm" href="/world/?board=1" style="--tc:#06b6d4;margin-top:8px"><i class="dot" style="background:#06b6d4"></i>Open in 3D</a></nav><section id="lb-pane">${pane()}</section></div>`; $$('[data-t]').forEach(b => b.onclick = () => { tab = b.dataset.t; draw(); }); wire(); };
  const pane = () => {
    if (tab === 'today') { const t = dayKey(); const mood = (L.moods.find(m => m.d === t) || {}).m; const due = L.goals.filter(g => g.col === 'doing').slice(0, 4); return `<h3>Today · ${new Date().toLocaleDateString([], { weekday: 'long', month: 'long', day: 'numeric' })}</h3><div class="today"><div class="fl-card"><h4>How are you?</h4><div class="mood">${['😄', '🙂', '😐', '😔', '😤'].map(m => `<button data-mood="${m}" class="${mood === m ? 'on' : ''}">${m}</button>`).join('')}</div><p class="muted" style="margin-top:8px">${L.moods.slice(-7).map(m => m.m).join(' ') || 'Your last 7 days show here.'}</p></div><div class="fl-card"><h4>Habits today</h4>${L.habits.length ? L.habits.map(h => `<label style="display:flex;gap:8px;align-items:center;padding:4px 0"><input type="checkbox" data-hab="${h.id}" ${(h.days || []).includes(t) ? 'checked' : ''}> ${esc(h.t)} <small class="muted">${streak(h.days)}🔥</small></label>`).join('') : '<p class="muted">Add habits in the Habits tab.</p>'}</div><div class="fl-card"><h4>In motion</h4>${due.length ? due.map(g => `<div class="gc" style="cursor:default"><span class="tag" style="--tc:#0ea5e9">${esc(g.tag || 'Goal')}</span>${esc(g.t)}</div>`).join('') : '<p class="muted">Drag a goal into Doing.</p>'}</div><div class="fl-card"><h4>Grateful for</h4><input id="gr" placeholder="one thing, then Enter" style="width:100%"><p class="muted" style="margin-top:6px">${L.gratitude.slice(-3).map(g => '• ' + esc(g.t)).join('<br>')}</p></div></div>`; }
    if (tab === 'goals') return `<h3>Goals <span class="muted">drag between columns · tap ✕ to remove</span></h3><div class="fl-chips" style="margin-bottom:10px"><input id="g-new" placeholder="New goal" style="flex:1;min-width:160px"><select id="g-tag">${['Me', 'Home', 'Work', 'Money', 'Health', 'Family', 'Fun', 'Giving'].map(t => `<option>${t}</option>`).join('')}</select><button class="fl-btn p sm" id="g-add">Add</button></div><div class="kan">${Object.entries(COLS).map(([k, [n, c]]) => `<div class="col" data-col="${k}"><h4>${n}<span>${L.goals.filter(g => g.col === k).length}</span></h4>${L.goals.filter(g => g.col === k).map(g => `<div class="gc" draggable="true" data-g="${g.id}" style="--tc:${c}"><span class="tag">${esc(g.tag || 'Goal')}</span>${esc(g.t)}<button class="x" data-del="${g.id}">✕</button><div class="mv">${Object.keys(COLS).filter(x => x !== k).map(x => `<button data-move="${g.id}:${x}">→ ${COLS[x][0]}</button>`).join('')}</div></div>`).join('')}</div>`).join('')}</div>`;
    if (tab === 'habits') { const days = last14(); return `<h3>Habits <span class="muted">last 14 days · streaks</span></h3><div class="fl-chips" style="margin-bottom:10px"><input id="h-new" placeholder="New habit" style="flex:1;min-width:160px"><button class="fl-btn p sm" id="h-add">Add</button></div><div style="overflow:auto"><table class="hab"><tr><th></th>${days.map(d => `<th>${new Date(d).getDate()}</th>`).join('')}<th>🔥</th><th></th></tr>${L.habits.map(h => `<tr><td>${esc(h.t)}</td>${days.map(d => `<td><i class="${(h.days || []).includes(d) ? 'on' : ''}" data-tick="${h.id}:${d}"></i></td>`).join('')}<td class="st">${streak(h.days)}</td><td><button class="x" data-hdel="${h.id}" style="border:0;background:none;color:#94a3b8;cursor:pointer">✕</button></td></tr>`).join('')}</table></div>`; }
    if (tab === 'wheel') { const K = Object.keys(L.wheel); const n = K.length || 1; const pts = K.map((k, i) => { const a = -Math.PI / 2 + i * 2 * Math.PI / n; const r = 10 + (L.wheel[k] || 0) * 9; return [100 + Math.cos(a) * r, 100 + Math.sin(a) * r]; }); const labels = K.map((k, i) => { const a = -Math.PI / 2 + i * 2 * Math.PI / n; return `<text x="${(100 + Math.cos(a) * 112).toFixed(0)}" y="${(100 + Math.sin(a) * 112).toFixed(0)}" text-anchor="middle" font-size="9" font-weight="700" fill="#475569">${esc(k)}</text>`; }).join(''); return `<h3>Life wheel <span class="muted">1 = needs love · 10 = thriving</span></h3><div class="wheel"><svg viewBox="-20 -20 240 240" style="width:220px;max-width:100%">${[25, 50, 75, 100].map(r => `<circle cx="100" cy="100" r="${r}" fill="none" stroke="#e2e8f0"/>`).join('')}<polygon points="${pts.map(p => p.join(',')).join(' ')}" fill="rgba(14,165,233,.25)" stroke="#0ea5e9" stroke-width="2"/>${labels}</svg><div>${K.map(k => `<label>${esc(k)} <input type="range" min="1" max="10" value="${L.wheel[k]}" data-w="${k}"><b>${L.wheel[k]}</b></label>`).join('')}<div class="fl-chips" style="margin-top:8px"><input id="w-new" placeholder="Add an area (Faith, Learning…)"><button class="fl-btn sm" id="w-add">Add</button><button class="fl-btn sm" id="w-share">Share my wheel to my feed</button></div></div></div>`; }
    if (tab === 'vision') return `<h3>Vision board <span class="muted">drag to reorder · S / M / L sizes · tap to edit</span></h3><div class="fl-chips" style="margin-bottom:10px"><input id="v-new" placeholder="A dream, a word, a place…" style="flex:1;min-width:160px"><button class="fl-btn p sm" id="v-add">Add card</button><label class="fl-btn sm">Photo card <input type="file" id="v-img" accept="image/*" hidden></label></div><div class="vis">${L.vision.cards.map(c => `<div class="vc ${c.s || 's'}" draggable="true" data-v="${c.id}" style="background:${c.c || '#7c3aed'}">${c.img ? `<img src="${esc(c.img)}" alt="">` : ''}<div class="tools"><button data-vs="${c.id}">${(c.s || 's').toUpperCase()}</button><button data-vc="${c.id}">●</button><button data-vx="${c.id}">✕</button></div><span>${esc(c.t)}</span></div>`).join('')}</div>`;
    if (tab === 'projects') return `<h3>Projects</h3><div class="fl-chips" style="margin-bottom:10px"><input id="p-new" placeholder="New project" style="flex:1;min-width:160px"><button class="fl-btn p sm" id="p-add">Add</button></div><div class="proj">${L.projects.map(p => `<div class="pr"><b>${esc(p.t)}</b><select data-ps="${p.id}">${['Idea', 'Planning', 'Building', 'Launched', 'Paused'].map(s => `<option ${p.s === s ? 'selected' : ''}>${s}</option>`).join('')}</select><button data-pdel="${p.id}" style="border:0;background:none;color:#94a3b8;cursor:pointer">✕</button></div>`).join('') || '<p class="muted">Nothing yet.</p>'}</div>`;
    if (tab === 'money') { const sum = (a) => a.reduce((x, y) => x + (+y.v || 0), 0); return `<h3>Money <span class="muted">monthly, simple, private</span></h3><div class="money"><div class="fl-card"><h4>Comes in</h4><div class="fl-chips"><input data-mn="inc" placeholder="Name" style="flex:1"><input data-mv="inc" type="number" placeholder="$" style="width:90px"><button class="fl-btn sm" data-madd="inc">Add</button></div><div class="lst">${L.money.inc.map(r => `<div><span>${esc(r.t)}</span><span>$${(+r.v).toLocaleString()} <button data-mdel="inc:${r.id}" style="border:0;background:none;color:#94a3b8;cursor:pointer">✕</button></span></div>`).join('')}</div><div class="tot">$${sum(L.money.inc).toLocaleString()}</div></div><div class="fl-card"><h4>Goes out</h4><div class="fl-chips"><input data-mn="exp" placeholder="Name" style="flex:1"><input data-mv="exp" type="number" placeholder="$" style="width:90px"><button class="fl-btn sm" data-madd="exp">Add</button></div><div class="lst">${L.money.exp.map(r => `<div><span>${esc(r.t)}</span><span>$${(+r.v).toLocaleString()} <button data-mdel="exp:${r.id}" style="border:0;background:none;color:#94a3b8;cursor:pointer">✕</button></span></div>`).join('')}</div><div class="tot">$${sum(L.money.exp).toLocaleString()}</div></div></div><p class="muted" style="margin-top:8px">Left over each month: <b>$${(sum(L.money.inc) - sum(L.money.exp)).toLocaleString()}</b></p>`; }
    if (tab === 'gen') return `<h3>Generators <span class="muted">personal and business · post any result to your feed</span></h3><div class="gen">${[['steps', 'Goal → 5 steps', 'Type a goal', 'personal'], ['week', 'My week from my goals', '', 'personal'], ['affirm', 'Morning affirmation', 'A word that describes this season', 'personal'], ['grat', 'Gratitude prompt', '', 'personal'], ['mission', 'Business mission statement', 'Business name + what you do', 'business'], ['posts', '5 post ideas for my brand', 'Business name + who you serve', 'business'], ['bio', 'Short bio', 'Your name + what you do', 'both'], ['offer', 'An offer people say yes to', 'What you sell', 'business']].map(([k, n, ph, who]) => `<div class="g"><h4>${n} <small class="muted">${who}</small></h4>${ph ? `<input data-gin="${k}" placeholder="${ph}" style="width:100%">` : ''}<div class="fl-chips" style="margin-top:6px"><button class="fl-btn sm p" data-gen="${k}">Generate</button><button class="fl-btn sm" data-gpost="${k}" hidden>Post to feed</button></div><div class="out" data-gout="${k}" hidden></div></div>`).join('')}</div>`;
    return '';
  };
  const gen = (k, v) => { const g = L.goals.filter(x => x.col !== 'done'); const first = (s) => s.split(/[,+|]| and /)[0].trim(); if (k === 'steps') { const t = v || (g[0] && g[0].t) || 'my goal'; return `${t}\n\n1. Decide what "done" looks like in one sentence.\n2. Block two 25-minute sessions this week for it.\n3. Do the smallest ugly first version.\n4. Tell one person what you did (post it).\n5. Set the next small step before you stop.`; } if (k === 'week') { const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']; return days.map((d, i) => `${d}: ${g[i % Math.max(1, g.length)] ? g[i % g.length].t : 'rest and plan'} · ${L.habits[i % Math.max(1, L.habits.length)] ? L.habits[i % L.habits.length].t : ''}`).join('\n') + '\nSat: something fun\nSun: review the week, pick one win'; } if (k === 'affirm') { const w = v || 'steady'; return `Today I am ${w}. I do the next right thing, I keep my word to myself, and I let that be enough.`; } if (k === 'grat') return ['What made today easier than it could have been?', 'Who helped you this month without being asked?', 'Name one thing your body did for you today.', 'What is working right now that you usually ignore?'][Math.floor(Math.random() * 4)]; if (k === 'mission') { const n = first(v || 'My business'); return `${n} exists to make life easier for the people we serve — honest work, clear prices, and we pick up the phone. We grow by earning the next referral.`; } if (k === 'posts') { const n = first(v || 'My brand'); return `1. Before/after: one real job, one real result, no stock photos.\n2. The question we get asked most — answered in 3 lines.\n3. Meet the team: who answers when you call ${n}.\n4. One mistake we see customers make, and how to avoid it.\n5. A thank-you to a customer by name (with permission).`; } if (k === 'bio') { const n = first(v || (me.name || 'Me')); return `${n} · ${(v || '').split(/[,+|]/)[1]?.trim() || 'building something good'} · Denver-rooted, works anywhere · say hi.`; } if (k === 'offer') { const w = first(v || 'what we do'); return `Try ${w} with zero risk: a clear quote in 24 hours, a start date you can plan around, and if we miss it, the first visit is on us.`; } return ''; };
  const wire = () => {
    $$('[data-mood]').forEach(b => b.onclick = () => { const t = dayKey(); L.moods = L.moods.filter(m => m.d !== t).concat([{ d: t, m: b.dataset.mood }]).slice(-60); save(); draw(); });
    $$('[data-hab]').forEach(c => c.onchange = () => { const h = L.habits.find(x => x.id === c.dataset.hab); const t = dayKey(); h.days = h.days || []; if (c.checked) { if (!h.days.includes(t)) h.days.push(t); } else h.days = h.days.filter(d => d !== t); save(); draw(); });
    const gr = $('#gr'); if (gr) gr.onkeydown = (e) => { if (e.key === 'Enter' && gr.value.trim()) { L.gratitude.push({ d: dayKey(), t: gr.value.trim().slice(0, 140) }); L.gratitude = L.gratitude.slice(-100); save(); draw(); } };
    const ga = $('#g-add'); if (ga) ga.onclick = () => { const v = $('#g-new').value.trim(); if (!v) return; L.goals.push({ id: uid(), t: v.slice(0, 120), col: 'dream', tag: $('#g-tag').value }); save(); draw(); };
    $$('[data-del]').forEach(b => b.onclick = () => { L.goals = L.goals.filter(g => g.id !== b.dataset.del); save(); draw(); });
    $$('[data-move]').forEach(b => b.onclick = () => { const [id, col] = b.dataset.move.split(':'); const g = L.goals.find(x => x.id === id); if (g) { g.col = col; save(); draw(); } });
    let dragId = null; $$('[data-g]').forEach(el => { el.ondragstart = () => { dragId = el.dataset.g; }; }); $$('[data-col]').forEach(col => { col.ondragover = (e) => { e.preventDefault(); col.classList.add('over'); }; col.ondragleave = () => col.classList.remove('over'); col.ondrop = (e) => { e.preventDefault(); col.classList.remove('over'); const g = L.goals.find(x => x.id === dragId); if (g) { g.col = col.dataset.col; save(); draw(); } }; });
    const ha = $('#h-add'); if (ha) ha.onclick = () => { const v = $('#h-new').value.trim(); if (!v) return; L.habits.push({ id: uid(), t: v.slice(0, 60), days: [] }); save(); draw(); };
    $$('[data-tick]').forEach(i => i.onclick = () => { const [id, d] = i.dataset.tick.split(':'); const h = L.habits.find(x => x.id === id); h.days = h.days || []; if (h.days.includes(d)) h.days = h.days.filter(x => x !== d); else h.days.push(d); save(); draw(); });
    $$('[data-hdel]').forEach(b => b.onclick = () => { L.habits = L.habits.filter(h => h.id !== b.dataset.hdel); save(); draw(); });
    $$('[data-w]').forEach(r => r.oninput = () => { L.wheel[r.dataset.w] = +r.value; r.nextElementSibling.textContent = r.value; save(); }); $$('[data-w]').forEach(r => r.onchange = () => draw());
    const wa = $('#w-add'); if (wa) wa.onclick = () => { const v = $('#w-new').value.trim(); if (!v || Object.keys(L.wheel).length >= 10) return; L.wheel[v.slice(0, 16)] = 5; save(); draw(); };
    const ws = $('#w-share'); if (ws) ws.onclick = () => post('My life wheel this week: ' + Object.entries(L.wheel).map(([k, v]) => `${k} ${v}/10`).join(' · ') + ' — working on it, one habit at a time. #LIFEboard');
    const va = $('#v-add'); if (va) va.onclick = () => { const v = $('#v-new').value.trim(); if (!v) return; L.vision.cards.push({ id: uid(), t: v.slice(0, 80), c: PAL[L.vision.cards.length % PAL.length], s: 's' }); save(); draw(); };
    const vi = $('#v-img'); if (vi) vi.onchange = async (e) => { const f = e.target.files[0]; if (!f) return; const r = new FileReader(); r.onload = () => { const img = new Image(); img.onload = () => { const c = document.createElement('canvas'); const s = Math.min(1, 480 / img.width); c.width = img.width * s; c.height = img.height * s; c.getContext('2d').drawImage(img, 0, 0, c.width, c.height); L.vision.cards.push({ id: uid(), t: f.name.replace(/\.[^.]+$/, '').slice(0, 40), c: '#0f172a', s: 'm', img: c.toDataURL('image/jpeg', 0.7) }); save(); draw(); }; img.src = r.result; }; r.readAsDataURL(f); };
    $$('[data-vs]').forEach(b => b.onclick = (e) => { e.stopPropagation(); const c = L.vision.cards.find(x => x.id === b.dataset.vs); c.s = { s: 'm', m: 'l', l: 's' }[c.s || 's']; save(); draw(); });
    $$('[data-vc]').forEach(b => b.onclick = (e) => { e.stopPropagation(); const c = L.vision.cards.find(x => x.id === b.dataset.vc); c.c = PAL[(PAL.indexOf(c.c) + 1) % PAL.length]; save(); draw(); });
    $$('[data-vx]').forEach(b => b.onclick = (e) => { e.stopPropagation(); L.vision.cards = L.vision.cards.filter(x => x.id !== b.dataset.vx); save(); draw(); });
    $$('[data-v]').forEach(el => { el.onclick = (e) => { if (e.target.closest('button')) return; const c = L.vision.cards.find(x => x.id === el.dataset.v); const v = prompt('Edit card', c.t); if (v !== null) { c.t = v.slice(0, 80); save(); draw(); } }; el.ondragstart = () => { dragId = el.dataset.v; }; el.ondragover = (e) => { e.preventDefault(); el.classList.add('over'); }; el.ondragleave = () => el.classList.remove('over'); el.ondrop = (e) => { e.preventDefault(); el.classList.remove('over'); const from = L.vision.cards.findIndex(x => x.id === dragId), to = L.vision.cards.findIndex(x => x.id === el.dataset.v); if (from < 0 || to < 0 || from === to) return; const [m] = L.vision.cards.splice(from, 1); L.vision.cards.splice(to, 0, m); save(); draw(); }; });
    const pa = $('#p-add'); if (pa) pa.onclick = () => { const v = $('#p-new').value.trim(); if (!v) return; L.projects.push({ id: uid(), t: v.slice(0, 80), s: 'Idea' }); save(); draw(); };
    $$('[data-ps]').forEach(s => s.onchange = () => { L.projects.find(p => p.id === s.dataset.ps).s = s.value; save(); }); $$('[data-pdel]').forEach(b => b.onclick = () => { L.projects = L.projects.filter(p => p.id !== b.dataset.pdel); save(); draw(); });
    $$('[data-madd]').forEach(b => b.onclick = () => { const k = b.dataset.madd; const n = $(`[data-mn="${k}"]`).value.trim(), v = +$(`[data-mv="${k}"]`).value; if (!n || !v) return; L.money[k].push({ id: uid(), t: n.slice(0, 40), v }); save(); draw(); });
    $$('[data-mdel]').forEach(b => b.onclick = () => { const [k, id] = b.dataset.mdel.split(':'); L.money[k] = L.money[k].filter(r => r.id !== id); save(); draw(); });
    $$('[data-gen]').forEach(b => b.onclick = () => { const k = b.dataset.gen; const inp = $(`[data-gin="${k}"]`); const out = gen(k, inp ? inp.value.trim() : ''); const o = $(`[data-gout="${k}"]`); o.hidden = false; o.textContent = out; const pb = $(`[data-gpost="${k}"]`); pb.hidden = false; pb.onclick = () => post(out); });
  };
  draw();
}
