/* ============================================================
   The COMM HUB (v7, Oct 2026) · every mailbox opens one.
   Messages: the full inbox with inline threads (reply, edit, delete, react, pictures, Unity Calls, meetings),
   tabs Inbox / Requests / Pinned / Archived, search, realtime. Same engine + thread as the DM page (aou-comm.js).
   Port: the hologram globe, bio, socials, stats, QR, RSS/JSON feed, and either the EASY configurator (your own
   hub) or the request deck (someone else's: connection, phone number, package, picture, GIF, file, ping).
   ============================================================ */
import { createStore, mountComm, ensureCommCSS, commToast, CI } from './aou-comm.js';
import { CALL_NAME, CALL_PATH } from './aou-call.js';
const $ = (s, r = document) => r.querySelector(s); const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const SOCIALS = [['x', 'X'], ['instagram', 'Instagram'], ['facebook', 'Facebook'], ['youtube', 'YouTube'], ['tiktok', 'TikTok'], ['linkedin', 'LinkedIn'], ['threads', 'Threads'], ['bluesky', 'Bluesky'], ['discord', 'Discord'], ['twitch', 'Twitch'], ['pinterest', 'Pinterest'], ['snapchat', 'Snapchat'], ['whatsapp', 'WhatsApp'], ['signal', 'Signal'], ['myspace', 'MySpace'], ['website', 'Website'], ['email', 'Email'], ['custom1', 'My own link'], ['custom2', 'My own link 2']];
const BLOCKED = /porn|xxx|onlyfans|sex|nsfw|escort|adult|xvideos|pornhub|fansly|nude/i;
const TOGGLES = [['feedPublic', 'Public feed', 'Anyone can read my public posts and subscribe'], ['dm', 'Direct messages', 'People can message me here'], ['connect', 'Connection requests', 'People can ask to connect'], ['phone', 'Phone-number requests', 'People can ask for my number'], ['package', 'Package requests', 'People can ask to send me something physical'], ['pics', 'Pictures, GIFs + files', 'People can send me media'], ['ping', 'Ping me when online', 'People can ask to be told when I am in the world'], ['fax', 'Fax', 'Show my fax number (sent free through FaxZero)'], ['socials', 'Show my socials', 'My links appear on my hub'], ['rss', 'RSS / JSON feed', 'Offer a feed link of my public posts']];
const DECK = [['connect', 'hand', 'Request connection', 'connect'], ['phone', 'phone', 'Request phone number', 'phone'], ['package', 'box', 'Package request', 'package'], ['pic', 'image', 'Send a picture', 'pics'], ['gif', 'image', 'Send a GIF', 'pics'], ['file', 'file', 'Send a file', 'pics'], ['ping', 'bell', 'Ping me when online', 'ping']];
const ZACH = { socials: { x: 'https://x.com/eyetoad', facebook: 'https://www.facebook.com/share/1FCtkAgToH/', website: 'https://eyetoad.com/', youtube: 'https://www.youtube.com/@eyetoad', instagram: 'https://www.instagram.com/eyetoad/', linkedin: 'https://www.linkedin.com/company/eye-to-ad-media/', tiktok: 'https://www.tiktok.com/@eyetoad', email: 'mailto:info@eyetoad.com' }, bio: 'Hi, I\'m Zach. I built allofus.one so all of us can find each other, help each other and build something good together. Say hi any time.' };
export const HUB_CSS = `
#hub{position:fixed;inset:0;z-index:99988;background:var(--bg);color:var(--ink);font-family:Poppins,"Segoe UI",Arial,sans-serif;display:grid;grid-template-rows:auto minmax(0,1fr);overflow:hidden}
#hub *{box-sizing:border-box}#hub :focus-visible{outline:2px solid #6366f1;outline-offset:2px}
#hub .hb-top{display:flex;align-items:center;gap:10px;padding:8px 12px;background:#fff;border-bottom:1px solid var(--line);min-width:0}
#hub .hb-logo{width:40px;height:40px;border-radius:10px;display:grid;place-items:center;background:linear-gradient(135deg,#0369a1,#4f46e5);color:#fff;flex:none}#hub .hb-logo .cm-i{width:22px;height:22px}
#hub .hb-t{display:flex;flex-direction:column;min-width:0;margin-right:auto}#hub .hb-t h1{margin:0;font:800 17px/1.2 Poppins,Arial;white-space:nowrap}#hub .hb-tabs .cm-badge{margin-left:2px}#hub .hb-t small{color:var(--mut);font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
#hub .hb-led{display:inline-block;width:8px;height:8px;border-radius:50%;background:#22c55e;margin-right:6px;vertical-align:1px}
#hub .hb-tabs{display:flex;gap:4px;background:var(--soft);border-radius:12px;padding:3px}#hub .hb-tabs button{display:inline-flex;align-items:center;gap:6px;white-space:nowrap;border:0;background:none;border-radius:10px;padding:8px 12px;font:700 13px Poppins,Arial;color:var(--mut);cursor:pointer;min-height:38px}#hub .hb-tabs button[aria-selected=true]{background:#fff;color:var(--ink);box-shadow:0 1px 3px rgba(2,8,30,.12)}#hub .hb-tabs .cm-i{width:18px;height:18px}
#hub .hb-call{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--line2);border-radius:10px;padding:8px 12px;min-height:40px;font:700 13px Poppins,Arial;color:var(--ink);text-decoration:none;white-space:nowrap}#hub .hb-call:hover{border-color:#94a3b8}#hub .hb-call .cm-i{width:18px;height:18px;color:var(--ind)}
#hub .hb-x{width:40px;height:40px;border:1px solid var(--line2);background:#fff;border-radius:10px;display:grid;place-items:center;cursor:pointer;color:var(--ink);flex:none}
#hub .hb-body{min-height:0;padding:12px;overflow:hidden}#hub .hb-pane{height:100%;min-height:0}#hub .hb-pane[hidden]{display:none}#hub .hb-pane.msgs{max-width:1320px;margin:0 auto}#hub .hb-pane.port{overflow:auto}
#hub .hb-port{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,440px);gap:12px;max-width:1120px;margin:0 auto;align-items:start}
#hub .hb-card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:14px 16px;min-width:0}#hub .hb-card h2{margin:0 0 8px;font:800 15px Poppins,Arial}#hub .hb-card h3{margin:14px 0 6px;font:800 13px Poppins,Arial;color:#475569}
#hub .hb-globe{background:radial-gradient(ellipse at 50% 20%,#0f2a5e,#050a1e 72%);color:#dff6ff;text-align:center;border:0}#hub canvas{width:min(300px,70vw);height:min(300px,70vw);display:block;margin:0 auto}
#hub .hb-who h2{margin:2px 0 4px;font:800 22px Poppins,Arial;color:#fff}#hub .hb-who p{margin:4px auto;max-width:520px;color:#cfe9ff;font-size:14px;line-height:1.5}
#hub .hb-soc{display:flex;flex-wrap:wrap;gap:6px;justify-content:center;margin:10px 0}#hub .hb-soc a,#hub .hb-soc button,#hub .hb-chip{display:inline-flex;align-items:center;gap:6px;border:1px solid rgba(124,248,255,.45);background:rgba(56,240,255,.1);color:#e6fbff;border-radius:10px;padding:7px 11px;font:700 12.5px Poppins,Arial;text-decoration:none;cursor:pointer;min-height:36px}#hub .hb-soc .cm-i{width:16px;height:16px}
#hub .hb-stat{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:10px auto;max-width:420px}#hub .hb-stat div{background:rgba(5,10,30,.55);border:1px solid rgba(56,240,255,.25);border-radius:10px;padding:6px}#hub .hb-stat b{display:block;font:800 18px Poppins,Arial;color:#7cf8ff}#hub .hb-stat small{font-size:10px;color:#9fd3ff;letter-spacing:.06em}
#hub .hb-qr{margin:8px auto 0;font-size:12px;color:#9fd3ff}#hub .hb-qr img{border-radius:10px;background:#fff;padding:4px;display:block;margin:0 auto 6px}
#hub label.hb-l{display:block;font:700 12px Poppins,Arial;color:#475569;margin:10px 0 4px}
#hub .hb-card input[type=text],#hub .hb-card input[type=url],#hub .hb-card textarea{width:100%;border:1px solid var(--line2);border-radius:10px;padding:9px 11px;font:500 14px Poppins,Arial;color:var(--ink);background:#fff;min-height:40px}#hub .hb-card textarea{min-height:80px;resize:vertical}
#hub .hb-deck{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:6px 0 4px}#hub .hb-deck button{display:flex;align-items:center;gap:8px;text-align:left;border:1px solid var(--line2);background:#fff;border-radius:10px;padding:9px 10px;font:700 13px Poppins,Arial;color:var(--ink);cursor:pointer;min-height:44px}#hub .hb-deck button .cm-i{width:18px;height:18px;color:var(--ind)}#hub .hb-deck button[aria-pressed=true]{border-color:var(--ind);background:#eef2ff}#hub .hb-deck button:disabled{opacity:.4;cursor:not-allowed}
#hub .hb-err{color:#dc2626;font-weight:700;font-size:13px;min-height:1em;margin:6px 0 0}#hub .hb-ok{color:#16a34a;font-weight:700;font-size:13px}
#hub .hb-sign{max-width:460px;margin:40px auto;text-align:center}
@media (max-width:899px){#hub .hb-body{padding:0}#hub .hb-pane.port{padding:12px}#hub .hb-port{grid-template-columns:1fr}#hub .hb-top{padding:6px 8px;gap:6px}#hub .hb-x,#hub .hb-call{width:44px;height:44px;padding:0;justify-content:center}#hub .hb-call span{display:none}#hub .hb-tabs button{min-height:44px;padding:8px 10px}#hub .hb-logo{display:none}#hub .cm-app{height:100%}}
@media (max-width:520px){#hub .hb-t small{display:none}#hub .hb-tabs button>.cm-i{display:none}#hub .hb-tabs button{padding:8px 9px}#hub .hb-t h1{font-size:15px}#hub .hb-deck{grid-template-columns:1fr}}
`;
let hubCSS = false;
export async function openHub({ sb, me, owner, toast: _t, onClose }) {
  if (document.getElementById('hub')) return; ensureCommCSS(); if (!hubCSS && !document.getElementById('hub-css')) { const st = document.createElement('style'); st.id = 'hub-css'; st.textContent = HUB_CSS; document.head.appendChild(st); } hubCSS = true;
  const toast = commToast; /* the Feed's toast sits under this overlay */
  const mine = !!(me && owner && me.id === owner.id); const Q = new URLSearchParams(location.search);
  const cfg = Object.assign({ feedPublic: true, dm: true, connect: true, phone: false, package: false, pics: true, socials: true, rss: true, socialsLinks: {}, bio: '' }, (owner && owner.home && owner.home.hub) || {}); if (owner && owner.zach) { cfg.socialsLinks = Object.assign({}, ZACH.socials, cfg.socialsLinks); cfg.bio = cfg.bio || ZACH.bio; cfg.phone = true; cfg.package = true; }
  const oname = (owner && owner.name) || 'Someone'; const prevFocus = document.activeElement; const prevOverflow = document.documentElement.style.overflow;
  const el = document.createElement('div'); el.id = 'hub'; el.setAttribute('role', 'dialog'); el.setAttribute('aria-modal', 'true'); el.setAttribute('aria-labelledby', 'hub-title');
  el.innerHTML = `<header class="hb-top"><span class="hb-logo" aria-hidden="true">${CI.hex}</span><div class="hb-t"><h1 id="hub-title">Comm Hub</h1><small><span class="hb-led" aria-hidden="true"></span>${mine ? 'Your port' : esc(oname) + '\'s port'} · link established</small></div>
    <div class="hb-tabs" role="tablist" aria-label="Comm Hub sections"><button type="button" role="tab" id="hb-t-msgs" aria-controls="hb-p-msgs" data-pane="msgs">${CI.inbox}<span>Messages</span></button><button type="button" role="tab" id="hb-t-port" aria-controls="hb-p-port" data-pane="port">${CI.hex}<span>${mine ? 'My port' : 'Port'}</span></button></div>
    <a class="hb-call" href="${CALL_PATH}" target="_blank" rel="noopener" title="Open ${CALL_NAME}">${CI.video}<span>${CALL_NAME}</span></a><button type="button" class="hb-x" aria-label="Close Comm Hub">${CI.x}</button></header>
    <div class="hb-body"><div class="hb-pane msgs" id="hb-p-msgs" role="tabpanel" aria-labelledby="hb-t-msgs"></div><div class="hb-pane port" id="hb-p-port" role="tabpanel" aria-labelledby="hb-t-port" hidden>
      <div class="hb-port"><section class="hb-card hb-globe" aria-label="${esc(oname)}"><canvas id="hub-globe" width="420" height="420" aria-hidden="true"></canvas><div class="hb-who"><h2>${esc(oname)}</h2><p>${esc(cfg.bio || '')}</p><div class="hb-soc" id="hub-soc"></div><div class="hb-stat" id="hub-stat"></div><div class="hb-soc"><a href="/?u=${esc((owner && owner.username) || 'me')}">${CI.user}<span>${mine ? 'My' : 'Their'} page + feed</span></a>${cfg.rss ? `<button type="button" id="hub-rss">${CI.download}<span>Feed link</span></button>` : ''}${!mine && me ? `<button type="button" data-goto="msgs">${CI.send}<span>Message</span></button>` : ''}</div><div class="hb-qr" id="hub-qr"></div></div></section>
      <section class="hb-card" id="hub-right"><h2>${mine ? 'Easy configurator' : 'Send a request'}</h2><div id="hub-r"></div></section></div></div></div>`;
  document.body.appendChild(el); document.documentElement.style.overflow = 'hidden';
  let store = null, app = null, raf = 0;
  const close = () => { cancelAnimationFrame(raf); raf = 0; try { app && app.destroy(); } catch (e) { } try { store && store.destroy(); } catch (e) { } el.remove(); document.documentElement.style.overflow = prevOverflow; try { prevFocus && prevFocus.focus && prevFocus.focus(); } catch (e) { } onClose && onClose(); };
  $('.hb-x', el).onclick = close;
  el.addEventListener('keydown', (e) => { e.stopPropagation(); if (e.key === 'Escape' && !document.querySelector('.cm-menu') && !$('.cm-sheet', el)) { e.preventDefault(); close(); } if (e.key === 'Tab') { const f = $$('button:not([disabled]),a[href],input:not([type=hidden]):not([type=file]),textarea,select,[tabindex="0"]', el).filter(x => x.offsetParent !== null); if (!f.length) return; if (e.shiftKey && document.activeElement === f[0]) { e.preventDefault(); f[f.length - 1].focus(); } else if (!e.shiftKey && document.activeElement === f[f.length - 1]) { e.preventDefault(); f[0].focus(); } } });
  ['keyup', 'keypress'].forEach(ev => el.addEventListener(ev, (e) => e.stopPropagation()));

  /* ---------- tabs ---------- */
  let pane = '';
  const show = (p) => { pane = p; $$('.hb-tabs [data-pane]', el).forEach(b => { const on = b.dataset.pane === p; b.setAttribute('aria-selected', String(on)); b.tabIndex = on ? 0 : -1; }); $('#hb-p-msgs', el).hidden = p !== 'msgs'; $('#hb-p-port', el).hidden = p !== 'port'; if (p === 'port' && !raf) draw(); if (p !== 'port') { cancelAnimationFrame(raf); raf = 0; } };
  $('.hb-tabs', el).addEventListener('click', (e) => { const b = e.target.closest('[data-pane]'); if (b) show(b.dataset.pane); });
  $('.hb-tabs', el).addEventListener('keydown', (e) => { if (!/Arrow(Left|Right)/.test(e.key)) return; const n = pane === 'msgs' ? 'port' : 'msgs'; show(n); $(`[data-pane="${n}"]`, el).focus(); });
  el.addEventListener('click', (e) => { const g = e.target.closest('[data-goto]'); if (g) show(g.dataset.goto); });

  /* ---------- the hologram globe (only animates while the Port tab is open) ---------- */
  const cv = $('#hub-globe', el), g = cv.getContext('2d'); let rot = 0; const R = 150, cx = 210, cy = 200; const pts = []; for (let i = 0; i < 90; i++) pts.push([Math.random() * Math.PI * 2, (Math.random() - 0.5) * Math.PI * 0.9, Math.random()]);
  const still = (() => { try { return matchMedia('(prefers-reduced-motion: reduce)').matches; } catch (e) { return false; } })();
  const draw = () => { rot += 0.006; g.clearRect(0, 0, 420, 420); g.save(); const grad = g.createRadialGradient(cx, cy, R * 0.2, cx, cy, R * 1.25); grad.addColorStop(0, 'rgba(56,240,255,.18)'); grad.addColorStop(1, 'rgba(56,240,255,0)'); g.fillStyle = grad; g.fillRect(0, 0, 420, 420); g.strokeStyle = 'rgba(56,240,255,.55)'; g.lineWidth = 1;
    for (let la = -75; la <= 75; la += 15) { const r = R * Math.cos(la * Math.PI / 180), y = cy - R * Math.sin(la * Math.PI / 180) * 0.92; g.beginPath(); g.ellipse(cx, y, r, r * 0.22, 0, 0, Math.PI * 2); g.stroke(); }
    for (let lo = 0; lo < 180; lo += 22.5) { const a = lo * Math.PI / 180 + rot; g.beginPath(); for (let t = -Math.PI / 2; t <= Math.PI / 2 + 0.01; t += 0.1) { const x = cx + R * Math.cos(t) * Math.cos(a), y = cy - R * Math.sin(t) * 0.92; const z = Math.cos(t) * Math.sin(a); if (t === -Math.PI / 2) g.moveTo(x, y); else g.lineTo(x, y); g.globalAlpha = z > 0 ? 0.9 : 0.25; } g.stroke(); g.globalAlpha = 1; }
    for (const [lo, la, k] of pts) { const a = lo + rot; const z = Math.cos(la) * Math.sin(a); if (z < 0) continue; const x = cx + R * Math.cos(la) * Math.cos(a), y = cy - R * Math.sin(la) * 0.92; g.fillStyle = k > 0.8 ? '#ff4fd8' : k > 0.5 ? '#7cff6b' : '#ffd23f'; g.shadowColor = g.fillStyle; g.shadowBlur = 8; g.beginPath(); g.arc(x, y, 2.2 + (Math.sin(Date.now() / 300 + k * 10) + 1), 0, 6.28); g.fill(); g.shadowBlur = 0; }
    g.restore(); raf = still ? 0 : requestAnimationFrame(draw); };

  /* ---------- socials, QR, stats, RSS ---------- */
  const soc = $('#hub-soc', el); if (cfg.socials) soc.innerHTML = SOCIALS.filter(([k]) => cfg.socialsLinks[k] && !BLOCKED.test(cfg.socialsLinks[k])).map(([k, n]) => `<a href="${esc(cfg.socialsLinks[k])}" target="_blank" rel="noopener">${CI.link}<span>${k.startsWith('custom') && cfg.socialsNames && cfg.socialsNames[k] ? esc(cfg.socialsNames[k]) : n}</span></a>`).join('') || '<span style="color:#9fd3ff;font-size:13px">No links shared yet.</span>'; if (cfg.fax && cfg.faxNumber) soc.innerHTML += `<a href="https://faxzero.com/" target="_blank" rel="noopener">${CI.file}<span>Fax ${esc(cfg.faxNumber)} (free via FaxZero)</span></a>`;
  { const link = 'https://allofus.one/?u=' + encodeURIComponent((owner && owner.username) || ''); const qr = $('#hub-qr', el); qr.innerHTML = `<img alt="QR code to this hub" width="110" height="110" loading="lazy" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(link)}"><span>Scan to open this hub</span> <span class="hb-soc" style="display:inline-flex;margin:4px 0 0"><button type="button" id="hub-copy">${CI.copy}<span>Copy link</span></button></span>`; $('#hub-copy', el).onclick = async () => { try { await navigator.clipboard.writeText(link); toast('Link copied.'); } catch (e) { prompt('Copy this link:', link); } }; }
  const stat = $('#hub-stat', el); const fill = async () => { if (!sb || !owner) { stat.innerHTML = ''; return; } try { const [{ count: posts }, { count: conns }] = await Promise.all([sb.from('feed_posts').select('id', { count: 'exact', head: true }).eq('user_id', owner.id).eq('public', true), sb.from('hub_requests').select('id', { count: 'exact', head: true }).eq('to_user', owner.id).eq('kind', 'connect').eq('status', 'accepted')]); stat.innerHTML = `<div><b>${posts || 0}</b><small>PUBLIC POSTS</small></div><div><b>${conns || 0}</b><small>CONNECTIONS</small></div><div><b>${[cfg.dm, cfg.connect, cfg.phone, cfg.package, cfg.pics].filter(Boolean).length}</b><small>CHANNELS OPEN</small></div>`; } catch (e) { stat.innerHTML = ''; } }; fill();
  const rssBtn = $('#hub-rss', el); if (rssBtn) rssBtn.onclick = async () => { if (!sb) { toast('The feed link needs the live server.'); return; } const base = sb.supabaseUrl || ''; const key = sb.supabaseKey || ''; const url = `${base}/rest/v1/feed_posts?select=id,text,kind,link,media,created_at&user_id=eq.${owner.id}&public=eq.true&order=created_at.desc&apikey=${key}`; const { data } = await sb.from('feed_posts').select('*').eq('user_id', owner.id).eq('public', true).order('created_at', { ascending: false }).limit(50); const rss = `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${esc(owner.name)} · allofus.one</title><link>https://allofus.one/?u=${esc(owner.username || '')}</link><description>Public posts</description>${(data || []).map(p => `<item><title>${esc((p.text || p.kind).slice(0, 80))}</title><link>https://allofus.one/?u=${esc(owner.username || '')}</link><pubDate>${new Date(p.created_at).toUTCString()}</pubDate><description>${esc(p.text || '')}</description></item>`).join('')}</channel></rss>`; const blob = new Blob([rss], { type: 'application/rss+xml' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = (owner.username || 'feed') + '.rss.xml'; a.click(); try { await navigator.clipboard.writeText(url); toast('RSS file downloaded, and the live JSON feed link is copied.'); } catch (e) { toast('RSS file downloaded.'); } };

  /* ---------- Messages tab: the inbox (mine) or the thread with this person (theirs) ---------- */
  const msgs = $('#hb-p-msgs', el);
  const openFull = (p) => { location.href = '/?v=dm' + (p && p.username ? '&with=' + encodeURIComponent(p.username) : ''); };
  if (me && sb !== undefined) {
    store = createStore({ sb, me, toast });
    if (mine) app = mountComm(msgs, { store, mode: 'hub', toast, onOpenFull: openFull });
    else app = mountComm(msgs, { store, mode: 'hub', single: owner.id, toast, onOpenFull: openFull });
    store.loadAll().then(async () => { store.subscribe(); app.renderList(); const w = Q.get('with'); if (mine && w) await app.open(w); const badge = () => { const n = store.threads().filter(t => t.unread && !t.archived).length; const tb = $('[data-pane="msgs"]', el); let b = $('.cm-badge', tb); if (!b) { b = document.createElement('b'); b.className = 'cm-badge'; tb.appendChild(b); } b.hidden = !n; b.textContent = n; b.setAttribute('aria-label', n + ' unread'); }; badge(); store.on(badge); });
  } else msgs.innerHTML = `<div class="hb-card hb-sign"><h2>Sign in to message ${esc(oname)}</h2><p style="color:var(--mut)">Your messages, requests and ${CALL_NAME}s live in your Comm Hub. Joining is free.</p><div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap"><button type="button" class="cm-btn p" data-join>Join free</button><button type="button" class="cm-btn" data-signin>Sign in</button></div></div>`;
  $$('[data-join],[data-signin]', msgs).forEach(b => b.addEventListener('click', () => { close(); }));

  /* ---------- right card: configurator (mine) or request deck (theirs) ---------- */
  const right = $('#hub-r', el);
  const sw = (k, n, d) => `<label class="cm-sw"><span><b>${n}</b><small>${d}</small></span><input type="checkbox" data-k="${k}" ${cfg[k] ? 'checked' : ''}><i aria-hidden="true"></i></label>`;
  if (mine) {
    right.innerHTML = TOGGLES.map(([k, n, d]) => sw(k, n, d)).join('') + `<label class="hb-l" for="hc-bio">About me (shows on my hub)</label><textarea id="hc-bio" maxlength="400">${esc(cfg.bio || '')}</textarea><label class="hb-l" for="hc-fax">Fax number (optional)</label><input type="text" id="hc-fax" value="${esc(cfg.faxNumber || '')}" placeholder="+1 303 555 0100"><p style="font-size:12px;color:var(--mut)">Family friendly only: adult links are blocked automatically and get your hub closed.</p><h3>My links</h3>` + SOCIALS.map(([k, n]) => `<label class="hb-l" for="hs-${k}">${n}</label>${k.startsWith('custom') ? `<input type="text" data-sn="${k}" aria-label="Name for ${n}" value="${esc((cfg.socialsNames || {})[k] || '')}" placeholder="Name it (e.g. My Etsy)" style="margin-bottom:4px">` : ''}<input type="url" id="hs-${k}" data-s="${k}" value="${esc(cfg.socialsLinks[k] || '')}" placeholder="https://">`).join('') + `<div style="margin-top:12px;display:flex;gap:10px;align-items:center"><button type="button" class="cm-btn p" id="hc-save">Save configuration</button><span class="hb-ok" id="hc-ok" role="status"></span></div><p style="font-size:12px;color:var(--mut);margin-top:8px">Messaging privacy (who can message you, requests, read receipts, sound) lives in Messages → settings.</p>`;
    $('#hc-save', el).onclick = async () => { TOGGLES.forEach(([k]) => { cfg[k] = $(`[data-k="${k}"]`, right).checked; }); cfg.bio = $('#hc-bio', el).value.trim(); cfg.faxNumber = ($('#hc-fax', el).value || '').trim(); cfg.socialsLinks = {}; cfg.socialsNames = {}; let bad = false; SOCIALS.forEach(([k]) => { const v = $(`[data-s="${k}"]`, el).value.trim(); if (v && BLOCKED.test(v)) { bad = true; return; } if (v) cfg.socialsLinks[k] = v; const nEl = $(`[data-sn="${k}"]`, el); if (nEl && nEl.value.trim()) cfg.socialsNames[k] = nEl.value.trim().slice(0, 30); }); if (bad) toast('One link was blocked: adult sites are not allowed here.');
      if (!sb) { toast('Saving needs the live server.'); return; } let home = me.home || {}; try { const { data } = await sb.from('profiles').select('home').eq('id', me.id).maybeSingle(); if (data && data.home) home = data.home; } catch (e) { } const next = Object.assign({}, home, { hub: cfg }); try { const { error } = await sb.from('profiles').update({ home: next }).eq('id', me.id); if (error) throw error; me.home = next; $('#hc-ok', el).textContent = 'Saved.'; toast('Hub configured.'); } catch (e) { toast('Could not save: ' + (e.message || e)); } };
  } else {
    right.innerHTML = `<div class="hb-deck" role="group" aria-label="What to send">${DECK.map(([k, icon, n, flag]) => `<button type="button" data-k="${k}" aria-pressed="false" ${cfg[flag] ? '' : 'disabled'}>${CI[icon]}<span>${n}</span></button>`).join('')}${cfg.fax && cfg.faxNumber ? `<a class="cm-btn" href="https://faxzero.com/" target="_blank" rel="noopener">${CI.file}<span>Fax them (free)</span></a>` : ''}</div><label class="hb-l" id="hs-l" for="hs-dm">Note</label><textarea id="hs-dm" maxlength="2000" placeholder="Add a note (optional)"></textarea><input type="url" id="hs-url" aria-label="GIF address" placeholder="GIF address (https://…gif)" style="display:none;margin-top:6px"><input type="file" id="hs-f" hidden><div style="margin-top:10px;display:flex;gap:8px;flex-wrap:wrap"><button type="button" class="cm-btn p" id="hs-go">${CI.send}<span>Send</span></button>${me && cfg.dm !== false ? `<button type="button" class="cm-btn" data-goto="msgs">${CI.inbox}<span>Write a message instead</span></button>` : ''}</div><p class="hb-err" id="hs-err" role="alert"></p>`;
    let kind = ''; const L = { connect: 'Why connect? (optional)', phone: 'Why do you need it? (optional)', package: 'What are you sending, from where?', pic: 'A note with your picture', gif: 'A note with your GIF', file: 'A note with your file', ping: 'Why (optional): they hear the next time they are in the world' };
    const pick = (k) => { kind = k; $$('.hb-deck button', right).forEach(b => b.setAttribute('aria-pressed', String(b.dataset.k === k))); $('#hs-l', el).textContent = L[k] || 'Note'; $('#hs-url', el).style.display = k === 'gif' ? '' : 'none'; if (k === 'pic' || k === 'file') { $('#hs-f', el).accept = k === 'pic' ? 'image/*' : '*/*'; $('#hs-f', el).click(); } };
    $$('.hb-deck button', right).forEach(b => b.onclick = () => pick(b.dataset.k)); const firstOpen = DECK.find(d => cfg[d[3]]); if (firstOpen) pick(firstOpen[0] === 'pic' || firstOpen[0] === 'file' ? 'connect' : firstOpen[0]);
    $('#hs-go', el).onclick = async () => { const err = $('#hs-err', el); if (!me) { err.textContent = 'Sign in (Join) first.'; return; } if (!sb) { err.textContent = 'Offline.'; return; } if (!kind) { err.textContent = 'Pick what to send.'; return; } let media = null; try { if (kind === 'gif') { media = $('#hs-url', el).value.trim(); if (!/^https?:\/\//.test(media)) { err.textContent = 'Paste a GIF address.'; return; } } if (kind === 'pic' || kind === 'file') { const f = $('#hs-f', el).files[0]; if (!f) { err.textContent = 'Pick a file first.'; return; } const ext = (f.name.split('.').pop() || 'bin').toLowerCase().replace(/[^a-z0-9]/g, ''); const path = `${me.id}/hub-${Date.now()}.${ext}`; const { error: ue } = await sb.storage.from('posts').upload(path, f, { contentType: f.type || 'application/octet-stream' }); if (ue) throw ue; media = sb.storage.from('posts').getPublicUrl(path).data.publicUrl; } const body = $('#hs-dm', el).value.trim(); if (kind === 'package' && !body) { err.textContent = 'Say what you are sending.'; return; } const { error } = await sb.from('hub_requests').insert({ from_user: me.id, to_user: owner.id, kind: kind === 'ping' ? 'dm' : kind, body: kind === 'ping' ? 'PING: ' + (body || 'tell me when you are online') : body, media }); if (error) throw error; err.textContent = ''; toast(kind === 'ping' ? 'Ping set. They see it the moment they open their hub.' : 'Sent. It shows in your conversation with ' + oname + '.'); $('#hs-dm', el).value = ''; if (store) store.loadAll(); } catch (e) { err.textContent = e.message || String(e); } };
  }
  show(Q.get('pane') === 'port' || (!mine && !me) ? 'port' : 'msgs'); setTimeout(() => { const t = $('.hb-tabs [aria-selected=true]', el); if (t && !el.contains(document.activeElement)) t.focus(); }, 0);
  return { close, store, app };
}
