/* 🪐 ORBIT · the allofus.one helper (Oct 2026). A friendly little moon-station with glasses and a big smile.
   Deterministic keyword intents (no API key), knows every link and feature of the Feed, the 3D world, VR and
   World VR Mall, helps business owners, and hands off to a human (1-800-481-8638 or info at eyetoad.com) when
   asked. Side tab keeps the character's shape when collapsed. */
const ORBIT_SVG = (s = 64) => `<svg viewBox="0 0 100 100" width="${s}" height="${s}" aria-hidden="true"><defs><radialGradient id="ob" cx="38%" cy="32%" r="70%"><stop offset="0" stop-color="#c9d4e6"/><stop offset=".6" stop-color="#7d8aa6"/><stop offset="1" stop-color="#3c4660"/></radialGradient><radialGradient id="oe" cx="50%" cy="50%" r="50%"><stop offset="0" stop-color="#38f0ff"/><stop offset=".7" stop-color="#0ea5e9"/><stop offset="1" stop-color="#0b1a3a"/></radialGradient></defs><circle cx="50" cy="50" r="46" fill="url(#ob)"/><path d="M4 56 Q50 66 96 56" stroke="#2b3447" stroke-width="2.5" fill="none" opacity=".7"/><circle cx="35" cy="34" r="12" fill="url(#oe)"/><circle cx="35" cy="34" r="12" fill="none" stroke="#0b1a3a" stroke-width="2"/><rect x="18" y="24" width="34" height="22" rx="8" fill="none" stroke="#14183a" stroke-width="3.5"/><rect x="56" y="24" width="30" height="22" rx="8" fill="none" stroke="#14183a" stroke-width="3.5"/><path d="M52 35 h4" stroke="#14183a" stroke-width="3.5"/><circle cx="71" cy="35" r="5" fill="#14183a"/><circle cx="73" cy="33" r="1.8" fill="#fff"/><path d="M28 64 Q50 86 74 64" stroke="#14183a" stroke-width="4.5" fill="none" stroke-linecap="round"/><path d="M34 70 Q50 80 66 70" fill="#ff8aa6"/><g opacity=".5" fill="#1f2a44"><circle cx="78" cy="56" r="2"/><circle cx="62" cy="76" r="1.5"/><circle cx="22" cy="72" r="1.6"/><circle cx="84" cy="70" r="1.3"/></g></svg>`;
export const ORBIT_CSS = `#orbit-tab{position:fixed;right:-6px;top:52%;z-index:95;width:84px;height:92px;border:0;background:transparent;cursor:pointer;padding:0;filter:drop-shadow(0 10px 20px rgba(2,8,30,.35));transition:transform .2s}#orbit-tab:hover{transform:translateX(-6px) scale(1.04)}#orbit-tab svg{animation:orbitBob 3.6s ease-in-out infinite}#orbit-tab .say{position:absolute;right:66px;top:14px;background:#fff;color:#14183a;border-radius:14px 14px 2px 14px;padding:6px 10px;font:800 12px Poppins,Arial;white-space:nowrap;box-shadow:0 8px 20px rgba(2,8,30,.2);border:1px solid #e2e8f0}@keyframes orbitBob{0%,100%{transform:translateY(0) rotate(-3deg)}50%{transform:translateY(-6px) rotate(3deg)}}
#orbit{position:fixed;right:14px;bottom:14px;z-index:130;width:min(380px,calc(100vw - 28px));height:min(600px,calc(100vh - 28px));background:#fff;border-radius:22px;box-shadow:0 30px 80px rgba(2,8,30,.45);display:none;flex-direction:column;overflow:hidden;border:1px solid #e2e8f0}#orbit.on{display:flex}#orbit .hd{display:flex;align-items:center;gap:10px;padding:10px 12px;background:linear-gradient(135deg,#0b1a3a,#1e3a6a);color:#fff}#orbit .hd b{font:900 15px Poppins,Arial;flex:1}#orbit .hd small{display:block;font:500 11px Poppins,Arial;color:#9fdcff}#orbit .hd button{border:0;background:rgba(255,255,255,.14);color:#fff;border-radius:50%;width:30px;height:30px;cursor:pointer}#orbit .log{flex:1;overflow:auto;padding:12px;display:flex;flex-direction:column;gap:8px;background:#f6f8fc}#orbit .m{max-width:86%;padding:9px 12px;border-radius:16px;font:500 13.5px/1.45 Poppins,Arial;color:#14183a;white-space:pre-wrap}#orbit .m.b{background:#fff;border:1px solid #e2e8f0;border-bottom-left-radius:4px;align-self:flex-start}#orbit .m.u{background:linear-gradient(135deg,#0ea5e9,#6366f1);color:#fff;border-bottom-right-radius:4px;align-self:flex-end}#orbit .m a{color:#0369a1;font-weight:700}#orbit .m.u a{color:#fff}#orbit .chips{display:flex;gap:6px;flex-wrap:wrap;padding:0 12px 8px;background:#f6f8fc}#orbit .chips button{border:1.5px solid #dbe3ee;background:#fff;border-radius:999px;padding:6px 10px;font:700 12px Poppins,Arial;cursor:pointer}#orbit .chips button:hover{border-color:#0ea5e9;background:#f0f9ff}#orbit form{display:flex;gap:6px;padding:10px;border-top:1px solid #e2e8f0;background:#fff}#orbit form input{flex:1;border:1.5px solid #cbd5e1;border-radius:12px;padding:10px 12px;font:600 13.5px Poppins,Arial;outline:0}#orbit form input:focus{border-color:#0ea5e9}#orbit form button{border:0;background:linear-gradient(135deg,#0ea5e9,#6366f1);color:#fff;border-radius:12px;padding:0 14px;font:800 13px Poppins,Arial;cursor:pointer}@media(max-width:600px){#orbit-tab{top:auto;bottom:150px;width:66px;height:72px}#orbit{right:0;bottom:0;width:100vw;height:100vh;border-radius:0}}`;
const PHONE = '1-800-481-8638';
const L = {
  feed: '/', join: '/?v=u', brand: '/?v=brand', groups: '/?v=groups', conn: '/?v=conn', alerts: '/?v=notif', search: '/?v=search', video: '/?v=video', boost: '/boost/', world: '/world/', vr: '/world/?vr=1', house: '/world/?home=1', coaster: '/world/?to=coaster', beach: '/world/?to=beach', board: '/?board=1', work: '/?work=1', hub: '/?hub=1', rooms: '/rooms/', match: '/match/', mall: 'https://worldvrmall.com/', mallLease: 'https://worldvrmall.com/lease/', mallDir: 'https://worldvrmall.com/directory/', eyetoad: 'https://eyetoad.com/', sc: 'https://searchconverts.com/', usa: 'https://usabusinesssearch.com/', pr: 'https://pressreleaseforbusiness.com/', agn: 'https://actionglobalnews.com/', lifeboard: 'https://ailifeboard.com/', rules: '/community-rules/', privacy: '/privacy/', terms: '/terms/', mission: '/mission/', a11y: '/accessibility/'
};
const a = (t, h) => `<a href="${h}"${/^https?:/.test(h) ? ' target="_blank" rel="noopener"' : ''}>${t}</a>`;
/* intents: [regex, reply(ctx) -> string, chips] — first match wins, so put the specific before the general */
const INTENTS = [
  [/\b(human|person|real people|talk to someone|call|phone|speak to|agent|representative|support)\b/i, () => `You always get a person here. Call ${PHONE} (we answer), or email info at eyetoad dot com. Office: 1001 Bannock St #660, Denver. Want me to try first? Tell me what you are after.`, ['Join', 'Brand page help', 'VR controls']],
  [/\b(join|sign ?up|sign ?in|log ?in|register|account|password|magic link)\b/i, () => `Joining takes a minute and stays in the Feed: tap ${a('Join free', L.join)} (name, @username, email, password). Prefer to build your 3D house and character first? ${a('Join in 3D', L.world + '?join=1')}. Forgot your password? Use "Email me a sign-in link" on the sign-in tab.`, ['What can I do here?', 'Build my house', 'Brand page']],
  [/\b(brand page|business page|my brand|business|company|listing|advertis|promote|customers|leads|seo|google|rank|website|web ?site|marketing|ads?)\b/i, () => `Brand pages run from your profile: ${a('open Brand', L.brand)} → Build my Brand page. Drag sections, upload a logo and cover, add services, FAQ, video, an open HTML block and a JSON-LD block, plus two admins.\n\nWant it done right, fast? Our experts build it fully optimized for conversions, search engines and AI engines in 24–48 hours, with a free listing on ${a('usabusinesssearch.com', L.usa)}, a press release on ${a('pressreleaseforbusiness.com', L.pr)} and a 3D storefront in ${a('World VR Mall', L.mall)}. Tap "Have the experts build it" on the Brand page, or call ${PHONE}. For a full-service plan: ${a('eyetoad.com', L.eyetoad)} · ${a('searchconverts.com', L.sc)}.`, ['Have the experts build it', 'searchBOOST', 'Mall storefront']],
  [/\b(searchboost|search boost|campaign|post boost|group ad|cover photo ad)\b/i, () => `${a('searchBOOST', L.boost)} is the marketing hub: ad and post generators, the campaign builder, packages, and group advertising to 200,000+ members in our local buy/sell/trade groups. Everything there is a gateway to real humans at ${a('Eye To Ad Media', L.eyetoad)} if you want it run for you.`, ['Brand page', 'Human']],
  [/\b(mall|store|storefront|shop|lease|rent a store|sell (my )?products|ecommerce|shopify)\b/i, () => `${a('World VR Mall', L.mall)} is a walk-in 3D mall with real storefronts that link to your checkout. ${a('Lease a store', L.mallLease)} (set up in about ten minutes), browse the ${a('directory', L.mallDir)}, ride the Chiller, or put on a Quest and shop in VR. Brand page owners get a storefront as part of the expert build.`, ['Lease a store', 'Brand page', 'VR controls']],
  [/\b(vr|quest|headset|oculus|laser|controller|grip|trigger|menu button|teleport|giant|ant|size mode|view|follow cam|drone)\b/i, () => `VR on a Quest: open ${a('allofus.one/world/?vr=1', L.vr)} and tap Enter VR.\n• Left stick walks, right stick snap-turns.\n• Trigger = click what the laser points at. Grip = pull yourself there. Stick-click = teleport.\n• Y = the big menu (places, rides, views, size, floor, bug report). X = cycle first person / follow cam / drone.\n• A = do the nearest thing. B = log a bug with your position.\n• Size mode is off until you turn it on in the menu (then both grips resize you). Rides always reset you to life-size.\nIf the floor feels wrong, Raise / Lower my view is in the menu.`, ['Ride the coaster', 'Bug report', 'Build my house']],
  [/\b(coaster|roller|ride|chiller|thrill)\b/i, () => `🎢 The Peace Coaster: ${a('jump straight to it', L.coaster)}, step on the purple pad, press A (or tap). In the mall it is the Chiller: eleven ride modes on the same steel. In VR, open the Y menu → Ride the coaster.`, ['VR controls', 'Beach']],
  [/\b(house|home|build|land|lot|character|avatar|customi[sz]e|outfit|face|selfie)\b/i, () => `Your 3D house: ${a('My house', L.house)} opens it (new members land in the builder first). Customize your character, land and house from the 🎨 Customize button in the world, or ${a('Jump into 3D', L.world)} and press C. Your selfie becomes your face in 3D if you want it to.`, ['Join', 'VR controls']],
  [/\b(group|buy|sell|trade|free stuff|marketplace|vehicles|furniture|classified)\b/i, () => `${a('Groups', L.groups)}: national buy / sell / trade / free-stuff groups with no fees, no ranking games and no ads you did not ask for. Open a group, tap Join, post. Members of the business growth accelerator get priority placement across our 200,000+ member local groups.`, ['Post something', 'Brand page']],
  [/\b(feed|post|react|comment|share|save|dear feed|algorithm|timeline)\b/i, () => `The ${a('Feed', L.feed)} shows Everyone, your Connections, Mine or Saved. There is no hidden algorithm: Dear Feed (right rail) is the whole algorithm — type what you want more of. React with the strip under a post, comment, save, or Share → feed, group, room, connection, your 3D house sign, or any app.`, ['Dear Feed', 'Search']],
  [/\b(connect|connection|friend|follow|wave|people|find someone|username)\b/i, () => `Find anyone with ${a('Search', L.search)} (@username works), tap Connect; they accept under ${a('Connections', L.conn)}. In 3D, walk up and wave. Messages live in the ${a('Comm Hub', L.hub)}.`, ['Search', 'Comm Hub']],
  [/\b(room|meeting|conference|presentation|present|webinar|group call|video call|zoom|together|global room)\b/i, () => `Rooms: ${a('Comm Hub', L.hub)} has live text rooms (#general, #business, #kindness, #banquet, #help). The Global Room — a virtual space for your whole team or group with a presentation wall, in flat, 3D or VR — is being set up at ${a('allofus.one/rooms', L.rooms)}: pick a setting, size and format and it builds the space.`, ['Set up a room', 'Comm Hub']],
  [/\b(lifeboard|life board|dashboard|goals|habits|health|wellness|track)\b/i, () => `${a('LIFEboard', L.board)} is your life dashboard — goals, habits, health, money, the stuff that matters — and it syncs with the ${a('AI LIFEboard app', L.lifeboard)}. One honest place to see how you are doing and what to do next.`, ['FLOWworks', 'Join']],
  [/\b(flowworks|flow works|pads?|tools|whiteboard|workspace|files|notes|kanban|canvas)\b/i, () => `${a('FLOWworks', L.work)} is the work canvas: pads for notes, files, flows, calendars, web, email and more. Drag them around, ⤢ to go full screen, upload files (saved to your account). It is yours alone unless you share a pad.`, ['LIFEboard', 'Join']],
  [/\b(search|find|where is|how do i get to|lost)\b/i, () => `${a('Search', L.search)} covers people, posts, brands and groups (top bar on desktop, the 🔍 on mobile). In 3D, press Y in VR or open the map to jump to any place: beach, spiders, golf, snowboard, coaster, Unity Heights, the lake, the zoo, the gallery, the arcade.`, ['VR controls', 'Groups']],
  [/\b(bug|broken|glitch|not working|error|crash|stuck|report)\b/i, () => `Thank you — allofus.one is in active development and every report is read by a person. Tap the 🐞 button (bottom left) and type one line; your page and device come along automatically. In VR press B and the report captures your exact position.`, ['Human', 'VR controls']],
  [/\b(privacy|data|rules|terms|safe|kids|accessib|mission|about|who made|zach)\b/i, () => `${a('Mission', L.mission)} · ${a('Community rules', L.rules)} · ${a('Privacy', L.privacy)} · ${a('Terms', L.terms)} · ${a('Accessibility', L.a11y)}. Built in Denver by ${a('Eye To Ad Media', L.eyetoad)} for everyone. Our job: the most useful, fun and helpful place on Earth.`, ['Join', 'Human']],
  [/\b(news|press release|pr|announce|media)\b/i, () => `${a('pressreleaseforbusiness.com', L.pr)} publishes your release; ${a('Action Global News', L.agn)} carries business and tech news and distribution. Both are part of the expert Brand page build.`, ['Brand page', 'Human']],
  [/\b(hi|hello|hey|yo|sup|good (morning|afternoon|evening))\b/i, (c) => `Hey${c.name ? ' ' + c.name : ''}! 🪐 I am Orbit. I know every corner of allofus.one and World VR Mall, and I am very good at pointing. What are you here to do?`, ['Join', 'Brand page', 'VR controls', 'Ride the coaster']],
  [/\b(thank|thanks|awesome|great|love)\b/i, () => `Right back at you. You are exactly the kind of person this place is built for. Anything else?`, ['What can I do here?']],
  [/\b(sad|lonely|stress|tired|hard day|depress|anx)\b/i, () => `I am glad you are here. One real thing: you matter, and a tiny next step counts. #kindness in the ${a('Comm Hub', L.hub)} has people who will listen, and ${a('LIFEboard', L.board)} can hold one small goal for today. If it is heavy, talk to someone you trust or your local helpline — real people, right now.`, ['Comm Hub', 'LIFEboard']],
];
const DEFAULT = (c) => `I did not catch that one, but here is the map: ${a('Feed', L.feed)} · ${a('Brand pages', L.brand)} · ${a('Groups', L.groups)} · ${a('3D world', L.world)} · ${a('VR', L.vr)} · ${a('World VR Mall', L.mall)} · ${a('LIFEboard', L.board)} · ${a('FLOWworks', L.work)}. Or type "human" and I will hand you to a real person.`;
export function mountOrbit(ctx = {}) {
  if (document.getElementById('orbit-tab')) return; const me = () => (ctx.me && ctx.me()) || null;
  const tab = document.createElement('button'); tab.id = 'orbit-tab'; tab.setAttribute('aria-label', 'Chat with Orbit'); tab.innerHTML = ORBIT_SVG(72) + '<span class="say">Need a hand?</span>'; document.body.appendChild(tab);
  const box = document.createElement('div'); box.id = 'orbit'; box.innerHTML = `<div class="hd">${ORBIT_SVG(40)}<b>Orbit<small>allofus.one helper · humans at ${PHONE}</small></b><button data-x aria-label="Close">✕</button></div><div class="log"></div><div class="chips"></div><form><input placeholder="Ask me anything… or type human" maxlength="300" autocomplete="off"><button>Send</button></form>`; document.body.appendChild(box);
  const log = box.querySelector('.log'), chips = box.querySelector('.chips'), form = box.querySelector('form'), input = form.querySelector('input');
  const say = (html, who = 'b') => { const m = document.createElement('div'); m.className = 'm ' + who; if (who === 'u') m.textContent = html; else m.innerHTML = html; log.appendChild(m); log.scrollTop = log.scrollHeight; };
  const setChips = (list) => { chips.innerHTML = (list || []).map(c => `<button type="button">${c}</button>`).join(''); chips.querySelectorAll('button').forEach(b => b.onclick = () => ask(b.textContent)); };
  const ask = (q) => { say(q, 'u'); const c = { name: (me() || {}).name }; let hit = null; for (const [rx, fn, ch] of INTENTS) { if (rx.test(q)) { hit = [fn(c), ch]; break; } } setTimeout(() => { say(hit ? hit[0] : DEFAULT(c)); setChips(hit ? hit[1] : ['Join', 'Brand page', 'VR controls', 'Human']); }, 260); try { const h = JSON.parse(localStorage.getItem('orbit_log') || '[]'); h.push([Date.now(), q.slice(0, 120)]); localStorage.setItem('orbit_log', JSON.stringify(h.slice(-40))); } catch (e) { } };
  form.onsubmit = (e) => { e.preventDefault(); const q = input.value.trim(); if (!q) return; input.value = ''; ask(q); };
  let opened = false; const open = () => { box.classList.add('on'); tab.style.display = 'none'; if (!opened) { opened = true; const m = me(); say(`Hey${m && m.name ? ' ' + m.name : ''}! 🪐 I am Orbit — the friendly moon-station of allofus.one. I can get you joined, build your Brand page, teach you the VR controls or find you a human. What are you here to do?`); setChips(['Join', 'Brand page help', 'VR controls', 'Ride the coaster', 'Human']); } setTimeout(() => input.focus(), 80); };
  const close = () => { box.classList.remove('on'); tab.style.display = ''; }; tab.onclick = open; box.querySelector('[data-x]').onclick = close;
  window.ORBIT = { open, close, ask }; setTimeout(() => { const s = tab.querySelector('.say'); if (s) s.style.display = 'none'; }, 9000);
}
