/* Mount Peace v2 (Oct 2026): levels (Bluebird · Dusk · STORM), real jumps with air time, snowmen to
   smash (carrot nose, charcoal eyes, top hat), deer to dodge, enclosed gondola cabins you sit inside. */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { M, box, cyl, sph } from './aou-kit.js';
const T = THREE; const MOB = isMobile();
export function buildSki2(app, W) {
  const K = W.ski; if (!K) return; const { curve, ty, half, top, base } = K; const S = app.scene; const st = K.state; const toast = (m, ms) => app.toast(m, ms);
  const at = (k, off) => { const p = curve.getPointAt(k), tg = curve.getTangentAt(k); const x = p.x - tg.z * off, z = p.z + tg.x * off; return { x, z, y: ty(x, z), tg }; };
  // snowmen
  const snowM = M(0xffffff, { roughness: 0.9 }); const smen = []; const mkSnowman = (k, off) => { const q = at(k, off); const g = new T.Group(); g.position.set(q.x, q.y, q.z); S.add(g); sph(0.5, snowM, 0, 0.5, 0, g, 14); sph(0.38, snowM, 0, 1.25, 0, g, 12); const hd = sph(0.28, snowM, 0, 1.8, 0, g, 12); const nose = new T.Mesh(new T.ConeGeometry(0.06, 0.32, 8), M(0xff8a1f)); nose.rotation.x = Math.PI / 2; nose.position.set(0, 1.78, 0.4); g.add(nose); for (const sx of [-0.1, 0.1]) sph(0.045, M(0x111111, { roughness: 0.2 }), sx, 1.88, 0.24, g, 6); for (const y of [1.0, 1.2, 1.4]) sph(0.04, M(0x111111), 0, y, 0.37, g, 6); cyl(0.3, 0.3, 0.03, M(0x111111), 0, 2.07, 0, g, 16); cyl(0.2, 0.2, 0.34, M(0x111111), 0, 2.25, 0, g, 16); box(0.42, 0.06, 0.06, M(0xe11d48), 0, 2.1, 0, g); for (const sx of [-1, 1]) { const arm = cyl(0.025, 0.02, 0.7, M(0x6b4a2a), sx * 0.6, 1.3, 0, g, 5); arm.rotation.z = sx * 1.1; } const bits = []; g.traverse(o => { if (o.isMesh) bits.push(o); }); smen.push({ g, k, off, bits, alive: true, lvl: 0 }); return g; };
  const deer = []; const mkDeer = (k, off) => { const q = at(k, off); const g = new T.Group(); g.position.set(q.x, q.y, q.z); S.add(g); const fur = M(0x9b6a3c, { roughness: 0.9 }); const body = sph(0.5, fur, 0, 1.0, 0, g, 12); body.scale.set(0.7, 0.6, 1.1); const neck = cyl(0.14, 0.18, 0.7, fur, 0, 1.45, 0.45, g, 8); neck.rotation.x = -0.5; const hd = sph(0.2, fur, 0, 1.85, 0.75, g, 10); hd.scale.set(0.8, 0.8, 1.2); for (const sx of [-1, 1]) { const ant = cyl(0.02, 0.03, 0.5, M(0x5a3d22), sx * 0.12, 2.15, 0.65, g, 5); ant.rotation.z = sx * 0.5; const tip = cyl(0.015, 0.02, 0.25, M(0x5a3d22), sx * 0.3, 2.3, 0.6, g, 5); tip.rotation.z = sx * 1.3; sph(0.04, M(0x111111), sx * 0.12, 1.9, 0.92, g, 6); } for (const [x, z] of [[-0.25, 0.4], [0.25, 0.4], [-0.25, -0.4], [0.25, -0.4]]) cyl(0.05, 0.04, 0.9, fur, x, 0.45, z, g, 6); sph(0.1, M(0xffffff), 0, 1.05, -0.6, g, 6); g.rotation.y = Math.PI; deer.push({ g, k, off, base: off, dir: 1, hit: 0 }); };
  const coins = []; const coinM = new T.MeshStandardMaterial({ color: 0xffd23f, metalness: 0.9, roughness: 0.2, emissive: 0x7a5200, emissiveIntensity: 0.6 }); const mkCoin = (k, off, y = 0) => { const q = at(k, off); const c = new T.Mesh(new T.TorusGeometry(0.4, 0.1, 8, 18), coinM); c.position.set(q.x, q.y + 1.2 + y, q.z); S.add(c); coins.push({ c, k, off, y }); };
  const jumps = []; const mkJump = (k) => { const q = at(k, 0); const r = new T.Mesh(new T.BoxGeometry(half * 1.6, 1.4, 5), M(0xdbeafe, { roughness: 0.7 })); r.position.set(q.x, q.y + 0.5, q.z); r.rotation.y = Math.atan2(q.tg.x, q.tg.z); r.rotation.x = -0.28; S.add(r); const tag = makeSprite('🎿 JUMP', { scale: 2.6, accent: '#38f0ff' }); tag.position.set(q.x, q.y + 3.6, q.z); S.add(tag); jumps.push({ k, done: false }); };
  // placements along the run
  [0.14, 0.3, 0.48, 0.63, 0.8].forEach((k, i) => mkSnowman(k, Math.sin(i * 2.3) * 4.5)); [0.22, 0.56, 0.74].forEach((k, i) => mkSnowman(k, (i % 2 ? -1 : 1) * 2)); [0.38, 0.69].forEach((k) => mkDeer(k, 5.5)); for (let i = 0; i < 18; i++) mkCoin(0.1 + i * 0.048, Math.cos(i * 1.4) * 4.2, i % 5 === 0 ? 1.5 : 0); [0.42, 0.78].forEach(mkJump); [0.44, 0.46, 0.8, 0.82].forEach((k, i) => mkCoin(k, 0, 2.2 + (i % 2)));
  // levels + storm
  const LV = [['☀️ Bluebird day', 'Clear skies, friendly snow. Learn the line.', 1], ['🌆 Dusk run', 'Low light, faster snow, more snowmen.', 1.25], ['⛈️ STORM', 'Blizzard, wind that pushes you, double points.', 1.5]]; let level = 0; let storm = null; const fog0 = app.scene.fog ? [app.scene.fog.near, app.scene.fog.far, app.scene.fog.color.getHex()] : null;
  const mkStorm = () => { const n = MOB ? 600 : 1600; const pos = new Float32Array(n * 3); for (let i = 0; i < n; i++) { pos[i * 3] = (Math.random() - 0.5) * 60; pos[i * 3 + 1] = Math.random() * 30; pos[i * 3 + 2] = (Math.random() - 0.5) * 60; } const g = new T.BufferGeometry(); g.setAttribute('position', new T.BufferAttribute(pos, 3)); const p = new T.Points(g, new T.PointsMaterial({ color: 0xffffff, size: 0.22, transparent: true, opacity: 0.9, depthWrite: false })); p.frustumCulled = false; S.add(p); return p; };
  const setLevel = (i) => { level = i; if (storm) { S.remove(storm); storm = null; } if (app.scene.fog && fog0) { app.scene.fog.near = fog0[0]; app.scene.fog.far = fog0[1]; app.scene.fog.color.setHex(fog0[2]); } if (i === 2) { storm = mkStorm(); if (app.scene.fog) { app.scene.fog.near = 6; app.scene.fog.far = 90; app.scene.fog.color.setHex(0xbfc8d6); } } if (i === 1 && app.scene.fog) { app.scene.fog.far = Math.min(app.scene.fog.far, 420); app.scene.fog.color.setHex(0x8f7fa6); } smen.forEach((s, j) => { s.g.visible = i > 0 || j < 5; s.alive = s.g.visible; s.g.traverse(o => { if (o.isMesh) { o.visible = true; o.position.y = o.userData.y0 ?? (o.userData.y0 = o.position.y); } }); }); };
  W.startSki2 = () => { app.popup('⛷️ Mount Peace · pick your run', '<p>Smash snowmen ⛄ (+50), grab coins 🪙 (+10), hit the jumps for air 🎿 (+40), and dodge the deer 🦌 (hitting one costs 3 seconds, and they will give you a look).</p>', LV.map(([n, d], i) => ({ label: n + ' · ' + d, primary: i === 0, fn: () => { setLevel(i); setTimeout(() => W.startSki(), 200); } }))); };
  // gondola cabins instead of chairs, and a cabin around you while you ride
  const cabin = (col) => { const g = new T.Group(); const gl = new T.MeshPhysicalMaterial({ color: 0xcfefff, transparent: true, opacity: 0.3, roughness: 0.05, side: T.DoubleSide, depthWrite: false }); box(2.0, 0.12, 2.0, M(col), 0, -2.3, 0, g); box(2.1, 0.5, 2.1, M(col), 0, -0.6, 0, g); for (const [x, z] of [[-1, -1], [1, -1], [-1, 1], [1, 1]]) box(0.08, 1.7, 0.08, M(col), x, -1.45, z, g); for (const [w, d, x, z] of [[2, 0.03, 0, -1], [2, 0.03, 0, 1], [0.03, 2, -1, 0], [0.03, 2, 1, 0]]) box(w, 1.6, d, gl, x, -1.4, z, g); box(1.8, 0.12, 0.6, M(0x444444), 0, -1.9, -0.6, g); box(1.8, 0.12, 0.6, M(0x444444), 0, -1.9, 0.6, g); box(0.08, 0.8, 0.08, M(0x333333), 0, 0.1, 0, g); return g; };
  if (K.chairs) K.chairs.forEach((ch, i) => { ch.c.children.forEach(c => c.visible = false); ch.c.add(cabin([0x2563eb, 0xe11d48, 0xffd23f, 0x16a34a][i % 4])); });
  W.rideLift2 = () => { if (app.ride) return; const cab = cabin(0xffffff); cab.position.set(0, 1.95, 0); app.player.add(cab); W.rideLift(); const prev = app.targetDist; app.targetDist = Math.max(prev > 0.6 ? prev : 5, 5); const un = app.onUpdate(() => { if (!app.ride) { app.player.remove(cab); app.targetDist = prev > 0.6 ? prev : 5; app.updaters = app.updaters.filter(q => q !== un); } }); };
  // the run itself: jumps, hits, coins, storm wind
  let air = 0, airV = 0, wrapped = null, bits = []; const burst = (g, col) => { for (let i = 0; i < 14; i++) { const b = new T.Mesh(new T.SphereGeometry(0.09 + Math.random() * 0.12, 6, 5), M(col)); b.position.copy(g.position).add(new T.Vector3(0, 1.2, 0)); b.userData.v = new T.Vector3((Math.random() - 0.5) * 8, 4 + Math.random() * 6, (Math.random() - 0.5) * 8); b.userData.t = 0; S.add(b); bits.push(b); } };
  app.onUpdate((dt, t) => { for (const b of bits) { b.userData.t += dt; b.userData.v.y -= 14 * dt; b.position.addScaledVector(b.userData.v, dt); b.rotation.x += dt * 5; if (b.userData.t > 1.6) { S.remove(b); } } bits = bits.filter(b => b.userData.t <= 1.6); for (const c of coins) c.c.rotation.y += dt * 3; for (const d of deer) { d.g.position.y = ty(d.g.position.x, d.g.position.z) + (d.hit > 0 ? Math.abs(Math.sin(d.hit * 12)) * 0.6 : 0); if (d.hit > 0) d.hit -= dt; } if (storm) { const a = storm.geometry.attributes.position.array; const P = app.player.position; storm.position.set(P.x, P.y, P.z); for (let i = 1; i < a.length; i += 3) { a[i] -= dt * 9; a[i - 1] += dt * 6; if (a[i] < 0) { a[i] = 30; a[i - 1] = (Math.random() - 0.5) * 60; } } storm.geometry.attributes.position.needsUpdate = true; }
    if (!st.on || !app.ride) { if (wrapped) { wrapped = null; } return; }
    if (!wrapped) { wrapped = app.ride; const pos0 = app.ride.pos; app.ride.pos = () => { const p = pos0(); p.y += air; return p; }; jumps.forEach(j => j.done = false); coins.forEach(c => c.c.visible = true); st.pts2 = 0; if (level === 2) toast('⛈️ STORM: the wind is pushing you right. Fight it.', 2500); }
    const dtt = Math.min(0.05, dt); if (level === 2) st.u = Math.min(half - 0.5, st.u + dtt * 2.2 * Math.sin(t * 0.7)); if (air > 0 || airV > 0) { airV -= 22 * dtt; air = Math.max(0, air + airV * dtt); if (air === 0 && airV < 0) { airV = 0; app.buzz && app.buzz(30); } }
    for (const j of jumps) if (!j.done && st.k > j.k) { j.done = true; airV = 9.5; air = 0.01; st.pts += Math.round(40 * LV[level][2]); toast('🎿 AIR! +' + Math.round(40 * LV[level][2]), 900); app.celebrate && app.celebrate('🎿'); }
    for (const sm of smen) if (sm.alive && Math.abs(sm.k - st.k) < 0.007 && Math.abs(sm.off - st.u) < 1.5) { sm.alive = false; burst(sm.g, 0xffffff); sm.g.traverse(o => { if (o.isMesh) o.visible = false; }); const p = Math.round(50 * LV[level][2]); st.pts += p; toast('⛄ SMASH! +' + p, 900); app.buzz && app.buzz(50); }
    for (const d of deer) if (d.hit <= 0 && Math.abs(d.k - st.k) < 0.006 && Math.abs(d.off - st.u) < 1.8) { d.hit = 1.2; st.t0 -= 3; toast('🦌 Oof! You clipped a deer: +3 s. It is fine. It is judging you.', 1600); app.buzz && app.buzz(80); }
    for (const c of coins) if (c.c.visible && Math.abs(c.k - st.k) < 0.006 && Math.abs(c.off - st.u) < 1.4 && (c.y === 0 || air > c.y * 0.6)) { c.c.visible = false; st.pts += Math.round(10 * LV[level][2]); }
    for (const d of deer) { if (st.k > d.k - 0.05 && st.k < d.k) { d.off += dtt * 1.5 * d.dir; if (Math.abs(d.off) > half - 1) d.dir *= -1; const q = at(d.k, d.off); d.g.position.x = q.x; d.g.position.z = q.z; } } });
  // find it: signposts and a place that points at the start gate
  try { buildRuns(app, W); } catch (e) { console.error('runs', e); }
  app.addPlace && app.addPlace({ id: 'skirun', name: '⛷️ Mount Peace ski run · 3 levels, jumps, snowmen', icon: '⛷️', x: top.x - 10, z: top.z - 2, cat: 'Fun', top: true, keys: 'ski snowboard run mountain jumps snowmen deer storm levels coburn gondola', say: 'The start gate is right here. Tap it and pick a level.' });
}

/* ---- MOUNT COBES v3: four runs with turns, cliffs and rivers, the BLIZZARD wipeout, the gear shop ---- */
export function buildRuns(app, W) {
  const K = W.ski; if (!K) return; const { ty, top, base, half } = K; const S = app.scene; const toast = (m, ms) => app.toast(m, ms); const st = K.state;
  const mk = (pts) => new T.CatmullRomCurve3(pts.map(([x, z]) => new T.Vector3(x, 0, z)));
  const RUNS = [
    { id: 'glade', name: '🌲 Glade Twister', desc: 'Tight turns through the pines.', pts: [[top.x - 26, top.z - 6], [top.x - 44, top.z - 26], [top.x - 20, top.z - 44], [top.x - 48, top.z - 66], [top.x - 24, top.z - 90], [top.x - 46, top.z - 118], [base.x - 30, base.z + 12]], snow: 3, deer: 2, coins: 14, jumps: [0.5] },
    { id: 'cliff', name: '🪨 Cliff Drop', desc: 'Two big drops. Hold on.', pts: [[top.x + 10, top.z - 10], [top.x + 30, top.z - 36], [top.x + 36, top.z - 60], [top.x + 20, top.z - 96], [top.x + 30, top.z - 130], [base.x + 10, base.z + 8]], snow: 2, deer: 1, coins: 10, jumps: [0.3, 0.62], cliffs: [0.3, 0.62] },
    { id: 'river', name: '🌊 River Run', desc: 'Three rivers to clear.', pts: [[top.x + 44, top.z - 4], [top.x + 62, top.z - 30], [top.x + 50, top.z - 58], [top.x + 70, top.z - 86], [top.x + 54, top.z - 116], [base.x + 40, base.z + 6]], snow: 2, deer: 2, coins: 12, jumps: [0.28, 0.55, 0.8], rivers: [0.3, 0.57, 0.82] },
    { id: 'cruiser', name: '☁️ Summit Cruiser', desc: 'Long, wide, fast.', pts: [[top.x - 60, top.z + 4], [top.x - 90, top.z - 30], [top.x - 80, top.z - 70], [top.x - 100, top.z - 110], [top.x - 70, top.z - 150], [base.x - 60, base.z + 4]], snow: 4, deer: 1, coins: 18, jumps: [0.45, 0.75] },
  ];
  const snowM = new T.MeshStandardMaterial({ color: 0xf4f8ff, roughness: 0.6 }); const runMeshes = [];
  for (const R of RUNS) { R.curve = mk(R.pts); const N = 160, pos = [], uv = [], idx = []; for (let i = 0; i <= N; i++) { const k = i / N; const p = R.curve.getPointAt(k), tg = R.curve.getTangentAt(k); const nx = -tg.z, nz = tg.x; for (const sd of [-1, 1]) { const x = p.x + nx * half * sd, z = p.z + nz * half * sd; pos.push(x, ty(x, z) + 0.12, z); uv.push(sd > 0 ? 1 : 0, k * 20); } if (i < N) { const a = i * 2; idx.push(a, a + 1, a + 2, a + 1, a + 3, a + 2); } } const g = new T.BufferGeometry(); g.setAttribute('position', new T.Float32BufferAttribute(pos, 3)); g.setAttribute('uv', new T.Float32BufferAttribute(uv, 2)); g.setIndex(idx); g.computeVertexNormals(); const m = new T.Mesh(g, snowM); m.userData.noCollide = true; S.add(m); runMeshes.push(m); R.obj = []; R.coinObj = []; R.deerObj = [];
    const at = (k, off) => { const p = R.curve.getPointAt(k), tg = R.curve.getTangentAt(k); const x = p.x - tg.z * off, z = p.z + tg.x * off; return { x, z, y: ty(x, z), tg }; };
    for (let i = 0; i < R.snow * 3; i++) { const k = 0.1 + i * (0.8 / (R.snow * 3)); const off = Math.sin(i * 2.1) * 4.5; const q = at(k, off); const g2 = new T.Group(); g2.position.set(q.x, q.y, q.z); S.add(g2); sph(0.5, snowM, 0, 0.5, 0, g2, 12); sph(0.36, snowM, 0, 1.22, 0, g2, 10); sph(0.27, snowM, 0, 1.76, 0, g2, 10); const nose = new T.Mesh(new T.ConeGeometry(0.06, 0.3, 8), M(0xff8a1f)); nose.rotation.x = Math.PI / 2; nose.position.set(0, 1.74, 0.38); g2.add(nose); for (const sx of [-0.1, 0.1]) sph(0.045, M(0x111111), sx, 1.84, 0.23, g2, 6); cyl(0.3, 0.3, 0.03, M(0x111111), 0, 2.02, 0, g2, 14); cyl(0.19, 0.19, 0.32, M(0x111111), 0, 2.2, 0, g2, 14); R.obj.push({ g: g2, k, off, alive: true }); }
    for (let i = 0; i < R.deer; i++) { const k = 0.3 + i * 0.35; const q = at(k, 4); const d = new T.Group(); d.position.set(q.x, q.y, q.z); S.add(d); const fur = M(0x9b6a3c); const b = sph(0.5, fur, 0, 1, 0, d, 10); b.scale.set(0.7, 0.6, 1.1); sph(0.2, fur, 0, 1.8, 0.7, d, 8); for (const [x, z] of [[-0.25, 0.4], [0.25, 0.4], [-0.25, -0.4], [0.25, -0.4]]) cyl(0.05, 0.04, 0.9, fur, x, 0.45, z, d, 6); R.deerObj.push({ g: d, k, off: 4, dir: 1, hit: 0 }); }
    for (let i = 0; i < R.coins; i++) { const k = 0.08 + i * (0.85 / R.coins); const off = Math.cos(i * 1.4) * 4; const q = at(k, off); const c = new T.Mesh(new T.TorusGeometry(0.4, 0.1, 8, 18), new T.MeshStandardMaterial({ color: 0xffd23f, metalness: 0.9, roughness: 0.2, emissive: 0x7a5200, emissiveIntensity: 0.6 })); c.position.set(q.x, q.y + 1.2, q.z); S.add(c); R.coinObj.push({ c, k, off }); }
    for (const k of R.jumps) { const q = at(k, 0); const r = new T.Mesh(new T.BoxGeometry(half * 1.6, 1.4, 5), M(0xdbeafe)); r.position.set(q.x, q.y + 0.5, q.z); r.rotation.y = Math.atan2(q.tg.x, q.tg.z); r.rotation.x = -0.28; S.add(r); }
    for (const k of (R.rivers || [])) { const q = at(k + 0.04, 0); const w = new T.Mesh(new T.PlaneGeometry(half * 2.4, 7), new T.MeshStandardMaterial({ color: 0x1f8fd0, roughness: 0.1, metalness: 0.3, transparent: true, opacity: 0.85 })); w.rotation.x = -Math.PI / 2; w.rotation.z = -Math.atan2(q.tg.x, q.tg.z); w.position.set(q.x, q.y + 0.15, q.z); S.add(w); const tag = makeSprite('🌊 RIVER · hit the jump', { scale: 2.6, accent: '#38f0ff' }); tag.position.set(q.x, q.y + 3.6, q.z); S.add(tag); }
    for (const k of (R.cliffs || [])) { const q = at(k + 0.02, 0); const tag = makeSprite('🪨 CLIFF DROP', { scale: 2.8, accent: '#ff4f79' }); tag.position.set(q.x, q.y + 4, q.z); S.add(tag); }
    const sg = makeSprite(R.name, { scale: 3.4, accent: '#ffffff' }); const q0 = at(0.02, 0); sg.position.set(q0.x, q0.y + 4.5, q0.z); S.add(sg); R.at = at; }
  // gear
  const gear = () => { try { return JSON.parse(localStorage.getItem('aou_gear') || '{}'); } catch (e) { return {}; } }; const setGear = (g) => localStorage.setItem('aou_gear', JSON.stringify(g));
  const board = new T.Group(); board.visible = false; app.player.add(board); const refitBoard = () => { while (board.children.length) board.remove(board.children[0]); const g = gear(); const col = g.color || 0xe11d48; const mat = new T.MeshStandardMaterial({ color: g.pattern === 'custom' ? 0xffffff : col, roughness: 0.35, metalness: 0.2 }); if (g.pattern === 'custom' && g.img) { const t = new T.TextureLoader().load(g.img); t.colorSpace = T.SRGBColorSpace; mat.map = t; } else if (g.pattern && g.pattern !== 'solid') { const c = document.createElement('canvas'); c.width = 128; c.height = 512; const q = c.getContext('2d'); q.fillStyle = '#' + new T.Color(col).getHexString(); q.fillRect(0, 0, 128, 512); const P = { stripes: () => { for (let y = 0; y < 512; y += 48) { q.fillStyle = '#ffffff'; q.fillRect(0, y, 128, 16); } }, flames: () => { q.fillStyle = '#ffd23f'; for (let i = 0; i < 14; i++) { q.beginPath(); q.moveTo(i * 10, 512); q.lineTo(i * 10 + 5, 300 + Math.random() * 120); q.lineTo(i * 10 + 10, 512); q.fill(); } }, galaxy: () => { for (let i = 0; i < 300; i++) { q.fillStyle = `hsl(${200 + Math.random() * 100},90%,${60 + Math.random() * 40}%)`; q.fillRect(Math.random() * 128, Math.random() * 512, 2, 2); } }, peace: () => { q.strokeStyle = '#fff'; q.lineWidth = 8; for (const y of [120, 300, 450]) { q.beginPath(); q.arc(64, y, 40, 0, 6.28); q.moveTo(64, 80 + (y - 120)); q.lineTo(64, 160 + (y - 120)); q.moveTo(64, y); q.lineTo(36, y + 28); q.moveTo(64, y); q.lineTo(92, y + 28); q.stroke(); } }, rainbow: () => { for (let y = 0; y < 512; y += 24) { q.fillStyle = `hsl(${y * 0.7 % 360},90%,60%)`; q.fillRect(0, y, 128, 24); } } }; (P[g.pattern] || P.stripes)(); const t = new T.CanvasTexture(c); t.colorSpace = T.SRGBColorSpace; mat.map = t; mat.color.setHex(0xffffff); }
    if (g.type === 'board') { const b = new T.Mesh(new T.BoxGeometry(0.3, 0.04, 1.6), mat); b.position.set(0, 0.03, 0.1); board.add(b); const nose = new T.Mesh(new T.SphereGeometry(0.15, 10, 6), mat); nose.scale.set(1, 0.25, 1); nose.position.set(0, 0.03, 0.9); board.add(nose); } else for (const sx of [-0.16, 0.16]) { const sk = new T.Mesh(new T.BoxGeometry(0.1, 0.04, 1.7), mat); sk.position.set(sx, 0.03, 0.2); board.add(sk); } }; refitBoard();
  W.gearShop = () => { const g = gear(); const html = `<p class="aou-lbl">Ride</p><div class="aou-chips" data-g="type">${[['skis', '🎿 Skis'], ['board', '🏂 Snowboard']].map(([v, l]) => `<button data-v="${v}" class="${(g.type || 'skis') === v ? 'on' : ''}">${l}</button>`).join('')}</div><p class="aou-lbl">Color</p><div class="aou-chips" data-g="color">${[0xe11d48, 0x38f0ff, 0xffd23f, 0x7cff6b, 0xb08cff, 0x111111, 0xffffff].map(c => `<button data-v="${c}" style="background:#${new T.Color(c).getHexString()};color:${c === 0xffffff || c === 0xffd23f ? '#111' : '#fff'}" class="${(g.color || 0xe11d48) === c ? 'on' : ''}">●</button>`).join('')}</div><p class="aou-lbl">Pattern</p><div class="aou-chips" data-g="pattern">${[['solid', 'Solid'], ['stripes', 'Stripes'], ['flames', 'Flames'], ['galaxy', 'Galaxy'], ['peace', 'Peace signs'], ['rainbow', 'Rainbow'], ['custom', '🖼️ My own image']].map(([v, l]) => `<button data-v="${v}" class="${(g.pattern || 'solid') === v ? 'on' : ''}">${l}</button>`).join('')}</div><input type="file" id="gear-f" accept="image/*" style="margin-top:8px"><p class="muted2">Your pattern also goes on your jacket when you ride.</p>`;
    const m = (W.UI && W.UI.modal) ? W.UI.modal('🎿 Gear shop · Mount Cobes', html) : null; if (!m) { toast('Gear shop needs the menu system.'); return; } m.querySelectorAll('[data-g]').forEach(row => row.onclick = (e) => { const b = e.target.closest('button'); if (!b) return; row.querySelectorAll('button').forEach(q => q.classList.toggle('on', q === b)); const ng = gear(); ng[row.dataset.g] = isNaN(+b.dataset.v) ? b.dataset.v : +b.dataset.v; setGear(ng); refitBoard(); }); m.querySelector('#gear-f').onchange = (e) => { const f = e.target.files[0]; if (!f) return; const r = new FileReader(); r.onload = () => { const im = new Image(); im.onload = () => { const c = document.createElement('canvas'); c.width = 128; c.height = 512; c.getContext('2d').drawImage(im, 0, 0, 128, 512); const ng = gear(); ng.pattern = 'custom'; ng.img = c.toDataURL('image/webp', 0.8); setGear(ng); refitBoard(); toast('🖼️ Custom pattern on!'); }; im.src = r.result; }; r.readAsDataURL(f); }; };
  // run a route
  const RS = { on: false, R: null, k: 0, u: 0, v: 0, t0: 0, pts: 0, air: 0, airV: 0, falls: 0, lvl: 0 }; const keys = new Set(); addEventListener('keydown', (e) => { if (RS.on) keys.add(e.key.toLowerCase()); }); addEventListener('keyup', (e) => keys.delete(e.key.toLowerCase()));
  const hud = document.createElement('div'); hud.style.cssText = 'position:absolute;inset:0;pointer-events:none;z-index:40;font-family:Poppins,Arial;display:none'; hud.innerHTML = '<div style="position:absolute;top:64px;left:50%;transform:translateX(-50%);display:flex;gap:14px;background:rgba(255,255,255,.94);padding:8px 16px;border-radius:999px;font-weight:900;color:#0f172a;box-shadow:0 8px 24px rgba(0,0,0,.3)"><b id="r-t">0.0 s</b><span id="r-s">0 pts</span><span id="r-l">❤️❤️❤️</span></div><div style="position:absolute;bottom:150px;left:0;right:0;display:flex;justify-content:space-between;padding:0 18px;pointer-events:none"><button id="r-l2" style="pointer-events:auto;width:70px;height:70px;border-radius:50%;border:0;background:rgba(255,255,255,.9);font-size:28px;touch-action:none">◀</button><button id="r-r2" style="pointer-events:auto;width:70px;height:70px;border-radius:50%;border:0;background:rgba(255,255,255,.9);font-size:28px;touch-action:none">▶</button></div>'; (document.getElementById('wvm-hud') || document.body).appendChild(hud); let steer = 0; const hold = (id, v) => { const b = hud.querySelector(id); b.onpointerdown = () => { steer = v; }; b.onpointerup = b.onpointerleave = b.onpointercancel = () => { if (steer === v) steer = 0; }; }; hold('#r-l2', -1); hold('#r-r2', 1);
  const scores = () => { try { return JSON.parse(localStorage.getItem('aou_cobes_scores') || '[]'); } catch (e) { return []; } };
  const wipeout = (reason) => { RS.on = false; app.ride = null; board.visible = false; hud.style.display = 'none'; const sc = Math.round(RS.pts + Math.max(0, 500 - (app.t - RS.t0) * 6)); const list = scores(); list.push({ run: RS.R.name, score: sc, d: new Date().toLocaleDateString() }); list.sort((a, b) => b.score - a.score); localStorage.setItem('aou_cobes_scores', JSON.stringify(list.slice(0, 8)));
    const o = document.createElement('div'); o.style.cssText = 'position:fixed;inset:0;z-index:99989;pointer-events:none'; const cv = document.createElement('canvas'); cv.width = innerWidth; cv.height = innerHeight; cv.style.cssText = 'width:100%;height:100%'; o.appendChild(cv); document.body.appendChild(o); const q = cv.getContext('2d'); const N = 900; const fl = []; for (let i = 0; i < N; i++) fl.push([Math.random() * cv.width, -Math.random() * cv.height, 1 + Math.random() * 3, 1 + Math.random() * 4]); let fill = 0, t0 = performance.now(); const card = document.createElement('div'); card.style.cssText = 'position:absolute;left:50%;top:50%;transform:translate(-50%,-50%) scale(.6);opacity:0;transition:.6s;background:#fff;border-radius:22px;padding:18px 22px;font:700 15px Poppins,Arial;color:#0f172a;text-align:center;pointer-events:auto;box-shadow:0 20px 60px rgba(0,0,0,.5);max-width:92vw'; card.innerHTML = `<div style="font-size:52px">⛈️</div><h3 style="margin:4px 0;font:900 22px Poppins,Arial">WIPEOUT · ${reason}</h3><p>${RS.R.name} · <b>${sc} pts</b></p><div style="text-align:left;background:#f1f5f9;border-radius:12px;padding:8px 12px;font-size:13px"><b>🏔️ High scores</b>${list.slice(0, 5).map((s2, i) => `<div>${i + 1}. ${s2.score} · ${s2.run} · ${s2.d}</div>`).join('')}</div><div style="display:flex;gap:8px;justify-content:center;margin-top:10px;flex-wrap:wrap"><button id="w-again" style="border:0;border-radius:999px;padding:11px 18px;font:900 14px Poppins,Arial;background:#16a34a;color:#fff;cursor:pointer">🔁 Start over</button><button id="w-pick" style="border:1px solid #cbd5e1;border-radius:999px;padding:11px 16px;font:800 14px Poppins,Arial;background:#fff;cursor:pointer">⛷️ Pick a run</button><button id="w-x" style="border:1px solid #cbd5e1;border-radius:999px;padding:11px 14px;background:#fff;cursor:pointer">✕</button></div>`; o.appendChild(card);
    const loop = (now) => { if (!o.isConnected) return; const k = Math.min(1, (now - t0) / 2600); fill = k * 0.9; q.clearRect(0, 0, cv.width, cv.height); q.fillStyle = 'rgba(230,240,255,.92)'; q.fillRect(0, cv.height * (1 - fill), cv.width, cv.height * fill); q.fillStyle = '#fff'; for (const f of fl) { f[1] += f[3] * 2.4; f[0] += Math.sin(now / 300 + f[2]) * 2 + 1.5; if (f[1] > cv.height) { f[1] = -10; f[0] = Math.random() * cv.width; } if (f[0] > cv.width) f[0] = 0; q.beginPath(); q.arc(f[0], f[1], f[2], 0, 6.28); q.fill(); } if (k > 0.5) { card.style.opacity = 1; card.style.transform = 'translate(-50%,-50%) scale(1)'; } requestAnimationFrame(loop); }; requestAnimationFrame(loop); const close = () => { o.remove(); app.player.position.set(RS.R.pts[0][0], ty(RS.R.pts[0][0], RS.R.pts[0][1]), RS.R.pts[0][1]); }; card.querySelector('#w-x').onclick = close; card.querySelector('#w-again').onclick = () => { close(); setTimeout(() => run(RS.R, RS.lvl), 200); }; card.querySelector('#w-pick').onclick = () => { close(); setTimeout(pick, 200); }; };
  const run = (R, lvl) => { if (app.ride) return; RS.on = true; RS.R = R; RS.k = 0; RS.u = 0; RS.v = 3; RS.t0 = app.t; RS.pts = 0; RS.air = 0; RS.airV = 0; RS.falls = 0; RS.lvl = lvl; R.obj.forEach(o => { o.alive = true; o.g.visible = true; }); R.coinObj.forEach(c => c.c.visible = true); R.jd = R.jumps.map(() => false); hud.style.display = ''; board.visible = true; refitBoard(); toast(`⛷️ ${R.name}: A/D or ◀ ▶ to steer. Smash snowmen, miss deer, hit the jumps. 3 hearts.`, 4000);
    app.ride = { pos: () => { const dt = Math.min(0.05, app._skiDt || 0.016); const tg = R.curve.getTangentAt(Math.min(0.999, RS.k)); const p = R.curve.getPointAt(Math.min(0.999, RS.k)); const s = steer || (keys.has('a') || keys.has('arrowleft') ? -1 : keys.has('d') || keys.has('arrowright') ? 1 : 0); RS.u = Math.max(-half + 0.5, Math.min(half - 0.5, RS.u + s * dt * 6 + (lvl === 2 ? Math.sin(app.t * 0.8) * dt * 2.2 : 0))); const slope = Math.max(0.2, -tg.y + 0.6); RS.v = Math.min(14 + lvl * 3, RS.v + dt * 4); RS.k = Math.min(0.999, RS.k + dt * RS.v / R.curve.getLength() * 1.4); const x = p.x - tg.z * RS.u, z = p.z + tg.x * RS.u; app.ride.yaw = Math.atan2(tg.x, tg.z); if (app.avatar) app.avatar.rotation.z = -s * 0.25; board.rotation.y = 0;
        if (RS.air > 0 || RS.airV > 0) { RS.airV -= 22 * dt; RS.air = Math.max(0, RS.air + RS.airV * dt); } R.jumps.forEach((jk, i) => { if (!R.jd[i] && RS.k > jk) { R.jd[i] = true; RS.airV = 10 + (R.cliffs ? 3 : 0); RS.air = 0.01; RS.pts += 40; toast('🎿 AIR! +40', 800); } });
        if (R.rivers) for (const rk of R.rivers) if (RS.k > rk + 0.02 && RS.k < rk + 0.06 && RS.air < 0.4) { if (app.t - (RS.wet || 0) > 2) { RS.wet = app.t; RS.falls++; RS.t0 -= 4; toast('🌊 SPLASH! +4 s. Hit the jump before the river!', 1500); app.buzz && app.buzz(100); } }
        if (R.cliffs) for (const ck of R.cliffs) if (RS.k > ck + 0.03 && RS.k < ck + 0.05 && Math.abs(RS.u) > half - 1.2) { wipeout('off the cliff'); return new T.Vector3(x, ty(x, z) + 0.15, z); }
        for (const o of R.obj) if (o.alive && Math.abs(o.k - RS.k) < 0.008 && Math.abs(o.off - RS.u) < 1.5) { o.alive = false; o.g.visible = false; RS.pts += 50; toast('⛄ SMASH! +50', 700); app.buzz && app.buzz(40); }
        for (const d of R.deerObj) { if (RS.k > d.k - 0.06 && RS.k < d.k) { d.off += dt * 1.8 * d.dir; if (Math.abs(d.off) > half - 1) d.dir *= -1; const q2 = R.at(d.k, d.off); d.g.position.x = q2.x; d.g.position.z = q2.z; } if (d.hit <= 0 && Math.abs(d.k - RS.k) < 0.007 && Math.abs(d.off - RS.u) < 1.8) { d.hit = 2; RS.falls++; app.buzz && app.buzz(90); toast('🦌 Clipped a deer! ' + (3 - RS.falls) + ' hearts left', 1500); } if (d.hit > 0) d.hit -= dt; }
        for (const c of R.coinObj) if (c.c.visible && Math.abs(c.k - RS.k) < 0.007 && Math.abs(c.off - RS.u) < 1.4) { c.c.visible = false; RS.pts += 10; }
        hud.querySelector('#r-t').textContent = (app.t - RS.t0).toFixed(1) + ' s'; hud.querySelector('#r-s').textContent = RS.pts + ' pts'; hud.querySelector('#r-l').textContent = '❤️'.repeat(Math.max(0, 3 - RS.falls)) + '🖤'.repeat(Math.min(3, RS.falls));
        if (RS.falls >= 3) { wipeout('too many crashes'); return new T.Vector3(x, ty(x, z) + 0.15, z); } if (RS.k >= 0.998 && !RS.ending) { RS.ending = true; setTimeout(() => { RS.ending = false; finish(); }, 0); } return new T.Vector3(x, ty(x, z) + 0.15 + RS.air, z); }, yaw: 0, stand: true }; };
  const finish = () => { RS.on = false; app.ride = null; board.visible = false; hud.style.display = 'none'; const sc = Math.round(RS.pts + Math.max(0, 600 - (app.t - RS.t0) * 6)); const list = scores(); list.push({ run: RS.R.name, score: sc, d: new Date().toLocaleDateString() }); list.sort((a, b) => b.score - a.score); localStorage.setItem('aou_cobes_scores', JSON.stringify(list.slice(0, 8))); app.celebrate && app.celebrate('🏆'); app.popup && app.popup('🏁 ' + RS.R.name + ' · done!', `<p style="font-size:20px"><b>${sc} pts</b> · ${(app.t - RS.t0).toFixed(1)} s</p><div class="muted2">High scores: ${list.slice(0, 5).map((s2, i) => (i + 1) + '. ' + s2.score + ' (' + s2.run + ')').join(' · ')}</div>`, [{ label: '🔁 Again', fn: () => run(RS.R, RS.lvl) }, { label: '⛷️ Another run', fn: pick }, { label: '🎿 Gear shop', fn: () => W.gearShop() }]); };
  const pick = () => app.popup && app.popup('🏔️ MOUNT COBES · pick your run', '<p>Four runs, every one different. Then pick a level: Bluebird, Dusk, or BLIZZARD (the wind pushes you, and so do the deer).</p>', RUNS.flatMap(R => [0, 1, 2].map(l => ({ label: R.name + ' · ' + ['☀️ Bluebird', '🌆 Dusk', '⛈️ BLIZZARD'][l], fn: () => setTimeout(() => { app.player.position.set(R.pts[0][0], ty(R.pts[0][0], R.pts[0][1]), R.pts[0][1]); run(R, l); }, 200) }))).concat([{ label: '🎿 Gear shop · skis, board, patterns', fn: () => W.gearShop() }]));
  app.onUpdate((dt) => { app._skiDt = dt; for (const R of RUNS) for (const c of R.coinObj) c.c.rotation.y += dt * 3; });
  W.pickRun = pick; const gx = top.x - 2, gz = top.z + 10; const kiosk = new T.Group(); kiosk.position.set(gx, ty(gx, gz), gz); S.add(kiosk); box(2.6, 2.2, 0.5, M(0x1e1b4b), 0, 1.1, 0, kiosk); const kt = makeSprite('🏔️ MOUNT COBES · 4 runs · gear shop', { scale: 4, accent: '#38f0ff' }); kt.position.y = 3.4; kiosk.add(kt); app.addObstacle && app.addObstacle(gx, gz, 1.5); app.addInteractable && app.addInteractable(gx, gz + 1.6, 3.2, '🏔️ Mount Cobes: pick a run / gear shop', pick); app.addHotspot && app.addHotspot(kiosk, { fn: pick });
  app.addPlace && app.addPlace({ id: 'cobes', name: '🏔️ Mount Cobes · 4 runs, blizzard mode, gear shop', icon: '🏔️', x: gx, z: gz + 3, cat: 'Fun', top: true, keys: 'mount cobes ski snowboard runs blizzard glade cliff river cruiser gear', say: 'Tap the kiosk at the summit to pick a run.' });
}
