/* ============================================================
   FLAT · allofus.one (v6, Oct 2026)
   The flat side of the world: a personal page you control, a real
   feed, groups (national buy · sell · trade), a composer with big
   text, photos, links, For Sale, polls, video/GIF, Advertise business,
   and reactions. No algorithm: newest first, nothing hidden from you.
   Used by /flat/ (standalone page) and by the 3D world (FLAT button).
   ============================================================ */
import { CONFIG } from './aou-config.js';
const $ = (s, r = document) => r.querySelector(s); const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const BAD = /\b(f+u+c+k+\w*|sh[i1]+t+\w*|b[i1]+t+c+h+\w*|a+s+s+h+o+l+e+\w*|c+u+n+t+\w*|wh[o0]+r+e+\w*|sl+u+t+\w*|p[o0]+r+n+\w*|d+a+m+n+\w*|p+u+s+s+y+|c+o+c+k+\w*)\b/gi;
const clean = (t) => String(t || '').replace(BAD, (w) => w[0] + '•'.repeat(Math.max(2, w.length - 1)));
export const GROUPS = [['general', '🛍️ General · buy sell trade'], ['vehicles', '🚗 Vehicles'], ['furniture', '🛋️ Furniture + home'], ['electronics', '📱 Electronics'], ['tools', '🔧 Tools + equipment'], ['kids', '🧸 Baby + kids'], ['free', '🎁 Free stuff'], ['services', '🧰 Services + pros'], ['business', '📣 Advertise your business'], ['wishes', '🏮 Sky lantern wishes']];
export const SKINS = [['sky', 'Sky', 'linear-gradient(135deg,#0ea5e9,#6366f1 55%,#a855f7)'], ['sunset', 'Sunset', 'linear-gradient(135deg,#f97316,#ec4899 55%,#a855f7)'], ['mint', 'Mint', 'linear-gradient(135deg,#06b6d4,#22c55e)'], ['midnight', 'Midnight', 'linear-gradient(135deg,#1e1b4b,#0f172a)'], ['peace', 'Peace', 'linear-gradient(135deg,#fde68a,#fca5a5,#c4b5fd)'], ['gold', 'Gold', 'linear-gradient(135deg,#f59e0b,#fbbf24,#fde68a)']];
export const BIGSTYLES = [['none', 'Normal'], ['big', 'Big + bold'], ['sky', 'Big on sky'], ['sunset', 'Big on sunset'], ['neon', 'Neon'], ['zach', 'Big with Zach in shades 😎'], ['peace', 'Big peace']];
const bgFor = (s) => ({ sky: 'linear-gradient(135deg,#0ea5e9,#6366f1,#a855f7)', sunset: 'linear-gradient(135deg,#f97316,#ec4899,#a855f7)', neon: '#05081a', zach: 'linear-gradient(90deg,rgba(14,165,233,.92),rgba(99,102,241,.75)), url(/images/zach-face-shades.webp) right center/contain no-repeat, #0ea5e9', peace: 'linear-gradient(135deg,#fde68a,#fca5a5,#c4b5fd)', big: '#fff' }[s] || '');
const since = (d) => { const s = (Date.now() - new Date(d)) / 1000; return s < 60 ? 'just now' : s < 3600 ? Math.floor(s / 60) + 'm' : s < 86400 ? Math.floor(s / 3600) + 'h' : Math.floor(s / 86400) + 'd'; };
const ytId = (u) => { const m = String(u || '').match(/(?:youtu\.be\/|v=|shorts\/|embed\/)([A-Za-z0-9_-]{6,})/); return m ? m[1] : null; };

export const FLAT_CSS = `
.fl{font-family:Poppins,"Segoe UI",Arial,sans-serif;color:#14183a;background:#f1f3f8;min-height:100%}.fl a{color:#2563eb}
.fl-top{position:sticky;top:0;z-index:5;background:#fff;border-bottom:1px solid #e5e7eb}.fl-top .w{max-width:1100px;margin:auto;display:flex;align-items:center;gap:10px;padding:8px 14px}.fl-top .brand{font:900 18px Poppins,Arial;color:#14183a;text-decoration:none;display:inline-flex;align-items:center}.fl-top nav{display:flex;flex-wrap:wrap;gap:4px}@media (max-width:640px){.fl-top .brand img{height:32px!important}.fl-top nav button,.fl-top nav a{padding:6px 8px;font-size:12px}}.fl-top nav{margin-left:auto;display:flex;gap:6px;flex-wrap:wrap}.fl-top nav a,.fl-top nav button{border:0;background:#f1f3f8;color:#14183a;border-radius:12px;padding:7px 12px;font:800 13px Poppins,Arial;text-decoration:none;cursor:pointer}.fl-top nav .on{background:#1e1b4b;color:#fff}
.fl-cover{height:200px;background:var(--skin,linear-gradient(135deg,#0ea5e9,#6366f1 55%,#a855f7)) center/cover}.fl-head{max-width:1100px;margin:-56px auto 0;padding:0 14px;display:flex;gap:16px;align-items:flex-end;flex-wrap:wrap}.fl-ava{width:112px;height:112px;border-radius:50%;border:5px solid #fff;background:#6366f1 center/cover;color:#fff;display:flex;align-items:center;justify-content:center;font:900 44px Poppins}.fl-name h1{margin:0;font:900 26px Poppins,Arial}.fl-name p{margin:2px 0 0;color:#475569}.fl-act{margin-left:auto;display:flex;gap:8px;flex-wrap:wrap;padding-bottom:8px}
.fl-btn{border:1px solid #cbd5e1;background:#fff;color:#14183a!important;border-radius:12px;padding:9px 14px;font:800 13px Poppins,Arial;cursor:pointer;text-decoration:none;display:inline-flex;gap:6px;align-items:center}.fl-btn.p{background:linear-gradient(135deg,#0ea5e9,#6366f1 55%,#a855f7);color:#fff!important;border-color:transparent}.fl-btn.sm{padding:5px 10px;font-size:12px}
.fl-grid{max-width:1100px;margin:14px auto;padding:0 14px;display:grid;grid-template-columns:300px 1fr;gap:14px}@media (max-width:860px){.fl-grid{grid-template-columns:1fr}}
.fl-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:14px 16px;margin-bottom:12px}.fl-card h3{margin:0 0 8px;font:900 15px Poppins,Arial}.fl-card label{display:block;font-weight:800;font-size:12px;color:#475569;margin:8px 0 4px}.fl-card input:not([type=checkbox]),.fl-card select,.fl-card textarea{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:12px;padding:9px 12px;font:600 14px Poppins,Arial;color:#14183a}.fl-card textarea{min-height:90px}
.fl-chips{display:flex;flex-wrap:wrap;gap:6px}.fl-chips button{border:1px solid #cbd5e1;background:#fff;border-radius:12px;padding:6px 11px;font:700 12.5px Poppins,Arial;cursor:pointer}.fl-chips button.on{background:#1e1b4b;color:#fff;border-color:#1e1b4b}
.fl-comp textarea{min-height:110px;font-size:16px}.fl-comp .prev{border-radius:14px;padding:18px;margin:8px 0;font:900 26px/1.2 Poppins,Arial;color:#fff;min-height:40px;text-shadow:0 2px 8px rgba(0,0,0,.25)}.fl-comp .prev.none{display:none}.fl-comp .prev.big{color:#14183a;text-shadow:none;border:2px dashed #cbd5e1}.fl-comp .prev.neon{color:#7cf8ff;text-shadow:0 0 12px #38f0ff,0 0 30px #38f0ff}.fl-comp .tools{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}.fl-comp .extra{display:none;background:#f8fafc;border-radius:12px;padding:8px 12px;margin:6px 0}.fl-comp .extra.on{display:block}.fl-comp .thumbs{display:flex;gap:6px;flex-wrap:wrap}.fl-comp .thumbs img{width:64px;height:64px;object-fit:cover;border-radius:8px}
.fl-post{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:14px 16px;margin-bottom:12px}.fl-post .who{display:flex;gap:10px;align-items:center;margin-bottom:8px}.fl-post .who .av{width:40px;height:40px;border-radius:50%;background:#6366f1;color:#fff;display:flex;align-items:center;justify-content:center;font:900 16px Poppins}.fl-post .who b{display:block}.fl-post .who small{color:#64748b}.fl-post .txt{white-space:pre-wrap;font-size:15.5px;line-height:1.55}.fl-post .bigtxt{border-radius:14px;padding:22px 18px;font:900 clamp(22px,4vw,34px)/1.2 Poppins,Arial;color:#fff;text-shadow:0 2px 8px rgba(0,0,0,.25);margin:4px 0}.fl-post .bigtxt.big{color:#14183a;text-shadow:none;background:#fff;border:2px solid #e5e7eb}.fl-post .bigtxt.neon{color:#7cf8ff;text-shadow:0 0 12px #38f0ff,0 0 30px #38f0ff}
.fl-post .pics{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:6px;margin:8px 0}.fl-post .pics img{width:100%;border-radius:12px;max-height:380px;object-fit:cover}.fl-post .vid{aspect-ratio:16/9;width:100%;border-radius:12px;border:0;margin:8px 0}.fl-post .sale{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;padding:8px 12px;margin:8px 0;font-weight:800}.fl-post .ad{background:#fff7ed;border:1px solid #fed7aa;border-radius:12px;padding:8px 12px;margin:8px 0}.fl-post .poll{margin:8px 0}.fl-post .poll button{display:block;width:100%;text-align:left;border:1px solid #cbd5e1;background:#fff;border-radius:10px;padding:8px 12px;margin:4px 0;font:700 14px Poppins,Arial;cursor:pointer;position:relative;overflow:hidden}.fl-post .poll button i{position:absolute;left:0;top:0;bottom:0;background:#dbeafe;z-index:0}.fl-post .poll button span{position:relative;z-index:1}.fl-post .link{display:block;background:#f8fafc;border:1px solid #e5e7eb;border-radius:10px;padding:8px 12px;margin:8px 0;word-break:break-all;font-size:13px}
.fl-post .acts{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.fl-post .acts button{border:1px solid #e5e7eb;background:#fff;border-radius:12px;padding:5px 10px;font:700 12.5px Poppins,Arial;cursor:pointer}.fl-post .acts button.on{background:#fee2e2;border-color:#fecaca}.fl-post .grp{font-size:12px;color:#64748b}.fl-post .cmts{border-top:1px solid #f1f5f9;margin-top:8px;padding-top:8px}.fl-post .cmt{font-size:13.5px;padding:4px 0}.fl-post .cmt.offer{background:#f0fdf4;border-radius:10px;padding:6px 10px}.fl-post .cmt .off{color:#15803d;font-weight:800}.fl-post .cmt small{color:#94a3b8}.fl-post .cmt-form{display:flex;gap:6px;margin-top:6px}.fl-post .cmt-form input{flex:1;border:1px solid #cbd5e1;border-radius:12px;padding:8px 12px;font:600 13px Poppins,Arial}
.vfeed{scroll-snap-type:y mandatory;max-height:85vh;overflow:auto;border-radius:16px}.vfeed .vpost{scroll-snap-align:start}.vfeed .vid{aspect-ratio:9/16;max-height:70vh;margin:auto;display:block}.fl-empty{text-align:center;color:#64748b;padding:30px 10px}.fl-err{color:#b91c1c;font-weight:800;min-height:1em}.muted{color:#64748b;font-size:13px}.hp{position:absolute!important;left:-9999px!important;opacity:0}
`;

/* mount the whole FLAT experience into a container. opts: { sb, me (profile or null), view: 'u'|'feed'|'groups', username, onEnter3D, toast } */
export async function mountFlat(root, opts) {
  const { sb, toast = (m) => console.log(m) } = opts; let me = opts.me || null; let view = opts.view || 'feed', group = opts.group || 'general', target = null;
  root.innerHTML = `<div class="fl"><div class="fl-top"><div class="w"><a class="brand" href="/"><img src="/images/allofus-lockup.png" alt="allofus.one" style="height:40px;width:auto;vertical-align:middle"></a><nav><button data-v="feed">📰 Feed</button><button data-v="u">🙂 My page</button><button data-v="groups">🛍️ Groups</button><button data-v="video">🎬 Video</button><a href="/?v=hub">📡 Comm Hub</a><a href="/?v=work">⬡ FLOWworks</a><a href="/match/">🎯 Match</a><a href="/">🧊 Back to 3D</a></nav></div></div><div id="fl-body"></div></div>`;
  const body = $('#fl-body', root); const nav = (v) => { view = v; $$('.fl-top nav button', root).forEach(b => b.classList.toggle('on', b.dataset.v === v)); render(); }; $$('.fl-top nav button', root).forEach(b => b.onclick = () => nav(b.dataset.v));
  const loadMe = async () => { if (!sb) return; const { data: { user } } = await sb.auth.getUser(); if (!user) { me = null; return; } const { data } = await sb.from('profiles').select('*').eq('id', user.id).maybeSingle(); me = data ? { id: data.id, username: data.username, name: data.display_name, home: data.home || {}, email: user.email } : { id: user.id, name: (user.email || 'Friend').split('@')[0], home: {}, email: user.email }; };
  if (!me) await loadMe();
  const flat = () => Object.assign({ skin: 'sky', bio: '', showOnHome: true, cover: '' }, (me && me.home && me.home.flat) || {});
  const saveFlat = async (f) => { if (!me) return; me.home = Object.assign({}, me.home || {}, { flat: f }); await sb.from('profiles').update({ home: me.home }).eq('id', me.id); };
  const upload = async (file, folder = 'posts') => { if (!sb || !me) throw new Error('sign in'); const ext = (file.name.split('.').pop() || 'jpg').toLowerCase().replace(/[^a-z0-9]/g, ''); const path = `${me.id}/${Date.now()}-${Math.random().toString(36).slice(2, 7)}.${ext}`; const { error } = await sb.storage.from('posts').upload(path, file, { contentType: file.type || 'application/octet-stream' }); if (error) throw error; return sb.storage.from('posts').getPublicUrl(path).data.publicUrl; };
  const needMe = () => { if (me) return true; toast('Sign in in the 3D world first (tap 🔑 Join), then come back.'); return false; };

  const fab = () => { let f = document.getElementById('fl-fab'); if (!f) { f = document.createElement('button'); f.id = 'fl-fab'; f.textContent = '✚'; f.title = 'Write a post'; f.setAttribute('aria-label', 'Write a post'); f.style.cssText = 'position:fixed;right:16px;bottom:22px;z-index:60;width:58px;height:58px;border-radius:50%;border:0;background:linear-gradient(135deg,#0ea5e9,#6366f1);color:#fff;font:900 28px Poppins,Arial;box-shadow:0 12px 30px rgba(79,70,229,.45);cursor:pointer'; document.body.appendChild(f); } f.style.display = ''; f.onclick = () => { const c = document.querySelector('.fl-comp'); if (!c) { toast('Open the feed or a group to post.'); return; } c.scrollIntoView({ behavior: 'smooth', block: 'start' }); const ta = c.querySelector('textarea'); setTimeout(() => ta && ta.focus(), 350); c.style.boxShadow = '0 0 0 3px #38f0ff'; setTimeout(() => c.style.boxShadow = '', 1500); }; };
  const composer = (mount, { groupSlug = null, after }) => { fab(); const c = document.createElement('div'); c.className = 'fl-card fl-comp'; c.innerHTML = `<h3>${groupSlug ? 'Post to ' + esc((GROUPS.find(g => g[0] === groupSlug) || [])[1] || groupSlug) : '✍️ What\'s on your mind?'}</h3><textarea id="c-t" maxlength="3000" placeholder="Write openly. Add pics, a link, a poll, something for sale…"></textarea><div class="prev none" id="c-prev"></div>
    <div class="tools"><button class="fl-btn sm" data-x="pics">📷 Photos</button><button class="fl-btn sm" data-x="link">🔗 Link / video / GIF</button><button class="fl-btn sm" data-x="sale">🏷️ For sale</button><button class="fl-btn sm" data-x="poll">📊 Poll</button><button class="fl-btn sm" data-x="ad">📣 Advertise business</button><button class="fl-btn sm" data-x="big">🔠 Big text</button><label class="fl-btn sm"><input type="checkbox" id="c-pub" checked> Public</label></div>
    <input type="file" id="c-f" accept="image/*" multiple style="display:none"><div class="extra" id="x-pics"><div class="thumbs" id="c-th"></div></div>
    <div class="extra" id="x-link"><label>Link, YouTube or GIF address<input id="c-link" placeholder="https://"></label></div>
    <div class="extra" id="x-sale"><label>Price<input id="c-price" placeholder="$25 or Free"></label><label>Location (city, state)<input id="c-loc" placeholder="Denver, CO"></label></div>
    <div class="extra" id="x-poll"><label>Poll options (2 to 4)</label><input id="c-p1" placeholder="Option 1"><input id="c-p2" placeholder="Option 2"><input id="c-p3" placeholder="Option 3 (optional)"><input id="c-p4" placeholder="Option 4 (optional)"></div>
    <div class="extra" id="x-ad"><label>Business name<input id="c-biz"></label><label>Website<input id="c-bizurl" placeholder="https://"></label><p class="muted">Ads are free here. Keep it honest and local-friendly. Also list it free on <a href="https://usabusinesssearch.com/" target="_blank" rel="noopener">usabusinesssearch.com</a>.</p></div>
    <div class="extra" id="x-big"><div class="fl-chips" id="c-styles">${BIGSTYLES.map(([k, n], i) => `<button data-s="${k}" class="${i ? '' : 'on'}">${n}</button>`).join('')}</div></div>
    <div class="tools"><button class="fl-btn p" id="c-go">Post</button><span class="fl-err" id="c-err"></span></div>`; mount.appendChild(c);
    const st = { pics: [], style: 'none', kind: 'post' }; const x = (k, on) => { const el = $('#x-' + k, c); el.classList.toggle('on', on === undefined ? !el.classList.contains('on') : on); if (k === 'sale' && el.classList.contains('on')) st.kind = 'sale'; if (k === 'poll' && el.classList.contains('on')) st.kind = 'poll'; if (k === 'ad' && el.classList.contains('on')) st.kind = 'ad'; };
    $$('[data-x]', c).forEach(b => b.onclick = () => { if (b.dataset.x === 'pics') { $('#c-f', c).click(); x('pics', true); return; } x(b.dataset.x); });
    $('#c-f', c).onchange = async (e) => { for (const f of e.target.files) { try { const u = await upload(f); st.pics.push(u); $('#c-th', c).innerHTML = st.pics.map(p => `<img src="${esc(p)}" alt="">`).join(''); } catch (err) { $('#c-err', c).textContent = 'Photo upload failed: ' + (err.message || err); } } };
    const prev = () => { const p = $('#c-prev', c); p.className = 'prev ' + st.style; p.textContent = $('#c-t', c).value; p.style.background = bgFor(st.style); }; $('#c-t', c).oninput = prev; $$('#c-styles button', c).forEach(b => b.onclick = () => { $$('#c-styles button', c).forEach(q => q.classList.toggle('on', q === b)); st.style = b.dataset.s; prev(); });
    $('#c-go', c).onclick = async () => { if (!needMe()) return; const err = $('#c-err', c); const text = clean($('#c-t', c).value.trim()); const link = $('#c-link', c).value.trim(); if (!text && !st.pics.length && !link) { err.textContent = 'Write something, or add a photo or link.'; return; } const row = { user_id: me.id, kind: st.kind, text, style: { big: st.style }, media: st.pics, link: link || null, public: $('#c-pub', c).checked, group_slug: groupSlug }; if (st.kind === 'sale') { row.price = $('#c-price', c).value.trim(); row.location = $('#c-loc', c).value.trim(); } if (st.kind === 'ad') { row.business = $('#c-biz', c).value.trim(); row.link = $('#c-bizurl', c).value.trim() || row.link; row.group_slug = row.group_slug || 'business'; } if (st.kind === 'poll') { const ops = [1, 2, 3, 4].map(i => $('#c-p' + i, c).value.trim()).filter(Boolean); if (ops.length < 2) { err.textContent = 'A poll needs at least 2 options.'; return; } row.poll = { options: ops, counts: ops.map(() => 0), voters: {} }; }
      const { error } = await sb.from('feed_posts').insert(row); if (error) { err.textContent = error.message; return; } toast('✅ Posted!'); c.remove(); after && after(); }; };

  const postEl = (p, names) => { const el = document.createElement('article'); el.className = 'fl-post'; const nm = names[p.user_id] || {}; const big = p.style && p.style.big && p.style.big !== 'none'; const yt = ytId(p.link); const gif = /\.(gif|webp|png|jpe?g)(\?|$)/i.test(p.link || ''); const mine = me && p.user_id === me.id;
    el.innerHTML = `<div class="who"><div class="av">${esc((nm.name || 'F')[0])}</div><div><b>${esc(nm.name || 'Friend')}${nm.username ? ' <small>@' + esc(nm.username) + '</small>' : ''}</b><small>${since(p.created_at)}${p.group_slug ? ' · ' + esc((GROUPS.find(g => g[0] === p.group_slug) || [])[1] || p.group_slug) : ''}${p.public ? '' : ' · 🔒 private'}</small></div><span style="margin-left:auto">${mine ? '<button class="fl-btn sm" data-del>🗑</button>' : ''}</span></div>
      ${p.text ? (big ? `<div class="bigtxt ${esc(p.style.big)}" style="background:${bgFor(p.style.big)}">${esc(p.text)}</div>` : `<div class="txt">${esc(p.text)}</div>`) : ''}
      ${p.kind === 'sale' ? `<div class="sale">🏷️ For sale · ${esc(p.price || 'ask')}${p.location ? ' · 📍 ' + esc(p.location) : ''}</div>` : ''}${p.kind === 'ad' ? `<div class="ad">📣 <b>${esc(p.business || 'Local business')}</b>${p.link ? ' · <a href="' + esc(p.link) + '" target="_blank" rel="noopener">visit</a>' : ''}</div>` : ''}
      ${(p.media || []).length ? `<div class="pics">${p.media.map(u => `<img src="${esc(u)}" alt="" loading="lazy">`).join('')}</div>` : ''}${yt ? `<iframe class="vid" src="https://www.youtube.com/embed/${yt}" allowfullscreen loading="lazy" title="video"></iframe>` : gif ? `<div class="pics"><img src="${esc(p.link)}" alt="" loading="lazy"></div>` : p.link && p.kind !== 'ad' ? `<a class="link" href="${esc(p.link)}" target="_blank" rel="noopener">🔗 ${esc(p.link)}</a>` : ''}
      ${p.kind === 'poll' && p.poll ? `<div class="poll">${p.poll.options.map((o, i) => { const tot = (p.poll.counts || []).reduce((a, b) => a + b, 0) || 0; const n = (p.poll.counts || [])[i] || 0; const voted = me && p.poll.voters && p.poll.voters[me.id] !== undefined; return `<button data-vote="${i}"><i style="width:${voted && tot ? Math.round(n / tot * 100) : 0}%"></i><span>${esc(o)}${voted ? ' · ' + n : ''}</span></button>`; }).join('')}</div>` : ''}
      <div class="acts">${['❤️', '✌️', '😂', '🤗', '🔥'].map(e => `<button data-r="${e}">${e}</button>`).join('')}<span class="muted" data-rc></span><button data-cm style="margin-left:auto">💬 Comments</button>${p.kind === 'sale' ? '<button data-offer>🤝 Make an offer</button>' : ''}${p.kind === 'ad' ? '<button data-ask>❓ Ask</button>' : ''}</div><div class="cmts" data-cmts style="display:none"></div>`;
    $$('[data-vote]', el).forEach(b => b.onclick = async () => { if (!needMe()) return; const { data, error } = await sb.rpc('vote_poll', { p_post: p.id, p_option: +b.dataset.vote }); if (error) { toast(error.message); return; } p.poll = data; render(); });
    $$('[data-r]', el).forEach(b => b.onclick = async () => { if (!needMe()) return; await sb.from('feed_reactions').upsert({ post_id: p.id, user_id: me.id, emoji: b.dataset.r }); $$('[data-r]', el).forEach(q => q.classList.toggle('on', q === b)); loadReacts(); });
    const cmts = $('[data-cmts]', el); const loadC = async () => { cmts.style.display = ''; cmts.innerHTML = '<div class="muted">Loading…</div>'; const { data, error } = await sb.from('feed_comments').select('*').eq('post_id', p.id).order('created_at'); if (error) { cmts.innerHTML = `<div class="muted">${esc(error.message)}<br><small>Run the v8 SQL if the table is missing.</small></div>`; return; } await fillNames(data || []); cmts.innerHTML = (data || []).map(c => `<div class="cmt ${c.kind}"><b>${esc((names[c.user_id] || {}).name || 'Friend')}</b> ${c.kind === 'offer' ? '<span class="off">🤝 offers ' + esc(c.amount || '') + '</span> ' : ''}<span>${esc(c.body || '')}</span><small> · ${since(c.created_at)}</small></div>`).join('') + `<div class="cmt-form"><input data-ci maxlength="1000" placeholder="${me ? 'Comment, ask a question…' : 'Sign in in the 3D world to comment'}" ${me ? '' : 'disabled'}><button class="fl-btn sm p" data-cgo ${me ? '' : 'disabled'}>Send</button></div>`; const go = async (kind, amount) => { if (!needMe()) return; const inp = $('[data-ci]', cmts); const body = clean((inp.value || '').trim()); if (!body && !amount) return; const { error: e2 } = await sb.from('feed_comments').insert({ post_id: p.id, user_id: me.id, kind, body, amount }); if (e2) { toast(e2.message); return; } if (kind === 'offer') toast('🤝 Offer sent. The seller sees it here and in their hub.'); loadC(); if (sb && p.user_id !== me.id) { try { await sb.from('hub_requests').insert({ from_user: me.id, to_user: p.user_id, kind: 'dm', body: (kind === 'offer' ? '🤝 Offer on your post: ' + amount + ' · ' : '💬 On your post: ') + body.slice(0, 300) + ' · https://allofus.one/?u=' + (names[p.user_id] || {}).username }); } catch (e3) { } } }; $('[data-cgo]', cmts).onclick = () => go('comment'); $('[data-ci]', cmts).onkeydown = (e) => { if (e.key === 'Enter') go('comment'); }; };
    $('[data-cm]', el).onclick = () => { if (cmts.style.display === 'none') loadC(); else cmts.style.display = 'none'; }; const ob = $('[data-offer]', el); if (ob) ob.onclick = async () => { if (!needMe()) return; const amt = prompt('Your offer (for example $40, or "trade for a bike"):'); if (!amt) return; await loadC(); const inp = $('[data-ci]', cmts); const note = prompt('Add a note? (pickup, shipping, questions)') || ''; inp.value = note; const body = clean(note.trim()); const { error: e2 } = await sb.from('feed_comments').insert({ post_id: p.id, user_id: me.id, kind: 'offer', body, amount: amt.trim() }); if (e2) { toast(e2.message); return; } toast('🤝 Offer sent!'); loadC(); try { if (p.user_id !== me.id) await sb.from('hub_requests').insert({ from_user: me.id, to_user: p.user_id, kind: 'dm', body: '🤝 Offer on your "' + String(p.text || 'item').slice(0, 40) + '": ' + amt + (body ? ' · ' + body : '') }); } catch (e3) { } }; const ab = $('[data-ask]', el); if (ab) ab.onclick = () => loadC();
    const dl = $('[data-del]', el); if (dl) dl.onclick = async () => { if (!confirm('Delete this post?')) return; await sb.from('feed_posts').delete().eq('id', p.id); el.remove(); };
    const loadReacts = async () => { const { data } = await sb.from('feed_reactions').select('emoji,user_id').eq('post_id', p.id); if (!data) return; const cnt = {}; data.forEach(r => { cnt[r.emoji] = (cnt[r.emoji] || 0) + 1; if (me && r.user_id === me.id) $$('[data-r]', el).forEach(q => q.classList.toggle('on', q.dataset.r === r.emoji)); }); $('[data-rc]', el).textContent = Object.entries(cnt).map(([e, n]) => e + ' ' + n).join('  '); }; loadReacts(); return el; };
  const names = {}; const fillNames = async (posts) => { const ids = [...new Set(posts.map(p => p.user_id).filter(i => !names[i]))]; if (!ids.length) return; const { data } = await sb.from('profiles').select('id,username,display_name').in('id', ids); (data || []).forEach(r => { names[r.id] = { username: r.username, name: r.display_name }; }); };
  const feedList = async (mount, q) => { mount.innerHTML = '<div class="fl-empty">Loading…</div>'; if (!sb) { mount.innerHTML = '<div class="fl-empty">The feed needs the live server.</div>'; return; } let qq = sb.from('feed_posts').select('*').order('created_at', { ascending: false }).limit(60); if (q.user) qq = qq.eq('user_id', q.user); if (q.group) qq = qq.eq('group_slug', q.group); if (q.publicOnly) qq = qq.eq('public', true); const { data, error } = await qq; if (error) { mount.innerHTML = `<div class="fl-empty">${esc(error.message)}<br><small>If this says the table does not exist, the v6 SQL has not been run yet.</small></div>`; return; } if (!data.length) { mount.innerHTML = '<div class="fl-empty">Nothing here yet. Be the first. ✍️</div>'; return; } await fillNames(data); mount.innerHTML = ''; data.forEach(p => mount.appendChild(postEl(p, names))); };

  const render = async () => { body.innerHTML = ''; if (view === 'u') { let prof = me; if (opts.username && (!me || opts.username !== me.username)) { const { data } = await sb.rpc('find_user', { p_username: opts.username }); prof = data && data[0] ? { id: data[0].id, username: data[0].username, name: data[0].display_name, home: data[0].home || {} } : null; if (!prof) { body.innerHTML = '<div class="fl-empty">No one by that name yet.</div>'; return; } } if (!prof) { body.innerHTML = `<div class="fl-grid"><div></div><div class="fl-card"><h3>Your page</h3><p>Sign in in the 3D world first (tap 🔑 Join), then your flat page lives here, public if you want it, with your feed, your skin and your story.</p><a class="fl-btn p" href="/">Go to the world</a></div></div>`; return; } const f = Object.assign({ skin: 'sky', bio: '', showOnHome: true, cover: '' }, (prof.home && prof.home.flat) || {}); const mine = me && prof.id === me.id; const skin = SKINS.find(s => s[0] === f.skin) || SKINS[0];
      body.innerHTML = `<div class="fl-cover" style="--skin:${f.cover ? 'url(' + esc(f.cover) + ')' : skin[2]}"></div><div class="fl-head"><div class="fl-ava" ${f.avatar ? `style="background-image:url(${esc(f.avatar)})"` : ''}>${f.avatar ? '' : esc((prof.name || 'F')[0])}</div><div class="fl-name"><h1>${esc(prof.name || 'Friend')}</h1><p>${prof.username ? '@' + esc(prof.username) + ' · ' : ''}allofus.one</p></div><div class="fl-act">${mine ? '<button class="fl-btn" id="u-edit">🎨 Customize my page</button>' : `<a class="fl-btn p" href="/?u=${esc(prof.username || '')}">🧊 Visit their 3D home</a>`}<a class="fl-btn" href="/?to=${esc(prof.username || '')}">📍 Share</a></div></div>
        <div class="fl-grid"><aside><div class="fl-card"><h3>About</h3><p>${esc(f.bio) || '<span class="muted">Nothing written yet.</span>'}</p>${f.socials ? Object.entries(f.socials).filter(([, v]) => v).map(([k, v]) => `<a class="fl-btn sm" href="${esc(v)}" target="_blank" rel="noopener">${esc(k)}</a> `).join('') : ''}</div>${mine ? `<div class="fl-card" id="u-cust" style="display:none"><h3>🎨 Customize</h3><label>Skin</label><div class="fl-chips" id="u-skins">${SKINS.map(([k, n, g]) => `<button data-k="${k}" class="${k === f.skin ? 'on' : ''}" style="background:${g};color:#fff;border:0">${n}</button>`).join('')}</div><label>Or upload your own cover (art, a photo, anything)<input type="file" id="u-cover" accept="image/*"></label><label>Profile photo<input type="file" id="u-ava" accept="image/*"></label><label>About you<textarea id="u-bio" maxlength="500">${esc(f.bio)}</textarea></label><label>Links (one per line: name | https://)</label><textarea id="u-soc" maxlength="800" placeholder="Instagram | https://instagram.com/you\nWebsite | https://">${esc(Object.entries(f.socials || {}).map(([k, v]) => k + ' | ' + v).join('\n'))}</textarea><label><input type="checkbox" id="u-home" ${f.showOnHome ? 'checked' : ''}> Show my latest public posts on the front of my 3D home</label><label>How many posts on the house <select id="u-n"><option ${f.homeN == 1 ? 'selected' : ''}>1</option><option ${!f.homeN || f.homeN == 3 ? 'selected' : ''}>3</option><option ${f.homeN == 5 ? 'selected' : ''}>5</option></select></label><div class="tools" style="margin-top:8px"><button class="fl-btn p" id="u-save">Save</button></div></div>` : ''}</aside><section id="u-feed"></section></div>`;
      const feed = $('#u-feed', body); if (mine) composer(feed, { after: () => feedList($('#u-list', body) || feed, { user: prof.id }) }); const list = document.createElement('div'); list.id = 'u-list'; feed.appendChild(list); feedList(list, { user: prof.id, publicOnly: !mine });
      if (mine) { $('#u-edit', body).onclick = () => { const c = $('#u-cust', body); c.style.display = c.style.display === 'none' ? '' : 'none'; }; let nf = Object.assign({}, f); $$('#u-skins button', body).forEach(b => b.onclick = () => { nf.skin = b.dataset.k; nf.cover = ''; $$('#u-skins button', body).forEach(q => q.classList.toggle('on', q === b)); }); $('#u-cover', body).onchange = async (e) => { try { nf.cover = await upload(e.target.files[0]); toast('Cover uploaded'); } catch (err) { toast('Upload failed'); } }; $('#u-ava', body).onchange = async (e) => { try { nf.avatar = await upload(e.target.files[0]); toast('Photo uploaded'); } catch (err) { toast('Upload failed'); } }; $('#u-save', body).onclick = async () => { nf.bio = clean($('#u-bio', body).value.trim()); nf.socials = {}; $('#u-soc', body).value.split('\n').forEach(l => { const [k, v] = l.split('|').map(x => (x || '').trim()); if (k && /^https?:/.test(v)) nf.socials[k] = v; }); nf.showOnHome = $('#u-home', body).checked; nf.homeN = +$('#u-n', body).value; await saveFlat(nf); toast('✅ Saved'); render(); }; } return; }
    if (view === 'video') { body.innerHTML = `<div class="fl-grid"><aside><div class="fl-card"><h3>🎬 Video feed</h3><p class="muted">Everyone's video posts, newest first, full width, swipe up. Post one from the feed: paste a YouTube link in "Link / video / GIF".</p>${me ? '<a class="fl-btn p" href="/">➕ Post a video</a>' : ''}</div></aside><section id="v-feed" class="vfeed"></section></div>`; const vf = $('#v-feed', body); vf.innerHTML = '<div class="fl-empty">Loading…</div>'; const { data } = await sb.from('feed_posts').select('*').eq('public', true).not('link', 'is', null).order('created_at', { ascending: false }).limit(80); const vids = (data || []).filter(p => ytId(p.link)); if (!vids.length) { vf.innerHTML = '<div class="fl-empty">No videos yet. Be the first. 🎬</div>'; return; } await fillNames(vids); vf.innerHTML = ''; vids.forEach(p => { const el = postEl(p, names); el.classList.add('vpost'); vf.appendChild(el); }); return; }
    if (view === 'groups') { body.innerHTML = `<div class="fl-grid"><aside><div class="fl-card"><h3>🛍️ Buy · Sell · Trade</h3><p class="muted">National groups, no fees, no algorithm. Local pickup or ship it. Be kind, be honest.</p><div class="fl-chips" id="g-list" style="flex-direction:column;align-items:stretch">${GROUPS.map(([k, n]) => `<button data-g="${k}" class="${k === group ? 'on' : ''}">${n}</button>`).join('')}</div><p class="muted" style="margin-top:10px">Own a business? List it free in the national directory: <a href="https://usabusinesssearch.com/" target="_blank" rel="noopener">usabusinesssearch.com</a></p></div></aside><section id="g-feed"></section></div>`; $$('#g-list button', body).forEach(b => b.onclick = () => { group = b.dataset.g; render(); }); const gf = $('#g-feed', body); if (me) composer(gf, { groupSlug: group, after: () => feedList($('#g-list2', body), { group }) }); const l = document.createElement('div'); l.id = 'g-list2'; gf.appendChild(l); feedList(l, { group, publicOnly: true }); return; }
    body.innerHTML = `<div class="fl-grid"><aside><div class="fl-card"><h3>📰 Your feed</h3><p class="muted">Newest first. Everyone's public posts, plus yours. No algorithm, nothing hidden.</p><div class="fl-chips"><button class="on" data-f="all">Everyone</button><button data-f="mine">Just mine</button></div></div><div class="fl-card"><h3>Why this is different</h3><p class="muted">You decide what's public. We don't rank, hide or sell your attention. <a href="/mission/">Read the mission</a>.</p></div></aside><section id="f-feed"></section></div>`; const ff = $('#f-feed', body); if (me) composer(ff, { after: () => feedList($('#f-list', body), { publicOnly: true }) }); else ff.innerHTML = '<div class="fl-card"><p>Sign in in the 3D world (tap 🔑 Join) to post. You can read everything without an account.</p></div>'; const fl = document.createElement('div'); fl.id = 'f-list'; ff.appendChild(fl); feedList(fl, { publicOnly: true }); $$('[data-f]', body).forEach(b => b.onclick = () => { $$('[data-f]', body).forEach(q => q.classList.toggle('on', q === b)); feedList(fl, b.dataset.f === 'mine' && me ? { user: me.id } : { publicOnly: true }); }); };
  nav(view);
  return { render, nav, get me() { return me; } };
}

/* Standalone page boot: /flat/ */
export async function bootFlatPage() { let sb = null; try { const { createClient } = await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'); sb = createClient(CONFIG.SUPABASE_URL, CONFIG.SUPABASE_ANON_KEY); const { ssoReceive } = await import('./aou-sso.js'); await ssoReceive(sb); } catch (e) { console.warn('flat offline', e); } const st = document.createElement('style'); st.textContent = FLAT_CSS; document.head.appendChild(st); const q = new URLSearchParams(location.search); const toast = (m) => { const t = document.createElement('div'); t.textContent = m; t.style.cssText = 'position:fixed;left:50%;top:14px;transform:translateX(-50%);background:#14183a;color:#fff;padding:9px 16px;border-radius:12px;font:700 13px Poppins,Arial;z-index:99;box-shadow:0 8px 24px rgba(0,0,0,.3)'; document.body.appendChild(t); setTimeout(() => t.remove(), 2800); }; return mountFlat(document.getElementById('flat'), { sb, view: q.get('u') ? 'u' : (q.get('g') ? 'groups' : (q.get('view') || 'feed')), username: q.get('u') && q.get('u') !== 'me' ? q.get('u') : null, group: q.get('g') || 'general', toast }); }
