/* ============================================================
   allofus.one · conference presenting (v4)
   Put anything on the 26 m screen: PDF, PowerPoint / Word /
   Excel (Office viewer), MP3 / audio, video, images, YouTube or
   any web page. Upload a file (stored in your Supabase bucket)
   or paste a link. Everyone in the hall gets it live, PDF pages
   and slides follow the presenter. © 2026 allofus.one
   ============================================================ */
const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export function kindOf(url, mime = '') { const u = (url || '').toLowerCase().split('?')[0].split('#')[0]; if (/youtu\.?be/.test(url)) return 'youtube'; if (/\.pdf$/.test(u) || mime.includes('pdf')) return 'pdf'; if (/\.(pptx?|ppsx?|docx?|xlsx?)$/.test(u) || /officedocument|powerpoint|msword|excel/.test(mime)) return 'office'; if (/\.(mp3|wav|ogg|m4a|aac|flac)$/.test(u) || mime.startsWith('audio')) return 'audio'; if (/\.(mp4|webm|mov|m4v)$/.test(u) || mime.startsWith('video')) return 'video'; if (/\.(png|jpe?g|gif|webp|avif|svg)$/.test(u) || mime.startsWith('image')) return 'image'; return 'web'; }
export function ytId(url) { const m = String(url).match(/(?:youtu\.be\/|v=|embed\/|shorts\/)([\w-]{11})/); return m ? m[1] : null; }
export function embedHTML(st) { const u = st.url; switch (st.kind) {
  case 'pdf': return `<iframe title="PDF" src="${esc(u)}#page=${st.page || 1}&view=FitH" allow="fullscreen"></iframe>`;
  case 'office': return `<iframe title="Slides" src="https://view.officeapps.live.com/op/embed.aspx?src=${encodeURIComponent(u)}" allow="fullscreen"></iframe>`;
  case 'audio': return `<div class="cf-audio"><div class="cf-eq">${'<i></i>'.repeat(12)}</div><audio src="${esc(u)}" controls autoplay></audio></div>`;
  case 'video': return `<video src="${esc(u)}" controls autoplay playsinline></video>`;
  case 'image': return `<img src="${esc(u)}" alt="${esc(st.title)}">`;
  case 'youtube': return `<iframe title="Video" src="https://www.youtube-nocookie.com/embed/${ytId(u)}?autoplay=1&rel=0" allow="autoplay; encrypted-media; picture-in-picture; fullscreen"></iframe>`;
  default: return `<iframe title="Web page" src="${esc(u)}" sandbox="allow-scripts allow-same-origin allow-popups allow-forms"></iframe>`; } }

export function initConference(app, W, UI, opts = {}) {
  const DB = UI.DB; const getMe = () => UI.getMe && UI.getMe(); const screen = () => W.confScreen; let cur = null, hb = 0, viewer = null;
  const css = document.createElement('style'); css.textContent = `.cf-view{position:fixed;inset:0;z-index:99992;background:rgba(2,6,23,.78);display:flex;align-items:center;justify-content:center;padding:10px}.cf-card{background:#0b1033;color:#fff;border-radius:18px;width:min(1200px,100%);height:min(92vh,820px);display:flex;flex-direction:column;overflow:hidden;box-shadow:0 30px 90px rgba(0,0,0,.6)}.cf-head{display:flex;align-items:center;gap:10px;padding:10px 14px;background:linear-gradient(90deg,#1e1b4b,#3b0d4a)}.cf-head b{flex:1;font:800 16px Poppins,Arial;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cf-head button,.cf-head a{border:0;border-radius:12px;padding:8px 12px;font:800 13px Poppins,Arial;cursor:pointer;background:#fff;color:#0f172a;text-decoration:none}.cf-body{flex:1;background:#000;display:flex;align-items:center;justify-content:center;min-height:0}.cf-body iframe,.cf-body video{width:100%;height:100%;border:0;background:#fff}.cf-body img{max-width:100%;max-height:100%}.cf-audio{display:flex;flex-direction:column;align-items:center;gap:20px}.cf-eq{display:flex;gap:6px;align-items:flex-end;height:120px}.cf-eq i{width:14px;background:linear-gradient(#38f0ff,#a855f7);border-radius:6px;animation:cfEq 1s ease-in-out infinite}.cf-eq i:nth-child(odd){animation-delay:.3s}.cf-eq i:nth-child(3n){animation-delay:.6s}@keyframes cfEq{0%,100%{height:20%}50%{height:100%}}.cf-pg{display:flex;align-items:center;gap:6px}.cf-pg span{font-weight:800}.cf-live{background:#e11d48;border-radius:12px;padding:3px 9px;font:800 11px Poppins,Arial}`; document.head.appendChild(css);
  const showOnScreen = (st) => { const s = screen(); if (!s) return; if (!st) { s.card(['ALL OF US · CONFERENCE CENTER', 'Walk to the podium and tap 📽️ Present']); return; } if (st.kind === 'image') s.image(st.url); else s.card(['📽️ ' + (st.title || 'Presentation'), 'by ' + (st.by || 'a presenter') + (st.kind === 'pdf' ? ' · page ' + (st.page || 1) : '') + ' · tap the screen to watch'], st.kind === 'audio' ? ['#1e1b4b', '#0e7490'] : ['#0b1033', '#3b0d4a']); };
  const openViewer = (st) => { closeViewer(); const mine = st.byId && getMe() && st.byId === getMe().id; viewer = document.createElement('div'); viewer.className = 'cf-view'; viewer.innerHTML = `<div class="cf-card" role="dialog" aria-label="Presentation"><div class="cf-head"><span class="cf-live">LIVE</span><b>${esc(st.title || 'Presentation')} · ${esc(st.by || '')}</b>${st.kind === 'pdf' && mine ? `<span class="cf-pg"><button data-pg="-1">◀</button><span>Page ${st.page || 1}</span><button data-pg="1">▶</button></span>` : st.kind === 'pdf' ? `<span>Page ${st.page || 1}</span>` : ''}${mine ? '<button data-stop>⏹ Stop presenting</button>' : ''}<a href="${esc(st.url)}" target="_blank" rel="noopener">↗ Open</a><button data-x aria-label="Close">✕</button></div><div class="cf-body">${embedHTML(st)}</div></div>`; document.body.appendChild(viewer); app.paused = true;
    viewer.onclick = (e) => { if (e.target.closest('[data-x]') || e.target === viewer) closeViewer(); const pg = e.target.closest('[data-pg]'); if (pg && cur) { cur.page = Math.max(1, (cur.page || 1) + +pg.dataset.pg); broadcast(); showOnScreen(cur); openViewer(cur); } if (e.target.closest('[data-stop]')) stop(); }; };
  const closeViewer = () => { if (viewer) { viewer.remove(); viewer = null; app.paused = false; } };
  const broadcast = () => { if (cur && DB.live && DB.fx) DB.fx(Object.assign({ kind: 'conf' }, cur)); };
  const start = (st) => { const me = getMe(); cur = Object.assign({ page: 1, by: (me && me.name) || 'Guest', byId: me && me.id, at: Date.now() }, st); showOnScreen(cur); openViewer(cur); broadcast(); clearInterval(hb); hb = setInterval(broadcast, 15000); app.toast('📽️ You are presenting. Everyone in the hall sees it.', 3600); };
  const stop = () => { if (cur && DB.live && DB.fx) DB.fx({ kind: 'conf', stop: true, byId: cur.byId }); cur = null; clearInterval(hb); showOnScreen(null); closeViewer(); };
  // listen for other presenters (chained onto the existing fx handler)
  const prev = W.onFx; W.onFx = (pl) => { if (pl && pl.kind === 'conf') { if (pl.stop) { if (cur && cur.byId === pl.byId) cur = null; showOnScreen(null); return; } const isNew = !cur || cur.url !== pl.url || cur.page !== pl.page; const me = getMe(); if (me && pl.byId === me.id) return; cur = pl; showOnScreen(pl); if (isNew && screen() && screen().inside()) { app.popup('📽️ ' + (pl.title || 'Presentation') + ' is live', '<p>' + esc(pl.by || 'Someone') + ' is presenting on the giant screen.</p>', [{ label: '📽️ Watch', primary: true, fn: () => openViewer(pl) }]); } else if (viewer && isNew) openViewer(pl); return; } if (prev) prev(pl); };
  const openConference = () => { const me = getMe(); const m = UI.modal('📽️ Present on the giant screen', `${cur ? `<p class="lt-good">Now showing: <b>${esc(cur.title)}</b> by ${esc(cur.by)}</p><div class="lt-row"><button class="lt-btn holo" id="cf-watch">📽️ Watch</button>${cur.byId && me && cur.byId === me.id ? '<button class="lt-btn" id="cf-stop">⏹ Stop</button>' : ''}</div><hr>` : ''}
      <label>Title<input id="cf-t" maxlength="60" placeholder="Q4 kickoff, my art show, band demo…"></label>
      <label>Paste a link (PDF, PowerPoint, Word, MP3, video, image, YouTube or any web page)<input id="cf-u" placeholder="https://…"></label>
      <p class="aou-lbl">Or upload a file</p><input id="cf-f" type="file" accept=".pdf,.ppt,.pptx,.doc,.docx,.xls,.xlsx,.mp3,.wav,.m4a,.ogg,.mp4,.webm,.png,.jpg,.jpeg,.gif,.webp,.html,.htm">
      <p class="muted2">${DB.live ? 'Uploads go to your allofus.one storage so everyone in the hall can see them (50 MB max). PowerPoint and Word need a public link to preview; uploads give you one.' : 'Demo mode: uploads play only on this device until accounts are live.'}</p>
      <div class="lt-row"><button class="lt-btn holo" id="cf-go">📽️ Start presenting</button><button class="lt-btn" id="cf-voice">🎙️ Join hall voice</button></div><p class="aou-err" id="cf-e"></p>`);
    const q = (s) => m.querySelector(s); q('#cf-t').onkeydown = q('#cf-u').onkeydown = (e) => e.stopPropagation();
    if (q('#cf-watch')) q('#cf-watch').onclick = () => { UI.close(); openViewer(cur); }; if (q('#cf-stop')) q('#cf-stop').onclick = () => { UI.close(); stop(); };
    q('#cf-voice').onclick = () => { UI.close(); opts.joinVoice && opts.joinVoice('conference'); };
    q('#cf-go').onclick = async () => { const err = q('#cf-e'); err.textContent = ''; const title = (window.AOU && window.AOU.clean ? window.AOU.clean(q('#cf-t').value) : q('#cf-t').value).trim() || 'Presentation'; let url = q('#cf-u').value.trim(); const f = q('#cf-f').files[0]; let mime = '';
      if (f) { if (f.size > 50 * 1024 * 1024) { err.textContent = 'That file is over 50 MB.'; return; } mime = f.type || ''; if (DB.live && me && DB.sb.storage) { q('#cf-go').disabled = true; q('#cf-go').textContent = 'Uploading…'; const path = me.id + '/' + Date.now() + '-' + f.name.replace(/[^\w.\-]+/g, '_'); const { error } = await DB.sb.storage.from('conference').upload(path, f, { upsert: false, contentType: mime || undefined }); if (error) { err.textContent = 'Upload failed: ' + error.message + ' (has the v4 storage SQL been run?)'; q('#cf-go').disabled = false; q('#cf-go').textContent = '📽️ Start presenting'; return; } url = DB.sb.storage.from('conference').getPublicUrl(path).data.publicUrl; } else url = URL.createObjectURL(f); }
      if (!/^(https?:|blob:)/.test(url)) { err.textContent = 'Add a link that starts with https:// or pick a file.'; return; }
      UI.close(); start({ url, title, kind: kindOf(f ? f.name : url, mime) }); }; };
  return { openConference, start, stop, openViewer, current: () => cur };
}
