/* allofus.one · onboarding (Oct 9 2026)
   1. The guided tour: five spotlight steps for every new member (and once for existing accounts) —
      Your page & photo → Connections → Post something → LIFEboard → Go 3D / VR. Keyboard: ← → Enter Esc.
   2. The claim flow: when someone signs in whose email pre-claimed a Brand page (pages.admin_emails, v17),
      a 4-step guided modal — welcome → finish your profile → review the page → your VR home spot.
   Nothing here touches /world/. Works in demo mode (saves are skipped, the walk-through still runs). */
import { ic } from './aou-icons2.js';
const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export const ONBOARD_CSS = `
.tour-ov{position:fixed;inset:0;z-index:300;pointer-events:auto}.tour-hole{position:absolute;border-radius:16px;box-shadow:0 0 0 200vmax rgba(5,10,30,.62);transition:left .3s,top .3s,width .3s,height .3s;pointer-events:none;outline:3px solid #38f0ff;outline-offset:4px}
.tour-card{position:absolute;z-index:2;box-sizing:border-box;width:min(360px,calc(100vw - 32px));background:#fff;color:#14183a;border-radius:18px;box-shadow:0 30px 80px rgba(2,8,30,.45);padding:16px 18px 14px;font-family:var(--ff,Poppins,Arial);animation:fmIn .25s ease-out}.tour-card .k{display:flex;align-items:center;gap:8px;font:800 11px var(--ff);letter-spacing:.08em;text-transform:uppercase;color:#0ea5e9}.tour-card .k .hic{width:18px;height:18px}.tour-card h3{margin:6px 0 4px;font:900 19px var(--fd,Georgia,serif)}.tour-card p{margin:0 0 10px;font-size:13.5px;line-height:1.45;color:#334155}.tour-card .row{display:flex;gap:6px;align-items:center}.tour-card .row .sp{flex:1}.tour-card .dots{display:flex;gap:4px;margin:0 0 10px}.tour-card .dots i{height:4px;flex:1;border-radius:2px;background:#e2e8f0}.tour-card .dots i.on{background:#0ea5e9}.tour-card .fl-btn{min-height:36px}
.cl-wrap{position:fixed;inset:0;z-index:290;background:rgba(5,10,30,.6);backdrop-filter:blur(4px);display:flex;align-items:center;justify-content:center;padding:14px}.cl{background:#fff;color:#14183a;border-radius:22px;width:min(560px,100%);max-height:94vh;overflow:auto;box-shadow:0 30px 80px rgba(2,8,30,.45);animation:fmIn .25s ease-out;font-family:var(--ff,Poppins,Arial)}.cl .hero{padding:22px 22px 14px;color:#fff;border-radius:22px 22px 0 0;position:relative;overflow:hidden}.cl .hero:after{content:"";position:absolute;inset:-40% -10%;background:linear-gradient(115deg,transparent 40%,rgba(255,255,255,.22) 50%,transparent 60%);transform:translateX(-60%);animation:clSheen 5s ease-in-out infinite}@keyframes clSheen{0%,20%{transform:translateX(-60%)}60%,100%{transform:translateX(60%)}}.cl .hero .k{font:800 11px var(--ff);letter-spacing:.1em;text-transform:uppercase;opacity:.85}.cl .hero h2{margin:4px 0 2px;font:900 24px var(--fd,Georgia,serif)}.cl .hero p{margin:0;font-size:13.5px;opacity:.92}.cl .bd{padding:14px 22px 18px}.cl .steps{display:flex;gap:6px;margin-bottom:12px}.cl .steps i{flex:1;height:5px;border-radius:3px;background:#e2e8f0}.cl .steps i.on{background:#0ea5e9}.cl label{display:block;font:700 12px var(--ff);color:#475569;margin:8px 0 3px}.cl input:not([type=file]),.cl textarea{width:100%;border:1.5px solid #cbd5e1;border-radius:12px;padding:10px 12px;font:600 14px var(--ff);box-sizing:border-box;outline:0}.cl input:focus,.cl textarea:focus{border-color:#0ea5e9}.cl .row{display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin-top:12px}.cl .row .sp{flex:1}.cl .spot{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:6px}.cl .spot button{border:1.5px solid #e2e8f0;background:#fff;border-radius:12px;padding:8px 10px;font:700 12px var(--ff);cursor:pointer;text-align:left}.cl .spot button.on{border-color:#0ea5e9;background:#f0f9ff}.cl .pv{display:flex;gap:10px;align-items:center;margin:6px 0}.cl .pv .av{width:56px;height:56px;border-radius:50%;background:#e0f2fe center/cover;display:grid;place-items:center;font:900 22px var(--ff);color:#0b1a3a;flex:none}.cl .vr{background:linear-gradient(135deg,#0b1a3a,#1e3a6a);color:#fff;border-radius:16px;padding:14px;margin-top:6px;font-size:13px;line-height:1.5}.cl .vr b{color:#38f0ff}.cl .muted{color:#64748b;font-size:12px}
@media(prefers-reduced-motion:reduce){.cl .hero:after{animation:none}}`;
/* ---------- the tour ---------- */
export function startTour(ctx) {
  const { $, toast } = ctx; const me = ctx.me; const first = (me && me.name ? me.name.split(' ')[0] : 'friend');
  const mobile = () => matchMedia('(max-width:1000px)').matches;
  const STEPS = [
    { icon: '🙂', k: 'Step 1 · Your page', h: `Your page and your photo, ${esc(first)}`, p: 'Everything you post lives on your page. Add a photo and a line about you so people know who they are meeting. Tap <b>My page</b> any time to edit it.', sel: () => mobile() ? '.fl-bottom [data-v="u"]' : '.fl-id, .fl-top [data-v="u"]' },
    { icon: '🤝', k: 'Step 2 · Connections', h: 'You start connected with Zach', p: 'Zach is the founder of allofus.one and your first connection — so your feed is never empty on day one. One tap (⋯ → Disconnect) removes it. Connections are people you choose, not “friends” or “followers”.', sel: () => mobile() ? '.fl-bottom [data-v="conn"]' : '#conn-panel, .fl-top [data-v="conn"]' },
    { icon: '✍️', k: 'Step 3 · Post something', h: 'Say the first thing', p: 'Text, photos, a video, a poll, something for sale, an event, a need. No algorithm decides who sees it — your connections and the groups you pick do.', sel: () => '.fl-pill, .fl-comp, [data-open-comp], #fl-fab', before: () => { const b = $('[data-open-comp]'); if (b && !$('.fl-comp')) b.click(); } },
    { icon: '🧩', k: 'Step 4 · LIFEboard', h: 'Your LIFEboard', p: 'Goals, habits, the life wheel, trackers, journal, money tools, a widget dash you lay out yourself. Private to you, and the same board shows in 3D and VR.', sel: () => '.rail a[href="/?v=board"], .fl-foot a[href="/?board=1"]' },
    { icon: '🧊', k: 'Step 5 · Go 3D / VR', h: 'Feed · 3D · VR, one account', p: 'The rail at the top switches modes. <b>Feed</b> is this page. <b>3D</b> opens the world in your browser (walk, build, meet). <b>VR</b> is the same world in a headset. Your page, posts and people are the same in all three.', sel: () => '.ms' }
  ];
  let i = 0; const ov = document.createElement('div'); ov.className = 'tour-ov'; ov.setAttribute('role', 'dialog'); ov.setAttribute('aria-modal', 'true'); ov.setAttribute('aria-label', 'Welcome tour'); ov.innerHTML = '<div class="tour-hole"></div><div class="tour-card" tabindex="-1"></div>'; document.body.appendChild(ov);
  const hole = ov.firstChild, card = ov.lastChild; const prevOverflow = document.body.style.overflow;
  const finish = (why) => { try { localStorage.setItem('aou_tour_done', '1'); localStorage.removeItem('aou_tour_pending'); } catch (e) { } ov.remove(); removeEventListener('resize', place); removeEventListener('keydown', keys, true); document.body.style.overflow = prevOverflow; if (why === 'done') toast && toast('You are all set. Welcome in.'); };
  const target = () => { const s = STEPS[i]; const sels = s.sel().split(',').map(x => x.trim()); for (const q of sels) { const el = $(q); if (el && el.offsetParent !== null && el.getBoundingClientRect().width > 0) return el; } return null; };
  const place = () => { const el = target(); const vw = innerWidth, vh = innerHeight; let r = null; if (el) { el.scrollIntoView({ block: 'center', behavior: 'instant' in Element.prototype ? 'instant' : 'auto' }); r = el.getBoundingClientRect(); } if (r) { const pad = 8; Object.assign(hole.style, { left: (r.left - pad) + 'px', top: (r.top - pad) + 'px', width: (r.width + pad * 2) + 'px', height: (r.height + pad * 2) + 'px', opacity: 1 }); } else { Object.assign(hole.style, { left: '50%', top: '40%', width: '0px', height: '0px', opacity: 1 }); } const cw = Math.min(360, vw - 32), ch = card.offsetHeight || 220; let left = 16, top = 16; if (r) { left = Math.max(16, Math.min(vw - cw - 16, r.left)); top = r.bottom + 14; if (top + ch > vh - 10) top = Math.max(10, r.top - ch - 14); if (r.height > vh * 0.7) top = Math.max(10, vh - ch - 20); } else { left = (vw - cw) / 2; top = Math.max(16, (vh - ch) / 2); } card.style.left = left + 'px'; card.style.top = top + 'px'; };
  const draw = () => { const s = STEPS[i]; if (s.before) { try { s.before(); } catch (e) { } } card.innerHTML = `<div class="k">${ic(s.icon)} ${s.k}</div><h3>${s.h}</h3><p>${s.p}</p><div class="dots">${STEPS.map((x, j) => `<i class="${j <= i ? 'on' : ''}"></i>`).join('')}</div><div class="row">${i ? '<button class="fl-btn sm" data-back>Back</button>' : ''}<span class="sp"></span><button class="fl-btn sm" data-skip>Skip tour</button><button class="fl-btn p sm" data-next>${i === STEPS.length - 1 ? 'Done' : 'Next'}</button></div>`; card.querySelector('[data-next]').onclick = next; card.querySelector('[data-skip]').onclick = () => finish('skip'); const b = card.querySelector('[data-back]'); if (b) b.onclick = () => { i = Math.max(0, i - 1); draw(); }; setTimeout(place, 30); setTimeout(place, 350); card.querySelector('[data-next]').focus(); };
  const next = () => { if (i >= STEPS.length - 1) { finish('done'); return; } i++; draw(); };
  const keys = (e) => { if (e.key === 'Escape') { e.preventDefault(); finish('skip'); } else if (e.key === 'ArrowRight' || (e.key === 'Enter' && !e.target.closest('button'))) { e.preventDefault(); next(); } else if (e.key === 'ArrowLeft') { e.preventDefault(); if (i) { i--; draw(); } } else if (e.key === 'Tab') { const f = [...card.querySelectorAll('button')]; if (!f.length) return; const a = document.activeElement; const idx = f.indexOf(a); if (e.shiftKey && (idx <= 0)) { e.preventDefault(); f[f.length - 1].focus(); } else if (!e.shiftKey && idx === f.length - 1) { e.preventDefault(); f[0].focus(); } else if (!card.contains(a)) { e.preventDefault(); f[0].focus(); } } };
  addEventListener('keydown', keys, true); addEventListener('resize', place); document.body.style.overflow = 'hidden'; ov.addEventListener('click', (e) => { if (e.target === ov) next(); }); draw(); return { finish, next };
}
/* should the tour run now? once per device: right after joining, or once for accounts that never saw it */
export function tourDue(me) { try { if (new URLSearchParams(location.search).get('debugtour')) return true; if (!me) return false; if (localStorage.getItem('aou_tour_pending') === '1') return true; return !localStorage.getItem('aou_tour_done'); } catch (e) { return false; } }
/* ---------- the claim flow ---------- */
export const VR_SPOTS = [['gate', 'The Gateway (spawn)'], ['plaza', 'Central Plaza'], ['city', 'The City'], ['library', 'Library district'], ['falls', 'The Falls'], ['desert', 'Desert district'], ['beach', 'Beach Cove'], ['starport', 'Starport'], ['art', 'Art Garden'], ['unity', 'Unity Heights'], ['skyrange', 'Sky Range golf'], ['coaster', 'Peace Coaster'], ['lake-dillon', 'Lake Dillon'], ['conference', 'Conference Center'], ['first-street', 'First Street homes'], ['balloons', 'Kindness Commons']];
export function claimModal(ctx, pg) {
  const { sb, toast, upload } = ctx; const me = ctx.me || {}; const f = Object.assign({ bio: '', city: '' }, (me.home && me.home.flat) || {}); const color = (pg.extra && pg.extra.color) || pg.color || '#0ea5e9';
  const x = Object.assign({}, pg.extra || {}); const cta = x.cta || {}; let step = 0; let photo = f.avatar || null, cover = pg.cover || null; let spot = pg.vr_home || pg.world_spot || 'gate';
  const w = document.createElement('div'); w.className = 'cl-wrap'; w.setAttribute('role', 'dialog'); w.setAttribute('aria-modal', 'true'); w.setAttribute('aria-label', 'You manage ' + pg.name); document.body.appendChild(w);
  const mark = () => { try { localStorage.setItem('aou_claimed_' + pg.slug, String(Date.now())); } catch (e) { } };
  const close = () => { mark(); w.remove(); removeEventListener('keydown', esc_, true); };
  const esc_ = (e) => { if (e.key === 'Escape') { e.preventDefault(); close(); } }; addEventListener('keydown', esc_, true);
  const save = async (table, patch, match) => { if (!sb || !me.id) return; try { let q = sb.from(table).update(patch); for (const [k, v] of Object.entries(match)) q = q.eq(k, v); const { error } = await q; if (error && /column|schema cache/i.test(error.message)) { const p2 = Object.assign({}, patch); delete p2.extra; delete p2.hours; let q2 = sb.from(table).update(p2); for (const [k, v] of Object.entries(match)) q2 = q2.eq(k, v); await q2; } else if (error) toast(error.message); } catch (e) { } };
  const hero = (k, h, p) => `<div class="hero" style="background:linear-gradient(135deg,${esc(color)},#0b1a3a)"><div class="k">${k}</div><h2>${h}</h2><p>${p}</p></div>`;
  const steps = () => `<div class="steps">${[0, 1, 2, 3].map(j => `<i class="${j <= step ? 'on' : ''}"></i>`).join('')}</div>`;
  const draw = () => {
    if (step === 0) w.innerHTML = `<div class="cl">${hero('Welcome', `You manage <span style="white-space:nowrap">${esc(pg.name)}</span>`, 'Your email was pre-linked to this Brand page. It is yours to run from your personal account: post as the page, take messages, edit everything.')}<div class="bd">${steps()}<p>Four quick steps and you are set: your profile, a look at the page, and your spot in the 3D world (it works in VR too).</p><p class="muted">Nothing here is permanent — every piece can be changed later from the page's ⚙ Manage bar or your Control panel.</p><div class="row"><button class="fl-btn sm" data-later>Later</button><span class="sp"></span><button class="fl-btn p" data-next>Let's go</button></div></div></div>`;
    else if (step === 1) w.innerHTML = `<div class="cl">${hero('Step 2 of 4', 'Finish your profile', 'People who message the page see who answers. A photo and a line help.')}<div class="bd">${steps()}<div class="pv"><div class="av" ${photo ? `style="background-image:url(${esc(photo)});color:transparent"` : ''}>${esc((me.name || 'Y')[0])}</div><label class="fl-btn sm" style="margin:0">${ic('📷')} Profile photo<input type="file" accept="image/*" data-photo hidden></label><span class="muted" data-pst></span></div><label>About you</label><textarea data-bio maxlength="500" rows="3" placeholder="Registered dietitian, mom of two, runs the GLP-1 360 plan…">${esc(f.bio)}</textarea><label>City</label><input data-city maxlength="60" value="${esc(f.city)}" placeholder="Denver, CO"><div class="row"><button class="fl-btn sm" data-back>Back</button><span class="sp"></span><button class="fl-btn sm" data-skip>Skip</button><button class="fl-btn p" data-next>Save and continue</button></div></div></div>`;
    else if (step === 2) w.innerHTML = `<div class="cl">${hero('Step 3 of 4', 'Review the page', 'The headline people see first. Make it yours.')}<div class="bd">${steps()}<label>Cover photo</label><div class="pv"><div class="av" style="border-radius:12px;width:96px;${cover ? `background-image:url(${esc(cover)})` : `background:${esc(color)}`}"></div><label class="fl-btn sm" style="margin:0">${ic('🖼️')} Upload cover<input type="file" accept="image/*" data-cover hidden></label><span class="muted" data-cst></span></div><label>Tagline</label><input data-tag maxlength="140" value="${esc(pg.tagline || '')}"><label>Main button (call to action)</label><div style="display:flex;gap:6px"><input data-ctal maxlength="40" value="${esc(cta.label || (pg.phone ? 'Call us' : 'Visit the website'))}" placeholder="Book a call" style="flex:1"><input data-ctah maxlength="200" value="${esc(cta.href || (pg.phone ? 'tel:' + String(pg.phone).replace(/[^0-9+]/g, '') : pg.website || ''))}" placeholder="https:// or tel:" style="flex:2"></div><label>Hours</label><input data-hours maxlength="120" value="${esc(pg.hours || '')}" placeholder="Mon-Fri 8am-6pm MT"><div class="row"><button class="fl-btn sm" data-back>Back</button><span class="sp"></span><button class="fl-btn sm" data-skip>Skip</button><button class="fl-btn p" data-next>Save and continue</button></div></div></div>`;
    else w.innerHTML = `<div class="cl">${hero('Step 4 of 4', 'Your VR home', 'Every page gets a spot in the 3D world. Yours is where visitors land when they tap “Visit in 3D”.')}<div class="bd">${steps()}<div class="vr">${ic('🕶️')} <b>How it works.</b> The same world runs in a browser (3D) and in a headset (VR). Your VR home is a place in it — a storefront, a corner of the plaza, a waterfall. Members can walk there, meet you, and tap through to this page. You can move it any time from ⚙ Manage → VR home spot.</div><label>Pick your spot</label><div class="spot">${VR_SPOTS.map(([id, n]) => `<button data-spot="${id}" class="${id === spot ? 'on' : ''}">${esc(n)}</button>`).join('')}</div><div class="row"><button class="fl-btn sm" data-back>Back</button><span class="sp"></span><button class="fl-btn sm" data-later>Later</button><a class="fl-btn sm" data-go3d href="/world/?to=${esc(spot)}">${ic('🧊')} See it in 3D</a><a class="fl-btn p" data-govr href="/world/?to=${esc(spot)}&vr=1">${ic('🕶️')} Go to my VR home</a></div></div></div>`;
    const q = (s) => w.querySelector(s); const nx = q('[data-next]'), bk = q('[data-back]'), sk = q('[data-skip]'), lt = q('[data-later]');
    if (bk) bk.onclick = () => { step--; draw(); }; if (sk) sk.onclick = () => { step++; draw(); }; if (lt) lt.onclick = close;
    const ph = q('[data-photo]'); if (ph) ph.onchange = async () => { try { q('[data-pst]').textContent = 'Uploading…'; photo = await upload(ph.files[0], 'avatars'); q('.pv .av').style.backgroundImage = 'url(' + photo + ')'; q('.pv .av').style.color = 'transparent'; q('[data-pst]').textContent = 'Looks good.'; } catch (e) { q('[data-pst]').textContent = 'Upload needs the live server.'; } };
    const cv = q('[data-cover]'); if (cv) cv.onchange = async () => { try { q('[data-cst]').textContent = 'Uploading…'; cover = await upload(cv.files[0], 'pages'); q('.pv .av').style.backgroundImage = 'url(' + cover + ')'; q('[data-cst]').textContent = 'Looks good.'; } catch (e) { q('[data-cst]').textContent = 'Upload needs the live server.'; } };
    w.querySelectorAll('[data-spot]').forEach(b => b.onclick = async () => { spot = b.dataset.spot; w.querySelectorAll('[data-spot]').forEach(z => z.classList.toggle('on', z === b)); q('[data-go3d]').href = '/world/?to=' + spot; q('[data-govr]').href = '/world/?to=' + spot + '&vr=1'; if (pg.id) await save('pages', { vr_home: spot }, { id: pg.id }); });
    if (q('[data-govr]')) { q('[data-govr]').onclick = mark; q('[data-go3d]').onclick = mark; }
    if (nx) nx.onclick = async () => {
      if (step === 1) { const flat = Object.assign({}, f, { bio: q('[data-bio]').value.trim().slice(0, 500), city: q('[data-city]').value.trim().slice(0, 60) }); if (photo) flat.avatar = photo; const home = Object.assign({}, me.home || {}, { flat }); await save('profiles', { home }, { id: me.id }); if (me.home) me.home.flat = flat; toast('Profile saved'); }
      if (step === 2) { const patch = { tagline: q('[data-tag]').value.trim().slice(0, 140), hours: q('[data-hours]').value.trim().slice(0, 120), extra: Object.assign({}, x, { cta: { label: q('[data-ctal]').value.trim().slice(0, 40), href: q('[data-ctah]').value.trim().slice(0, 200) } }) }; if (cover) patch.cover = cover; if (pg.id) await save('pages', patch, { id: pg.id }); Object.assign(pg, patch); toast('Page saved'); }
      step++; draw(); };
    setTimeout(() => { const b = q('[data-next], [data-govr]'); b && b.focus(); }, 40);
  };
  draw(); return { close };
}
/* which of my pages was just claimed and has not had its walk-through on this device? */
export function claimDue(pages, me, claimedNow) { try { const day = 86400000; return (pages || []).find(p => p.slug && !localStorage.getItem('aou_claimed_' + p.slug) && me && p.owner_id !== me.id && (claimedNow > 0 || (p.claimed_at && Date.now() - new Date(p.claimed_at).getTime() < day))) || null; } catch (e) { return null; } }
