/* ============================================================
   ZACH'S TRUCK + THE HOUSE, v2.9
   - The truck, for real: electric, cherry-red metallic with clear coat, chrome grille with a light bar, headlights
     with beams, two fog lights below, a roof rack of four more, real glass, side mirrors, lifted on coilovers,
     a hydraulic lift (body up/down), a scissor lift that takes the cab 200 ft up for the view, a working dash
     (mph, battery, odometer), a radio that plays allofus stations, and a tilt bed that only unloads the jet ski
     when you are parked by water. You DRIVE it: head and shoulders behind the glass, nothing poking through.
   - The house: a west wing (different stone, copper roof, windows, a balcony front and side) so it is not a box,
     paint modes you tap through at the wall (stone, ocean, sunset, forest, midnight, rainbow that cycles)
   - The banquet hall: a long table inside, loaded with food, decorated for the 49th. Sit down → the Birthday chat room.
   - The feed board: every claimed home in Unity Heights gets one out front, like Zach's.
   ============================================================ */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { M, glow, box, cyl, sph, textPlane } from './aou-kit.js';
import { terrainY, addFlat } from './aou-terrain.js';
const T = THREE; const MOB = isMobile();
export function buildTruck(app, W, X, Z) {
  const S = app.scene; const toast = (m, ms) => app.toast(m, ms); const gy = (x, z) => terrainY(x, z);
  const TX = X - 34, TZ = Z + 30; const truck = new T.Group(); truck.position.set(TX, gy(TX, TZ), TZ); truck.rotation.y = 0.4; S.add(truck); const body = new T.Group(); body.position.y = 0.78; truck.add(body); truck.userData.body = body;
  const paint = new T.MeshPhysicalMaterial({ color: 0xc8001a, metalness: 0.65, roughness: 0.18, clearcoat: 1, clearcoatRoughness: 0.08 }); const chrome = M(0xf0f4f8, { metalness: 1, roughness: 0.06 }); const dark = M(0x111318, { roughness: 0.55 }); const rubber = M(0x16181c, { roughness: 0.95 }); const glass = new T.MeshPhysicalMaterial({ color: 0x8fb8d8, metalness: 0.2, roughness: 0.03, transparent: true, opacity: 0.38, side: T.DoubleSide });
  // frame, cab, bed
  box(2.3, 0.4, 5.8, dark, 0, 0.35, 0, body); const hood = box(2.5, 0.62, 2.0, paint, 0, 1.05, 1.9, body); const cabLo = box(2.5, 0.9, 2.1, paint, 0, 1.2, 0.1, body); const cab = box(2.3, 0.95, 1.9, dark, 0, 2.05, 0.1, body); const ws = new T.Mesh(new T.PlaneGeometry(2.2, 0.9), glass); ws.position.set(0, 2.05, 1.06); ws.rotation.x = -0.35; body.add(ws); const rw = new T.Mesh(new T.PlaneGeometry(2.2, 0.8), glass); rw.position.set(0, 2.05, -0.86); rw.rotation.x = 0.25; rw.rotation.y = Math.PI; body.add(rw); for (const sx of [-1, 1]) { const sw = new T.Mesh(new T.PlaneGeometry(1.7, 0.8), glass); sw.position.set(sx * 1.16, 2.05, 0.1); sw.rotation.y = sx * Math.PI / 2; body.add(sw); const mir = box(0.08, 0.22, 0.34, paint, sx * 1.42, 1.95, 0.75, body); const mg = new T.Mesh(new T.PlaneGeometry(0.3, 0.2), chrome); mg.position.set(sx * 1.47, 1.95, 0.75); mg.rotation.y = sx * Math.PI / 2 + Math.PI; body.add(mg); cyl(0.03, 0.03, 0.3, chrome, sx * 1.3, 1.95, 0.75, body, 6).rotation.z = Math.PI / 2; } box(2.5, 0.08, 1.95, paint, 0, 2.55, 0.1, body);
  box(2.5, 0.7, 2.7, paint, 0, 1.0, -1.65, body); for (const sx of [-1.12, 1.12]) box(0.26, 0.55, 2.7, paint, sx, 1.3, -1.65, body); const tailgate = box(2.26, 0.55, 0.1, paint, 0, 1.3, -3.0, body); const bedFloor = box(2.0, 0.06, 2.6, dark, 0, 0.72, -1.65, body);
  // grille + light bar + bumpers + fenders
  const grille = box(1.7, 0.5, 0.12, chrome, 0, 1.0, 2.92, body); for (let i = 0; i < 6; i++) box(1.6, 0.03, 0.14, dark, 0, 0.8 + i * 0.08, 2.93, body); const lightbar = box(1.8, 0.06, 0.1, glow(0xd8f3ff, 2.5), 0, 1.36, 2.96, body); box(2.7, 0.22, 0.3, chrome, 0, 0.55, 2.95, body); box(2.7, 0.22, 0.3, chrome, 0, 0.55, -3.1, body); for (const sx of [-1, 1]) { for (const z of [1.85, -1.85]) { const fender = new T.Mesh(new T.TorusGeometry(0.78, 0.16, 8, 20, Math.PI), paint); fender.rotation.y = Math.PI / 2; fender.position.set(sx * 1.35, 0.52, z); body.add(fender); } }
  // lights: headlights + fog + roof rack with 4 + beams
  const lights = []; const beams = []; const mkLight = (x, y, z, r, col, px, py, pz) => { const l = sph(r, glow(col, 2.2), x, y, z, body, 10); lights.push(l); const beam = new T.Mesh(new T.ConeGeometry(0.9, 9, 12, 1, true), new T.MeshBasicMaterial({ color: col, transparent: true, opacity: 0.12, side: T.DoubleSide, depthWrite: false })); beam.position.set(x, y, z + 4.6); beam.rotation.x = -Math.PI / 2; beam.visible = false; body.add(beam); beams.push(beam); return l; }; for (const sx of [-0.85, 0.85]) { mkLight(sx, 1.1, 2.96, 0.17, 0xfff6d5); mkLight(sx * 0.9, 0.62, 2.98, 0.11, 0xfff0a0); } box(2.0, 0.07, 0.4, chrome, 0, 2.62, 0.7, body); for (let i = 0; i < 4; i++) { cyl(0.09, 0.09, 0.22, dark, -0.75 + i * 0.5, 2.74, 0.7, body, 8).rotation.x = Math.PI / 2; mkLight(-0.75 + i * 0.5, 2.74, 0.85, 0.09, 0xffffff); } const tails = []; for (const sx of [-1, 1]) tails.push(box(0.3, 0.22, 0.06, glow(0xff2f4f, 1.6), sx * 1.0, 1.15, -3.06, body)); const lightsOn = { v: false };
  // wheels: big tires with tread, chrome spokes that spin, coilovers
  const wheels = []; for (const [x, z] of [[-1.42, 1.85], [1.42, 1.85], [-1.42, -1.85], [1.42, -1.85]]) { const w = new T.Group(); w.position.set(x, 0, z); body.add(w); const tire = new T.Mesh(new T.TorusGeometry(0.62, 0.3, 12, 28), rubber); tire.rotation.y = Math.PI / 2; w.add(tire); for (let k = 0; k < 18; k++) { const lug = box(0.34, 0.06, 0.14, rubber, 0, Math.cos(k / 18 * 6.283) * 0.9, Math.sin(k / 18 * 6.283) * 0.9, w); lug.rotation.x = -k / 18 * 6.283; } const rim = new T.Mesh(new T.CylinderGeometry(0.4, 0.4, 0.34, 20), chrome); rim.rotation.z = Math.PI / 2; w.add(rim); for (let k = 0; k < 6; k++) { const sp = box(0.36, 0.72, 0.07, chrome, 0, 0, 0, w); sp.rotation.x = k * Math.PI / 6; } const cap = sph(0.09, glow(0xd1001c, 1), 0, 0, 0, w, 8); wheels.push(w); const spring = new T.Mesh(new T.TorusKnotGeometry(0.16, 0.045, 48, 8, 1, 8), chrome); spring.position.set(x * 0.72, 0.5, z); spring.scale.set(1, 1.7, 1); body.add(spring); const shock = cyl(0.05, 0.05, 0.9, M(0xffd23f, { metalness: 0.8 }), x * 0.72, 0.5, z + 0.25, body, 8); }
  // jet ski in the bed (from the jamoke module) + bed tilt
  const bed = new T.Group(); bed.position.set(0, 1.0, -0.3); body.add(bed); bedFloor.position.set(0, -0.28, -1.35); bed.add(bedFloor); const ski = W.mkJetski ? W.mkJetski(0x38f0ff) : null; if (ski) { ski.position.set(0, 0.0, -1.3); ski.scale.setScalar(0.85); bed.add(ski); }
  // dash: a readout above the hood (visible from the seat), radio
  const dash = { set visible(v) { if (!v && ST.dashS) { body.remove(ST.dashS); ST.dashS = null; } } }; const RADIO = [['off', null], ['🎵 Calm', 'V1RPi2MYptM'], ['🎶 12-hr music', 'LFASWuckB1c'], ['🌲 Nature', 'ipf7ifVSeDU']]; let radio = 0;
  const sg = makeSprite("🛻 ZACH'S ELECTRIC 4x4 · drive · lights · lift · scissor sky mode", { scale: 4.4, accent: '#ff4f79' }); sg.position.set(0, 4.8, 0); truck.add(sg); app.addObstacle && app.addObstacle(TX, TZ, 3.2);
  const ST = { lift: 0, liftOn: false, sciss: 0, scissOn: false, tilt: 0, tiltOn: false, odo: 0, batt: 100, driving: false, last: null }; let scissor = null;
  const nearWater = () => { const p = truck.position; for (let a = 0; a < 6.283; a += 0.5) for (const r of [6, 12, 20]) { if (app._waterAt && app._waterAt(p.x + Math.cos(a) * r, p.z + Math.sin(a) * r) !== null) return true; } return false; };
  const controls = () => { const html = `<p>Electric. No tailpipe, no apologies. Everything here is live.</p><div class="aou-chips"><button class="lt-btn holo" data-tk="drive">🛻 ${ST.driving ? 'Hop out' : 'Drive it'}</button><button class="lt-btn" data-tk="lights">💡 Lights ${lightsOn.v ? 'off' : 'on'}</button><button class="lt-btn" data-tk="lift">🛠️ Hydraulic lift ${ST.liftOn ? 'down' : 'up'}</button><button class="lt-btn" data-tk="sciss">🪜 Scissor sky mode ${ST.scissOn ? 'down' : '(200 ft)'}</button><button class="lt-btn" data-tk="tilt">🛻 Tilt the bed ${ST.tiltOn ? 'back' : '· unload jet ski'}</button><button class="lt-btn" data-tk="radio">📻 Radio: ${RADIO[radio][0]}</button><button class="lt-btn" data-tk="paint">🎨 Repaint</button></div><p class="aou-note">The jet ski only unloads when you are parked by water. Scissor mode is a parked view; come down to drive.</p>`; const m = W.api && W.api.modal ? W.api.modal("🛻 Zach's 4x4", html) : null; (m || document).querySelectorAll('[data-tk]').forEach(b => b.onclick = () => { const k = b.dataset.tk; W.api && W.api.closeModal && W.api.closeModal(); if (k === 'drive') drive(); if (k === 'lights') { lightsOn.v = !lightsOn.v; beams.forEach(bm => bm.visible = lightsOn.v); lights.forEach(l => l.material.emissiveIntensity = lightsOn.v ? 4 : 1.2); lightbar.material.emissiveIntensity = lightsOn.v ? 5 : 1.5; toast(lightsOn.v ? '💡 All lights on. The neighbors can see you from space.' : '💡 Lights off.', 2000); } if (k === 'lift') { ST.liftOn = !ST.liftOn; toast(ST.liftOn ? '🛠️ Hydraulics up. Monster stance.' : '🛠️ Hydraulics down.', 1800); } if (k === 'sciss') sciss(); if (k === 'tilt') { if (!nearWater() && !ST.tiltOn) { toast('🌊 Not here. Park within a few car-lengths of water first, then tilt. Lake Dillon is behind the house; the pool is out front.', 4500); return; } ST.tiltOn = !ST.tiltOn; toast(ST.tiltOn ? '🛻 Bed up. Jet ski sliding into the water.' : '🛻 Bed down.', 2200); } if (k === 'radio') { radio = (radio + 1) % RADIO.length; if (W.jukebox && W.jukebox.play) { if (RADIO[radio][1]) W.jukebox.play(RADIO[radio][1]); else W.jukebox.stop && W.jukebox.stop(); } toast('📻 ' + RADIO[radio][0], 1500); } if (k === 'paint') { const c = [0xc8001a, 0x0a84ff, 0x111318, 0xffd23f, 0x30d158, 0xbf5af2][Math.floor(Math.random() * 6)]; paint.color.setHex(c); toast('🎨 Fresh wrap.', 1200); } }); };
  const drive = () => { if (app.vehicle || app.ride) { if (app.vehicle) { const it = (app.interactables || []).find(i => /Hop out/.test(i.label || '')); it && it.fn(app); } return; } if (ST.scissOn) { toast('🪜 Come down first.', 1500); return; } ST.driving = true; dash.visible = true; app.player.position.set(truck.position.x, gy(truck.position.x, truck.position.z), truck.position.z); app.driveCart(truck, { speed: 3.4, seatY: 2.35, roofY: 3.35, clipY: 2.65, label: '🛻 Electric torque. Drag to steer, joystick to go, TURBO for a shove. Tap 🚪 to hop out.', park: (v) => { v.m.position.y = gy(v.m.position.x, v.m.position.z); ST.driving = false; dash.visible = false; } }); };
  const sciss = () => { if (ST.driving) { toast('🪜 Hop out of the cab first, then scissor.', 2000); return; } if (!scissor) { scissor = new T.Group(); truck.add(scissor); scissor.userData.legs = []; for (let i = 0; i < 2; i++) for (const sx of [-1, 1]) { const l1 = box(0.12, 1, 0.12, M(0xffd23f, { metalness: 0.7, roughness: 0.3 }), sx * 0.9, 0, 0, scissor); const l2 = box(0.12, 1, 0.12, M(0xffd23f, { metalness: 0.7, roughness: 0.3 }), sx * 0.9, 0, 0, scissor); scissor.userData.legs.push([l1, l2, i]); } } ST.scissOn = !ST.scissOn; if (ST.scissOn) { const t0 = app.t; app.ride = { pos: () => { const k = Math.min(1, (app.t - t0) / 9); const e = k < 0.5 ? 2 * k * k : 1 - Math.pow(-2 * k + 2, 2) / 2; ST.sciss = e; const y = truck.position.y + 0.78 + e * 60; body.position.y = 0.78 + e * 60; return new T.Vector3(truck.position.x, y + 2.6, truck.position.z); }, yaw: app.yaw, stand: true, until: 1e12 }; app.targetDist = Math.max(app.targetDist, 8); app.pitch = -0.1; toast('🪜 Scissor up. 200 feet. Drag to look. Tap the truck sign to come down.', 4500); app.buzz && app.buzz(40); } else { const t0 = app.t, from = ST.sciss; app.ride = { pos: () => { const k = Math.min(1, (app.t - t0) / 7); const e = from * (1 - (k < 0.5 ? 2 * k * k : 1 - Math.pow(-2 * k + 2, 2) / 2)); ST.sciss = e; body.position.y = 0.78 + e * 60; if (k >= 1) { app.ride = null; app.seatClear && app.seatClear(); app.player.position.set(truck.position.x + 2.5, gy(truck.position.x + 2.5, truck.position.z), truck.position.z); } return new T.Vector3(truck.position.x, truck.position.y + body.position.y + 2.6, truck.position.z); }, yaw: app.yaw, stand: true, until: 1e12 }; toast('🪜 Coming down.', 1800); } };
  app.addInteractable && app.addInteractable(TX, TZ + 4, 4.2, "🛻 Zach's 4x4: drive · lights · lift · scissor · bed", controls); app.addHotspot && app.addHotspot(body, { fn: controls });
  app.addPlace && app.addPlace({ id: 'truck', name: "🛻 Zach's electric 4x4", icon: '🛻', x: TX, z: TZ + 5, cat: 'Fun', keys: 'truck drive 4x4 lift scissor jet ski electric', say: 'Drive it, light it up, lift it, or scissor it 200 feet into the sky.' });
  app.onUpdate((dt, t) => { const P = app.player.position; const d = Math.hypot(P.x - truck.position.x, P.z - truck.position.z); if (d > 120 && !ST.driving && !ST.scissOn) return; const vel = app.vehicle && app.vehicle.m === truck ? (ST.last ? ST.last.distanceTo(truck.position) / Math.max(dt, 0.001) : 0) : 0; ST.last = (ST.last || new T.Vector3()).copy(truck.position); const spin = ST.driving ? vel * dt / 0.62 : 0; wheels.forEach(w => { w.rotation.x += spin; }); if (ST.driving) { ST.odo += vel * dt / 1609; ST.batt = Math.max(5, ST.batt - vel * dt * 0.004); if (Math.floor(t * 4) !== Math.floor((t - dt) * 4)) { if (ST.dashS) { body.remove(ST.dashS); ST.dashS.material.map && ST.dashS.material.map.dispose(); ST.dashS.material.dispose(); } ST.dashS = makeSprite(`${Math.round(vel * 2.237)} mph · 🔋 ${Math.round(ST.batt)}% · odo ${ST.odo.toFixed(2)} mi · 📻 ${RADIO[radio][0]}`, { scale: 2.4, accent: '#38f0ff', bg: 'rgba(5,12,34,0.8)' }); ST.dashS.position.set(0, 3.4, 0.5); body.add(ST.dashS); } tails.forEach(tl => tl.material.emissiveIntensity = vel < 0.5 ? 3 : 1.4); }
    const wantLift = ST.liftOn ? 0.45 : 0; ST.lift += (wantLift - ST.lift) * Math.min(1, dt * 2); body.children.forEach(c => { if (!wheels.includes(c) && c !== scissor) c.position.y = (c.userData.y0 ?? (c.userData.y0 = c.position.y)) + ST.lift; }); if (!ST.scissOn && ST.sciss === 0) body.position.y = 0.78 + Math.sin(t * 1.3) * 0.015;
    const wantTilt = ST.tiltOn ? 0.6 : 0; ST.tilt += (wantTilt - ST.tilt) * Math.min(1, dt * 1.8); bed.rotation.x = ST.tilt; tailgate.rotation.x = ST.tilt * 1.6; if (ski) { ski.position.z = -1.3 - ST.tilt * 4.2; ski.position.y = -ST.tilt * 2.2; if (ST.tilt > 0.55 && !ST.skiOut) { ST.skiOut = true; toast('🚤 Jet ski is in the water. Tap it to ride.', 3000); const wx = truck.position.x - Math.sin(truck.rotation.y) * 7, wz = truck.position.z - Math.cos(truck.rotation.y) * 7; const free = W.mkJetski(0x38f0ff); free.position.set(wx, (app._waterAt && app._waterAt(wx, wz)) ?? gy(wx, wz), wz); S.add(free); app.addInteractable && app.addInteractable(wx, wz, 2.4, '🚤 Ride the truck jet ski', () => W.rideJetski && W.rideJetski(free)); } if (ST.tilt < 0.1) ST.skiOut = false; }
    if (scissor) { scissor.visible = ST.sciss > 0.001; const h = ST.sciss * 60; scissor.userData.legs.forEach(([l1, l2, i]) => { const segH = h / 4 + 0.6; const w = 2.4; const ang = Math.atan2(segH, w); const len = Math.hypot(segH, w); l1.scale.y = len; l2.scale.y = len; l1.position.set(l1.position.x, 0.4 + (i * 2 + 0.5) * segH, 0); l2.position.copy(l1.position); l1.rotation.x = Math.PI / 2 - ang; l2.rotation.x = -(Math.PI / 2 - ang); }); }
  });
  return { truck, drive, controls };
}

/* ---------------- the west wing + paint modes ---------------- */
export function buildWing(app, W, X, Z) {
  const S = app.scene; const y0 = terrainY(X, Z) + 0.05; const G = new T.Group(); G.position.set(X, y0, Z); S.add(G); const toast = (m, ms) => app.toast(m, ms);
  const wallM = new T.MeshStandardMaterial({ color: 0xb8a58e, roughness: 0.85 }); const stoneTex = (() => { const c = document.createElement('canvas'); c.width = c.height = 256; const g = c.getContext('2d'); g.fillStyle = '#c9b89d'; g.fillRect(0, 0, 256, 256); for (let i = 0; i < 90; i++) { g.fillStyle = `hsl(${30 + Math.random() * 15},${18 + Math.random() * 20}%,${58 + Math.random() * 18}%)`; const x = Math.random() * 256, y = Math.floor(Math.random() * 8) * 32, w = 30 + Math.random() * 40; g.fillRect(x, y + 2, w, 28); } const t = new T.CanvasTexture(c); t.wrapS = t.wrapT = T.RepeatWrapping; t.repeat.set(3, 2); return t; })(); wallM.map = stoneTex; const copper = M(0x8d5a3a, { metalness: 0.7, roughness: 0.35 }); const glass = new T.MeshPhysicalMaterial({ color: 0xbfe3ff, transparent: true, opacity: 0.4, roughness: 0.05 });
  // the wing sits on the north side (left, from the street), stepped back, two stories, round tower corner, balcony front + side
  const WX = -6, WZ = -24; box(16, 8.4, 11, wallM, WX, 4.2, WZ, G); const tower = cyl(4.2, 4.2, 10.5, wallM, WX - 8, 5.25, WZ - 3, G, 20); const cone = new T.Mesh(new T.ConeGeometry(4.6, 3.6, 20), copper); cone.position.set(WX - 8, 12.3, WZ - 3); G.add(cone); const roof = new T.Mesh(new T.BoxGeometry(17, 0.5, 12), copper); roof.position.set(WX, 8.65, WZ); G.add(roof); const gable = new T.Mesh(new T.CylinderGeometry(0.1, 6.2, 2.4, 4, 1), copper); gable.rotation.y = Math.PI / 4; gable.scale.set(1.45, 1, 1); gable.position.set(WX, 10, WZ); G.add(gable);
  for (const lvl of [2.4, 6.4]) { for (let i = -2; i <= 2; i++) { box(1.5, 1.7, 0.12, glass, WX + i * 3, lvl, WZ + 5.56, G); box(1.7, 1.9, 0.08, M(0xf4f1ea), WX + i * 3, lvl, WZ + 5.52, G).position.z -= 0.001; box(1.5, 1.7, 0.12, glass, WX - 8.1, lvl, WZ - 3 + (i % 2) * 2.2, G).rotation.y = Math.PI / 2; } }
  const bal = (bx, by, bz, w, d, rot) => { const g = new T.Group(); g.position.set(bx, by, bz); g.rotation.y = rot; G.add(g); box(w, 0.25, d, M(0xe9e2d4), 0, 0, 0, g); for (let i = 0; i <= Math.round(w / 0.7); i++) cyl(0.04, 0.04, 1.0, M(0xdfe6f2, { metalness: 0.8 }), -w / 2 + i * 0.7, 0.55, d / 2 - 0.1, g, 6); box(w, 0.06, 0.08, M(0xdfe6f2, { metalness: 0.8 }), 0, 1.05, d / 2 - 0.1, g); const glow2 = box(w, 0.05, 0.05, glow(0x38f0ff, 1.2), 0, 0.18, d / 2 - 0.02, g); return g; }; bal(WX, 4.5, WZ + 6.6, 9, 2.2, 0); bal(WX - 9.3, 4.5, WZ - 3, 6, 2.2, Math.PI / 2); bal(WX - 8, 9.9, WZ - 3, 0.1, 0.1, 0);
  for (let i = 0; i < 5; i++) { const l = sph(0.12, glow(0xfff0b0, 1.6), WX - 7 + i * 3.5, 7.6, WZ + 5.9, G, 8); }
  addFlat({ x1: X + WX - 8, x2: X + WX + 8, z1: Z + WZ - 5.5, z2: Z + WZ + 5.5, y: y0 + 0.3, soft: 3 }); app.addObstacle && app.addObstacle(X + WX, Z + WZ, 8); app.addObstacle && app.addObstacle(X + WX - 8, Z + WZ - 3, 4.2);
  // paint modes: tap the wall
  const MODES = [['stone', null], ['ocean', 0x5aa9e6], ['sunset', 0xff8a5b], ['forest', 0x6fae7a], ['midnight', 0x3b4a7a], ['rainbow', 'rainbow']]; let mode = 0; const paintables = []; G.traverse(o => { if (o.isMesh && o.material === wallM) paintables.push(o); }); const base = wallM.color.clone(); const mansion = W.estate && W.estate.mansion && W.estate.mansion.group; const mats = new Set(); if (mansion) mansion.traverse(o => { if (o.isMesh && o.material && o.material.color && !o.material.transparent && o.geometry && o.geometry.type === 'BoxGeometry' && o.geometry.parameters.height > 2.5 && o.geometry.parameters.width > 3) mats.add(o.material); }); mats.forEach(m => m.userData.base = m.color.clone());
  const applyMode = (t) => { const [n, c] = MODES[mode]; const col = c === 'rainbow' ? new T.Color().setHSL((t * 0.08) % 1, 0.85, 0.6) : c === null ? null : new T.Color(c); wallM.color.copy(col || base); mats.forEach(m => m.color.copy(col ? col.clone().lerp(m.userData.base, 0.35) : m.userData.base)); };
  const cycle = () => { mode = (mode + 1) % MODES.length; toast('🎨 House: ' + MODES[mode][0] + (MODES[mode][1] === 'rainbow' ? ' · cycling' : ''), 1800); applyMode(app.t); app.celebrate && app.celebrate('🎨'); };
  app.addInteractable && app.addInteractable(X + WX, Z + WZ + 8, 4.5, '🎨 Tap the wall: change the house color (rainbow mode too)', cycle); app.addHotspot && app.addHotspot(tower, { fn: cycle });
  const sgn = makeSprite('🏰 THE WEST WING · balconies · tap the wall to repaint the house', { scale: 4.2, accent: '#ffd23f' }); sgn.position.set(WX, 14.5, WZ); G.add(sgn);
  app.onUpdate((dt, t) => { if (MODES[mode][1] === 'rainbow') applyMode(t); });
}

/* ---------------- the banquet hall ---------------- */
export function buildBanquet(app, W, X, Z) {
  const S = app.scene; const y0 = terrainY(X, Z) + 0.05 + 0.24; const G = new T.Group(); G.position.set(X, y0, Z); S.add(G); const toast = (m, ms) => app.toast(m, ms);
  const BX = -4, BZ = 0; const table = box(14, 0.12, 2.6, M(0x5b3a1e, { roughness: 0.4, metalness: 0.1 }), BX, 0.9, BZ, G); for (const [x, z] of [[-6, -1], [6, -1], [-6, 1], [6, 1]]) cyl(0.08, 0.1, 0.9, M(0x3e2a14), BX + x, 0.45, BZ + z, G, 8); const cloth = box(14.2, 0.02, 1.2, M(0xffffff), BX, 0.97, BZ, G); for (let i = 0; i < 14; i++) { const sx = i % 2 ? 1 : -1; const ch = new T.Group(); ch.position.set(BX - 6.5 + Math.floor(i / 2) * 2.1, 0, BZ + sx * 2.0); G.add(ch); box(0.5, 0.06, 0.5, M(0x2f6bff), 0, 0.5, 0, ch); box(0.5, 0.6, 0.06, M(0x2f6bff), 0, 0.8, -sx * 0.22, ch); for (const [a, b] of [[-0.2, -0.2], [0.2, -0.2], [-0.2, 0.2], [0.2, 0.2]]) cyl(0.025, 0.025, 0.5, M(0xdfe6f2, { metalness: 0.8 }), a, 0.25, b, ch, 6); }
  // the feast: cake, turkey, pizzas, fruit, drinks, candles
  const food = (x, z, mk) => { const g = new T.Group(); g.position.set(BX + x, 0.98, BZ + z); G.add(g); mk(g); }; food(0, 0, g => { cyl(0.55, 0.6, 0.35, M(0xffe0f0), 0, 0.18, 0, g, 24); cyl(0.4, 0.45, 0.3, M(0xffb7d5), 0, 0.5, 0, g, 24); cyl(0.26, 0.3, 0.26, M(0xffe0f0), 0, 0.78, 0, g, 24); for (let i = 0; i < 7; i++) { const a = i / 7 * 6.283; cyl(0.015, 0.015, 0.22, M(0xffffff), Math.cos(a) * 0.18, 1.0, Math.sin(a) * 0.18, g, 5); sph(0.03, glow(0xffb347, 2.5), Math.cos(a) * 0.18, 1.13, Math.sin(a) * 0.18, g, 6); } const n = makeSprite('🎂 49', { scale: 1.2, accent: '#ff4fd8' }); n.position.y = 1.5; g.add(n); }); food(-3.5, 0, g => { const t = sph(0.42, M(0xc77a3a, { roughness: 0.6 }), 0, 0.3, 0, g, 12); t.scale.set(1.2, 0.8, 1); cyl(0.55, 0.6, 0.04, M(0xffffff), 0, 0.02, 0, g, 24); for (const sx of [-1, 1]) cyl(0.03, 0.05, 0.3, M(0xd9a441), sx * 0.3, 0.55, -0.2, g, 5).rotation.z = sx * 0.6; }); food(3.5, 0.2, g => { cyl(0.5, 0.5, 0.05, M(0xf2c14e), 0, 0.03, 0, g, 24); cyl(0.42, 0.42, 0.03, M(0xd9262a), 0, 0.06, 0, g, 24); for (let i = 0; i < 9; i++) cyl(0.06, 0.06, 0.02, M(0xa0202a), Math.cos(i) * 0.3, 0.085, Math.sin(i * 2) * 0.3, g, 8); }); food(-1.8, 0.6, g => { for (let i = 0; i < 8; i++) sph(0.08, M([0xff4f79, 0x7cff6b, 0xffd23f, 0xff8a3d][i % 4]), (Math.random() - 0.5) * 0.5, 0.1 + (i % 3) * 0.07, (Math.random() - 0.5) * 0.4, g, 8); cyl(0.38, 0.3, 0.14, M(0x8a5a2b), 0, 0.02, 0, g, 16); }); food(1.8, -0.6, g => { for (let i = 0; i < 6; i++) { cyl(0.06, 0.06, 0.26, new T.MeshPhysicalMaterial({ color: 0xbfe3ff, transparent: true, opacity: 0.4 }), -0.4 + i * 0.16, 0.13, 0, g, 8); cyl(0.05, 0.05, 0.14, M([0xffd23f, 0xff4f79, 0x7cff6b][i % 3]), -0.4 + i * 0.16, 0.08, 0, g, 8); } }); food(5.5, -0.3, g => { for (let i = 0; i < 5; i++) box(0.3, 0.1, 0.5, M(0xc9823a), -0.5 + i * 0.25, 0.05, 0, g); }); food(-5.5, 0.3, g => { for (let i = 0; i < 10; i++) sph(0.05, M(0xffe08a), (Math.random() - 0.5) * 0.6, 0.06, (Math.random() - 0.5) * 0.4, g, 6); cyl(0.4, 0.3, 0.1, M(0xffffff), 0, 0.02, 0, g, 16); });
  // decor: streamers across the ceiling, banner, balloons at the corners
  for (let i = 0; i < 8; i++) { const st = box(0.06, 0.02, 7, M([0xff4f79, 0xffd23f, 0x38f0ff, 0xb388ff][i % 4]), BX - 7 + i * 2, 3.6, BZ, G); st.rotation.x = 0.08; } const ban = textPlane(['🎉 HAPPY 49TH ZACH 🎉', 'the banquet · pull up a chair'], 8, 2, { bg: '#7a1fa8', fg: '#fff', accent: '#ffd23f' }); ban.position.set(BX, 3.2, BZ - 3.6); ban.material.side = T.DoubleSide; G.add(ban); for (const [x, z] of [[-7.5, -3], [7.5, -3], [-7.5, 3], [7.5, 3]]) for (let k = 0; k < 5; k++) sph(0.3, new T.MeshStandardMaterial({ color: [0xff4f79, 0xffd23f, 0x7cff6b, 0x38f0ff, 0xb388ff][k], metalness: 0.3, roughness: 0.3, emissive: [0xff4f79, 0xffd23f, 0x7cff6b, 0x38f0ff, 0xb388ff][k], emissiveIntensity: 0.3 }), BX + x + Math.cos(k) * 0.3, 2.2 + k * 0.3, BZ + z + Math.sin(k) * 0.3, G, 10);
  const sit = () => { if (W.api && W.api.openRoom) { W.api.openRoom('birthday-party'); } else if (W.api && W.api.openChat) W.api.openChat('chats'); toast('🍽️ Pull up a chair. Everyone at this table is in the Birthday room.', 3000); }; app.addInteractable && app.addInteractable(X + BX, Z + BZ + 3.2, 5, '🍽️ The banquet: sit down → Birthday chat room', sit); app.addHotspot && app.addHotspot(table, { fn: sit }); app.addObstacle && app.addObstacle(X + BX, Z + BZ, 1.3);
  const sgn = makeSprite('🍽️ THE BANQUET · sit down for the birthday room', { scale: 3.6, accent: '#ffd23f' }); sgn.position.set(BX, 2.4, BZ + 3.4); G.add(sgn);
  app.addPlace && app.addPlace({ id: 'banquet', name: "🍽️ Zach's banquet hall · birthday room", icon: '🍽️', x: X + BX, z: Z + BZ + 4, cat: 'Homes', keys: 'banquet dinner table party birthday room chat food', say: 'The long table inside No. 1 Unity Road. Sit and the Birthday chat room opens.' });
}
