/* ============================================================
   UNITY HEIGHTS (v2.3) · 15 solar-panel streets that start at Zach's
   house and curve south-east through the hills, with kindness signs,
   solar lamps, and 30 claimable model homes, each a different shape,
   size, material and color, each with a floating neon LIFEboard over
   the door and a finished futuristic interior. Claim one, then make it
   yours in the Home builder.
   ============================================================ */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { M, glow, box, cyl, sph, textPlane } from './aou-kit.js';
import { terrainY, addFlat } from './aou-terrain.js';
import { TEX, buildCustomHome } from './aou-build.js';
import { makeFlower } from './aou-garden.js';
const T = THREE; const MOB = isMobile();
const SAY = ['Kindness is the best.', 'A smile can change someone\'s day.', 'You are enough. Right now.', 'Find the good.', 'Be the light.', 'Slow down. Look up.', 'Say the kind thing out loud.', 'We all belong here.', 'Help someone today.', 'Peace and love, man. ✌️', 'Your story matters.', 'Leave people better than you found them.', 'Breathe. You got this.', 'Call your mom.', 'Be the peace you seek.'];
const STREETS = ['Unity Boulevard', 'Peace Lane', 'Kindness Way', 'Stephanie Drive', 'Sunrise Loop', 'Harmony Court', 'Hope Street', 'Good Neighbor Road', 'Lantern Lane', 'Solar Ridge', 'Smile Circle', 'Gratitude Way', 'Lightkeeper Lane', 'Together Terrace', 'Horizon Row'];
const SPECS = [
  { shape: 'L', w: 14, d: 12, floors: 2, wall: 'cedar', roof: 'flat', roofMat: 'solar', accent: '#38f0ff', pool: 'none', trees: 2 }, { shape: 'rect', w: 12, d: 10, floors: 3, wall: 'stucco', wallColor: '#f4e8d6', roof: 'hip', roofMat: 'slate', accent: '#ff4fd8', pool: 'rect', trees: 1 }, { shape: 'U', w: 16, d: 12, floors: 1, wall: 'stone', roof: 'flat', roofMat: 'green', accent: '#7cff6b', pool: 'round', trees: 3 }, { shape: 'court', w: 18, d: 14, floors: 2, wall: 'brick', roof: 'gable', roofMat: 'copper', accent: '#ffd23f', pool: 'none', trees: 2 }, { shape: 'rect', w: 9, d: 9, floors: 2, wall: 'glass', roof: 'flat', roofMat: 'solar', accent: '#b388ff', pool: 'none', trees: 1 }, { shape: 'L', w: 13, d: 11, floors: 1, wall: 'hemp', wallColor: '#dfe8d4', roof: 'shed', roofMat: 'cedar', accent: '#ff8a3d', pool: 'rect', trees: 2 },
  { shape: 'rect', w: 11, d: 12, floors: 3, wall: 'concrete', roof: 'flat', roofMat: 'green', accent: '#38f0ff', pool: 'none', trees: 1 }, { shape: 'U', w: 15, d: 13, floors: 2, wall: 'cedar', roof: 'hip', roofMat: 'slate', accent: '#ffd23f', pool: 'round', trees: 2 }, { shape: 'rect', w: 10, d: 14, floors: 2, wall: 'metal', roof: 'gable', roofMat: 'aluminum', accent: '#ff4fd8', pool: 'none', trees: 2 }, { shape: 'L', w: 15, d: 10, floors: 2, wall: 'stucco', wallColor: '#c9b7e8', roof: 'flat', roofMat: 'solar', accent: '#7cff6b', pool: 'rect', trees: 1 }, { shape: 'court', w: 16, d: 16, floors: 1, wall: 'stone', roof: 'flat', roofMat: 'copper', accent: '#b388ff', pool: 'round', trees: 3 }, { shape: 'rect', w: 8, d: 11, floors: 3, wall: 'brick', roof: 'shed', roofMat: 'solar', accent: '#ff8a3d', pool: 'none', trees: 1 },
  { shape: 'L', w: 12, d: 13, floors: 2, wall: 'glass', roof: 'hip', roofMat: 'green', accent: '#38f0ff', pool: 'rect', trees: 2 }, { shape: 'rect', w: 13, d: 9, floors: 1, wall: 'hemp', wallColor: '#ffe8c2', roof: 'gable', roofMat: 'clay', accent: '#ffd23f', pool: 'none', trees: 2 }, { shape: 'U', w: 17, d: 11, floors: 2, wall: 'concrete', roof: 'flat', roofMat: 'solar', accent: '#ff4fd8', pool: 'round', trees: 1 }];
const WALLC = ['#ffffff', '#f4e8d6', '#dfe8d4', '#c9b7e8', '#ffe8c2', '#d6ecff', '#ffd6e0', '#e2e8f0', '#cfe8d8', '#f0dfc8'];
export function buildStreets(app, W, X0, Z0) {
  const S = app.scene; const toast = (m, ms) => app.toast(m, ms); const G = new T.Group(); S.add(G); const dirtM = new T.MeshStandardMaterial({ color: 0x8a6a46, roughness: 1 }); const solar = (() => { try { const t = TEX.solar(); const t2 = t.clone(); t2.needsUpdate = true; t2.wrapS = t2.wrapT = T.RepeatWrapping; t2.repeat.set(1, 1); return new T.MeshStandardMaterial({ map: t2, metalness: 0.55, roughness: 0.35 }); } catch (e) { return M(0x1b2a4a, { metalness: 0.6, roughness: 0.3 }); } })();
  const pondOk = (x, z) => Math.hypot(x - 250, z + 230) > 48 && Math.hypot(x - 44, z - 105) > 70;
  // Unity Boulevard: one road out the front gate, dirt for the first stretch, solar after. Branches peel off it, alternating sides.
  const start = new T.Vector3(X0 - 46, 0, Z0 + 2); const curves = []; const rr = (i, k) => Math.abs((Math.sin(i * 12.9898 + k * 78.233) * 43758.5453) % 1);
  const trunkPts = [start.clone(), new T.Vector3(X0 - 110, 0, Z0 - 2), new T.Vector3(X0 - 170, 0, Z0 + 18), new T.Vector3(X0 - 235, 0, Z0 + 4), new T.Vector3(X0 - 300, 0, Z0 + 30), new T.Vector3(X0 - 360, 0, Z0 + 20)]; const trunk = new T.CatmullRomCurve3(trunkPts, false, 'catmullrom', 0.4); curves.push({ c: trunk, name: STREETS[0], i: 0, trunk: true });
  // rolling hills between the lanes: gentle raised flats at varied heights so it is not a flat grid, plus two parks
  for (let k = 0; k < 9; k++) { const u = 0.12 + k * 0.1; const p = trunk.getPointAt(u), tg = trunk.getTangentAt(u); const side = k % 2 ? 1 : -1; const hx = p.x - tg.z * (70 + rr(k, 9) * 40) * side, hz = p.z + tg.x * (70 + rr(k, 9) * 40) * side; addFlat({ x: hx, z: hz, r: 26 + rr(k, 4) * 14, y: terrainY(hx, hz) + 4 + rr(k, 5) * 7, soft: 34 }); }
  const PARKS = [[0.3, 1], [0.72, -1]].map(([u, side]) => { const p = trunk.getPointAt(u), tg = trunk.getTangentAt(u); return { x: p.x - tg.z * 46 * side, z: p.z + tg.x * 46 * side, u, side }; });
  for (let i = 1; i < 14; i++) { const u = i < 11 ? 0.22 + (i - 1) * 0.082 : 0.3 + (i - 11) * 0.25; const p = trunk.getPointAt(u), tg = trunk.getTangentAt(u); const side = i % 2 ? 1 : -1; const n = new T.Vector3(-tg.z, 0, tg.x).multiplyScalar(side); const len = (i < 11 ? 90 : 150) + rr(i, 1) * 70; const pts = [p.clone()]; let q = p.clone(); let dirv = n.clone(); for (let k = 1; k <= 3; k++) { dirv.applyAxisAngle(new T.Vector3(0, 1, 0), (rr(i, k + 2) - 0.5) * 0.7); q = q.clone().addScaledVector(dirv, len / 3); pts.push(q); } curves.push({ c: new T.CatmullRomCurve3(pts, false, 'catmullrom', 0.4), name: STREETS[i], i }); }
  // flatten under roads first, then lay the solar surface
  for (const { c } of curves) { const L = c.getLength(); for (let d = 0; d <= L; d += 34) { const p = c.getPointAt(Math.min(1, d / L)); addFlat({ x: p.x, z: p.z, r: 16, y: terrainY(p.x, p.z), soft: 14 }); } }
  const lamps = []; const signs = []; const anims = []; let lotN = 0; const lots = []; const WID = 7;
  curves.forEach(({ c, name, i, trunk: isTrunk }) => { const L = c.getLength(); const N = Math.max(12, Math.round(L / 5)); const pos = [], uv = [], idx = []; const DIRT = isTrunk ? 70 / L : 0; for (let k = 0; k <= N; k++) { const u = k / N; const p = c.getPointAt(u), tg = c.getTangentAt(u); const nx = -tg.z, nz = tg.x; for (const sd of [-1, 1]) { const x = p.x + nx * WID / 2 * sd, z = p.z + nz * WID / 2 * sd; pos.push(x, terrainY(x, z) + 0.1, z); uv.push(sd > 0 ? 1 : 0, u * L / 7); } if (k < N) { const a = k * 2; idx.push(a, a + 1, a + 2, a + 1, a + 3, a + 2); } } const g = new T.BufferGeometry(); g.setAttribute('position', new T.Float32BufferAttribute(pos, 3)); g.setAttribute('uv', new T.Float32BufferAttribute(uv, 2)); g.setIndex(idx); g.computeVertexNormals(); if (DIRT) { const cut = Math.round(N * DIRT); g.clearGroups(); const perRow = 6; g.addGroup(0, cut * perRow, 0); g.addGroup(cut * perRow, (N - cut) * perRow, 1); const road = new T.Mesh(g, [dirtM, solar]); road.userData.noCollide = true; road.receiveShadow = true; G.add(road); const tp = c.getPointAt(DIRT); const ts = makeSprite('🌞 solar road starts here · Unity Boulevard', { scale: 4, accent: '#ffd23f', far: 120 }); ts.position.set(tp.x, terrainY(tp.x, tp.z) + 3, tp.z); G.add(ts); } else { const road = new T.Mesh(g, solar); road.userData.noCollide = true; road.receiveShadow = true; G.add(road); }
    // glowing center line + edge strips
    const linePos = []; for (let k = Math.round(N * DIRT); k <= N; k++) { const p = c.getPointAt(k / N); linePos.push(p.x, terrainY(p.x, p.z) + 0.14, p.z); } const lg = new T.BufferGeometry(); lg.setAttribute('position', new T.Float32BufferAttribute(linePos, 3)); const line = new T.Line(lg, new T.LineDashedMaterial({ color: 0x38f0ff, dashSize: 2, gapSize: 2 })); line.computeLineDistances(); G.add(line); for (const sd of [-1, 1]) { const ep = []; for (let k = 0; k <= N; k++) { const p = c.getPointAt(k / N), tg = c.getTangentAt(k / N); const x = p.x - tg.z * (WID / 2 + 0.15) * sd, z = p.z + tg.x * (WID / 2 + 0.15) * sd; ep.push(x, terrainY(x, z) + 0.13, z); } const eg = new T.BufferGeometry(); eg.setAttribute('position', new T.Float32BufferAttribute(ep, 3)); G.add(new T.Line(eg, new T.LineBasicMaterial({ color: 0x7cf8ff, transparent: true, opacity: 0.6 }))); }
    // street name at the start, kindness signs + solar lamps along it
    const p0 = c.getPointAt(isTrunk ? 0.25 : 0.06); const sn = textPlane([name.toUpperCase()], 4.2, 0.9, { bg: '#0b2a4a', fg: '#fff', accent: '#38f0ff' }); sn.position.set(p0.x, terrainY(p0.x, p0.z) + 2.6, p0.z); sn.rotation.y = Math.atan2(c.getTangentAt(isTrunk ? 0.25 : 0.06).x, c.getTangentAt(isTrunk ? 0.25 : 0.06).z) + Math.PI / 2; sn.material.side = T.DoubleSide; G.add(sn); cyl(0.05, 0.05, 2.6, M(0x6b7280), p0.x, terrainY(p0.x, p0.z) + 1.3, p0.z, G, 6);
    for (let d = Math.max(45, DIRT * L + 20); d < L - 20; d += 90) { const u = d / L; const p = c.getPointAt(u), tg = c.getTangentAt(u); const side = (Math.round(d / 60) % 2 ? 1 : -1); const x = p.x - tg.z * (WID / 2 + 1.6) * side, z = p.z + tg.x * (WID / 2 + 1.6) * side; const y = terrainY(x, z); const post = cyl(0.07, 0.09, 5.2, M(0xdfe6f2, { metalness: 0.8 }), x, y + 2.6, z, G, 8); const head = box(0.5, 0.12, 0.9, solar, x, y + 5.3, z, G); const bulb = new T.Sprite(new T.SpriteMaterial({ map: glowTex(), color: 0xfff3b0, transparent: true, opacity: 0.85, depthWrite: false, blending: T.AdditiveBlending })); bulb.scale.setScalar(2.6); bulb.position.set(x, y + 4.9, z); G.add(bulb); lamps.push(bulb); if (Math.abs(d - L / 2) < 46 && !isTrunk) { const say = SAY[i % SAY.length]; const sg = makeSprite('💛 ' + say, { scale: 4, accent: '#ffd23f', far: 160 }); sg.position.set(x, y + 3.6, z); G.add(sg); signs.push(sg); } }
    // two lots per street, alternating sides, set back from the road
    if (isTrunk) return; for (let q = 0; q < 3 && lotN < 40; q++) { const u = 0.3 + q * 0.3; const p = c.getPointAt(u), tg = c.getTangentAt(u); const side = (i + q) % 2 ? 1 : -1; const cx = p.x - tg.z * 24 * side, cz = p.z + tg.x * 24 * side; if (Math.hypot(cx - (X0 - 125), cz - (Z0 - 48)) < 45 || Math.hypot(cx - (X0 - 135), cz - (Z0 + 62)) < 45) continue; if (!pondOk(cx, cz)) continue; const face = Math.atan2(-(cx - p.x), -(cz - p.z)); const id = 'uh-' + (lotN + 1); const lot = { id, x: cx, z: cz, face, road: 'solar:' + name, street: name, n: lotN + 1 }; lots.push(lot); if (W.lots) W.lots.set(id, lot); lotN++; } });
  // the model homes (or the owner's home once claimed)
  lots.forEach((lot, k) => { const { x: cx, z: cz, face, id } = lot; addFlat({ x: cx, z: cz, r: 24, y: terrainY(cx, cz), soft: 8 }); const y = terrainY(cx, cz); const claim = W.claims && W.claims.get(id);
    let H; const spec = Object.assign({}, SPECS[k % SPECS.length], { wallColor: SPECS[k % SPECS.length].wallColor || WALLC[k % WALLC.length], accent: SPECS[k % SPECS.length].accent, sign: '', mailbox: ['classic', 'modern', 'round'][k % 3], mailColor: ['#2f6bff', '#ff4f79', '#ffd23f'][k % 3], garden: k % 3 !== 1, solar: true, fence: k % 2 === 0, hottub: k % 4 === 0, fish: ['koi', 'tropical', 'goldfish'][k % 3] });
    if (claim) { H = (W.buildCustom && W.buildCustom(claim)) || buildCustomHome(spec); } else { try { H = buildCustomHome(spec); } catch (e) { console.error('model home', e); return; } }
    H.group.rotation.y = face + Math.PI; H.group.position.set(cx, y, cz); G.add(H.group); const ry = H.group.rotation.y; for (const [bx, bz, hw, hd] of (H.boxes || [])) { const cs = Math.cos(ry), sn = Math.sin(ry); app.obstacles.push({ x: cx + bx * cs + bz * sn, z: cz - bx * sn + bz * cs, hw: Math.abs(hw * cs) + Math.abs(hd * sn), hd: Math.abs(hw * sn) + Math.abs(hd * cs) }); }
    // floating neon LIFEboard over the door, cycling colors
    const lb = makeSprite('LIFEboard', { scale: 3.2, accent: '#38f0ff', bg: 'rgba(5,10,30,0.7)', fg: '#eaffff' }); const fy = y + 3.4 * (spec.floors || 2) + 2.2; lb.position.set(cx + Math.sin(face) * 6, fy, cz + Math.cos(face) * 6); lb.userData.hue = k * 0.07; G.add(lb); const ring = new T.Mesh(new T.TorusGeometry(1.1, 0.06, 8, 32), glow(0x38f0ff, 1.6)); ring.position.copy(lb.position); ring.position.y -= 0.8; G.add(ring); lb.userData.ring = ring; signs.push(lb);
    // interior: a globe and a fish tank just inside, lit
    const inside = new T.Group(); inside.position.set(cx, y, cz); inside.rotation.y = ry; G.add(inside); const globe = sph(0.55, new T.MeshStandardMaterial({ color: 0x2f6bff, emissive: 0x0b1a5a, emissiveIntensity: 0.6, metalness: 0.3, roughness: 0.4 }), -2.5, 1.5, 0, inside, 20); cyl(0.08, 0.3, 0.9, M(0x6b7280, { metalness: 0.8 }), -2.5, 0.45, 0, inside, 8); globe.userData.spin = true; anims.push(globe); const tank = new T.Mesh(new T.BoxGeometry(2.2, 1.1, 0.7), new T.MeshPhysicalMaterial({ color: 0x8fd3ff, transparent: true, opacity: 0.35, roughness: 0.05 })); tank.position.set(2.4, 1.4, 0); inside.add(tank); box(2.3, 0.08, 0.8, M(0x1e1b4b), 2.4, 0.84, 0, inside); for (let f = 0; f < 4; f++) { const fish = sph(0.08, M([0xff6a1f, 0xffd23f, 0x38f0ff, 0xff4fd8][f]), 2.4 + Math.cos(f * 1.5) * 0.7, 1.3 + (f % 2) * 0.3, Math.sin(f * 1.5) * 0.2, inside, 8); fish.scale.set(0.6, 0.5, 1.4); fish.userData.swim = f; anims.push(fish); } const lamp = sph(0.2, glow(0xffe9a8, 1.5), 0, 3.0, 0, inside, 10);
    // the claim sign (or the visit sign)
    const sx = cx + Math.sin(face) * 12, sz = cz + Math.cos(face) * 12; if (claim) { const nm = makeSprite('🏡 ' + (claim.name || 'Home'), { scale: 3.4, accent: '#ffd23f' }); nm.position.set(sx, terrainY(sx, sz) + 3.2, sz); G.add(nm); app.addInteractable(sx, sz, 5, '🏡 ' + (claim.name || 'Home') + ': visit', () => W.api.visitHome(claim)); } else { const st = new T.Group(); st.position.set(sx, terrainY(sx, sz), sz); st.rotation.y = face; G.add(st); cyl(0.06, 0.06, 1.6, M(0x8a5a2b), 0, 0.8, 0, st, 6); const pl = textPlane(['CLAIM ME', lot.street], 1.4, 0.8, { bg: '#ffd23f', fg: '#1e1b4b', accent: '#ff4fd8' }); pl.position.set(0, 1.9, 0); pl.material.side = T.DoubleSide; st.add(pl); app.addInteractable(sx, sz, 4.5, '🌍 Claim this home · ' + lot.street, () => W.api && W.api.claimLot ? W.api.claimLot(lot) : toast('Sign in to claim.')); app.addHotspot && app.addHotspot(pl, { fn: () => W.api && W.api.claimLot && W.api.claimLot(lot) }); } });
  // two parks: lawn, pond, benches, trees
  PARKS.forEach((pk, n) => { addFlat({ x: pk.x, z: pk.z, r: 30, y: terrainY(pk.x, pk.z), soft: 12 }); const y = terrainY(pk.x, pk.z); const lawn = new T.Mesh(new T.CircleGeometry(26, 32), M(0x4caf50, { roughness: 1 })); lawn.rotation.x = -Math.PI / 2; lawn.position.set(pk.x, y + 0.06, pk.z); lawn.userData.noCollide = true; G.add(lawn); const pond = new T.Mesh(new T.CircleGeometry(7, 24), new T.MeshPhysicalMaterial({ color: 0x19a7ff, transparent: true, opacity: 0.6, roughness: 0.05 })); pond.rotation.x = -Math.PI / 2; pond.position.set(pk.x + 6, y + 0.1, pk.z - 4); pond.userData.noCollide = true; G.add(pond); const pp = []; for (let i = 0; i < 12; i++) pp.push([pk.x + 6 + Math.cos(i / 12 * 6.283) * 7, pk.z - 4 + Math.sin(i / 12 * 6.283) * 7]); app.addWater && app.addWater({ poly: pp, y: y + 0.1 }); for (let i = 0; i < 4; i++) { const a = i / 4 * 6.283 + 0.4; const bx = pk.x + Math.cos(a) * 16, bz = pk.z + Math.sin(a) * 16; const bench = box(1.8, 0.12, 0.5, M(0x8a5a2b), bx, y + 0.5, bz, G); bench.rotation.y = -a; box(1.8, 0.5, 0.1, M(0x8a5a2b), bx, y + 0.8, bz - 0.2, G).rotation.y = -a; } for (let i = 0; i < 9; i++) { const a = i / 9 * 6.283; const tx = pk.x + Math.cos(a) * (20 + (i % 3) * 3), tz = pk.z + Math.sin(a) * (20 + (i % 2) * 4); const ty = terrainY(tx, tz); cyl(0.25, 0.35, 3, M(0x6b4a2a), tx, ty + 1.5, tz, G, 7); sph(2.2 + (i % 3) * 0.5, M([0x2e7d32, 0x43a047, 0x558b2f][i % 3], { roughness: 0.9 }), tx, ty + 4.2, tz, G, 10); app.addObstacle && app.addObstacle(tx, tz, 0.6); } const nm = ['Stephanie Park', 'Kindness Commons'][n]; const psg = makeSprite('🌳 ' + nm + ' · sit a while', { scale: 4.4, accent: '#7cff6b', far: 160 }); psg.position.set(pk.x, y + 5, pk.z); G.add(psg); app.addPlace && app.addPlace({ id: 'park-' + n, name: '🌳 ' + nm, icon: '🌳', x: pk.x, z: pk.z + 8, cat: 'Places', keys: 'park pond bench trees ' + nm.toLowerCase(), say: 'A lawn, a pond, four benches, and no agenda.' }); });
  // the gateway sign at the start, in the directory, and the gentle animation
  const gw = textPlane(['UNITY HEIGHTS', 'homes to claim · follow the road'], 4.6, 1.3, { bg: '#1b2a4a', fg: '#ffd23f', accent: '#38f0ff' }); gw.position.set(start.x - 4, terrainY(start.x - 4, start.z + 6) + 2.4, start.z + 6); gw.rotation.y = Math.PI / 2; gw.material.side = T.DoubleSide; G.add(gw); cyl(0.06, 0.06, 2.4, M(0x6b7280), start.x - 4, terrainY(start.x - 4, start.z + 6) + 1.2, start.z + 6, G, 6); app.addPlace && app.addPlace({ id: 'unity-heights', name: '🌞 Unity Heights · 14 streets · 40 homes · 2 parks', icon: '🌞', x: start.x, z: start.z + 6, cat: 'Homes', top: true, keys: 'neighborhood streets solar homes claim lots houses unity heights', say: 'Walk the solar streets. Every yellow sign is a home you can claim.' }); curves.forEach(({ c, name }, i) => { const p = c.getPointAt(0.5); app.addPlace && app.addPlace({ id: 'st-' + i, name: '🛣️ ' + name, icon: '🛣️', x: p.x, z: p.z, cat: 'Homes', keys: 'street road ' + name.toLowerCase() }); });
  app.onUpdate((dt, t) => { const P = app.player.position; if (Math.hypot(P.x - start.x, P.z - start.z) > 520) return; signs.forEach((s, i) => { if (s.userData.ring) { s.material.color.setHSL((t * 0.08 + s.userData.hue) % 1, 1, 0.75); s.userData.ring.material.color.setHSL((t * 0.08 + s.userData.hue) % 1, 1, 0.6); s.position.y += Math.sin(t * 1.4 + i) * dt * 0.08; s.userData.ring.rotation.z = t * 0.6; } }); const night = (new Date().getHours() >= 18 || new Date().getHours() < 6); lamps.forEach(l => { l.material.opacity = night ? 0.95 : 0.35; }); anims.forEach(o => { if (o.userData.spin) o.rotation.y += dt * 0.4; if (o.userData.swim !== undefined) { o.position.x = 2.4 + Math.cos(t * 0.8 + o.userData.swim * 1.5) * 0.7; o.rotation.y = Math.sin(t * 0.8 + o.userData.swim * 1.5) > 0 ? Math.PI : 0; } }); });
  return { lots, curves };
}
const glowTex = (() => { let t = null; return () => { if (t) return t; const c = document.createElement('canvas'); c.width = c.height = 128; const g = c.getContext('2d'); const gr = g.createRadialGradient(64, 64, 0, 64, 64, 64); gr.addColorStop(0, 'rgba(255,255,255,1)'); gr.addColorStop(0.35, 'rgba(255,255,255,.4)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(0, 0, 128, 128); t = new T.CanvasTexture(c); return t; }; })();
