/* ============================================================
   allofus.one · home builder + addresses + directory (v4)
   · Builder: shape, floors, wall + roof materials (slate, standing-
     seam aluminum, clay tile, cedar shake, copper, solar glass,
     living green), windows, pools you shape yourself (depth, fish,
     even sharks), gardens, solar, wind, fence, sign, mailbox style,
     and Lifeblocks: build anything block by block. Live 3D preview.
   · Every home gets a street address + a unique hashed address
     code (SHA-256 fingerprint, like a blockchain address) that can
     be shared anywhere: the link walks people right to the door.
   · 📒 Directory: every place and every home, phone-book style.
   © 2026 allofus.one
   ============================================================ */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { plantGarden } from './aou-garden.js';
const T = THREE; const MOB = isMobile();
const $ = (s, r = document) => r.querySelector(s); const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

/* ---------- material library (canvas textures, cached) ---------- */
const texCache = new Map();
function canvasTex(key, w, h, draw, rep = [1, 1]) { const k = key + rep.join('x'); if (texCache.has(k)) return texCache.get(k); const c = document.createElement('canvas'); c.width = w; c.height = h; draw(c.getContext('2d'), w, h); const t = new T.CanvasTexture(c); t.wrapS = t.wrapT = T.RepeatWrapping; t.repeat.set(rep[0], rep[1]); t.colorSpace = T.SRGBColorSpace; t.anisotropy = 4; texCache.set(k, t); return t; }
const R = (a, b) => a + Math.random() * (b - a);
export const TEX = {
  slate: () => canvasTex('slate', 256, 256, (g, w, h) => { for (let y = 0; y < h; y += 32) for (let x = -(y / 32 % 2) * 24; x < w; x += 48) { const l = R(22, 34); g.fillStyle = `hsl(${R(205, 220)},${R(6, 12)}%,${l}%)`; g.fillRect(x + 1, y + 1, 46, 30); g.fillStyle = `rgba(255,255,255,${R(0.03, 0.08)})`; g.fillRect(x + 2, y + 2, 44, 4); g.fillStyle = 'rgba(0,0,0,.45)'; g.fillRect(x, y + 30, 48, 2); } }),
  aluminum: () => canvasTex('alu', 256, 256, (g, w, h) => { g.fillStyle = '#c9ced4'; g.fillRect(0, 0, w, h); for (let x = 0; x < w; x += 32) { const gr = g.createLinearGradient(x, 0, x + 32, 0); gr.addColorStop(0, '#9aa1aa'); gr.addColorStop(0.08, '#eef1f4'); gr.addColorStop(0.16, '#b9bfc6'); gr.addColorStop(1, '#cfd4da'); g.fillStyle = gr; g.fillRect(x, 0, 32, h); } }),
  clay: () => canvasTex('clay', 256, 256, (g, w, h) => { g.fillStyle = '#a84a2a'; g.fillRect(0, 0, w, h); for (let y = 0; y < h; y += 24) for (let x = 0; x < w; x += 32) { const gr = g.createLinearGradient(x, 0, x + 32, 0); gr.addColorStop(0, '#7a2e18'); gr.addColorStop(0.5, `hsl(${R(12, 20)},62%,${R(42, 50)}%)`); gr.addColorStop(1, '#7a2e18'); g.fillStyle = gr; g.fillRect(x, y, 32, 22); } }),
  cedar: () => canvasTex('cedar', 256, 256, (g, w, h) => { for (let y = 0; y < h; y += 28) for (let x = -(y / 28 % 2) * 14; x < w; x += R(18, 30)) { g.fillStyle = `hsl(${R(20, 32)},${R(35, 50)}%,${R(30, 45)}%)`; g.fillRect(x, y, 28, 26); g.fillStyle = 'rgba(0,0,0,.35)'; g.fillRect(x + 27, y, 2, 26); } }),
  copper: () => canvasTex('copper', 256, 256, (g, w, h) => { g.fillStyle = '#6fb39b'; g.fillRect(0, 0, w, h); for (let i = 0; i < 600; i++) { g.fillStyle = `rgba(${R(140, 200)},${R(80, 120)},${R(40, 70)},${R(0.05, 0.25)})`; g.fillRect(R(0, w), R(0, h), R(2, 10), R(2, 10)); } for (let x = 0; x < w; x += 40) { g.fillStyle = 'rgba(0,0,0,.18)'; g.fillRect(x, 0, 3, h); } }),
  solar: () => canvasTex('solar', 128, 192, (g, w, h) => { const gr = g.createLinearGradient(0, 0, w, h); gr.addColorStop(0, '#1b3f8f'); gr.addColorStop(1, '#0a1f52'); g.fillStyle = gr; g.fillRect(0, 0, w, h); g.strokeStyle = 'rgba(190,215,255,.55)'; g.lineWidth = 2; for (let x = 0; x <= w; x += 32) { g.beginPath(); g.moveTo(x, 0); g.lineTo(x, h); g.stroke(); } for (let y = 0; y <= h; y += 32) { g.beginPath(); g.moveTo(0, y); g.lineTo(w, y); g.stroke(); } }),
  green: () => canvasTex('green', 256, 256, (g, w, h) => { g.fillStyle = '#4d8a2e'; g.fillRect(0, 0, w, h); for (let i = 0; i < 5000; i++) { g.strokeStyle = `hsl(${R(88, 118)},${R(45, 75)}%,${R(24, 50)}%)`; const x = R(0, w), y = R(0, h); g.beginPath(); g.moveTo(x, y); g.lineTo(x + R(-1.5, 1.5), y - R(2, 7)); g.stroke(); } for (let i = 0; i < 120; i++) { g.fillStyle = ['#ffd23f', '#fff', '#ff7ab8', '#b08cff'][i % 4]; g.beginPath(); g.arc(R(0, w), R(0, h), 1.6, 0, 6.28); g.fill(); } }),
  brick: () => canvasTex('brick', 256, 256, (g, w, h) => { g.fillStyle = '#d8d0c4'; g.fillRect(0, 0, w, h); for (let y = 0; y < h; y += 16) for (let x = -(y / 16 % 2) * 16; x < w; x += 32) { g.fillStyle = `hsl(${R(5, 16)},${R(45, 60)}%,${R(32, 44)}%)`; g.fillRect(x + 1, y + 1, 30, 14); } }),
  stone: () => canvasTex('stone', 256, 256, (g, w, h) => { g.fillStyle = '#8f8a80'; g.fillRect(0, 0, w, h); for (let i = 0; i < 70; i++) { g.fillStyle = `hsl(${R(30, 45)},${R(6, 14)}%,${R(48, 72)}%)`; g.beginPath(); g.ellipse(R(0, w), R(0, h), R(12, 26), R(8, 18), R(0, 3), 0, 6.28); g.fill(); g.strokeStyle = 'rgba(0,0,0,.25)'; g.stroke(); } }),
  wood: () => canvasTex('wood', 256, 256, (g, w, h) => { for (let y = 0; y < h; y += 16) { g.fillStyle = `hsl(${R(24, 34)},${R(35, 50)}%,${R(42, 56)}%)`; g.fillRect(0, y, w, 15); g.fillStyle = 'rgba(0,0,0,.25)'; g.fillRect(0, y + 15, w, 1); } }),
  stucco: () => canvasTex('stucco', 256, 256, (g, w, h) => { g.fillStyle = '#f2ece2'; g.fillRect(0, 0, w, h); for (let i = 0; i < 4000; i++) { g.fillStyle = `rgba(0,0,0,${R(0.01, 0.05)})`; g.fillRect(R(0, w), R(0, h), 2, 2); } }),
  hemp: () => canvasTex('hemp', 256, 256, (g, w, h) => { g.fillStyle = '#efe6d2'; g.fillRect(0, 0, w, h); for (let i = 0; i < 2600; i++) { g.strokeStyle = `rgba(${R(120, 180) | 0},${R(100, 150) | 0},${R(60, 100) | 0},${R(0.12, 0.3)})`; const x = R(0, w), y = R(0, h), a = R(0, 6.28), l = R(2, 8); g.beginPath(); g.moveTo(x, y); g.lineTo(x + Math.cos(a) * l, y + Math.sin(a) * l); g.stroke(); } }),
  concrete: () => canvasTex('concrete', 256, 256, (g, w, h) => { g.fillStyle = '#b8b6b0'; g.fillRect(0, 0, w, h); for (let i = 0; i < 3000; i++) { g.fillStyle = `rgba(${R(0, 255) > 128 ? 255 : 0},${0},${0},0)`; } for (let i = 0; i < 2500; i++) { g.fillStyle = `rgba(0,0,0,${R(0.02, 0.07)})`; g.fillRect(R(0, w), R(0, h), R(1, 3), R(1, 3)); } g.strokeStyle = 'rgba(0,0,0,.12)'; g.strokeRect(0, 0, w, h); }),
};
export const WALLS = [['hemp', 'Hempcrete', 0xffffff], ['brick', 'Brick', 0xffffff], ['stone', 'Fieldstone', 0xffffff], ['wood', 'Wood siding', 0xffffff], ['stucco', 'Stucco', 0xffffff], ['concrete', 'Concrete', 0xffffff], ['glass', 'All glass', 0xbfefff], ['metal', 'Metal panel', 0x8a96a3]];
export const ROOFS = [['flat', 'Flat + parapet'], ['gable', 'Gable'], ['hip', 'Hip'], ['shed', 'Modern shed'], ['butterfly', 'Butterfly'], ['dome', 'Dome'], ['garden', 'Living garden roof']];
export const ROOF_MATS = [['slate', 'Slate'], ['aluminum', 'Standing-seam aluminum'], ['clay', 'Clay tile'], ['cedar', 'Cedar shake'], ['copper', 'Copper'], ['solar', 'Solar glass'], ['green', 'Living green']];
export const SHAPES = [['rect', 'Rectangle'], ['L', 'L-shape'], ['U', 'U-shape'], ['court', 'Courtyard'], ['tower', 'Round tower']];
export const POOLS = [['none', 'No pool'], ['rect', 'Rectangle'], ['kidney', 'Kidney'], ['round', 'Round'], ['lagoon', 'Lagoon'], ['custom', 'Draw my own']];
export const FISH = [['none', 'No fish'], ['koi', 'Koi'], ['tropical', 'Tropical'], ['sharks', 'Friendly sharks 🦈']];
export const MAILBOX = [['classic', 'Classic'], ['modern', 'Modern'], ['rocket', 'Rocket'], ['birdhouse', 'Birdhouse'], ['castle', 'Castle']];
export const BLOCK_MATS = [['stone', 0xffffff], ['brick', 0xffffff], ['wood', 0xffffff], ['glass', 0xbfefff], ['gold', 0xffd23f], ['neon', 0x38f0ff], ['green', 0xffffff], ['slate', 0xffffff]];
export const DEFAULT_SPEC = () => ({ v: 1, shape: 'rect', w: 12, d: 10, floors: 2, wall: 'hemp', wallColor: '#ffffff', roof: 'gable', roofMat: 'slate', windows: 50, accent: '#38f0ff', pool: 'rect', poolDepth: 1.8, poolPts: [], fish: 'koi', garden: true, solar: true, wind: false, fence: true, trees: 3, hottub: false, sign: '', signColor: '#ff4fd8', fireworks: false, mailbox: 'classic', mailColor: '#2f6bff', blocks: [] });

function matFor(key, color, rep = [2, 2]) { if (key === 'glass') return new T.MeshPhysicalMaterial({ color: color || 0xbfefff, transparent: true, opacity: 0.35, roughness: 0.05, metalness: 0.2, depthWrite: false }); if (key === 'metal') return new T.MeshStandardMaterial({ color: color || 0x8a96a3, metalness: 0.75, roughness: 0.32 }); if (key === 'gold') return new T.MeshStandardMaterial({ color: 0xffd23f, metalness: 0.9, roughness: 0.2 }); if (key === 'neon') return new T.MeshStandardMaterial({ color: 0x38f0ff, emissive: 0x38f0ff, emissiveIntensity: 1.6 });
  const t = TEX[key] ? TEX[key]().clone() : null; if (t) { t.needsUpdate = true; t.repeat.set(rep[0], rep[1]); } const metal = key === 'aluminum' ? 0.8 : key === 'copper' ? 0.55 : key === 'solar' ? 0.6 : 0; return new T.MeshStandardMaterial({ color: color ? new T.Color(color) : 0xffffff, map: t, roughness: key === 'slate' ? 0.55 : key === 'aluminum' ? 0.3 : key === 'solar' ? 0.2 : 0.85, metalness: metal }); }
const B = (w, h, d, m, x, y, z, p) => { const o = new T.Mesh(new T.BoxGeometry(w, h, d), m); o.position.set(x, y, z); o.castShadow = !MOB; o.receiveShadow = true; if (p) p.add(o); return o; };

/* a roof over a w×d footprint at height y */
function roof(g, type, mat, w, d, x, y, z, solar) { const rm = matFor(mat, null, [w / 3, d / 3]); const rh = Math.min(w, d) * 0.32;
  if (type === 'flat' || type === 'garden') { B(w + 0.4, 0.35, d + 0.4, matFor('concrete'), x, y + 0.17, z, g); for (const [ww, dd, ox, oz] of [[w + 0.4, 0.3, 0, d / 2], [w + 0.4, 0.3, 0, -d / 2], [0.3, d + 0.4, w / 2, 0], [0.3, d + 0.4, -w / 2, 0]]) B(ww, 0.6, dd, matFor('concrete'), x + ox, y + 0.6, z + oz, g); if (type === 'garden' || mat === 'green') B(w - 0.2, 0.2, d - 0.2, matFor('green', null, [w / 4, d / 4]), x, y + 0.42, z, g); else B(w - 0.2, 0.06, d - 0.2, rm, x, y + 0.36, z, g); }
  else if (type === 'gable' || type === 'shed' || type === 'butterfly') { const sides = type === 'gable' ? [[-1, 1], [1, 1]] : type === 'shed' ? [[0, 2]] : [[-1, -1], [1, -1]];
    for (const [sx, k] of sides) { const half = type === 'shed' ? w : w / 2; const slope = type === 'shed' ? rh * 0.6 : rh * (k > 0 ? 1 : 0.45); const len = Math.hypot(half, slope); const p = B(len + 0.3, 0.16, d + 0.6, rm, 0, 0, 0, g); const ang = Math.atan2(slope, half) * (k > 0 ? 1 : -1); if (type === 'shed') { p.position.set(x, y + slope / 2, z); p.rotation.z = ang; } else { p.position.set(x + sx * half / 2, y + slope / 2, z); p.rotation.z = -sx * ang; } }
    if (type === 'gable') for (const sz of [-1, 1]) { const sh = new T.Shape(); sh.moveTo(-w / 2, 0); sh.lineTo(w / 2, 0); sh.lineTo(0, rh); sh.closePath(); const tri = new T.Mesh(new T.ShapeGeometry(sh), new T.MeshStandardMaterial({ color: 0xf2ece2, side: T.DoubleSide })); tri.position.set(x, y, z + sz * d / 2); g.add(tri); } }
  else if (type === 'hip') { const c = new T.Mesh(new T.ConeGeometry(Math.max(w, d) * 0.72, rh * 1.2, 4, 1), rm); c.rotation.y = Math.PI / 4; c.scale.set(w / Math.max(w, d), 1, d / Math.max(w, d)); c.position.set(x, y + rh * 0.6, z); c.castShadow = !MOB; g.add(c); }
  else if (type === 'dome') { const dm = new T.Mesh(new T.SphereGeometry(Math.min(w, d) * 0.55, 32, 16, 0, Math.PI * 2, 0, Math.PI / 2), mat === 'solar' || mat === 'aluminum' || mat === 'copper' ? rm : matFor('glass')); dm.position.set(x, y, z); g.add(dm); B(w + 0.3, 0.3, d + 0.3, matFor('concrete'), x, y + 0.15, z, g); }
  if (solar && type !== 'dome') { const sp = matFor('solar'); for (let i = 0; i < Math.min(6, Math.floor(w / 2.2)); i++) { const pnl = B(1.8, 0.06, 1.2, sp, x - w / 2 + 1.4 + i * 2.1, y + (type === 'flat' || type === 'garden' ? 0.9 : rh * 0.55 + 0.2), z + d * 0.18, g); pnl.rotation.x = -0.35; } } }

function fishMesh(kind, i) { const col = kind === 'sharks' ? 0x7a8a99 : kind === 'koi' ? [0xff7a2a, 0xffffff, 0xffd23f][i % 3] : [0x00b4ff, 0xffd23f, 0xff4f79, 0x7cff6b][i % 4]; const s = kind === 'sharks' ? 0.55 : 0.18; const g = new T.Group(); const b = new T.Mesh(new T.SphereGeometry(s, 10, 6), new T.MeshStandardMaterial({ color: col, roughness: 0.4 })); b.scale.set(0.5, 0.45, 1.6); g.add(b); const tl = new T.Mesh(new T.ConeGeometry(s * 0.5, s * 0.9, 4), b.material); tl.rotation.x = Math.PI / 2; tl.position.z = -s * 1.6; g.add(tl); if (kind === 'sharks') { const fin = new T.Mesh(new T.ConeGeometry(s * 0.25, s * 0.8, 3), b.material); fin.position.set(0, s * 0.55, 0); g.add(fin); } return g; }
function poolShape(spec) { const pts = []; const n = 28; if (spec.pool === 'custom' && spec.poolPts && spec.poolPts.length >= 3) return spec.poolPts.map(([x, z]) => new T.Vector2(x, z));
  for (let i = 0; i < n; i++) { const a = i / n * Math.PI * 2; let r = 1; if (spec.pool === 'kidney') r = 1 - 0.32 * Math.max(0, Math.cos(a)) ** 3; if (spec.pool === 'lagoon') r = 1 + 0.18 * Math.sin(a * 3) + 0.1 * Math.cos(a * 5); const rx = spec.pool === 'round' ? 3 : 4.6, rz = spec.pool === 'round' ? 3 : 2.6; if (spec.pool === 'rect') { const sx = Math.sign(Math.cos(a)), sz = Math.sign(Math.sin(a)); pts.push(new T.Vector2(Math.abs(Math.cos(a)) > Math.abs(Math.sin(a)) * 1.6 ? sx * 4.6 : Math.cos(a) * 4.6 * 1.3, Math.abs(Math.sin(a)) * 1.6 > Math.abs(Math.cos(a)) ? sz * 2.6 : Math.sin(a) * 2.6 * 1.3)); continue; } pts.push(new T.Vector2(Math.cos(a) * rx * r, Math.sin(a) * rz * r)); }
  if (spec.pool === 'rect') return [new T.Vector2(-4.6, -2.6), new T.Vector2(4.6, -2.6), new T.Vector2(4.6, 2.6), new T.Vector2(-4.6, 2.6)]; return pts; }
function mailbox(style, color) { const g = new T.Group(); const c = new T.Color(color || '#2f6bff'); const m = new T.MeshStandardMaterial({ color: c, metalness: 0.4, roughness: 0.4 }); B(0.12, 1.2, 0.12, new T.MeshStandardMaterial({ color: 0x2a1a10 }), 0, 0.6, 0, g);
  if (style === 'modern') B(0.5, 0.7, 0.35, m, 0, 1.4, 0, g); else if (style === 'rocket') { const b = new T.Mesh(new T.CylinderGeometry(0.22, 0.22, 0.8, 16), m); b.position.y = 1.5; g.add(b); const n = new T.Mesh(new T.ConeGeometry(0.22, 0.35, 16), new T.MeshStandardMaterial({ color: 0xe11d48 })); n.position.y = 2.07; g.add(n); }
  else if (style === 'birdhouse') { B(0.5, 0.5, 0.5, m, 0, 1.45, 0, g); const r = new T.Mesh(new T.ConeGeometry(0.45, 0.35, 4), new T.MeshStandardMaterial({ color: 0x8a3a2a })); r.rotation.y = Math.PI / 4; r.position.y = 1.87; g.add(r); } else if (style === 'castle') { B(0.5, 0.6, 0.5, m, 0, 1.5, 0, g); for (const [x, z] of [[-0.18, -0.18], [0.18, -0.18], [-0.18, 0.18], [0.18, 0.18]]) B(0.12, 0.15, 0.12, m, x, 1.87, z, g); }
  else { const b = new T.Mesh(new T.CylinderGeometry(0.25, 0.25, 0.8, 16, 1, false, 0, Math.PI), m); b.rotation.z = Math.PI / 2; b.position.y = 1.45; g.add(b); B(0.5, 0.25, 0.8, m, 0, 1.33, 0, g); const flag = B(0.04, 0.3, 0.12, new T.MeshStandardMaterial({ color: 0xe11d48 }), 0.27, 1.55, 0.2, g); }
  return g; }

/* ---------- build a custom home from a spec (local −z faces the road) ---------- */
export function buildCustomHome(spec, opts = {}) {
  const s = Object.assign(DEFAULT_SPEC(), spec || {}); const g = new T.Group(); const boxes = []; const anim = [];
  const W = Math.min(22, Math.max(6, s.w)), D = Math.min(22, Math.max(6, s.d)), FL = Math.min(3, Math.max(1, s.floors)), fh = 3.4, H = FL * fh;
  const wm = matFor(s.wall, s.wall === 'glass' || s.wall === 'metal' ? null : s.wallColor, [W / 4, fh / 3]); const gl = matFor('glass'); const trim = new T.MeshStandardMaterial({ color: new T.Color(s.accent), metalness: 0.5, roughness: 0.35 });
  const vols = s.shape === 'L' ? [[0, 0, W, D], [W * 0.35, D * 0.7, W * 0.45, D * 0.55]] : s.shape === 'U' ? [[0, -D * 0.15, W, D * 0.6], [-W * 0.38, D * 0.35, W * 0.26, D * 0.5], [W * 0.38, D * 0.35, W * 0.26, D * 0.5]] : s.shape === 'court' ? [[0, -D * 0.4, W, D * 0.22], [0, D * 0.4, W, D * 0.22], [-W * 0.4, 0, W * 0.2, D * 0.6], [W * 0.4, 0, W * 0.2, D * 0.6]] : [[0, 0, W, D]];
  if (s.shape === 'tower') { const r = Math.min(W, D) / 2; const tw = new T.Mesh(new T.CylinderGeometry(r, r, H, 40), wm); tw.position.y = H / 2 + 0.2; g.add(tw); for (let f = 0; f < FL; f++) { const band = new T.Mesh(new T.CylinderGeometry(r + 0.03, r + 0.03, fh * 0.45 * s.windows / 60, 40, 1, true), gl); band.position.y = 0.2 + f * fh + fh * 0.55; g.add(band); } boxes.push([0, 0, r * 0.8, r * 0.8]); roof(g, s.roof === 'gable' || s.roof === 'shed' || s.roof === 'butterfly' ? 'hip' : s.roof, s.roofMat, r * 1.6, r * 1.6, 0, H + 0.2, 0, s.solar); }
  else for (const [vx, vz, vw, vd] of vols) { B(vw, H, vd, wm, vx, H / 2 + 0.2, vz, g); boxes.push([vx, vz, vw / 2 + 0.15, vd / 2 + 0.15]);
    for (let f = 0; f < FL; f++) { const wy = 0.2 + f * fh + fh * 0.55; const wh = fh * 0.5; const n = Math.max(1, Math.round(vw / 3 * s.windows / 50)); for (let i = 0; i < n; i++) { const wx = vx - vw / 2 + (i + 0.5) * vw / n; for (const sz of [-1, 1]) { const p = B(Math.min(2.6, vw / n * 0.7), wh, 0.08, gl, wx, wy, vz + sz * (vd / 2 + 0.03), g); p.userData.noOcclude = true; B(Math.min(2.6, vw / n * 0.7) + 0.16, 0.1, 0.2, trim, wx, wy - wh / 2, vz + sz * (vd / 2 + 0.06), g); } } if (f > 0) B(vw + 0.1, 0.18, vd + 0.1, trim, vx, 0.2 + f * fh, vz, g); }
    roof(g, s.roof, s.roofMat, vw, vd, vx, H + 0.2, vz, s.solar && vx === vols[0][0]); }
  // front door, steps, porch light
  const fz = -(s.shape === 'tower' ? Math.min(W, D) / 2 : (s.shape === 'court' ? D * 0.51 : s.shape === 'U' ? D * 0.45 : D / 2)) - 0.05; B(1.6, 2.6, 0.14, new T.MeshStandardMaterial({ color: 0x5a3a22, map: TEX.wood() }), 0, 1.5, fz, g); B(2.6, 0.2, 1.4, matFor('stone'), 0, 0.1, fz - 0.7, g); const lamp = new T.Mesh(new T.SphereGeometry(0.14, 10, 8), new T.MeshStandardMaterial({ color: 0xfff1c4, emissive: 0xffd88a, emissiveIntensity: 1.8 })); lamp.position.set(1.1, 2.7, fz - 0.15); g.add(lamp);
  // pool (+ fish), shaped by the owner
  if (s.pool !== 'none') { const pts = poolShape(s); const sh = new T.Shape(pts); const deep = Math.min(4, Math.max(0.5, s.poolDepth)); const col = new T.Color().setHSL(0.53, 0.75, 0.62 - deep * 0.07); const water = new T.Mesh(new T.ShapeGeometry(sh, 24), new T.MeshStandardMaterial({ color: col, transparent: true, opacity: 0.86, roughness: 0.08, metalness: 0.2 })); water.rotation.x = -Math.PI / 2; const pz = D / 2 + 6; water.position.set(0, 0.3, pz); g.add(water);
    const rim = new T.Mesh(new T.ExtrudeGeometry(new T.Shape(pts.map(p => p.clone().multiplyScalar(1.08))).holes.length ? sh : (() => { const o = new T.Shape(pts.map(p => p.clone().multiplyScalar(1.12))); o.holes.push(new T.Path(pts)); return o; })(), { depth: 0.3, bevelEnabled: false }), matFor('stone')); rim.rotation.x = -Math.PI / 2; rim.position.set(0, 0.32, pz); g.add(rim);
    if (s.fish !== 'none') { const fish = []; for (let i = 0; i < (s.fish === 'sharks' ? 2 : 6); i++) { const f = fishMesh(s.fish, i); g.add(f); fish.push([f, i]); } anim.push((t) => { for (const [f, i] of fish) { const a = t * (0.4 + i * 0.05) + i; const rr = s.pool === 'round' ? 1.8 : 2.4; f.position.set(Math.cos(a) * rr * 1.3, 0.12 - deep * 0.03, pz + Math.sin(a) * rr * 0.6); f.rotation.y = -a; } }); }
    if (s.hottub) { const ht = new T.Mesh(new T.CylinderGeometry(1.2, 1.2, 0.8, 24), matFor('wood')); ht.position.set(6.2, 0.4, pz + 2); g.add(ht); const hw2 = new T.Mesh(new T.CircleGeometry(1.05, 24), new T.MeshStandardMaterial({ color: 0x7ad8ff, emissive: 0x0b4f80, emissiveIntensity: 0.4 })); hw2.rotation.x = -Math.PI / 2; hw2.position.set(6.2, 0.81, pz + 2); g.add(hw2); } }
  // garden beds with living flowers
  if (s.garden) { const bed = new T.Group(); bed.position.set(-W / 2 - 1.2, 0.2, -D / 2 - 3); g.add(bed); B(2.2, 0.4, 5, matFor('wood'), 0, 0.2, 0, bed); const kinds = ['columbine', 'tulip', 'lupine', 'sunflower', 'allium']; const list = []; for (let i = 0; i < 8; i++) list.push([kinds[i % 5], (i % 2 - 0.5) * 0.9, -2 + i * 0.55, 0.9 + (i % 3) * 0.2, 0.4]); bed.userData.flowers = list; }
  // wind turbine, fence, trees
  if (s.wind) { const wt = new T.Group(); wt.position.set(W / 2 + 4, 0, D / 2 + 2); g.add(wt); const pole = new T.Mesh(new T.CylinderGeometry(0.1, 0.18, 9, 10), new T.MeshStandardMaterial({ color: 0xf4f6f8 })); pole.position.y = 4.5; wt.add(pole); const hub = new T.Group(); hub.position.set(0, 9.1, 0.3); wt.add(hub); for (let i = 0; i < 3; i++) { const bl = B(0.25, 3, 0.05, new T.MeshStandardMaterial({ color: 0xffffff }), 0, 1.5, 0, null); const piv = new T.Group(); piv.rotation.z = i * 2.094; piv.add(bl); hub.add(piv); } anim.push((t) => { hub.rotation.z = t * 2; }); }
  if (s.fence) { const fm = new T.MeshStandardMaterial({ color: 0xf4f1ea }); const fx = W / 2 + 6, fzz = D / 2 + 11; for (let x = -fx; x <= fx; x += 1.2) { B(0.12, 1, 0.12, fm, x, 0.5, fzz, g); } B(fx * 2, 0.08, 0.06, fm, 0, 0.85, fzz, g); }
  for (let i = 0; i < Math.min(6, s.trees || 0); i++) { const tx = (i % 2 ? 1 : -1) * (W / 2 + 3 + (i >> 1) * 1.5), tz = -D / 2 + 2 + i * 2.6; const tr = new T.Mesh(new T.CylinderGeometry(0.15, 0.25, 2.4, 8), new T.MeshStandardMaterial({ color: 0x6b4a2a })); tr.position.set(tx, 1.2, tz); g.add(tr); const cr = new T.Mesh(new T.IcosahedronGeometry(1.6, 1), new T.MeshStandardMaterial({ color: [0x3f8a3a, 0x4caf50, 0x2e7d32][i % 3], flatShading: true })); cr.position.set(tx, 3.2, tz); g.add(cr); boxes.push([tx, tz, 0.4, 0.4]); }
  // mailbox + notice sign at the road
  const mb = mailbox(s.mailbox, s.mailColor); mb.position.set(W / 2 + 1.5, 0, -D / 2 - 6.5); g.add(mb); g.userData.mailbox = mb;
  if (s.sign) { const sg = makeSprite(s.sign.slice(0, 40), { scale: 4.2, accent: s.signColor || '#ff4fd8' }); sg.position.set(0, H + 3.4, -D / 2); g.add(sg); }
  if (opts.addr) { const pl = makeSprite('📍 ' + opts.addr, { scale: 3.2, accent: '#ffd23f' }); pl.position.set(-W / 2 - 1.5, 1.8, -D / 2 - 6.5); g.add(pl); }
  if (s.fireworks) { const sparks = []; const cols = [0xff4f79, 0x38f0ff, 0xffd23f, 0x7cff6b, 0xb08cff]; for (let i = 0; i < 24; i++) { const sp = new T.Mesh(new T.SphereGeometry(0.12, 6, 4), new T.MeshBasicMaterial({ color: cols[i % 5] })); sp.visible = false; g.add(sp); sparks.push(sp); } anim.push((t) => { const k = (t % 4) / 4; for (let i = 0; i < sparks.length; i++) { const a = i / sparks.length * Math.PI * 2; const sp = sparks[i]; sp.visible = k > 0.3; const r = (k - 0.3) * 9; sp.position.set(Math.cos(a) * r, H + 9 + Math.sin(a) * r - (k - 0.3) * (k - 0.3) * 8, 0); } }); }
  // Lifeblocks
  if (s.blocks && s.blocks.length) { const byMat = {}; for (const b of s.blocks.slice(0, 400)) (byMat[b[3]] = byMat[b[3]] || []).push(b); const m4 = new T.Matrix4(); for (const [mk, list] of Object.entries(byMat)) { const im = new T.InstancedMesh(new T.BoxGeometry(1, 1, 1), matFor(mk, (BLOCK_MATS.find(q => q[0] === mk) || [])[1]), list.length); list.forEach((b, i) => { m4.makeTranslation(-W / 2 - 9 + b[0] + 0.5, b[1] + 0.5 + 0.2, -2 + b[2] + 0.5); im.setMatrixAt(i, m4); }); im.castShadow = !MOB; g.add(im); } boxes.push([-W / 2 - 4, 3, 5.2, 5.2]); }
  g.userData.anim = anim; g.traverse(o => { if (o.isMesh && o.castShadow === undefined) o.castShadow = !MOB; });
  return { group: g, boxes, spec: s };
}

/* ---------- addresses: street + hashed address code ---------- */
const STREETS = ['Unity Road', 'Kindness Lane', 'Harmony Way', 'Sunrise Drive', 'Peace Parkway', 'Starlight Avenue', 'Friendship Court', 'Hope Street', 'Meadow Loop', 'Gratitude Row'];
export async function addressCode(seed) { const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode('allofus.one|' + seed)); const b = new Uint8Array(buf); const A = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; let out = ''; for (let i = 0; i < 10; i++) out += A[b[i] % 32]; return { code: out.slice(0, 4) + '-' + out.slice(4, 8) + '-' + out.slice(8), num: 1 + ((b[10] << 8 | b[11]) % 9899), street: STREETS[b[12] % STREETS.length], hash: [...b].map(x => x.toString(16).padStart(2, '0')).join('') }; }
export const ESTATE_ADDR = [{ slug: 'founder', name: 'No. 1 Unity Road', owner: 'Zach', place: 'mansion', street: '1 Unity Road' }, { slug: 'silk', name: '8 Silk Lane', owner: 'Steph', place: 'silk', street: '8 Silk Lane' }, { slug: 'coburn', name: 'Coburn\'s Place', owner: 'Coburn', place: 'coburn', street: '1 Summit Way' }];

/* ============================================================
   init: custom homes in the world, directory, deep links, builder
   ============================================================ */
export function initBuild(app, W, UI) {
  const DB = UI.DB; const getMe = () => UI.getMe && UI.getMe(); const codes = new Map(); const homePlaces = new Set();
  // custom homes replace the stock style when the owner has a saved build
  W.buildCustom = (claim) => { const prof = W.profileCache && W.profileCache.get(claim.owner); const me = getMe(); const home = (me && me.id === claim.owner ? me.home : prof && prof.home) || {}; if (!home.build) return null; const H = buildCustomHome(home.build, { addr: home.addr ? home.addr.num + ' ' + home.addr.street : '' }); if (H.group.userData.anim.length) { const an = H.group.userData.anim; const f = (dt, t) => { if (!H.group.parent) { app.updaters = app.updaters.filter(q => q !== f); return; } for (const a of an) a(t); }; app.onUpdate(f); }
    H.group.traverse(o => { if (o.userData.flowers) setTimeout(() => plantGarden(app, o, o.userData.flowers, { birds: 1, range: 70 }), 50); }); return H; };
  const refreshHomes = async () => { for (const c of W.claims.values()) { const a = await addressCode('lot|' + c.id + '|' + c.owner); c.addr = a; codes.set(a.code, { claim: c }); if (!homePlaces.has(c.id)) { homePlaces.add(c.id); const prof = W.profileCache && W.profileCache.get(c.owner); app.addPlace({ id: 'home-' + c.id, name: '🏡 ' + (c.name || 'Home'), icon: '🏡', x: c.x, z: c.z + 12, cat: 'Homes', keys: [c.name, prof && prof.name, a.num + ' ' + a.street, a.code].join(' '), say: (c.name || 'A home') + ' · ' + a.num + ' ' + a.street }); } try { W.chunks.rebuildAt(c.x, c.z); } catch (e) { } } for (const e of ESTATE_ADDR) { const a = await addressCode('estate|' + e.slug); e.code = a.code; codes.set(a.code, { estate: e }); } };
  setTimeout(refreshHomes, 3500); setInterval(refreshHomes, 120000);
  const doorOf = (hit) => { if (hit.estate) return (app.places || []).find(p => p.id === hit.estate.place); const c = hit.claim; const lot = W.lots.get(c.id); const face = lot ? lot.face : 0; return { id: '_door', name: c.name || 'Home', icon: '🚪', x: c.x + Math.sin(face) * 13, z: c.z + Math.cos(face) * 13, keys: '', say: '🚪 You are at the door of ' + (c.name || 'this home') + '. Tap the mailbox to say hi.' }; };
  const linkFor = (code) => location.origin + '/?to=' + encodeURIComponent(code);
  // deep links: ?to=CODE (a home or estate) · ?place=id (any place)
  setTimeout(async () => { try { const q = new URLSearchParams(location.search); const to = q.get('to'), pl = q.get('place'); if (to) { await refreshHomes(); const hit = codes.get(to.toUpperCase()); if (hit) { const d = doorOf(hit); if (d) app.travel(d); } else app.toast('📍 That address was not found. It may have moved.'); } else if (pl) { const p = (app.places || []).find(x => x.id === pl); if (p) app.travel(p); } } catch (e) { } }, 5200);

  /* 📒 phone-book directory */
  const openDirectory = async (tab = 'places') => { await refreshHomes().catch(() => { }); const m = UI.modal('📒 Directory', `<div class="aou-tabs" id="dr-t"><button data-t="places" class="${tab === 'places' ? 'on' : ''}">📍 Places</button><button data-t="homes" class="${tab === 'homes' ? 'on' : ''}">🏡 Homes + addresses</button></div><div class="aou-compose"><input id="dr-q" placeholder="Search names, streets, address codes…" aria-label="Search the directory"></div><div id="dr-b" class="dr-list"></div><p class="muted2">Every home has a street address and a unique address code. Share the link and it walks people right to the door, from anywhere on the internet.</p>`, { wide: true });
    let cur = tab; const draw = () => { const q = ($('#dr-q', m).value || '').toLowerCase(); let rows = [];
      if (cur === 'places') { const cats = {}; for (const p of (app.places || [])) { if (p.id && (p.id.startsWith('home-') || p.id === 'zach' || p.id.startsWith('_'))) continue; if (q && !(p.name + ' ' + (p.keys || '') + ' ' + (p.cat || '')).toLowerCase().includes(q)) continue; (cats[p.cat || 'Places'] = cats[p.cat || 'Places'] || []).push(p); }
        const ord = ['Homes', 'Places', 'Fun', 'Life paths']; rows = Object.entries(cats).sort((a, b) => (ord.indexOf(a[0]) + 99) % 99 - (ord.indexOf(b[0]) + 99) % 99).map(([c, list]) => `<p class="aou-lbl">${esc(c)}</p>` + list.sort((a, b) => a.name.localeCompare(b.name)).map(p => `<div class="dr-row"><div><b>${esc(p.name)}</b><small>${esc((p.say || '').slice(0, 90))}</small></div><span><button class="lt-btn sm holo" data-go="${esc(p.id)}">Go</button><button class="lt-btn sm" data-lnk="place:${esc(p.id)}">🔗</button></span></div>`).join('')); }
      else { const homes = [...ESTATE_ADDR.map(e => ({ name: e.name, who: e.owner, street: e.street, code: e.code, hit: { estate: e } })), ...[...W.claims.values()].filter(c => c.addr).map(c => ({ name: c.name || 'Home', who: ((W.profileCache && W.profileCache.get(c.owner)) || {}).name || '', street: c.addr.num + ' ' + c.addr.street, code: c.addr.code, hit: { claim: c } }))].filter(h => !q || (h.name + h.who + h.street + h.code).toLowerCase().includes(q)).sort((a, b) => a.street.localeCompare(b.street, undefined, { numeric: true }));
        rows = [homes.map((h, i) => `<div class="dr-row"><div><b>${esc(h.name)}</b>${h.who ? ` <small>· ${esc(h.who)}</small>` : ''}<small>📍 ${esc(h.street)} · <code>${esc(h.code || '…')}</code></small></div><span><button class="lt-btn sm holo" data-door="${i}">🚪 Door</button><button class="lt-btn sm" data-lnk="${esc(h.code || '')}">🔗 Share</button></span></div>`).join('') || '<p class="lt-empty">No homes match.</p>']; m._homes = homes; }
      $('#dr-b', m).innerHTML = rows.join(''); };
    draw(); $('#dr-q', m).oninput = draw; $('#dr-q', m).onkeydown = (e) => e.stopPropagation(); $$('#dr-t button', m).forEach(b => b.onclick = () => { cur = b.dataset.t; $$('#dr-t button', m).forEach(x => x.classList.toggle('on', x === b)); draw(); });
    $('#dr-b', m).onclick = async (e) => { const go = e.target.closest('[data-go]'), door = e.target.closest('[data-door]'), lnk = e.target.closest('[data-lnk]');
      if (go) { const p = (app.places || []).find(x => x.id === go.dataset.go); UI.close(); if (p) app.travel(p); }
      if (door) { const h = m._homes[+door.dataset.door]; const d = doorOf(h.hit); UI.close(); if (d) app.travel(d); }
      if (lnk) { const v = lnk.dataset.lnk; if (!v) return; const url = v.startsWith('place:') ? location.origin + '/?place=' + encodeURIComponent(v.slice(6)) : linkFor(v); if (navigator.share) navigator.share({ title: 'Meet me on allofus.one', url }).catch(() => { }); else { navigator.clipboard && navigator.clipboard.writeText(url); app.toast('🔗 Link copied: ' + url); } } }; };

  /* 🏗️ the builder */
  const openBuilder = async () => { const me = getMe(); const h = (me && me.home) || {}; if (!me) { UI.close(); window.AOU.join && window.AOU.join('Join to build a home.'); return; } if (!h.lot) { const m0 = UI.modal('🏗️ Home builder', '<p>First claim your land. Walk past the Gateway down Unity Road and tap a green stake, then come back here.</p><p><button class="lt-btn holo" id="b-land">🌍 Take me to open land</button></p>'); $('#b-land', m0).onclick = () => { UI.close(); app.travel({ id: '_land', name: 'open land', icon: '🌍', x: 12, z: 214, keys: '', say: 'Green stakes = open land. Tap one to claim it.' }); }; return; }
    const spec = Object.assign(DEFAULT_SPEC(), h.build || {}); const addr = await addressCode('lot|' + h.lot + '|' + me.id);
    const sel = (key, list) => `<div class="aou-chips" data-k="${key}">${list.map(([v, l]) => `<button data-v="${v}" class="${String(spec[key]) === String(v) ? 'on' : ''}">${l}</button>`).join('')}</div>`;
    const m = UI.modal('🏗️ Home builder', `<div class="hb-wrap"><div class="hb-ctl"><div class="aou-tabs" id="hb-t">${['Shape', 'Walls', 'Roof', 'Yard', 'Blocks', 'Sign'].map((t, i) => `<button data-t="${t}" class="${i ? '' : 'on'}">${t}</button>`).join('')}</div><div id="hb-p"></div></div><div class="hb-view"><canvas id="hb-c" aria-label="Live 3D preview of your home. Drag to spin."></canvas><div class="hb-addr">📍 <b>${addr.num} ${addr.street}</b><br><code>${addr.code}</code></div><div class="lt-row"><button class="lt-btn holo" id="hb-save">💾 Save + build</button><button class="lt-btn" id="hb-share">🔗 Share my address</button><button class="lt-btn" id="hb-reset">↺ Reset</button></div></div></div>`, { full: true });
    const panels = {
      Shape: () => `<p class="aou-lbl">Footprint</p>${sel('shape', SHAPES)}<label>Width ${spec.w} m<input type="range" min="6" max="22" value="${spec.w}" data-n="w"></label><label>Depth ${spec.d} m<input type="range" min="6" max="22" value="${spec.d}" data-n="d"></label><p class="aou-lbl">Floors</p>${sel('floors', [[1, '1 story'], [2, '2 stories'], [3, '3 stories']])}<label>Windows ${spec.windows}%<input type="range" min="10" max="100" value="${spec.windows}" data-n="windows"></label>`,
      Walls: () => `<p class="aou-lbl">Wall material</p>${sel('wall', WALLS.map(w => [w[0], w[1]]))}<label>Wall tint<input type="color" value="${spec.wallColor}" data-c="wallColor"></label><label>Trim + accent<input type="color" value="${spec.accent}" data-c="accent"></label>`,
      Roof: () => `<p class="aou-lbl">Roof type</p>${sel('roof', ROOFS)}<p class="aou-lbl">Roof material</p>${sel('roofMat', ROOF_MATS)}<label class="hb-tg"><input type="checkbox" data-b="solar" ${spec.solar ? 'checked' : ''}> ☀️ Solar panels</label>`,
      Yard: () => `<p class="aou-lbl">Pool</p>${sel('pool', POOLS)}<div id="hb-draw" style="display:${spec.pool === 'custom' ? 'block' : 'none'}"><p class="muted2">Tap points to draw your pool outline (3 or more). It closes itself.</p><canvas id="hb-pd" width="300" height="180"></canvas><button class="lt-btn sm" id="hb-pclr">Clear</button></div><label>Depth ${spec.poolDepth} m<input type="range" min="0.5" max="4" step="0.1" value="${spec.poolDepth}" data-n="poolDepth"></label><p class="aou-lbl">Fish</p>${sel('fish', FISH)}<div class="hb-tgs">${[['hottub', '♨️ Hot tub'], ['garden', '🌸 Flower garden'], ['wind', '🌬️ Wind turbine'], ['fence', '🪵 Fence']].map(([k, l]) => `<label class="hb-tg"><input type="checkbox" data-b="${k}" ${spec[k] ? 'checked' : ''}> ${l}</label>`).join('')}</div><label>Trees ${spec.trees}<input type="range" min="0" max="6" value="${spec.trees}" data-n="trees"></label>`,
      Blocks: () => `<p class="muted2">Lifeblocks: build anything, block by block, beside your home. Each block gets its own fingerprint code.</p><div class="aou-chips" id="hb-bm">${BLOCK_MATS.map(([k], i) => `<button data-m="${k}" class="${i ? '' : 'on'}">${k}</button>`).join('')}</div><div class="lt-row">Level <select id="hb-lv">${[0, 1, 2, 3, 4, 5].map(l => `<option>${l}</option>`).join('')}</select><button class="lt-btn sm" id="hb-bclr">Clear all</button><span class="muted2" id="hb-bn">${spec.blocks.length} blocks</span></div><div class="hb-grid" id="hb-g">${[...Array(100)].map((_, i) => `<button data-i="${i}"></button>`).join('')}</div><p class="muted2" id="hb-fp"></p>`,
      Sign: () => `<label>Notice sign over your home (40 max, family friendly)<input id="hb-sg" maxlength="40" value="${esc(spec.sign)}" placeholder="Welcome friends!"></label><label>Sign color<input type="color" value="${spec.signColor}" data-c="signColor"></label><label class="hb-tg"><input type="checkbox" data-b="fireworks" ${spec.fireworks ? 'checked' : ''}> 🎆 Fireworks over my home</label><p class="aou-lbl">Mailbox</p>${sel('mailbox', MAILBOX)}<label>Mailbox color<input type="color" value="${spec.mailColor}" data-c="mailColor"></label>`,
    };
    let tab = 'Shape'; let lvl = 0, bmat = 'stone';
    // live preview
    const cv = $('#hb-c', m); const r = new T.WebGLRenderer({ canvas: cv, antialias: !MOB, alpha: true }); r.setPixelRatio(Math.min(2, devicePixelRatio)); r.outputColorSpace = T.SRGBColorSpace; const sc = new T.Scene(); const cam = new T.PerspectiveCamera(40, 1, 0.1, 400); sc.add(new T.HemisphereLight(0xffffff, 0x6b8a5a, 1.1)); const sun = new T.DirectionalLight(0xffffff, 1.6); sun.position.set(20, 30, -12); sc.add(sun); const gnd = new T.Mesh(new T.CircleGeometry(40, 48), new T.MeshStandardMaterial({ color: 0x7fb069 })); gnd.rotation.x = -Math.PI / 2; sc.add(gnd);
    let house = null, yaw = 0.7, pitch = 0.45, dist = 42, raf = 0, dragging = null; const anims = [];
    const rebuild = () => { if (house) { sc.remove(house); house.traverse(o => { if (o.geometry) o.geometry.dispose(); }); } const H = buildCustomHome(spec, { addr: addr.num + ' ' + addr.street }); house = H.group; anims.length = 0; anims.push(...H.group.userData.anim); sc.add(house); };
    const size = () => { const w = cv.clientWidth || 400, hh = cv.clientHeight || 300; r.setSize(w, hh, false); cam.aspect = w / hh; cam.updateProjectionMatrix(); };
    const loop = (t) => { if (!cv.isConnected) { r.dispose(); return; } if (!dragging) yaw += 0.003; cam.position.set(Math.sin(yaw) * Math.cos(pitch) * dist, Math.sin(pitch) * dist + 2, -Math.cos(yaw) * Math.cos(pitch) * dist + 4); cam.lookAt(0, 3, 4); for (const a of anims) a(t / 1000); r.render(sc, cam); raf = requestAnimationFrame(loop); };
    cv.onpointerdown = (e) => { cv.setPointerCapture(e.pointerId); dragging = { x: e.clientX, y: e.clientY, yaw, pitch }; }; cv.onpointermove = (e) => { if (!dragging) return; yaw = dragging.yaw + (e.clientX - dragging.x) * 0.01; pitch = Math.max(0.1, Math.min(1.3, dragging.pitch + (e.clientY - dragging.y) * 0.006)); }; cv.onpointerup = () => { dragging = null; }; cv.onwheel = (e) => { e.preventDefault(); dist = Math.max(16, Math.min(90, dist + e.deltaY * 0.04)); };
    rebuild(); setTimeout(() => { size(); raf = requestAnimationFrame(loop); }, 30); addEventListener('resize', size);
    UI.onClose = () => { cancelAnimationFrame(raf); r.dispose(); removeEventListener('resize', size); };
    const big = () => { if (spec.w * spec.d > 300 || (spec.floors === 3 && spec.w * spec.d > 200)) { if (!m._warned) { m._warned = true; app.toast('🌍 That is a big footprint. It could crowd the neighborhood: are you sure you need that much space? (max 22 × 22 m)', 6000); } } };
    const render = () => { $('#hb-p', m).innerHTML = panels[tab](); const P = $('#hb-p', m);
      $$('[data-k]', P).forEach(row => row.onclick = (e) => { const b = e.target.closest('button'); if (!b) return; const k = row.dataset.k; spec[k] = isNaN(+b.dataset.v) ? b.dataset.v : +b.dataset.v; render(); rebuild(); });
      $$('[data-n]', P).forEach(i => i.oninput = () => { spec[i.dataset.n] = +i.value; i.parentElement.firstChild.textContent = i.parentElement.firstChild.textContent.replace(/[\d.]+/, i.value); big(); rebuild(); });
      $$('[data-c]', P).forEach(i => i.oninput = () => { spec[i.dataset.c] = i.value; rebuild(); });
      $$('[data-b]', P).forEach(i => i.onchange = () => { spec[i.dataset.b] = i.checked; rebuild(); });
      const sg = $('#hb-sg', P); if (sg) { sg.onkeydown = (e) => e.stopPropagation(); sg.oninput = () => { spec.sign = sg.value; clearTimeout(m._st); m._st = setTimeout(rebuild, 400); }; }
      const pd = $('#hb-pd', P); if (pd) { const q = pd.getContext('2d'); const drawP = () => { q.fillStyle = '#e0f2fe'; q.fillRect(0, 0, 300, 180); q.strokeStyle = '#94a3b8'; for (let x = 0; x < 300; x += 20) { q.beginPath(); q.moveTo(x, 0); q.lineTo(x, 180); q.stroke(); } for (let y = 0; y < 180; y += 20) { q.beginPath(); q.moveTo(0, y); q.lineTo(300, y); q.stroke(); } if (spec.poolPts.length) { q.fillStyle = 'rgba(14,165,233,.6)'; q.beginPath(); spec.poolPts.forEach(([x, z], i) => { const px = 150 + x * 20, py = 90 + z * 20; i ? q.lineTo(px, py) : q.moveTo(px, py); }); q.closePath(); q.fill(); q.fillStyle = '#0c4a6e'; spec.poolPts.forEach(([x, z]) => { q.beginPath(); q.arc(150 + x * 20, 90 + z * 20, 4, 0, 6.28); q.fill(); }); } }; drawP();
        pd.onclick = (e) => { const rc = pd.getBoundingClientRect(); const x = ((e.clientX - rc.left) * 300 / rc.width - 150) / 20, z = ((e.clientY - rc.top) * 180 / rc.height - 90) / 20; if (spec.poolPts.length < 24) spec.poolPts.push([Math.round(x * 2) / 2, Math.round(z * 2) / 2]); drawP(); if (spec.poolPts.length >= 3) rebuild(); }; $('#hb-pclr', P).onclick = () => { spec.poolPts = []; drawP(); rebuild(); }; }
      if (tab === 'Blocks') { const gridEl = $('#hb-g', P); const paint = () => { $$('button', gridEl).forEach(b => { const i = +b.dataset.i; const x = i % 10, z = Math.floor(i / 10); const blk = spec.blocks.find(q => q[0] === x && q[1] === lvl && q[2] === z); const below = spec.blocks.find(q => q[0] === x && q[1] < lvl && q[2] === z); b.className = blk ? 'on m-' + blk[3] : below ? 'below' : ''; b.title = blk ? blk[3] + ' block' : 'empty'; }); $('#hb-bn', P).textContent = spec.blocks.length + ' blocks'; };
        paint(); $('#hb-lv', P).value = lvl; $('#hb-lv', P).onchange = (e) => { lvl = +e.target.value; paint(); }; $$('#hb-bm button', P).forEach(b => { b.classList.toggle('on', b.dataset.m === bmat); b.onclick = () => { bmat = b.dataset.m; $$('#hb-bm button', P).forEach(x => x.classList.toggle('on', x === b)); }; });
        gridEl.onclick = async (e) => { const b = e.target.closest('button'); if (!b) return; const i = +b.dataset.i; const x = i % 10, z = Math.floor(i / 10); const ix = spec.blocks.findIndex(q => q[0] === x && q[1] === lvl && q[2] === z); if (ix >= 0) spec.blocks.splice(ix, 1); else if (spec.blocks.length < 400) { spec.blocks.push([x, lvl, z, bmat]); const fp = await addressCode('block|' + me.id + '|' + x + ',' + lvl + ',' + z + '|' + bmat); $('#hb-fp', P).textContent = '🧱 Block fingerprint ' + fp.code + ' (' + bmat + ' at ' + x + ',' + lvl + ',' + z + ')'; } paint(); rebuild(); };
        $('#hb-bclr', P).onclick = () => { if (confirm('Clear all blocks?')) { spec.blocks = []; paint(); rebuild(); } }; } };
    $$('#hb-t button', m).forEach(b => b.onclick = () => { tab = b.dataset.t; $$('#hb-t button', m).forEach(x => x.classList.toggle('on', x === b)); render(); }); render();
    $('#hb-reset', m).onclick = () => { Object.assign(spec, DEFAULT_SPEC()); render(); rebuild(); };
    $('#hb-share', m).onclick = () => { const url = linkFor(addr.code); if (navigator.share) navigator.share({ title: 'Visit my home on allofus.one', text: addr.num + ' ' + addr.street, url }).catch(() => { }); else { navigator.clipboard && navigator.clipboard.writeText(url); app.toast('🔗 Copied: ' + url); } };
    $('#hb-save', m).onclick = async () => { const clean = window.AOU && window.AOU.clean; if (clean) spec.sign = clean(spec.sign); me.home = Object.assign({}, me.home, { build: JSON.parse(JSON.stringify(spec)), addr: { num: addr.num, street: addr.street, code: addr.code } }); try { await DB.saveMe(me); } catch (e) { app.toast('⚠️ Could not save: ' + (e.message || e)); return; } const c = W.claims.get(h.lot); if (c) { W.chunks.rebuildAt(c.x, c.z); } app.celebrate && app.celebrate('🏡'); app.toast('🏡 Saved and built at ' + addr.num + ' ' + addr.street + '!', 4200); };
  };
  injectCSS();
  return { openDirectory, openBuilder, addressCode, refreshHomes };
}
function injectCSS() { if (document.getElementById('hb-css')) return; const s = document.createElement('style'); s.id = 'hb-css'; s.textContent = `
.hb-wrap{display:grid;grid-template-columns:minmax(300px,420px) 1fr;gap:14px;height:100%;min-height:0}.hb-ctl{overflow:auto;padding-right:6px}.hb-view{display:flex;flex-direction:column;gap:8px;min-height:0}
#hb-c{flex:1;width:100%;min-height:300px;border-radius:18px;background:linear-gradient(#bfe3ff,#eaf6ff 60%,#d9f0d0);touch-action:none;cursor:grab}
.hb-addr{background:#fff7e6;border:1px solid #fde68a;border-radius:12px;padding:8px 12px;font-size:14px}.hb-addr code,.dr-row code{background:#0f172a;color:#7cff6b;border-radius:6px;padding:1px 6px;font-size:12.5px;letter-spacing:.06em}
.hb-ctl label{display:block;font-weight:800;font-size:13px;margin:10px 0 4px}.hb-ctl input[type=range]{width:100%;accent-color:#6366f1}.hb-ctl input[type=color]{width:56px!important;height:34px;padding:2px;display:block}
.hb-tgs{display:grid;grid-template-columns:1fr 1fr;gap:4px}.aou-body label.hb-tg{display:flex!important;flex-direction:row;align-items:center;gap:8px;font-weight:700}.aou-body .hb-tg input{width:20px!important;height:20px;flex:none}
#hb-pd{width:100%;max-width:300px;border-radius:10px;border:1px solid #cbd5e1;cursor:crosshair;display:block;margin:4px 0}
.hb-grid{display:grid;grid-template-columns:repeat(10,1fr);gap:3px;max-width:340px}.hb-grid button{aspect-ratio:1;border:1px solid #cbd5e1;border-radius:5px;background:#f8fafc;cursor:pointer;padding:0}.hb-grid button.below{background:#e2e8f0}
.hb-grid .m-stone{background:#a8a29e}.hb-grid .m-brick{background:#b45309}.hb-grid .m-wood{background:#a16207}.hb-grid .m-glass{background:#bae6fd}.hb-grid .m-gold{background:#facc15}.hb-grid .m-neon{background:#22d3ee;box-shadow:0 0 8px #22d3ee}.hb-grid .m-green{background:#4d7c0f}.hb-grid .m-slate{background:#475569}
.dr-list{max-height:56vh;overflow:auto}.dr-row{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:8px 4px;border-bottom:1px solid #f1f5f9}.dr-row b{font-size:14.5px}.dr-row small{display:block;color:#64748b}.dr-row span{display:flex;gap:6px;flex:none}
@media (max-width:820px){.hb-wrap{display:flex;flex-direction:column;height:auto}.hb-view{order:-1;flex:none}#hb-c{min-height:230px;height:230px;flex:none}.hb-ctl{overflow:visible;padding-right:0}}
`; document.head.appendChild(s); }
