/* 📊 allofus.one admin dashboard (needs allofus-v13.sql). Admins only (checked in the database, not here).
   KPIs, signups with emails + last seen, who is online right now (feed / 3D / VR / mall), 30-day charts drawn as
   inline SVG, a live activity ticker, bugs, Hearts and Brand tables. Realtime: new signups, posts, presence and
   bugs push in while the page is open; everything else refreshes every 60 s. */
export const ADMIN_CSS = `.ad-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px}.ad-kpi{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:12px 14px}.ad-kpi b{display:block;font:900 28px/1 Poppins,Arial;color:#14183a}.ad-kpi small{display:block;font:700 11px Poppins,Arial;color:#64748b;margin-top:4px;letter-spacing:.04em;text-transform:uppercase}.ad-kpi.live b{color:#16a34a}.ad-kpi .d{display:inline-block;width:8px;height:8px;border-radius:50%;background:#16a34a;box-shadow:0 0 0 4px rgba(22,163,74,.15);margin-right:6px;animation:adPulse 1.6s infinite}@keyframes adPulse{0%,100%{opacity:1}50%{opacity:.4}}
.ad-chart{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:12px 14px;margin-top:10px}.ad-chart h4{margin:0 0 6px;font:900 13px Poppins,Arial}.ad-chart svg{width:100%;height:120px;display:block}.ad-chart .lg{display:flex;gap:12px;font:700 11px Poppins,Arial;color:#64748b;margin-top:4px}.ad-chart .lg i{display:inline-block;width:10px;height:10px;border-radius:3px;margin-right:4px;vertical-align:-1px}
.ad-tbl{width:100%;border-collapse:collapse;font-size:12px}.ad-tbl th{text-align:left;font:800 10px Poppins,Arial;color:#64748b;letter-spacing:.06em;text-transform:uppercase;padding:6px;border-bottom:1px solid #e2e8f0}.ad-tbl td{padding:7px 6px;border-top:1px solid #f1f5f9;vertical-align:top}.ad-tbl .on{color:#16a34a;font-weight:800}.ad-tick{max-height:360px;overflow:auto}.ad-tick div{padding:6px 0;border-top:1px solid #f1f5f9;font-size:12px}.ad-tick b{color:#14183a}.ad-tick .k{display:inline-block;min-width:58px;font:800 10px Poppins,Arial;letter-spacing:.06em;text-transform:uppercase;color:#fff;border-radius:999px;padding:2px 8px;margin-right:6px;text-align:center}.ad-tick .k.signup{background:#16a34a}.ad-tick .k.post{background:#0ea5e9}.ad-tick .k.comment{background:#6366f1}.ad-tick .k.page{background:#f59e0b}.ad-tick .k.hearts{background:#e11d48}.ad-tick .k.bug{background:#ef4444}.ad-new{animation:adNew 1.2s ease-out}@keyframes adNew{from{background:#fef9c3}to{background:transparent}}
.ad-tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}`;
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const ago = (t) => { if (!t) return '—'; const s = (Date.now() - new Date(t).getTime()) / 1000; if (s < 60) return 'just now'; if (s < 3600) return Math.floor(s / 60) + 'm ago'; if (s < 86400) return Math.floor(s / 3600) + 'h ago'; return Math.floor(s / 86400) + 'd ago'; };
const fmt = (n) => (n == null ? '—' : Number(n).toLocaleString());
/* tiny inline SVG charts: no library, no requests */
const days = (n) => { const out = []; for (let i = n - 1; i >= 0; i--) { const d = new Date(); d.setDate(d.getDate() - i); out.push(d.toISOString().slice(0, 10)); } return out; };
const series = (rows, n) => { const m = {}; (rows || []).forEach(r => { m[String(r.d).slice(0, 10)] = +r.n; }); return days(n).map(d => m[d] || 0); };
const bars = (vals, color) => { const W = 600, H = 110, pad = 4; const mx = Math.max(1, ...vals); const bw = (W - pad * 2) / vals.length; return `<svg viewBox="0 0 ${W} ${H + 14}" preserveAspectRatio="none">${vals.map((v, i) => { const h = v / mx * H; return `<rect x="${(pad + i * bw).toFixed(1)}" y="${(H - h).toFixed(1)}" width="${Math.max(1, bw - 2).toFixed(1)}" height="${h.toFixed(1)}" rx="2" fill="${color}"><title>${v}</title></rect>`; }).join('')}<text x="${pad}" y="${H + 12}" font-size="10" fill="#64748b" font-family="Poppins,Arial">${vals.length} days ago</text><text x="${W - pad}" y="${H + 12}" font-size="10" fill="#64748b" text-anchor="end" font-family="Poppins,Arial">today · peak ${mx}</text></svg>`; };
const lines = (a, b, ca, cb) => { const W = 600, H = 110, pad = 4; const mx = Math.max(1, ...a, ...b); const pt = (vals) => vals.map((v, i) => `${(pad + i * (W - pad * 2) / Math.max(1, vals.length - 1)).toFixed(1)},${(H - v / mx * H).toFixed(1)}`).join(' '); return `<svg viewBox="0 0 ${W} ${H + 4}" preserveAspectRatio="none"><polyline points="${pt(a)}" fill="none" stroke="${ca}" stroke-width="2.5" stroke-linejoin="round"/><polyline points="${pt(b)}" fill="none" stroke="${cb}" stroke-width="2.5" stroke-linejoin="round" stroke-dasharray="4 3"/></svg>`; };
export async function adminDash(body, { sb, me, names, fillNames, rightRail, wireRight, toast, opts }) {
  const what = opts.what || 'dash';
  body.innerHTML = `<div class="fl3"><aside><div class="fl-card"><h3>📊 Dashboard</h3><div class="fl-chips" style="flex-direction:column;align-items:stretch">${[['dash', 'Overview + live'], ['signups', 'Signups + emails'], ['online', 'Who is online'], ['bugs', 'Bug reports'], ['hearts', 'Hearts'], ['pages', 'Brand pages']].map(([k, n]) => `<a class="fl-btn sm ${k === what ? 'p' : ''}" href="/?v=admin&what=${k}">${n}</a>`).join('')}<a class="fl-btn sm" href="/boost/?tab=admin">searchBOOST leads</a></div><p class="muted" style="font-size:11px;margin-top:8px">Only your admin logins see this. Numbers refresh every 60 s; signups, posts, presence and bugs push in live.</p></div></aside><section id="ad-main"><div class="fl-card"><p class="muted">Loading…</p></div></section>${rightRail()}</div>`; wireRight();
  const main = body.querySelector('#ad-main'); let stats = null, signups = [], activity = [], err = '';
  const load = async () => { try { const [s1, s2, s3] = await Promise.all([sb.rpc('admin_stats', { p_days: 30 }), sb.rpc('admin_signups', { p_limit: 300 }), sb.rpc('admin_activity', { p_limit: 60 })]); if (s1.error) throw s1.error; stats = s1.data || {}; signups = s2.data || []; activity = s3.data || []; err = ''; } catch (e) { err = e.message || String(e); } };
  const draw = async () => { if (!main.isConnected) return; if (err) { main.innerHTML = `<div class="fl-card"><h3>Dashboard needs allofus-v13.sql</h3><p class="fl-err">${esc(err)}</p><p class="muted">Run the v13 file in Supabase and reload. Until then the older tables still work under Bug reports / Hearts / Brand pages.</p></div>`; return; } const S = stats || {}; const online = signups.filter(u => u.last_seen && Date.now() - new Date(u.last_seen).getTime() < 3 * 60000);
    if (what === 'dash') { const su = series(S.signups_by_day, 30), po = series(S.posts_by_day, 30), ac = series(S.active_by_day, 30); main.innerHTML = `<div class="ad-kpis"><div class="ad-kpi live"><b><span class="d"></span>${fmt(S.online)}</b><small>online now</small></div><div class="ad-kpi"><b>${fmt(S.members)}</b><small>members</small></div><div class="ad-kpi"><b>${fmt(S.today)}</b><small>joined today</small></div><div class="ad-kpi"><b>${fmt(S.week)}</b><small>joined this week</small></div><div class="ad-kpi"><b>${fmt(S.posts24)}</b><small>posts · 24 h</small></div><div class="ad-kpi"><b>${fmt(S.comments24)}</b><small>comments · 24 h</small></div><div class="ad-kpi"><b>${fmt(S.pages)}</b><small>brand pages</small></div><div class="ad-kpi"><b>${fmt(S.hearts)} · ${fmt(S.hearts_matches)}</b><small>hearts · matches</small></div><div class="ad-kpi"><b>${fmt(S.bugs7)}</b><small>bugs · 7 d</small></div></div>
      <div class="ad-chart"><h4>Signups per day · 30 days</h4>${bars(su, '#16a34a')}</div><div class="ad-chart"><h4>Posts per day vs people active per day</h4>${lines(po, ac, '#0ea5e9', '#6366f1')}<div class="lg"><span><i style="background:#0ea5e9"></i>posts</span><span><i style="background:#6366f1"></i>active members (signed in that day)</span></div></div>
      <div class="ad-chart"><h4>Where people are right now</h4><div class="fl-chips">${Object.entries(S.online_by || {}).map(([k, n]) => `<span class="fl-btn sm">${esc(k)} · ${n}</span>`).join('') || '<span class="muted">Nobody online this minute.</span>'}</div>${(S.top_groups || []).length ? `<h4 style="margin-top:10px">Busiest groups</h4><div class="fl-chips">${S.top_groups.map(g => `<a class="fl-btn sm" href="/?g=${esc(g.g)}">${esc(g.g)} · ${g.n}</a>`).join('')}</div>` : ''}</div>
      <div class="ad-chart"><h4>Live activity</h4><div class="ad-tick" id="ad-tick">${activity.map(a => `<div><span class="k ${esc(a.kind)}">${esc(a.kind)}</span><b>${esc(a.who)}</b> ${esc(a.what)} <span class="muted">· ${ago(a.at)}</span></div>`).join('') || '<div class="muted">Quiet.</div>'}</div></div>`; }
    else if (what === 'signups' || what === 'online') { const rows = what === 'online' ? online : signups; main.innerHTML = `<div class="fl-card"><h3>${what === 'online' ? '🟢 Online now · ' + rows.length : '👥 Signups · ' + rows.length}</h3><div style="overflow:auto"><table class="ad-tbl"><tr><th>Email</th><th>Name</th><th>Joined</th><th>Last sign-in</th><th>Last seen</th><th>Where</th></tr>${rows.map(u => { const on = u.last_seen && Date.now() - new Date(u.last_seen).getTime() < 3 * 60000; return `<tr><td><a href="mailto:${esc(u.email)}">${esc(u.email)}</a></td><td>${esc(u.display_name || '')}${u.username ? ' <a href="/?u=' + esc(u.username) + '">@' + esc(u.username) + '</a>' : ''}</td><td title="${esc(u.created_at)}">${ago(u.created_at)}</td><td>${ago(u.last_sign_in_at)}</td><td class="${on ? 'on' : ''}">${on ? '● online' : ago(u.last_seen)}</td><td>${esc(u.where || '')}</td></tr>`; }).join('') || '<tr><td colspan="6" class="muted">Nobody yet.</td></tr>'}</table></div><p class="muted" style="font-size:11px">Export: select the table and copy, or ask for a CSV button.</p></div>`; }
    else { const tbl = { bugs: ['bugs', 'id,created_at,user_id,kind,note,page,ua,extra'], hearts: ['hearts_reports', 'id,created_at,reporter,about,about_sample,reason'], pages: ['pages', 'id,created_at,owner_id,name,slug,phone,website'] }[what]; let rows = []; let e2 = ''; try { const r = await sb.from(tbl[0]).select(tbl[1]).order('created_at', { ascending: false }).limit(150); rows = r.data || []; e2 = r.error ? r.error.message : ''; } catch (e) { e2 = e.message; } await fillNames(rows.map(r => ({ user_id: r.user_id || r.reporter || r.owner_id }))); main.innerHTML = `<div class="fl-card"><h3>${esc(tbl[0])} · ${rows.length}</h3>${e2 ? '<p class="fl-err">' + esc(e2) + '</p>' : ''}<div style="overflow:auto"><table class="ad-tbl"><tr><th>When</th><th>Who</th><th>What</th></tr>${rows.map(r => `<tr><td style="white-space:nowrap">${ago(r.created_at)}</td><td><b>${esc((names[r.user_id || r.reporter || r.owner_id] || {}).name || (r.user_id || r.reporter || r.owner_id || 'anon').slice(0, 8))}</b></td><td>${esc(r.note || r.reason || (r.name ? r.name + ' · /?page=' + r.slug : '') || '')}${r.page ? '<br><small class="muted">' + esc(r.page) + '</small>' : ''}${r.extra && r.extra.near ? '<br><small class="muted">near ' + esc(r.extra.near) + ' · scale ' + esc(r.extra.scale) + ' · floor ' + esc(r.extra.floor) + (r.extra.lastMiss ? ' · aimed at ' + esc(r.extra.lastMiss) : '') + '</small>' : ''}${r.about_sample ? '<br><small class="muted">sample ' + esc(r.about_sample) + '</small>' : ''}</td></tr>`).join('') || '<tr><td colspan="3" class="muted">Nothing yet.</td></tr>'}</table></div></div>`; } };
  await load(); await draw();
  /* realtime pushes + 60 s refresh */
  let ch = null; try { ch = sb.channel('admin-live'); ['profiles', 'presence', 'feed_posts', 'bugs'].forEach(t => ch.on('postgres_changes', { event: '*', schema: 'public', table: t }, async (p) => { if (!main.isConnected) { try { sb.removeChannel(ch); } catch (e) { } return; } if (t === 'profiles' && p.eventType === 'INSERT') toast('🎉 New member: ' + (p.new.display_name || p.new.username || 'someone')); if (t === 'bugs' && p.eventType === 'INSERT') toast('🐞 New bug report'); await load(); await draw(); const tk = main.querySelector('#ad-tick div'); if (tk) tk.classList.add('ad-new'); })); ch.subscribe(); } catch (e) { }
  const iv = setInterval(async () => { if (!main.isConnected) { clearInterval(iv); return; } await load(); await draw(); }, 60000);
}
/* presence heartbeat: once a minute, from any surface */
export function heartbeat(sb, me, where) { if (!sb || !me) return; const beat = () => { try { sb.from('presence').upsert({ user_id: me.id, where, page: location.pathname + location.search.slice(0, 60), last_seen: new Date().toISOString() }).then(() => { }); } catch (e) { } }; beat(); const iv = setInterval(() => { if (document.visibilityState === 'visible') beat(); }, 60000); addEventListener('visibilitychange', () => { if (document.visibilityState === 'visible') beat(); }); return () => clearInterval(iv); }
