/* allofus.one · Connections panel + hugs inbox (Oct 9 2026)
   - connPanel(mount, ctx): a scrollable list of your connections — avatar, name, online dot (presence < 3 min,
     live through the `presence` realtime channel), online first. Right-click / long-press / the ⋯ button opens
     a context menu: Hug, Crush, High five, Wave, Cheer, Message, View page, Disconnect.
   - Hugs land in the `hugs` table (v17) and animate with the existing vibe burst; the receiver gets a toast + badge
     on load and live. Disconnect deletes the connections row (v17 delete policy). Demo mode: everything renders
     empty-safe, nothing throws. */
import { burst, sendVibe } from './aou-dm.js';
import { ic } from './aou-icons2.js';
const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export const HUG_KINDS = [['hug', '🤗', 'Hug', 'sent you a hug'], ['crush', '💘', 'Crush', 'has a crush on you'], ['highfive', '🙌', 'High five', 'high-fived you'], ['wave', '👋', 'Wave', 'waved at you'], ['cheer', '🎉', 'Cheer', 'cheered for you']];
export const CONNS_CSS = `
#conn-panel .cp-list{max-height:340px;overflow:auto;scrollbar-width:thin;margin:0 -6px;padding:0 6px}#conn-panel .cp-row{display:flex;align-items:center;gap:9px;padding:6px 6px;border-radius:12px;position:relative;user-select:none;-webkit-user-select:none}#conn-panel .cp-row:hover,#conn-panel .cp-row.on{background:#f1f5f9}#conn-panel .cp-row .av{width:36px;height:36px;border-radius:50%;background:#e0f2fe center/cover;display:grid;place-items:center;font:900 14px var(--ff);color:#0b1a3a;flex:none;position:relative}#conn-panel .cp-row .av i{position:absolute;right:-1px;bottom:-1px;width:11px;height:11px;border-radius:50%;background:#cbd5e1;border:2px solid #fff}#conn-panel .cp-row.online .av i{background:#16a34a;box-shadow:0 0 0 2px rgba(22,163,74,.25)}#conn-panel .cp-row b{font-size:13px;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#conn-panel .cp-row small{color:#64748b;font-size:11px;display:block}#conn-panel .cp-row .nm{flex:1;min-width:0}#conn-panel .cp-row .more{border:0;background:transparent;border-radius:10px;width:30px;height:30px;cursor:pointer;color:#64748b;font:900 16px var(--ff);display:grid;place-items:center}#conn-panel .cp-row .more:hover{background:#e2e8f0;color:#0f172a}#conn-panel .cp-sum{display:flex;align-items:center;gap:6px;font:700 12px var(--ff);color:#64748b;margin:0 0 6px}#conn-panel .cp-sum .on-dot{margin:0}#conn-panel .cp-sum .badge{margin-left:auto;background:#ff3b5c;color:#fff;border-radius:12px;font:900 10px var(--ff);padding:2px 7px}
.cp-menu{position:fixed;z-index:160;background:#fff;border:1px solid #e2e8f0;border-radius:14px;box-shadow:0 16px 40px rgba(2,8,30,.2);padding:6px;min-width:200px;animation:fmIn .15s ease-out}.cp-menu button,.cp-menu a{display:flex;gap:9px;align-items:center;width:100%;border:0;background:transparent;text-align:left;padding:8px 10px;border-radius:10px;font:700 13px var(--ff);color:#14183a;cursor:pointer;text-decoration:none}.cp-menu button:hover,.cp-menu a:hover,.cp-menu button:focus-visible{background:#f1f5f9}.cp-menu .hic{width:18px;height:18px;color:var(--tc,#0ea5e9)}.cp-menu hr{border:0;border-top:1px solid #eef2f7;margin:4px 0}.cp-menu .hd{font:800 11px var(--ff);letter-spacing:.06em;text-transform:uppercase;color:#64748b;padding:6px 10px 2px}
.hug-toast{position:fixed;left:50%;top:14px;transform:translateX(-50%);z-index:150;width:max-content;max-width:min(92vw,560px);background:#fff;color:#14183a;border:1.5px solid #fbcfe8;border-radius:14px;padding:10px 14px;font:700 13px var(--ff);box-shadow:0 14px 34px rgba(2,8,30,.2);display:flex;gap:10px;align-items:center;max-width:92vw;animation:fmIn .25s ease-out}.hug-toast .big{font-size:26px;color:#ec4899;display:inline-flex}.hug-toast .big .hic{width:28px;height:28px}.hug-toast a{color:#0ea5e9;text-decoration:none}.hug-toast button{border:0;background:#f1f5f9;border-radius:10px;padding:6px 10px;cursor:pointer;font:800 12px var(--ff)}`;
/* ctx: { sb, me, names, fillNames, loadConns, presence, loadPresence, toast, needMe, live } */
export async function connPanel(mount, ctx) {
  const { sb, me, names, fillNames, toast } = ctx; if (!mount) return;
  if (!me) { mount.innerHTML = `<h3>${ic('🤝')} Connections</h3><p class="muted">Your people show here once you join. You start connected with Zach, the founder.</p>`; return; }
  mount.innerHTML = `<h3>${ic('🤝')} Connections</h3><div class="cp-sum"><span class="on-dot"></span><span data-sum>Loading…</span></div><div class="cp-list" role="list"></div>`;
  const list = mount.querySelector('.cp-list'), sum = mount.querySelector('[data-sum]'); let c; try { c = await ctx.loadConns(); } catch (e) { c = { ok: [], pendIn: [], pendOut: [] }; }
  const ids = (c.ok || []).slice(); try { await fillNames(ids.map(i => ({ user_id: i }))); await ctx.loadPresence(ids); } catch (e) { }
  const isOn = (id) => { const p = ctx.presence[id]; return !!(p && Date.now() - new Date(p.last_seen).getTime() < 180000); };
  const where = (id) => { const p = ctx.presence[id]; return p && p.where ? ({ feed: 'on the Feed', '3d': 'in 3D', vr: 'in VR', mall: 'in the mall' })[p.where] || p.where : ''; };
  const draw = () => { const sorted = ids.slice().sort((a, b) => (isOn(b) ? 1 : 0) - (isOn(a) ? 1 : 0) || String((names[a] || {}).name || '').localeCompare(String((names[b] || {}).name || ''))); const on = sorted.filter(isOn).length; sum.textContent = ids.length ? `${on} of ${ids.length} online` : 'No connections yet'; list.innerHTML = sorted.length ? sorted.map(id => { const n = names[id] || {}; return `<div class="cp-row ${isOn(id) ? 'online' : ''}" role="listitem" data-id="${esc(id)}" data-u="${esc(n.username || '')}" tabindex="0"><div class="av" ${n.avatar ? `style="background-image:url(${esc(n.avatar)});color:transparent"` : ''}>${esc((n.name || 'F')[0])}<i></i></div><div class="nm"><b>${esc(n.name || 'Friend')}</b><small>${isOn(id) ? 'online · ' + esc(where(id)) : (n.username ? '@' + esc(n.username) : '')}</small></div><button class="more" aria-label="Options for ${esc(n.name || 'this connection')}" aria-haspopup="menu">⋯</button></div>`; }).join('') : `<p class="muted" style="font-size:12px">Find people under <a href="/?v=conn">Connections</a> or connect from any post.</p>`; wire(); };
  const menu = (row, x, y) => { closeMenu(); const id = row.dataset.id, u = row.dataset.u; const n = names[id] || {}; const m = document.createElement('div'); m.className = 'cp-menu'; m.setAttribute('role', 'menu'); m.innerHTML = `<div class="hd">${esc(n.name || 'Connection')}</div>${HUG_KINDS.map(([k, e, l]) => `<button role="menuitem" data-hug="${k}" style="--tc:#ec4899">${ic(e)} ${l}</button>`).join('')}<hr><a role="menuitem" href="/?v=dm&with=${esc(u)}" style="--tc:#8b5cf6">${ic('💬')} Message</a><a role="menuitem" href="/?u=${esc(u)}" style="--tc:#f59e0b">${ic('🙂')} View page</a><hr><button role="menuitem" data-disc style="--tc:#ef4444">${ic('✕')} Disconnect</button>`; document.body.appendChild(m); const r = m.getBoundingClientRect(); m.style.left = Math.max(8, Math.min(x, innerWidth - r.width - 8)) + 'px'; m.style.top = Math.max(8, Math.min(y, innerHeight - r.height - 8)) + 'px'; row.classList.add('on'); m.querySelectorAll('[data-hug]').forEach(b => b.onclick = async () => { closeMenu(); await sendHug(ctx, id, b.dataset.hug, u); }); m.querySelector('[data-disc]').onclick = async () => { closeMenu(); if (!confirm('Disconnect from ' + (n.name || 'this person') + '? You can reconnect later.')) return; try { const { error } = await sb.from('connections').delete().eq('kind', 'connect').or(`and(requester.eq.${me.id},addressee.eq.${id}),and(requester.eq.${id},addressee.eq.${me.id})`); if (error) throw error; toast('Disconnected.'); const i = ids.indexOf(id); if (i >= 0) ids.splice(i, 1); draw(); } catch (e) { toast('Could not disconnect: ' + (e.message || 'server not reachable')); } }; const f = m.querySelector('button'); f && f.focus(); m.addEventListener('keydown', (e) => { const items = [...m.querySelectorAll('[role=menuitem]')]; const i = items.indexOf(document.activeElement); if (e.key === 'ArrowDown') { e.preventDefault(); items[(i + 1) % items.length].focus(); } if (e.key === 'ArrowUp') { e.preventDefault(); items[(i - 1 + items.length) % items.length].focus(); } if (e.key === 'Escape') { closeMenu(); row.focus(); } }); };
  const closeMenu = () => { document.querySelectorAll('.cp-menu').forEach(x => x.remove()); list.querySelectorAll('.cp-row.on').forEach(x => x.classList.remove('on')); };
  if (!connPanel._doc) { connPanel._doc = true; document.addEventListener('click', (e) => { if (!e.target.closest('.cp-menu') && !e.target.closest('.cp-row .more')) closeMenu(); }); document.addEventListener('scroll', closeMenu, { passive: true }); }
  const wire = () => { list.querySelectorAll('.cp-row').forEach(row => { row.querySelector('.more').onclick = (e) => { e.stopPropagation(); const r = e.currentTarget.getBoundingClientRect(); menu(row, r.left - 170, r.bottom + 4); }; row.oncontextmenu = (e) => { e.preventDefault(); menu(row, e.clientX, e.clientY); }; let t = 0; row.addEventListener('touchstart', (e) => { t = setTimeout(() => { const r = row.getBoundingClientRect(); menu(row, r.left + 20, r.bottom); try { navigator.vibrate && navigator.vibrate(12); } catch (x) { } }, 480); }, { passive: true }); ['touchend', 'touchmove', 'touchcancel'].forEach(ev => row.addEventListener(ev, () => clearTimeout(t), { passive: true })); row.onkeydown = (e) => { if (e.key === 'Enter' || e.key === ' ' || e.key === 'ContextMenu' || (e.shiftKey && e.key === 'F10')) { e.preventDefault(); const r = row.getBoundingClientRect(); menu(row, r.left + 20, r.bottom); } }; row.ondblclick = () => { location.href = '/?u=' + (row.dataset.u || ''); }; }); };
  draw();
  /* live dots */
  try { if (ctx.live && sb.channel) { const ch = sb.channel('presence-panel-' + me.id).on('postgres_changes', { event: '*', schema: 'public', table: 'presence' }, (p) => { const r = p.new; if (!r || !ids.includes(r.user_id)) return; ctx.presence[r.user_id] = r; draw(); }).subscribe(); const iv = setInterval(() => { if (!mount.isConnected) { clearInterval(iv); try { sb.removeChannel(ch); } catch (e) { } } else draw(); }, 60000); } } catch (e) { }
}
/* send a hug / crush / high five / wave / cheer — lands in `hugs`; falls back to the messages vibe if v17 is not installed */
export async function sendHug(ctx, toId, kind, username) {
  const { sb, me, toast } = ctx; const K = HUG_KINDS.find(k => k[0] === kind) || HUG_KINDS[0]; if (!me) { ctx.needMe && ctx.needMe(); return; }
  if (toId === me.id) { burst(K[1]); toast(K[1] + ' Sent to yourself. Self-care counts.'); return; }
  try { const { error } = await sb.from('hugs').insert({ from_id: me.id, to_id: toId, kind }); if (error) throw error; burst(K[1]); toast(K[1] + ' ' + K[2] + ' sent' + (username ? ' to @' + username : '')); }
  catch (e) { if (/relation|hugs|schema cache|not reachable|Failed to fetch/i.test(String(e.message)) && username) { try { await sendVibe({ sb, me, toast }, username, kind === 'highfive' ? 'five' : kind === 'cheer' ? 'vibes' : kind); return; } catch (x) { } } toast(e.message || 'Could not send.'); }
}
/* incoming hugs: unseen ones on load (toast + badge), live ones as they land */
export async function hugsInbox(ctx) {
  const { sb, me, names, fillNames, toast } = ctx; if (!me || !ctx.live) return; const seen = new Set();
  const show = async (rows) => { rows = rows.filter(r => !seen.has(r.id)); if (!rows.length) return; rows.forEach(r => seen.add(r.id)); try { await fillNames(rows.map(r => ({ user_id: r.from_id }))); } catch (e) { } const r0 = rows[0]; const K = HUG_KINDS.find(k => k[0] === r0.kind) || HUG_KINDS[0]; const n = names[r0.from_id] || {}; burst(K[1]); const t = document.createElement('div'); t.className = 'hug-toast'; t.setAttribute('role', 'status'); t.innerHTML = `<span class="big">${ic(K[1]) || ''}</span><span><a href="/?u=${esc(n.username || '')}"><b>${esc(n.name || 'Someone')}</b></a> ${K[3]}${rows.length > 1 ? ` · <b>+${rows.length - 1}</b> more` : ''}</span><button data-back>${ic(K[1])} Back</button><button data-x aria-label="Dismiss">✕</button>`; const host = document.querySelector('#fl-body .fl3 > section') || document.querySelector('#fl-body'); if (host) { t.classList.add('inline'); host.prepend(t); } else document.body.appendChild(t); const bye = () => t.remove(); t.querySelector('[data-x]').onclick = bye; t.querySelector('[data-back]').onclick = async () => { bye(); await sendHug(ctx, r0.from_id, r0.kind, n.username); }; if (!t.classList.contains("inline")) setTimeout(bye, 9000); const b = document.querySelector('[data-badge="conn"]'); if (b) { b.textContent = String((+b.textContent || 0) + rows.length); b.hidden = false; } try { await sb.from('hugs').update({ seen_at: new Date().toISOString() }).in('id', rows.map(r => r.id)); } catch (e) { } };
  try { const { data } = await sb.from('hugs').select('id,from_id,kind,created_at').eq('to_id', me.id).is('seen_at', null).order('created_at', { ascending: false }).limit(20); if (data && data.length) show(data); } catch (e) { }
  try { const ch = sb.channel('hugs-' + me.id).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'hugs', filter: 'to_id=eq.' + me.id }, (p) => { if (p.new) show([p.new]); }).subscribe(); window.addEventListener('beforeunload', () => { try { sb.removeChannel(ch); } catch (e) { } }, { once: true }); } catch (e) { }
}
