/* ============================================================
   The GLOBAL COMMUNICATION HUB (v6) · every mailbox opens one.
   A spinning hologram globe, a console of toggles that really work,
   an inbox, and a send deck: direct message, connection request,
   phone-number request, package request, picture, GIF, file.
   Owners set what they accept with the EASY configurator; RSS/JSON
   feed of their public posts; socials; everything saved to their profile.
   ============================================================ */
const $ = (s, r = document) => r.querySelector(s); const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const SOCIALS = [['x', '𝕏 / X'], ['instagram', '📸 Instagram'], ['facebook', '📘 Facebook'], ['youtube', '▶️ YouTube'], ['tiktok', '🎵 TikTok'], ['linkedin', '💼 LinkedIn'], ['threads', '🧵 Threads'], ['bluesky', '🦋 Bluesky'], ['discord', '🎮 Discord'], ['twitch', '📺 Twitch'], ['pinterest', '📌 Pinterest'], ['snapchat', '👻 Snapchat'], ['whatsapp', '💬 WhatsApp'], ['signal', '🔒 Signal'], ['myspace', '🎸 MySpace'], ['website', '🌐 Website'], ['email', '📧 Email'], ['custom1', '➕ My own link'], ['custom2', '➕ My own link 2']];
const BLOCKED = /porn|xxx|onlyfans|sex|nsfw|escort|adult|xvideos|pornhub|fansly|nude/i;
const TOGGLES = [['feedPublic', '📰 Public feed', 'Anyone can read my public posts and subscribe'], ['dm', '💬 Direct messages', 'People can message me here'], ['connect', '🤝 Connection requests', 'People can ask to connect'], ['phone', '📱 Phone-number requests', 'People can ask for my number'], ['package', '📦 Package requests', 'People can ask to send me something physical'], ['pics', '🖼️ Pictures, GIFs + files', 'People can send me media'], ['ping', '📡 Ping me when online', 'People can ask to be told when I am in the world'], ['fax', '📠 Fax', 'Show my fax number (sent free through FaxZero)'], ['socials', '🔗 Show my socials', 'My links appear on my hub'], ['rss', '📡 RSS / JSON feed', 'Offer a feed link of my public posts']];
const ZACH = { socials: { x: 'https://x.com/eyetoad', facebook: 'https://www.facebook.com/share/1FCtkAgToH/', website: 'https://eyetoad.com/', youtube: 'https://www.youtube.com/@eyetoad', instagram: 'https://www.instagram.com/eyetoad/', linkedin: 'https://www.linkedin.com/company/eye-to-ad-media/', tiktok: 'https://www.tiktok.com/@eyetoad', email: 'mailto:info@eyetoad.com' }, bio: 'Hi, I\'m Zach. I built allofus.one so all of us can find each other, help each other and build something good together. Say hi any time.' };
export const HUB_CSS = `
#hub{position:fixed;inset:0;z-index:99988;background:radial-gradient(ellipse at 50% 20%,#0f2a5e,#050a1e 70%);color:#dff6ff;font-family:Poppins,"Segoe UI",Arial,sans-serif;display:grid;grid-template-rows:auto 1fr;overflow:hidden}
#hub .top{display:flex;align-items:center;gap:12px;padding:10px 16px;border-bottom:1px solid rgba(56,240,255,.25);background:rgba(5,10,30,.6)}#hub .top b{font:900 16px/1 Poppins,Arial;letter-spacing:.08em;color:#7cf8ff;text-shadow:0 0 10px #38f0ff}#hub .top small{color:#9fd3ff;flex:1}#hub .x{border:1px solid #38f0ff;background:transparent;color:#7cf8ff;border-radius:10px;width:38px;height:38px;font-size:16px;cursor:pointer}
#hub .grid{display:grid;grid-template-columns:320px 1fr 340px;gap:12px;padding:12px;min-height:0;overflow:auto}@media (max-width:1000px){#hub .grid{grid-template-columns:1fr;overflow:auto}}
#hub .pan{background:rgba(8,20,50,.7);border:1px solid rgba(56,240,255,.3);border-radius:16px;padding:12px 14px;box-shadow:inset 0 0 30px rgba(56,240,255,.05);min-height:0;overflow:auto}#hub .pan h3{margin:0 0 8px;font:900 12px Poppins,Arial;letter-spacing:.18em;color:#7cf8ff;text-transform:uppercase}#hub .led{display:inline-block;width:8px;height:8px;border-radius:50%;background:#7cff6b;box-shadow:0 0 8px #7cff6b;margin-right:6px;animation:hubled 2s infinite}@keyframes hubled{50%{opacity:.4}}
#hub .globe{text-align:center}#hub canvas{width:min(360px,80vw);height:min(360px,80vw);display:block;margin:0 auto}#hub .who{margin-top:4px}#hub .who h2{margin:4px 0;font:900 24px Poppins,Arial;color:#fff}#hub .who p{margin:4px auto;max-width:520px;color:#cfe9ff;font-size:14px}#hub .soc{display:flex;flex-wrap:wrap;gap:6px;justify-content:center;margin:8px 0}
#hub .btn{border:1px solid #38f0ff;background:rgba(56,240,255,.12);color:#dff6ff;border-radius:10px;padding:8px 12px;font:800 12.5px Poppins,Arial;cursor:pointer;text-decoration:none;display:inline-flex;gap:6px;align-items:center}#hub .btn.p{background:linear-gradient(135deg,#0ea5e9,#6366f1);border-color:transparent;color:#fff}#hub .btn.g{border-color:#7cff6b;color:#d9ffd0}#hub .btn.r{border-color:#ff4f79;color:#ffd0dc}#hub .btn:disabled{opacity:.4;cursor:not-allowed}
#hub .sw{display:flex;align-items:center;gap:10px;padding:8px 0;border-bottom:1px solid rgba(56,240,255,.12)}#hub .sw div{flex:1}#hub .sw b{display:block;font-size:13px;color:#fff}#hub .sw small{color:#9fd3ff;font-size:11px}#hub .tg{appearance:none;width:44px;height:24px;border-radius:12px;background:#10204f;border:1px solid #38f0ff;position:relative;cursor:pointer;transition:.25s;flex:none}#hub .tg::after{content:"";position:absolute;top:3px;left:3px;width:16px;height:16px;border-radius:50%;background:#7cf8ff;box-shadow:0 0 8px #38f0ff;transition:left .25s}#hub .tg:checked{background:#1b7a4a}#hub .tg:checked::after{left:23px;background:#7cff6b}
#hub input[type=text],#hub input[type=url],#hub textarea{width:100%;box-sizing:border-box;background:#06122e;border:1px solid rgba(56,240,255,.4);color:#fff;border-radius:10px;padding:8px 10px;font:600 13px Poppins,Arial;margin:4px 0}#hub textarea{min-height:70px}#hub label{display:block;font-size:11px;color:#9fd3ff;font-weight:800;margin-top:6px;letter-spacing:.06em}
#hub .deck{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:8px 0}#hub .deck button{text-align:left}#hub .msg{background:rgba(5,10,30,.6);border:1px solid rgba(56,240,255,.2);border-radius:12px;padding:8px 10px;margin:6px 0;font-size:13px}#hub .msg b{color:#fff}#hub .msg small{color:#9fd3ff}#hub .msg .acts{display:flex;gap:6px;margin-top:6px}#hub .msg img{max-width:100%;border-radius:8px;margin-top:6px}
#hub .stat{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px;margin:8px 0}#hub .stat div{background:rgba(5,10,30,.6);border:1px solid rgba(56,240,255,.2);border-radius:10px;padding:6px;text-align:center}#hub .stat b{display:block;font:900 18px Poppins,Arial;color:#7cf8ff}#hub .stat small{font-size:10px;color:#9fd3ff;letter-spacing:.08em}#hub .err{color:#ffb3c2;font-weight:800;min-height:1em}#hub .ok{color:#7cff6b;font-weight:800}
`;
export async function openHub({ sb, me, owner, toast = (m) => console.log(m), onClose }) {
  if (document.getElementById('hub')) return; if (!document.getElementById('hub-css')) { const st = document.createElement('style'); st.id = 'hub-css'; st.textContent = HUB_CSS; document.head.appendChild(st); }
  const mine = me && owner && me.id === owner.id; const cfg = Object.assign({ feedPublic: true, dm: true, connect: true, phone: false, package: false, pics: true, socials: true, rss: true, socialsLinks: {}, bio: '' }, (owner && owner.home && owner.home.hub) || {}); if (owner && owner.zach) { cfg.socialsLinks = Object.assign({}, ZACH.socials, cfg.socialsLinks); cfg.bio = cfg.bio || ZACH.bio; cfg.phone = true; cfg.package = true; }
  const el = document.createElement('div'); el.id = 'hub'; el.innerHTML = `<div class="top"><b>⬡ GLOBAL COMMUNICATION HUB</b><small><span class="led"></span>LINK ESTABLISHED · ${esc((owner && owner.name) || 'Someone')}'s port · ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small><button class="x" aria-label="Close">✕</button></div><div class="grid"><section class="pan" id="hub-in"><h3>${mine ? 'Incoming' : 'Status'}</h3><div id="hub-inbox">…</div></section><section class="pan globe"><canvas id="hub-globe" width="420" height="420" aria-hidden="true"></canvas><div class="who"><h2>${esc((owner && owner.name) || 'Someone')}</h2><p>${esc(cfg.bio || '')}</p><div class="soc" id="hub-soc"></div><div class="stat" id="hub-stat"></div><div class="soc"><a class="btn" href="/?u=${esc((owner && owner.username) || 'me')}">📰 ${mine ? 'My' : 'Their'} FLAT page + feed</a>${cfg.rss ? '<button class="btn" id="hub-rss">📡 Feed link</button>' : ''}</div></div></section><section class="pan" id="hub-right"><h3>${mine ? 'Easy configurator' : 'Send'}</h3><div id="hub-r">…</div></section></div>`;
  document.body.appendChild(el); const close = () => { el.remove(); cancelAnimationFrame(raf); onClose && onClose(); }; $('.x', el).onclick = close; el.addEventListener('keydown', (e) => e.stopPropagation());
  // the hologram globe
  const cv = $('#hub-globe', el), g = cv.getContext('2d'); let raf = 0, rot = 0; const R = 150, cx = 210, cy = 200; const pts = []; for (let i = 0; i < 90; i++) { pts.push([Math.random() * Math.PI * 2, (Math.random() - 0.5) * Math.PI * 0.9, Math.random()]); }
  const draw = () => { rot += 0.006; g.clearRect(0, 0, 420, 420); g.save(); const grad = g.createRadialGradient(cx, cy, R * 0.2, cx, cy, R * 1.25); grad.addColorStop(0, 'rgba(56,240,255,.18)'); grad.addColorStop(1, 'rgba(56,240,255,0)'); g.fillStyle = grad; g.fillRect(0, 0, 420, 420); g.strokeStyle = 'rgba(56,240,255,.55)'; g.lineWidth = 1;
    for (let la = -75; la <= 75; la += 15) { const r = R * Math.cos(la * Math.PI / 180), y = cy - R * Math.sin(la * Math.PI / 180) * 0.92; g.beginPath(); g.ellipse(cx, y, r, r * 0.22, 0, 0, Math.PI * 2); g.stroke(); }
    for (let lo = 0; lo < 180; lo += 22.5) { const a = lo * Math.PI / 180 + rot; g.beginPath(); for (let t = -Math.PI / 2; t <= Math.PI / 2 + 0.01; t += 0.1) { const x = cx + R * Math.cos(t) * Math.cos(a), y = cy - R * Math.sin(t) * 0.92; const z = Math.cos(t) * Math.sin(a); if (t === -Math.PI / 2) g.moveTo(x, y); else g.lineTo(x, y); g.globalAlpha = z > 0 ? 0.9 : 0.25; } g.stroke(); g.globalAlpha = 1; }
    for (const [lo, la, k] of pts) { const a = lo + rot; const z = Math.cos(la) * Math.sin(a); if (z < 0) continue; const x = cx + R * Math.cos(la) * Math.cos(a), y = cy - R * Math.sin(la) * 0.92; g.fillStyle = k > 0.8 ? '#ff4fd8' : k > 0.5 ? '#7cff6b' : '#ffd23f'; g.shadowColor = g.fillStyle; g.shadowBlur = 8; g.beginPath(); g.arc(x, y, 2.2 + (Math.sin(Date.now() / 300 + k * 10) + 1), 0, 6.28); g.fill(); g.shadowBlur = 0; }
    g.strokeStyle = 'rgba(124,248,255,.35)'; for (let y = 0; y < 420; y += 4) { g.globalAlpha = 0.08; g.beginPath(); g.moveTo(0, y); g.lineTo(420, y); g.stroke(); } g.globalAlpha = 1; const bg = g.createLinearGradient(0, cy + R * 0.9, 0, 420); bg.addColorStop(0, 'rgba(56,240,255,.35)'); bg.addColorStop(1, 'rgba(56,240,255,0)'); g.fillStyle = bg; g.beginPath(); g.moveTo(cx - 40, 420); g.lineTo(cx - R * 0.7, cy + R * 0.9); g.lineTo(cx + R * 0.7, cy + R * 0.9); g.lineTo(cx + 40, 420); g.fill(); g.restore(); raf = requestAnimationFrame(draw); }; draw();
  // socials + stats
  const soc = $('#hub-soc', el); if (cfg.socials) soc.innerHTML = SOCIALS.filter(([k]) => cfg.socialsLinks[k] && !BLOCKED.test(cfg.socialsLinks[k])).map(([k, n]) => `<a class="btn" href="${esc(cfg.socialsLinks[k])}" target="_blank" rel="noopener">${k.startsWith('custom') && cfg.socialsNames && cfg.socialsNames[k] ? '🔗 ' + esc(cfg.socialsNames[k]) : n}</a>`).join('') || '<span class="muted">No links shared yet.</span>'; if (cfg.fax && cfg.faxNumber) soc.innerHTML += `<a class="btn" href="https://faxzero.com/" target="_blank" rel="noopener">📠 Fax ${esc(cfg.faxNumber)} (free via FaxZero)</a>`; { const qr = document.createElement('div'); qr.style.cssText = 'margin:8px auto;text-align:center'; const link = 'https://allofus.one/?u=' + encodeURIComponent((owner && owner.username) || ''); qr.innerHTML = `<img alt="QR code to this hub" width="110" height="110" style="border-radius:10px;background:#fff;padding:4px" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(link)}"><div style="font-size:11px;color:#9fd3ff">📱 scan to open this hub · <button class="btn" style="padding:3px 8px;font-size:11px" id="hub-copy">copy link</button></div>`; $('#hub-stat', el).after(qr); qr.querySelector('#hub-copy').onclick = async () => { try { await navigator.clipboard.writeText(link); toast('🔗 Copied.'); } catch (e) { prompt('Copy this link:', link); } }; }
  const stat = $('#hub-stat', el); const fill = async () => { if (!sb || !owner) { stat.innerHTML = ''; return; } const [{ count: posts }, { count: conns }] = await Promise.all([sb.from('feed_posts').select('id', { count: 'exact', head: true }).eq('user_id', owner.id).eq('public', true), sb.from('hub_requests').select('id', { count: 'exact', head: true }).eq('to_user', owner.id).eq('kind', 'connect').eq('status', 'accepted')]); stat.innerHTML = `<div><b>${posts || 0}</b><small>PUBLIC POSTS</small></div><div><b>${conns || 0}</b><small>CONNECTIONS</small></div><div><b>${[cfg.dm, cfg.connect, cfg.phone, cfg.package, cfg.pics].filter(Boolean).length}</b><small>CHANNELS OPEN</small></div>`; }; fill();
  const rssBtn = $('#hub-rss', el); if (rssBtn) rssBtn.onclick = async () => { const base = (sb && sb.supabaseUrl) || ''; const key = (sb && sb.supabaseKey) || ''; const url = `${base}/rest/v1/feed_posts?select=id,text,kind,link,media,created_at&user_id=eq.${owner.id}&public=eq.true&order=created_at.desc&apikey=${key}`; const { data } = await sb.from('feed_posts').select('*').eq('user_id', owner.id).eq('public', true).order('created_at', { ascending: false }).limit(50); const rss = `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${esc(owner.name)} · allofus.one</title><link>https://allofus.one/?u=${esc(owner.username || '')}</link><description>Public posts</description>${(data || []).map(p => `<item><title>${esc((p.text || p.kind).slice(0, 80))}</title><link>https://allofus.one/?u=${esc(owner.username || '')}</link><pubDate>${new Date(p.created_at).toUTCString()}</pubDate><description>${esc(p.text || '')}</description></item>`).join('')}</channel></rss>`; const blob = new Blob([rss], { type: 'application/rss+xml' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = (owner.username || 'feed') + '.rss.xml'; a.click(); try { await navigator.clipboard.writeText(url); toast('📡 RSS file downloaded, and the live JSON feed link is copied.'); } catch (e) { toast('📡 RSS file downloaded.'); } };
  // inbox (mine) / status (theirs)
  const inbox = $('#hub-inbox', el); const loadInbox = async () => { if (!mine) { inbox.innerHTML = `<div class="msg"><b>Channels open</b><br>${TOGGLES.filter(([k]) => cfg[k] && k !== 'socials' && k !== 'rss' && k !== 'feedPublic').map(([, n]) => '✅ ' + n).join('<br>') || 'This person keeps their port closed for now.'}</div>${me ? '' : '<div class="msg">Sign in (🔑 Join) to send anything.</div>'}`; return; } if (!sb) { inbox.innerHTML = '<div class="msg">Offline.</div>'; return; } const { data, error } = await sb.from('hub_requests').select('*').eq('to_user', me.id).order('created_at', { ascending: false }).limit(60); if (error) { inbox.innerHTML = `<div class="msg">${esc(error.message)}<br><small>Run the v6 SQL if this says the table is missing.</small></div>`; return; } if (!data.length) { inbox.innerHTML = '<div class="msg">Quiet for now. 🌙</div>'; return; } const ids = [...new Set(data.map(r => r.from_user))]; const { data: ppl } = await sb.from('profiles').select('id,display_name,username').in('id', ids); const nm = {}; (ppl || []).forEach(p => nm[p.id] = p);
    const L = { dm: '💬 Message', connect: '🤝 Connection request', phone: '📱 Phone-number request', package: '📦 Package request', pic: '🖼️ Picture', gif: '🎞️ GIF', file: '📎 File' }; inbox.innerHTML = data.map(r => `<div class="msg" data-id="${r.id}"><b>${esc((nm[r.from_user] || {}).display_name || 'Someone')}</b> <small>· ${L[r.kind] || r.kind} · ${new Date(r.created_at).toLocaleDateString()} · ${r.status}</small>${r.body ? '<div>' + esc(r.body) + '</div>' : ''}${r.media ? (/\.(gif|png|jpe?g|webp)(\?|$)/i.test(r.media) ? `<img src="${esc(r.media)}" alt="">` : `<a class="btn" href="${esc(r.media)}" target="_blank" rel="noopener">📎 Open file</a>`) : ''}${(r.kind === 'connect' || r.kind === 'phone' || r.kind === 'package') && r.status === 'new' ? `<div class="acts"><button class="btn g" data-acc>✅ Accept</button><button class="btn r" data-dec>Decline</button></div>` : ''}${r.kind === 'dm' ? `<div class="acts"><button class="btn" data-reply="${esc((nm[r.from_user] || {}).username || '')}" data-reply-id="${r.from_user}">↩ Reply</button></div>` : ''}</div>`).join('');
    $$('[data-acc],[data-dec]', inbox).forEach(b => b.onclick = async () => { const id = +b.closest('.msg').dataset.id; await sb.from('hub_requests').update({ status: b.hasAttribute('data-acc') ? 'accepted' : 'declined' }).eq('id', id); toast(b.hasAttribute('data-acc') ? '✅ Accepted. They can see it in their hub.' : 'Declined.'); loadInbox(); fill(); }); $$('[data-reply]', inbox).forEach(b => b.onclick = () => { /* reply opens the flat DM thread with that person — the old path focused a box that only exists on other people's hubs */ if (b.dataset.reply) { location.href = '/?v=dm&with=' + encodeURIComponent(b.dataset.reply); return; } sendTo = b.dataset.replyId; drawRight(); const box = $('#hs-dm', el); if (box) box.focus(); }); }; let sendTo = owner ? owner.id : null; loadInbox();
  // right panel: configurator (mine) or send deck (theirs)
  const right = $('#hub-r', el); const drawRight = () => { if (mine) { right.innerHTML = TOGGLES.map(([k, n, d]) => `<div class="sw"><div><b>${n}</b><small>${d}</small></div><input type="checkbox" class="tg" data-k="${k}" ${cfg[k] ? 'checked' : ''}></div>`).join('') + `<label>ABOUT ME (shows on my hub)</label><textarea id="hc-bio" maxlength="400">${esc(cfg.bio || '')}</textarea><label>📠 FAX NUMBER (optional)</label><input type="text" id="hc-fax" value="${esc(cfg.faxNumber || '')}" placeholder="+1 303 555 0100"><p style="font-size:11px;color:#9fd3ff">Family friendly only: adult links are blocked automatically and get your hub closed.</p>` + SOCIALS.map(([k, n]) => `<label>${n}</label>${k.startsWith('custom') ? `<input type="text" data-sn="${k}" value="${esc((cfg.socialsNames || {})[k] || '')}" placeholder="Name it (e.g. My Etsy)" style="margin-bottom:2px">` : ''}<input type="url" data-s="${k}" value="${esc(cfg.socialsLinks[k] || '')}" placeholder="https://">`).join('') + `<div style="margin-top:10px"><button class="btn p" id="hc-save">💾 Save configuration</button> <span class="ok" id="hc-ok"></span></div><p style="font-size:11px;color:#9fd3ff;margin-top:8px">Your hub is the one port to you: people reach you here by whatever you allow. Your public feed and socials go wherever you let them.</p>`;
      $('#hc-save', el).onclick = async () => { TOGGLES.forEach(([k]) => { cfg[k] = $(`[data-k="${k}"]`, el).checked; }); cfg.bio = $('#hc-bio', el).value.trim(); cfg.faxNumber = ($('#hc-fax', el).value || '').trim(); cfg.socialsLinks = {}; cfg.socialsNames = {}; let bad = false; SOCIALS.forEach(([k]) => { const v = $(`[data-s="${k}"]`, el).value.trim(); if (v && BLOCKED.test(v)) { bad = true; return; } if (v) cfg.socialsLinks[k] = v; const nEl = $(`[data-sn="${k}"]`, el); if (nEl && nEl.value.trim()) cfg.socialsNames[k] = nEl.value.trim().slice(0, 30); }); if (bad) toast('🚫 One link was blocked: adult sites are not allowed here.'); me.home = Object.assign({}, me.home || {}, { hub: cfg }); try { await sb.from('profiles').update({ home: me.home }).eq('id', me.id); $('#hc-ok', el).textContent = 'Saved ✓'; toast('💾 Hub configured.'); } catch (e) { toast('Could not save: ' + (e.message || e)); } }; return; }
      const can = (k) => cfg[k]; right.innerHTML = `<div class="deck"><button class="btn ${can('dm') ? '' : ''}" data-k="dm" ${can('dm') ? '' : 'disabled'}>💬 Direct message</button><button class="btn" data-k="connect" ${can('connect') ? '' : 'disabled'}>🤝 Request connection</button><button class="btn" data-k="phone" ${can('phone') ? '' : 'disabled'}>📱 Request phone #</button><button class="btn" data-k="package" ${can('package') ? '' : 'disabled'}>📦 Package request</button><button class="btn" data-k="pic" ${can('pics') ? '' : 'disabled'}>🖼️ Send a picture</button><button class="btn" data-k="gif" ${can('pics') ? '' : 'disabled'}>🎞️ Send a GIF</button><button class="btn" data-k="file" ${can('pics') ? '' : 'disabled'}>📎 Send a file</button><button class="btn" data-k="ping" ${can('ping') ? '' : 'disabled'}>📡 Ping me when online</button>${cfg.fax && cfg.faxNumber ? `<a class="btn" href="https://faxzero.com/" target="_blank" rel="noopener">📠 Fax them (free)</a>` : ''}</div><label id="hs-l">MESSAGE</label><textarea id="hs-dm" maxlength="2000" placeholder="Say hi…"></textarea><input type="url" id="hs-url" placeholder="GIF address (https://…gif)" style="display:none"><input type="file" id="hs-f" style="display:none"><div style="margin-top:8px"><button class="btn p" id="hs-go">📡 TRANSMIT</button></div><p class="err" id="hs-err"></p>`;
      let kind = 'dm'; const pick = (k) => { kind = k; $$('.deck button', right).forEach(b => b.classList.toggle('p', b.dataset.k === k)); $('#hs-l', el).textContent = { dm: 'MESSAGE', connect: 'WHY CONNECT? (optional)', phone: 'WHY DO YOU NEED IT? (optional)', package: 'WHAT ARE YOU SENDING, FROM WHERE?', pic: 'A NOTE WITH YOUR PICTURE', gif: 'A NOTE WITH YOUR GIF', file: 'A NOTE WITH YOUR FILE', ping: 'WHY (optional): they get told the next time they are in the world' }[k]; $('#hs-url', el).style.display = k === 'gif' ? '' : 'none'; if (k === 'pic' || k === 'file') { $('#hs-f', el).accept = k === 'pic' ? 'image/*' : '*/*'; $('#hs-f', el).click(); } }; $$('.deck button', right).forEach(b => b.onclick = () => pick(b.dataset.k)); pick('dm');
      $('#hs-go', el).onclick = async () => { const err = $('#hs-err', el); if (!me) { err.textContent = 'Sign in (🔑 Join) first.'; return; } if (!sb) { err.textContent = 'Offline.'; return; } let media = null; try { if (kind === 'gif') { media = $('#hs-url', el).value.trim(); if (!/^https?:\/\//.test(media)) { err.textContent = 'Paste a GIF address.'; return; } } if (kind === 'pic' || kind === 'file') { const f = $('#hs-f', el).files[0]; if (!f) { err.textContent = 'Pick a file first.'; return; } const ext = (f.name.split('.').pop() || 'bin').toLowerCase().replace(/[^a-z0-9]/g, ''); const path = `${me.id}/hub-${Date.now()}.${ext}`; const { error: ue } = await sb.storage.from('posts').upload(path, f, { contentType: f.type || 'application/octet-stream' }); if (ue) throw ue; media = sb.storage.from('posts').getPublicUrl(path).data.publicUrl; } const body = $('#hs-dm', el).value.trim(); if (kind === 'dm' && !body) { err.textContent = 'Write something.'; return; } const { error } = await sb.from('hub_requests').insert({ from_user: me.id, to_user: sendTo, kind: kind === 'ping' ? 'dm' : kind, body: kind === 'ping' ? '📡 PING: ' + (body || 'tell me when you are online') : body, media }); if (error) throw error; err.textContent = ''; toast(kind === 'ping' ? '📡 Ping set. They see it the moment they open their hub.' : '📡 Transmitted.'); $('#hs-dm', el).value = ''; } catch (e) { err.textContent = e.message || String(e); } }; };
  drawRight();
}
