/* 🎢 THE PEACE COASTER (v7): allofus.one's own coaster, built different from the mall's. A loop over the
   hub with a corkscrew and a dive, you sit IN the car, the real ride video's sound plays, and the full
   video plays at the end. Take a selfie mid-ride with the Selfie Studio. */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { M, glow, box, cyl } from './aou-kit.js';
import { terrainY } from './aou-terrain.js';
import { selfieStudio } from './aou-lakes.js';
const T = THREE; const MOB = isMobile();
export function buildCoaster(app, W) {
  const S = app.scene; const toast = (m, ms) => app.toast(m, ms); const CX = -170, CZ = 60; const gy = (x, z) => terrainY(x, z); const y0 = gy(CX, CZ);
  const P = [[0, 2, 0], [20, 26, 10], [44, 34, 40], [60, 20, 80], [40, 48, 110], [10, 30, 120], [-20, 56, 90], [-50, 30, 60], [-60, 44, 20], [-40, 18, -20], [-10, 38, -40], [20, 14, -30], [30, 6, -8], [8, 2, -2], [0, 2, 0]]; const curve = new T.CatmullRomCurve3(P.map(p => new T.Vector3(CX + p[0], y0 + p[1], CZ + p[2])), true, 'catmullrom', 0.55); curve.arcLengthDivisions = 800; const len = curve.getLength();
  const N = MOB ? 220 : 420; const up = new T.Vector3(0, 1, 0); const L = [], R = [], FR = []; let pr = new T.Vector3(1, 0, 0); for (let i = 0; i < N; i++) { const u = i / N; const p = curve.getPointAt(u), tn = curve.getTangentAt(u); const r = new T.Vector3().crossVectors(tn, up); if (r.lengthSq() < 1e-4) r.copy(pr); r.normalize(); pr = r; const tu = new T.Vector3().crossVectors(r, tn).normalize(); FR.push([p, tn, r, tu]); L.push(p.clone().addScaledVector(r, 0.6)); R.push(p.clone().addScaledVector(r, -0.6)); }
  const railM = M(0xb08cff, { metalness: 0.8, roughness: 0.25, emissive: 0x2a1060, emissiveIntensity: 0.4 }); const tube = (pts, rad) => { const m = new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts, true, 'catmullrom', 0.5), N, rad, 6, true), railM); m.userData.noCollide = true; m.userData.noCull = true; m.frustumCulled = false; S.add(m); }; tube(L, 0.12); tube(R, 0.12); const spine = []; for (const [p, , , tu] of FR) spine.push(p.clone().addScaledVector(tu, -0.45)); tube(spine, 0.22);
  const ties = new T.InstancedMesh(new T.BoxGeometry(1.5, 0.08, 0.2), M(0x2a3350), N); const mt = new T.Matrix4(); FR.forEach(([p, tn, r, tu], i) => { mt.makeBasis(r, tu, tn); mt.setPosition(p.x - tu.x * 0.2, p.y - tu.y * 0.2, p.z - tu.z * 0.2); ties.setMatrixAt(i, mt); }); ties.frustumCulled = false; S.add(ties);
  const cols = []; for (let i = 0; i < N; i += 6) { const p = spine[i]; if (p.y - gy(p.x, p.z) > 3) cols.push(p); } if (cols.length) { const im = new T.InstancedMesh(new T.CylinderGeometry(0.18, 0.24, 1, 8), M(0xd5dcea, { metalness: 0.6 }), cols.length); const d = new T.Object3D(); cols.forEach((p, i) => { const g = gy(p.x, p.z), h = p.y - g; d.position.set(p.x, g + h / 2, p.z); d.scale.set(1, h, 1); d.updateMatrix(); im.setMatrixAt(i, d.matrix); }); im.frustumCulled = false; S.add(im); }
  const hoops = [NEON(0x38f0ff), NEON(0xff4fd8), NEON(0xffd23f), NEON(0x7cff6b)]; function NEON(c) { return glow(c, 1.8); } for (let i = 0; i < 24; i++) { const u = i / 24; const p = curve.getPointAt(u), tn = curve.getTangentAt(u); const h = new T.Mesh(new T.TorusGeometry(3, 0.12, 6, 24), hoops[i % 4]); h.position.copy(p); h.quaternion.setFromRotationMatrix(new T.Matrix4().lookAt(p.clone().add(tn), p, up)); h.frustumCulled = false; S.add(h); }
  const car = () => { const c = new T.Group(); const bodyM = M(0x7c3aed, { metalness: 0.6, roughness: 0.3 }); box(1.9, 0.6, 3, bodyM, 0, 0.55, 0, c); box(1.7, 1.0, 0.2, M(0x14182a), 0, 1.15, -1.15, c); const bar = new T.Mesh(new T.TorusGeometry(0.6, 0.06, 6, 14, Math.PI), M(0xdfe6f2, { metalness: 0.95 })); bar.position.set(0, 0.95, 0.35); bar.rotation.x = Math.PI / 2 + 0.5; c.add(bar); const nose = new T.Mesh(new T.ConeGeometry(0.9, 1.6, 12), bodyM); nose.rotation.x = Math.PI / 2; nose.scale.z = 0.5; nose.position.set(0, 0.55, 2.2); c.add(nose); for (const sx of [-1, 1]) box(0.06, 0.1, 2.9, glow(0x38f0ff, 2), sx * 0.96, 0.6, 0, c); c.traverse(o => { o.userData.noOcclude = true; o.frustumCulled = false; }); return c; };
  const train = [0, 1, 2].map(() => { const c = car(); S.add(c); return c; }); let u = 0; const lm = new T.Matrix4(), lp = new T.Vector3(); const place = (obj, uu) => { const p = curve.getPointAt(uu), tn = curve.getTangentAt(uu); obj.position.copy(p); lm.lookAt(lp.copy(p).add(tn), p, up); obj.quaternion.setFromRotationMatrix(lm); return [p, tn]; };
  let riding = false; app.onUpdate((dt) => { if (riding) return; const slope = curve.getTangentAt(u).y; u = (u + dt * 0.03 * (1.3 - slope * 0.9)) % 1; train.forEach((c, i) => place(c, ((u - i * 3.6 / len) % 1 + 1) % 1)); });
  const VID = 'oAJLKDMihnU'; let audio = null; const startAudio = () => { try { audio = document.createElement('iframe'); audio.src = `https://www.youtube.com/embed/${VID}?autoplay=1&start=12&controls=0&playsinline=1`; audio.allow = 'autoplay; encrypted-media'; audio.style.cssText = 'position:fixed;right:10px;bottom:150px;width:180px;height:102px;border:2px solid #b08cff;border-radius:12px;z-index:9400;opacity:.9'; audio.title = 'Ride sound'; document.body.appendChild(audio); } catch (e) { } }; const stopAudio = () => { if (audio) { audio.remove(); audio = null; } };
  const ride = () => { if (app.ride || riding) return; riding = true; train.forEach(c => c.visible = false); const my = car(); S.add(my); const prev = app.targetDist; app.targetDist = 0.01; app.seatClip && app.seatClip(my, 0.95, { tilt: true, z: -0.3 }); startAudio(); let k = 0, tl = app.t, v = 0.4, yawS = null, pitS = 0, roll = 0; const t0 = app.t; toast('🎢 PEACE COASTER. Hold on. Drag to look around, 📸 for a selfie.', 3500);
    const sel = document.createElement('button'); sel.textContent = '📸 Ride selfie'; sel.style.cssText = 'position:fixed;left:50%;bottom:150px;transform:translateX(-50%);z-index:9401;border:0;border-radius:12px;padding:12px 18px;font:900 14px Poppins,Arial;background:#ff4fd8;color:#fff;cursor:pointer'; sel.onclick = () => selfieStudio(app); document.body.appendChild(sel);
    app.ride = { pos: (t) => { const dt = Math.min(0.05, Math.max(0, t - tl)); tl = t; const kc = Math.min(0.9999, k); const tn = curve.getTangentAt(kc); v += (Math.max(0.35, Math.min(2.2, 1.2 - tn.y * 1.25)) - v) * Math.min(1, dt * 1.4); k += dt * 0.04 * v; if (k >= 1) app.ride.until = t - 1; const [p] = place(my, kc); const tY = Math.atan2(-tn.x, -tn.z), tP = Math.asin(Math.max(-1, Math.min(1, tn.y))) * 0.8; if (yawS === null) yawS = tY; let da = tY - yawS; while (da > Math.PI) da -= Math.PI * 2; while (da < -Math.PI) da += Math.PI * 2; yawS += da * Math.min(1, dt * 7); pitS += (tP - pitS) * Math.min(1, dt * 6); app.yaw = yawS; app.pitch = Math.max(-1.4, Math.min(1.4, pitS)); app.roll = roll = (roll + (da * 8 - roll) * Math.min(1, dt * 4)); app.camera.fov += ((70 + Math.max(0, v - 1) * 18) - app.camera.fov) * Math.min(1, dt * 3); app.camera.updateProjectionMatrix(); if (Math.abs(tn.y) > 0.45 && app.buzz) app.buzz(20); return new T.Vector3(p.x, p.y - 0.1, p.z); }, until: undefined, done: () => { riding = false; app.seatClear && app.seatClear(); S.remove(my); train.forEach(c => c.visible = true); app.roll = 0; app.pitch = -0.1; app.camera.fov = 70; app.camera.updateProjectionMatrix(); app.targetDist = prev > 0.6 ? prev : 6; stopAudio(); sel.remove(); app.player.position.set(CX + 4, gy(CX + 4, CZ + 4), CZ + 4); app.celebrate && app.celebrate('🎢'); app.popup && app.popup('🎢 That was the Peace Coaster', `<p>${Math.round(app.t - t0)} seconds of pure stoke.</p>`, [{ label: '▶️ Watch the ride video full screen', fn: () => app.video && app.video(VID, 'Roller coaster ride', true) }, { label: '🔁 Ride again', fn: () => setTimeout(ride, 300) }, { label: '📸 Selfie studio', fn: () => selfieStudio(app) }]); } }; };
  const sg = makeSprite('🎢 THE PEACE COASTER · tap to ride', { scale: 4.4, accent: '#b08cff' }); sg.position.set(CX, y0 + 6, CZ + 4); S.add(sg); const pad = new T.Mesh(new T.CylinderGeometry(3, 3.3, 0.4, 24), M(0x1e1b4b, { metalness: 0.5 })); pad.position.set(CX + 4, y0 + 0.2, CZ + 4); S.add(pad); app.addInteractable && app.addInteractable(CX + 4, CZ + 4, 4, '🎢 Ride the Peace Coaster', ride); app.addHotspot && app.addHotspot(pad, { fn: ride }); app.addObstacle && app.addObstacle(CX, CZ, 1.6);
  app.addPlace && app.addPlace({ id: 'coaster', name: '🎢 The Peace Coaster', icon: '🎢', x: CX + 4, z: CZ + 8, cat: 'Fun', top: true, keys: 'roller coaster ride thrill corkscrew peace', say: 'Step on the purple pad and hold on.' });
}
