/* ============================================================
   LAKES (v7) · Zach's Lake Dillon (three arms, behind the house):
   open to the world. Swim, dive 30 ft with light rays, bubbles and
   caustics, tag fish for points, fish from the shore, picnic tables,
   a beach, the POW-WOW firepit (sit, talk, group chat), a jukebox with
   calm streams, the SELFIE STUDIO, and a $30 Visa card hidden deep.
   Lake Unity (Lake Como's Y shape) and two ponds out in the world.
   ============================================================ */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { M, glow, box, cyl, sph, textPlane, waterMaterial } from './aou-kit.js';
import { terrainY, addFlat } from './aou-terrain.js';
const T = THREE; const MOB = isMobile();
const DILLON = [[-1, 0.3], [-0.9, 0.55], [-0.7, 0.72], [-0.45, 0.82], [-0.25, 0.7], [-0.15, 0.45], [0.05, 0.4], [0.3, 0.6], [0.55, 0.78], [0.8, 0.88], [1.0, 0.72], [0.92, 0.5], [0.7, 0.42], [0.5, 0.28], [0.42, 0.05], [0.6, -0.25], [0.85, -0.5], [0.95, -0.8], [0.72, -0.95], [0.45, -0.8], [0.25, -0.55], [0.05, -0.4], [-0.15, -0.5], [-0.3, -0.78], [-0.55, -0.92], [-0.8, -0.8], [-0.85, -0.5], [-0.7, -0.3], [-0.6, -0.08], [-0.78, 0.05]];
const COMO = [[0, 1], [0.12, 0.9], [0.1, 0.6], [0.14, 0.3], [0.1, 0], [0.25, -0.3], [0.42, -0.6], [0.5, -0.9], [0.38, -1], [0.22, -0.8], [0.05, -0.45], [-0.08, -0.2], [-0.25, -0.5], [-0.45, -0.75], [-0.6, -0.95], [-0.7, -0.8], [-0.52, -0.5], [-0.3, -0.15], [-0.12, 0.1], [-0.14, 0.45], [-0.1, 0.75], [-0.08, 0.95]];
const glowTex = (() => { let t = null; return () => { if (t) return t; const c = document.createElement('canvas'); c.width = c.height = 128; const g = c.getContext('2d'); const gr = g.createRadialGradient(64, 64, 0, 64, 64, 64); gr.addColorStop(0, 'rgba(255,255,255,1)'); gr.addColorStop(0.35, 'rgba(255,255,255,.5)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(0, 0, 128, 128); t = new T.CanvasTexture(c); return t; }; })();

export function buildLakes(app, W, UI) {
  const S = app.scene; const toast = (m, ms) => app.toast(m, ms); const out = {};
  out.dillon = makeLake(app, W, UI, { name: "Zach's Lake Dillon", shape: DILLON, cx: 44 + 86, cz: 105 + 12, sx: 62, sz: 52, rot: 0.4, depth: 9.5, mine: true });
  out.unity = makeLake(app, W, UI, { name: 'Lake Unity', shape: COMO, cx: -260, cz: -290, sx: 48, sz: 80, rot: 0.2, depth: 6, mine: false });
  pond(app, W, { x: -120, z: 260, r: 22, name: 'Mirror Pond' }); pond(app, W, { x: 250, z: -230, r: 18, name: 'Dragonfly Pond' });
  return out;
}

function pond(app, W, { x, z, r, name }) { const S = app.scene; const y = terrainY(x, z); addFlat({ x, z, r: r + 6, y, soft: 14 }); const pts = []; for (let i = 0; i < 40; i++) { const a = i / 40 * Math.PI * 2; const k = 1 + 0.16 * Math.sin(3 * a + x) + 0.09 * Math.cos(5 * a); pts.push([x + Math.cos(a) * r * k, z + Math.sin(a) * r * k * 0.8]); } const sh = new T.Shape(pts.map(p => new T.Vector2(p[0] - x, -(p[1] - z)))); const m = new T.Mesh(new T.ShapeGeometry(sh, 6), waterMaterial(0x2a9ad8, 0x0b3f6e)); m.rotation.x = -Math.PI / 2; m.position.set(x, y + 0.25, z); S.add(m); const rim = new T.Shape(pts.map(p => new T.Vector2((p[0] - x) * 1.1, -(p[1] - z) * 1.1))); rim.holes.push(new T.Path(pts.map(p => new T.Vector2(p[0] - x, -(p[1] - z))))); const rm = new T.Mesh(new T.ShapeGeometry(rim, 6), M(0x9a8f7a, { roughness: 1 })); rm.rotation.x = -Math.PI / 2; rm.position.set(x, y + 0.22, z); S.add(rm); app.addWater && app.addWater({ poly: pts, y: y + 0.25 }); for (let i = 0; i < 5; i++) { const lp = new T.Mesh(new T.CircleGeometry(0.5, 14, 0.3, 6), M(0x2f8f3a, { side: T.DoubleSide })); lp.rotation.x = -Math.PI / 2; lp.position.set(x + Math.cos(i * 2) * r * 0.4, y + 0.3, z + Math.sin(i * 2) * r * 0.3); S.add(lp); } const sg = makeSprite('🪷 ' + name, { scale: 3, accent: '#7cf8ff' }); sg.position.set(x, y + 3, z + r * 0.8); S.add(sg); app.addPlace && app.addPlace({ id: 'pond-' + name.split(' ')[0].toLowerCase(), name: '🪷 ' + name, icon: '🪷', x: x, z: z + r + 4, cat: 'Places', keys: 'pond water lily swim quiet', say: 'A quiet pond. Swim if you like.' }); }

function makeLake(app, W, UI, o) {
  const S = app.scene; const toast = (m, ms) => app.toast(m, ms); const { cx, cz, sx, sz, rot, depth, mine, name } = o; const y0 = terrainY(cx, cz) - 0.6; const WY = y0 + 0.8; const c = Math.cos(rot), s = Math.sin(rot);
  const pts = o.shape.map(([u, v]) => { const x = u * sx, z = v * sz; return [cx + x * c - z * s, cz + x * s + z * c]; });
  addFlat({ x: cx, z: cz, r: Math.max(sx, sz) * 1.15, y: y0, soft: 18 });
  const shape = new T.Shape(pts.map(p => new T.Vector2(p[0] - cx, -(p[1] - cz)))); const water = new T.Mesh(new T.ShapeGeometry(shape, 10), waterMaterial(0x1f8fd0, 0x083a66)); water.rotation.x = -Math.PI / 2; water.position.set(cx, WY, cz); water.userData.noCollide = true; S.add(water);
  const inPoly = (x, z) => { let inside = false; for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) { const xi = pts[i][0], zi = pts[i][1], xj = pts[j][0], zj = pts[j][1]; if ((zi > z) !== (zj > z) && x < (xj - xi) * (z - zi) / (zj - zi) + xi) inside = !inside; } return inside; };
  app.addWater && app.addWater({ poly: pts, y: WY });
  // the basin and shoreline
  const prof = []; for (let i = 0; i <= 16; i++) { const k = i / 16; prof.push(new T.Vector2(1.08 - k * 1.08, -depth * Math.pow(k, 0.7) + 0.02)); } const bowl = new T.Mesh(new T.LatheGeometry(prof, 48), new T.MeshStandardMaterial({ color: 0xc9b28a, roughness: 1, side: T.DoubleSide })); bowl.position.set(cx, y0, cz); bowl.scale.set(sx, 1, sz); bowl.rotation.y = -rot; bowl.userData.noCollide = true; S.add(bowl);
  const rimShape = new T.Shape(pts.map(p => new T.Vector2((p[0] - cx) * 1.08, -(p[1] - cz) * 1.08))); rimShape.holes.push(new T.Path(pts.map(p => new T.Vector2(p[0] - cx, -(p[1] - cz))))); const rim = new T.Mesh(new T.ShapeGeometry(rimShape, 8), M(0xe9d6a6, { roughness: 1 })); rim.rotation.x = -Math.PI / 2; rim.position.set(cx, y0 + 0.75, cz); S.add(rim);
  const rockM = M(0x6b6f76, { roughness: 0.95, flatShading: true }); for (let i = 0; i < 22; i++) { const p = pts[Math.floor(i * pts.length / 22)]; const r = new T.Mesh(new T.DodecahedronGeometry(0.5 + (i % 3) * 0.4, 0), rockM); r.position.set(p[0] * 1.06 - cx * 0.06, y0 + 0.9, p[1] * 1.06 - cz * 0.06); r.rotation.set(i, i * 2, 0); S.add(r); }
  // underwater world: light rays, caustics, bubbles, weeds, the fish
  const rays = []; const rayM = new T.MeshBasicMaterial({ color: 0xbfefff, transparent: true, opacity: 0.08, blending: T.AdditiveBlending, depthWrite: false, side: T.DoubleSide }); for (let i = 0; i < (MOB ? 6 : 14); i++) { const r = new T.Mesh(new T.PlaneGeometry(2.4, depth + 2), rayM); const a = Math.random() * 6.283, rr = Math.random() * Math.min(sx, sz) * 0.7; r.position.set(cx + Math.cos(a) * rr, WY - depth / 2, cz + Math.sin(a) * rr); r.rotation.set(0, Math.random() * 3, 0.15); r.userData.noCollide = true; S.add(r); rays.push(r); }
  const caus = (() => { const c2 = document.createElement('canvas'); c2.width = c2.height = 256; const q = c2.getContext('2d'); q.fillStyle = '#000'; q.fillRect(0, 0, 256, 256); q.strokeStyle = 'rgba(255,255,255,.9)'; q.lineWidth = 2; for (let i = 0; i < 40; i++) { q.beginPath(); let x = Math.random() * 256, y = Math.random() * 256; q.moveTo(x, y); for (let k = 0; k < 4; k++) { x += (Math.random() - 0.5) * 80; y += (Math.random() - 0.5) * 80; q.quadraticCurveTo(x + 25, y - 25, x, y); } q.stroke(); } const t = new T.CanvasTexture(c2); t.wrapS = t.wrapT = T.RepeatWrapping; t.repeat.set(6, 6); return t; })(); const cm = new T.MeshBasicMaterial({ map: caus, transparent: true, opacity: 0.35, blending: T.AdditiveBlending, depthWrite: false }); const cmesh = new T.Mesh(new T.ShapeGeometry(shape, 6), cm); cmesh.rotation.x = -Math.PI / 2; cmesh.position.set(cx, y0 - depth + 0.4, cz); cmesh.scale.set(0.92, 0.92, 1); cmesh.userData.noCollide = true; S.add(cmesh);
  const BN = MOB ? 120 : 320; const bp = new Float32Array(BN * 3); const bs = []; for (let i = 0; i < BN; i++) { const a = Math.random() * 6.283, rr = Math.random() * Math.min(sx, sz) * 0.75; bs.push([cx + Math.cos(a) * rr, Math.random(), cz + Math.sin(a) * rr, 0.3 + Math.random() * 0.8]); } const bg = new T.BufferGeometry(); bg.setAttribute('position', new T.BufferAttribute(bp, 3)); const bubbles = new T.Points(bg, new T.PointsMaterial({ map: glowTex(), color: 0xdff6ff, size: 0.22, transparent: true, opacity: 0.85, depthWrite: false })); bubbles.frustumCulled = false; bubbles.visible = false; S.add(bubbles);
  const weedM = new T.MeshStandardMaterial({ color: 0x2f8a4a, side: T.DoubleSide, roughness: 0.8 }); const weeds = []; for (let i = 0; i < (MOB ? 30 : 70); i++) { const a = Math.random() * 6.283, rr = 0.25 + Math.random() * 0.6; const x = cx + Math.cos(a) * rr * sx * 0.9, z = cz + Math.sin(a) * rr * sz * 0.9; const h = 2 + Math.random() * 3; const w = new T.Mesh(new T.PlaneGeometry(0.4, h, 1, 4), weedM); w.position.set(x, y0 - depth * Math.pow(rr, 0.7) + h / 2 + 0.3, z); w.rotation.y = a; S.add(w); weeds.push(w); }
  // fish: realistic (scales, fins, eyes) and cartoon (bold shapes) mixed, 8 species
  const scaleTex = (c1, c2) => { const cv = document.createElement('canvas'); cv.width = 128; cv.height = 64; const q = cv.getContext('2d'); q.fillStyle = c1; q.fillRect(0, 0, 128, 64); q.strokeStyle = c2; q.lineWidth = 1.2; for (let y = 0; y < 64; y += 6) for (let x = (y / 6 % 2) * 4; x < 128; x += 8) { q.beginPath(); q.arc(x, y, 4, 0, Math.PI); q.stroke(); } const t = new T.CanvasTexture(cv); t.colorSpace = T.SRGBColorSpace; return t; };
  const SP = [['Rainbow trout', 'real', 0x9fb3a6, 0xff6f9a, 0.42], ['Largemouth bass', 'real', 0x6b8e4e, 0x2f4a2a, 0.5], ['Koi', 'toon', 0xff6a1f, 0xffffff, 0.4], ['Blue tang', 'toon', 0x1e5bff, 0xffd23f, 0.3], ['Golden carp', 'real', 0xd9b13b, 0x8a6a1a, 0.55], ['Clownfish', 'toon', 0xff7a1a, 0xffffff, 0.24], ['Pike', 'real', 0x7a8a5a, 0x3a4a2a, 0.6], ['Sunfish', 'toon', 0xffd23f, 0x38f0ff, 0.28]]; const fish = [];
  SP.forEach(([nm, kind, c1, c2, sc], si) => { const n = MOB ? 3 : 5; for (let i = 0; i < n; i++) { const f = new T.Group(); const real = kind === 'real'; const bm = real ? new T.MeshStandardMaterial({ map: scaleTex('#' + new T.Color(c1).getHexString(), '#' + new T.Color(c2).getHexString()), roughness: 0.3, metalness: 0.35 }) : M(c1, { roughness: 0.5 }); const body = new T.Mesh(new T.SphereGeometry(sc, real ? 18 : 10, real ? 12 : 8), bm); body.scale.set(real ? 0.42 : 0.55, real ? 0.62 : 0.8, real ? 1.9 : 1.4); f.add(body); const tail = new T.Mesh(new T.ConeGeometry(sc * 0.55, sc * 0.9, real ? 8 : 4), real ? new T.MeshStandardMaterial({ color: c2, roughness: 0.5, transparent: true, opacity: 0.85 }) : M(c2)); tail.rotation.x = Math.PI / 2; tail.position.z = -sc * 1.7; tail.scale.x = real ? 0.3 : 1; f.add(tail); if (real) { const dorsal = new T.Mesh(new T.ConeGeometry(sc * 0.4, sc * 0.5, 4), tail.material); dorsal.position.y = sc * 0.6; dorsal.scale.x = 0.2; f.add(dorsal); for (const sxx of [-1, 1]) { const pec = new T.Mesh(new T.ConeGeometry(sc * 0.25, sc * 0.5, 4), tail.material); pec.rotation.z = sxx * 1.2; pec.position.set(sxx * sc * 0.4, -sc * 0.1, sc * 0.3); f.add(pec); } } if (!real && nm === 'Clownfish') for (const z of [-0.2, 0.2]) { const st = new T.Mesh(new T.TorusGeometry(sc * 0.56, sc * 0.08, 6, 16), M(0xffffff)); st.position.z = z * sc * 3; f.add(st); } const eye = new T.Mesh(new T.SphereGeometry(sc * (real ? 0.09 : 0.14), 8, 6), M(0xffffff)); eye.position.set(sc * 0.3, sc * 0.2, sc * (real ? 1.2 : 0.7)); f.add(eye); const pup = new T.Mesh(new T.SphereGeometry(sc * 0.05, 6, 4), M(0x111111)); pup.position.set(sc * 0.34, sc * 0.2, sc * (real ? 1.28 : 0.82)); f.add(pup); S.add(f); const fs0 = { f, nm, tail, a: i * 1.3 + si, r: 0.15 + ((si * 7 + i * 5) % 60) / 100, y: -1.2 - ((si + i) % 7) * 1.1, sp: (real ? 0.22 : 0.3) + (i % 3) * 0.05, dir: si % 2 ? 1 : -1, tagged: 0 }; fish.push(fs0); if (app.addHotspot) app.addHotspot(f, { fn: () => tagFish(fs0) }); } });
  // dive + fish-tagging game
  const DIVE = { on: false, depth: 0, max: depth - 0.6, want: 0 }; const gy0 = app.opts.groundY; app.opts.groundY = (x, z) => (DIVE.on && inPoly(x, z)) ? WY - 0.6 - DIVE.depth : gy0(x, z);
  if (app._swim) { const swim0 = app._swim.bind(app); app._swim = (dt) => { const P = app.player.position; if (DIVE.on && DIVE.depth > 0.3 && inPoly(P.x, P.z) && app.avatar) { const av = app.avatar; av.rotation.order = 'YXZ'; av.rotation.x += ((app.moving ? 1.2 : 0.35) - av.rotation.x) * Math.min(1, dt * 4); av.position.y = 0.25 + Math.sin(app.t * 2) * 0.05; return; } return swim0(dt); }; }
  const game = { on: false, score: 0, t0: 0, best: +(localStorage.getItem('aou_fishtag_' + (mine ? 'd' : 'u')) || 0) }; const tagFish = (fs) => { if (!game.on) { toast('🐟 ' + fs.nm + '. Start the fish-tag game at the dive sign to score.', 2000); return; } if (app.t - fs.tagged < 6) return; const P = app.player.position; const d = fs.f.position.distanceTo(P); if (d > 4) { toast('🐟 Too far. Swim closer!', 1200); return; } fs.tagged = app.t; const pts = fs.nm === 'Pike' ? 30 : fs.nm === 'Rainbow trout' ? 25 : 10; game.score += pts; app.celebrate && app.celebrate('🐟'); toast('🏷️ Tagged a ' + fs.nm + '! +' + pts + ' · ' + game.score, 1300); };
  const ov = document.createElement('div'); ov.className = 'lk-under'; ov.style.cssText = 'position:absolute;inset:0;pointer-events:none;z-index:20;opacity:0;transition:opacity .5s;background:radial-gradient(ellipse at 50% 0%,rgba(80,200,255,.22),rgba(4,47,90,.55) 70%)'; (document.getElementById('wvm-hud') || document.body).appendChild(ov);
  const dv = document.createElement('div'); dv.className = 'lk-dive'; dv.style.cssText = 'position:absolute;left:50%;bottom:150px;transform:translateX(-50%);z-index:31;display:none;gap:6px;align-items:center;font-family:Poppins,Arial'; dv.innerHTML = '<button data-d="toggle" style="border:0;border-radius:14px;padding:10px 14px;font:900 15px Poppins,Arial;background:#0e7490;color:#fff;cursor:pointer">🤿 Dive</button><button data-d="down" style="border:0;border-radius:14px;padding:10px 14px;font:900 15px Poppins,Arial;background:#0e7490;color:#fff;touch-action:none">⬇</button><button data-d="up" style="border:0;border-radius:14px;padding:10px 14px;font:900 15px Poppins,Arial;background:#0e7490;color:#fff;touch-action:none">⬆</button><span class="lk-depth" style="background:#fff;border-radius:999px;padding:4px 10px;font:900 13px Poppins,Arial;color:#0e7490"></span><span class="lk-score" style="background:#ffd23f;border-radius:999px;padding:4px 10px;font:900 13px Poppins,Arial;color:#1e1b4b;display:none"></span>'; (document.getElementById('wvm-hud') || document.body).appendChild(dv);
  let hold = 0; dv.addEventListener('pointerdown', (e) => { const b = e.target.closest('[data-d]'); if (!b) return; if (b.dataset.d === 'toggle') { DIVE.on = !DIVE.on; if (!DIVE.on) DIVE.want = 0; toast(DIVE.on ? '🤿 Diving. ⬇⬆ or Q/E. About 30 ft to the bottom, and something is glinting down there…' : '🫧 Surface.', 3800); } else hold = b.dataset.d === 'down' ? 1 : -1; }); addEventListener('pointerup', () => hold = 0); addEventListener('keydown', (e) => { if (!DIVE.on || (e.target.closest && e.target.closest('input,textarea'))) return; if (/^[qQ]$/.test(e.key)) hold = 1; if (/^[eE]$/.test(e.key)) hold = -1; }); addEventListener('keyup', (e) => { if (/^[qeQE]$/.test(e.key)) hold = 0; });
  const fog0 = S.fog ? { c: S.fog.color.getHex(), n: S.fog.near, f: S.fog.far } : null; let under = false;
  // the chest ($30 Visa, one winner) in the deepest arm, behind weeds
  const CH = { x: cx + 0.72 * sx * c - 0.75 * sz * s, z: cz + 0.72 * sx * s + 0.75 * sz * c }; const chest = new T.Group(); chest.position.set(CH.x, y0 - depth + 0.6, CH.z); S.add(chest); box(1.3, 0.75, 0.85, M(0x7a4a1e), 0, 0.37, 0, chest); const lid = new T.Group(); lid.position.set(0, 0.75, -0.42); chest.add(lid); box(1.35, 0.28, 0.9, M(0x8a5a2b), 0, 0.14, 0.42, lid); box(1.4, 0.1, 0.1, M(0xffd23f, { metalness: 0.9 }), 0, 0.78, 0.44, chest); const cg = new T.Sprite(new T.SpriteMaterial({ map: glowTex(), color: 0xffd23f, transparent: true, opacity: 0, depthWrite: false, blending: T.AdditiveBlending })); cg.scale.setScalar(4); cg.position.y = 1; chest.add(cg); let found = false;
  const claim = () => { if (found) return; found = true; const sb = (UI && UI.DB && UI.DB.sb) || globalThis.AOU_SB; app.popup && app.popup('🎁 YOU FOUND IT: a $30 Visa gift card!', `<p>Only one person can claim this, the first valid claim wins and the chest closes for everyone else. Fill this in: a real person verifies before it ships.</p><label>Full name<input id="vz-n" maxlength="80"></label><label>Email<input id="vz-e" type="email" maxlength="120"></label><label>Phone<input id="vz-p" type="tel" maxlength="30"></label><label>Mailing address<input id="vz-a" maxlength="200"></label><label class="aou-chk"><input type="checkbox" id="vz-ok"> I am 18+, a U.S. resident, and I agree to the <a href="https://worldvrmall.com/prize-rules/" target="_blank">prize rules</a>.</label><p class="aou-err" id="vz-err"></p>`, [{ label: '🎁 Claim it', keep: true, fn: async () => { const v = (id) => (document.getElementById(id) || {}).value || ''; const err = document.getElementById('vz-err'); if (!v('vz-n').trim() || !/^\S+@\S+\.\S+$/.test(v('vz-e')) || v('vz-p').replace(/\D/g, '').length < 10 || !document.getElementById('vz-ok').checked) { if (err) err.textContent = 'Name, a real email, a 10-digit phone, and the checkbox.'; return; } const code = ('VISA30-' + Date.now().toString(36)).toUpperCase(); let r = 'offline'; if (sb) { try { const { data, error } = await sb.rpc('claim_prize', { p_prize: 'visa30', p_name: v('vz-n'), p_email: v('vz-e'), p_phone: v('vz-p'), p_address: v('vz-a'), p_code: code, p_page: 'allofus' }); if (!error) r = data; } catch (e) { } } app.closePopup && app.closePopup(); setTimeout(() => app.popup(r === 'won' ? '🎉 Claim received!' : r === 'taken' ? '🥲 Someone found it first' : r === 'limit' ? '🏆 You already won a prize' : '📞 The claim system did not answer', r === 'won' ? `<p>Your code: <code>${code}</code>. We will reach out within 3 business days. Questions: 1-800-481-8638.</p>` : r === 'taken' ? '<p>The chest is empty now. New prizes get hidden all the time.</p>' : r === 'limit' ? '<p>One prize per person so everyone gets a shot.</p>' : `<p>Call 1-800-481-8638 or email info@eyetoad.com with code <code>${code}</code> so you do not lose it.</p>`), 150); if (r !== 'offline') found = true; else found = false; } }]); if (!app.popup) toast('🎁 Chest found! Sign in to claim.'); };
  app.onUpdate((dt, t) => { const P = app.player.position; const near = Math.hypot(P.x - cx, P.z - cz) < Math.max(sx, sz) + 120; if (!near) { if (dv.style.display !== 'none') dv.style.display = 'none'; return; }
    const here = inPoly(P.x, P.z) && app._waterAt && app._waterAt(P.x, P.z) !== null; dv.style.display = here ? 'flex' : 'none'; if (!here && DIVE.on) { DIVE.on = false; DIVE.depth = 0; DIVE.want = 0; } if (DIVE.on) DIVE.want = Math.max(0, Math.min(DIVE.max, DIVE.want + hold * dt * 2.6)); DIVE.depth += (DIVE.want - DIVE.depth) * Math.min(1, dt * 3); dv.querySelector('[data-d="toggle"]').textContent = DIVE.on ? '⬆ Surface' : '🤿 Dive'; dv.querySelector('.lk-depth').textContent = DIVE.on ? Math.round(DIVE.depth * 3.28) + ' ft' : ''; const sc = dv.querySelector('.lk-score'); sc.style.display = game.on ? '' : 'none'; if (game.on) { const left = Math.max(0, 60 - (app.t - game.t0)); sc.textContent = '🐟 ' + game.score + ' · ' + Math.ceil(left) + 's'; if (left <= 0) { game.on = false; if (game.score > game.best) { game.best = game.score; localStorage.setItem('aou_fishtag_' + (mine ? 'd' : 'u'), game.best); app.celebrate && app.celebrate('🏆'); } app.popup && app.popup('🐟 Fish tag · time!', `<p style="font-size:18px"><b>${game.score} points</b> · best ${game.best}</p><p>Pike 30, trout 25, everything else 10. Tag by tapping a fish within 4 m.</p>`, [{ label: '🔁 Again', fn: () => startGame() }, { label: 'Done' }]); } }
    const u = DIVE.on && DIVE.depth > 0.5; if (u !== under) { under = u; ov.style.opacity = u ? 1 : 0; bubbles.visible = u; if (S.fog && fog0) { if (u) { S.fog.color.setHex(0x0b4f7a); S.fog.near = 2; S.fog.far = 40; } else { S.fog.color.setHex(fog0.c); S.fog.near = fog0.n; S.fog.far = fog0.f; } } }
    if (u) { S.fog.far = 42 - DIVE.depth * 2.2; for (let i = 0; i < BN; i++) { const b = bs[i]; b[1] = (b[1] + dt * b[3] * 0.25) % 1; bp[i * 3] = b[0] + Math.sin(t * 2 + i) * 0.1; bp[i * 3 + 1] = y0 - depth + b[1] * (depth + 0.5); bp[i * 3 + 2] = b[2]; } bg.attributes.position.needsUpdate = true; caus.offset.x = t * 0.02; caus.offset.y = Math.sin(t * 0.3) * 0.05; cm.opacity = 0.25 + Math.sin(t * 1.5) * 0.1; rays.forEach((r, i) => { r.material.opacity = 0.05 + Math.sin(t * 0.7 + i) * 0.04; r.rotation.y += dt * 0.05; }); }
    for (const w of weeds) w.rotation.z = Math.sin(t * 1.1 + w.position.x) * 0.14; for (const f of fish) { f.a += dt * f.sp * f.dir * 2.2 / (f.r * 3 + 1); const lx = Math.cos(f.a) * f.r * sx * 0.9, lz = Math.sin(f.a) * f.r * sz * 0.85; f.f.position.set(cx + lx * c - lz * s, WY + f.y + Math.sin(t + f.a) * 0.3, cz + lx * s + lz * c); f.f.rotation.y = -f.a - rot + (f.dir > 0 ? 0 : Math.PI); f.tail.rotation.y = Math.sin(t * 8 + f.a) * 0.5; if (f.tagged && app.t - f.tagged < 6) f.f.position.y += Math.sin((app.t - f.tagged) * 20) * 0.1; }
    const dch = Math.hypot(P.x - CH.x, P.z - CH.z); const open = DIVE.on && DIVE.depth > depth - 2.5 && dch < 7; lid.rotation.x += ((open ? -1.2 : 0) - lid.rotation.x) * Math.min(1, dt * 3); cg.material.opacity = open ? 0.7 + Math.sin(t * 4) * 0.2 : (DIVE.on && DIVE.depth > 4 ? 0.12 : 0); if (open && dch < 2.6 && mine) claim(); });
  const startGame = () => { game.on = true; game.score = 0; game.t0 = app.t; fish.forEach(f => f.tagged = 0); toast('🐟 FISH TAG: 60 seconds. Dive and tap fish within 4 m. Pike are worth the most.', 4000); };
  // shore: sign, beach, picnic tables, firepit POW-WOW, jukebox, fishing, selfie studio
  const sp = pts[0]; const SX = sp[0] + (sp[0] - cx) * 0.16, SZ = sp[1] + (sp[1] - cz) * 0.16; const gy = (x, z) => terrainY(x, z);
  const sign = textPlane([mine ? "ZACH'S LAKE DILLON" : 'LAKE UNITY', 'open to the world · swim · dive · fish · picnic', 'catch some VR rays · pow-wow by the fire'], 7, 2.6, { bg: '#0b2a4a', fg: '#fff', accent: '#38f0ff', font: 'bold 56px Poppins, Arial' }); sign.position.set(SX, gy(SX, SZ) + 2.6, SZ); S.add(sign); for (const dx of [-3.3, 3.3]) cyl(0.1, 0.12, 2.6, M(0x5a3d22), SX + dx, gy(SX, SZ) + 1.3, SZ, S, 8);
  app.addHotspot && app.addHotspot(sign, { title: mine ? "🏖️ Zach's Lake Dillon" : '🏞️ Lake Unity', html: `<p>${mine ? 'My lake is open to the world. Shaped like the real Lake Dillon: three arms, three coves. ' : 'Shaped like Lake Como. '}Swim it, dive it 30 feet with the fish, fish from the shore, picnic, catch some VR rays with music on, or sit at the fire and talk with whoever shows up.</p>`, actions: [{ label: '🐟 Start fish tag (60 s)', fn: startGame }, { label: '🤿 How to dive', fn: () => toast('Walk into the water, tap 🤿 Dive, then ⬇⬆ (or Q/E).', 4000) }] });
  const beachX = cx + (pts[8][0] - cx) * 1.12, beachZ = cz + (pts[8][1] - cz) * 1.12; const sand = new T.Mesh(new T.CircleGeometry(14, 32), M(0xf2dc9a, { roughness: 1 })); sand.rotation.x = -Math.PI / 2; sand.position.set(beachX, gy(beachX, beachZ) + 0.06, beachZ); S.add(sand); for (let i = 0; i < 4; i++) { const ch = box(1.6, 0.25, 2, M([0xff4f79, 0x38f0ff, 0xffd23f, 0xffffff][i]), beachX - 5 + i * 3.2, gy(beachX, beachZ) + 0.6, beachZ + 4, S); ch.rotation.x = -0.3; const um = new T.Mesh(new T.ConeGeometry(1.8, 0.8, 10, 1, true), M([0xff4f79, 0x38f0ff, 0xffd23f, 0x7cff6b][i], { side: T.DoubleSide })); um.position.set(beachX - 5 + i * 3.2 + 1, gy(beachX, beachZ) + 2.6, beachZ + 4); S.add(um); cyl(0.04, 0.04, 2.6, M(0xdddddd), beachX - 5 + i * 3.2 + 1, gy(beachX, beachZ) + 1.3, beachZ + 4, S, 6); }
  for (let i = 0; i < 3; i++) { const px = beachX + 10 + i * 5, pz = beachZ - 6 + i * 2; const tb = new T.Group(); tb.position.set(px, gy(px, pz), pz); S.add(tb); box(2.4, 0.12, 1.2, M(0x8a5a2b), 0, 0.75, 0, tb); for (const sz2 of [-1, 1]) box(2.4, 0.1, 0.4, M(0x8a5a2b), 0, 0.45, sz2 * 0.95, tb); for (const sx2 of [-0.9, 0.9]) { const lg = box(0.1, 0.8, 2.2, M(0x6b4a2a), sx2, 0.4, 0, tb); lg.rotation.x = 0.6; } app.addObstacle && app.addObstacle(px, pz, 1.4); }
  const picnic = makeSprite('🧺 Picnic tables · bring friends', { scale: 3, accent: '#ffd23f' }); picnic.position.set(beachX + 15, gy(beachX, beachZ) + 3.4, beachZ - 4); S.add(picnic);
  // the POW-WOW firepit: sit, talk, group chat with whoever is here
  const FX = beachX - 14, FZ = beachZ - 10; const fp = new T.Group(); fp.position.set(FX, gy(FX, FZ), FZ); S.add(fp); for (let i = 0; i < 12; i++) { const a = i / 12 * 6.283; const st = new T.Mesh(new T.DodecahedronGeometry(0.4, 0), rockM); st.position.set(Math.cos(a) * 1.4, 0.2, Math.sin(a) * 1.4); fp.add(st); } for (let i = 0; i < 3; i++) { const lg = cyl(0.14, 0.16, 2, M(0x5a3d22), 0, 0.42, 0, fp, 7); lg.rotation.z = Math.PI / 2 - 0.3; lg.rotation.y = i * 2.09; } const flames = [[0xff5a1f, 0.7, 1.9], [0xffa11f, 0.5, 1.5], [0xfff0a8, 0.28, 1.05]].map(([c2, w, h]) => { const f = new T.Mesh(new T.ConeGeometry(w, h, 10), new T.MeshBasicMaterial({ color: c2, transparent: true, opacity: 0.88, depthWrite: false })); f.position.set(0, 0.45 + h / 2, 0); f.userData.h = h; fp.add(f); return f; }); const fglow = new T.Sprite(new T.SpriteMaterial({ map: glowTex(), color: 0xff8a3d, transparent: true, opacity: 0.5, depthWrite: false, blending: T.AdditiveBlending })); fglow.scale.set(7, 5, 1); fglow.position.y = 1.4; fp.add(fglow);
  const seats = []; for (let i = 0; i < 8; i++) { const a = i / 8 * 6.283; const seat = cyl(0.42, 0.42, 1.7, M(0x6b4a2a), Math.cos(a) * 3.6, 0.42, Math.sin(a) * 3.6, fp, 9); seat.rotation.z = Math.PI / 2; seat.rotation.y = -a + Math.PI / 2; seats.push([FX + Math.cos(a) * 3.6, FZ + Math.sin(a) * 3.6, a]); } app.addObstacle && app.addObstacle(FX, FZ, 1.8);
  const fsign = makeSprite('🔥 POW-WOW FIRE · sit, talk, connect', { scale: 3.6, accent: '#ff8a3d' }); fsign.position.set(0, 4.6, 0); fp.add(fsign); const EN = 36, ep = new Float32Array(EN * 3), es = []; for (let i = 0; i < EN; i++) es.push(Math.random()); const eg = new T.BufferGeometry(); eg.setAttribute('position', new T.BufferAttribute(ep, 3)); const embers = new T.Points(eg, new T.PointsMaterial({ color: 0xffb347, size: 0.12, transparent: true, opacity: 0.9, depthWrite: false, blending: T.AdditiveBlending })); embers.frustumCulled = false; fp.add(embers);
  const sitFire = () => { const P = app.player.position; let best = seats[0], bd = 1e9; for (const sidx of seats) { const d = Math.hypot(sidx[0] - P.x, sidx[1] - P.z); if (d < bd) { bd = d; best = sidx; } } P.set(best[0], gy(best[0], best[1]), best[1]); if (app.avatar) app.avatar.rotation.y = Math.atan2(FX - best[0], FZ - best[1]); try { window.AOU_SIT && window.AOU_SIT(app.avatar, true); } catch (e) { } app.popup && app.popup('🔥 The pow-wow fire', '<p>Pull up a log. Whoever is here can talk out loud, type in the fire chat, or just sit. The fire is always lit.</p>', [{ label: '💬 Open the fire chat', fn: () => { if (W.api && W.api.openChat) W.api.openChat('chats'); } }, { label: '🎙️ Talk out loud', fn: () => { if (W.api && W.api.openVoice) W.api.openVoice(); else toast('🎙️ Voice: ✨ More → Voice chat'); } }, { label: '🤗 Group hug', fn: () => { if (W.api && W.api.hug) W.api.hug(); else toast('🤗'); } }, { label: '🧘 Just sit', fn: () => toast('🔥 Crackle. Pop. Nobody needs anything from you right now.', 4000) }]); };
  app.addInteractable && app.addInteractable(FX + 4.6, FZ, 3.2, '🔥 Sit at the pow-wow fire', sitFire); app.addHotspot && app.addHotspot(fp, { fn: sitFire });
  // jukebox: calm streams, inline player + open on YouTube
  const JB = [['🌊 Calming sounds', 'V1RPi2MYptM'], ['🎵 Relaxing music · 12 hrs, no ads', 'LFASWuckB1c'], ['🌲 Nature sounds · 8 hrs', 'ipf7ifVSeDU']]; const JX = beachX + 8, JZ = beachZ + 8; const jb = new T.Group(); jb.position.set(JX, gy(JX, JZ), JZ); S.add(jb); box(1.2, 1.8, 0.7, M(0x1e1b4b, { metalness: 0.4 }), 0, 0.9, 0, jb); box(1.0, 0.5, 0.05, glow(0x38f0ff, 1.4), 0, 1.3, 0.36, jb); for (let i = 0; i < 3; i++) cyl(0.12, 0.12, 0.06, glow([0xff4f79, 0xffd23f, 0x7cff6b][i], 1.6), -0.3 + i * 0.3, 0.6, 0.37, jb, 10); const jt = makeSprite('🎶 Lakeside jukebox · calm jams', { scale: 3, accent: '#38f0ff' }); jt.position.y = 2.8; jb.add(jt); app.addObstacle && app.addObstacle(JX, JZ, 0.9);
  const openJuke = () => app.popup && app.popup('🎶 Lakeside jukebox', '<p>Pick a stream. It plays right here (or open it on YouTube in a new tab). Perfect for working on the laptop by the water.</p>', JB.map(([n, id]) => ({ label: n, fn: () => app.video && app.video(id, n, true) })).concat(JB.map(([n, id]) => ({ label: '↗ ' + n.split(' ·')[0] + ' on YouTube', href: 'https://youtu.be/' + id, newTab: true }))));
  app.addInteractable && app.addInteractable(JX, JZ + 1.4, 2.6, '🎶 Lakeside jukebox', openJuke); app.addHotspot && app.addHotspot(jb, { fn: openJuke });
  // fishing from the shore: cast, wait for the tug, reel in time
  const DX = pts[20][0] * 1.05 - cx * 0.05, DZ = pts[20][1] * 1.05 - cz * 0.05; const dock = box(3, 0.3, 9, M(0x8a5a2b, { roughness: 1 }), 0, 0.85, 0, S); dock.position.set(DX, gy(DX, DZ) + 0.85, DZ); dock.rotation.y = Math.atan2(cx - DX, cz - DZ); for (let i = 0; i < 4; i++) for (const sx2 of [-1, 1]) { const px = DX + Math.sin(dock.rotation.y) * (-3.5 + i * 2.5) + Math.cos(dock.rotation.y) * sx2 * 1.4, pz = DZ + Math.cos(dock.rotation.y) * (-3.5 + i * 2.5) - Math.sin(dock.rotation.y) * sx2 * 1.4; cyl(0.12, 0.12, 2, M(0x6b4a2a), px, gy(DX, DZ) + 0.4, pz, S, 6); }
  let fishing = null; const fishHud = document.createElement('div'); fishHud.style.cssText = 'position:absolute;left:50%;top:70px;transform:translateX(-50%);z-index:33;display:none;background:#fff;border-radius:16px;padding:10px 16px;font:800 15px Poppins,Arial;color:#0f172a;box-shadow:0 10px 30px rgba(0,0,0,.3);text-align:center'; (document.getElementById('wvm-hud') || document.body).appendChild(fishHud);
  const castLine = () => { if (fishing) return; const best = +(localStorage.getItem('aou_fish_best') || 0); fishing = { t: 0, bite: 3 + Math.random() * 6, phase: 'wait', caught: 0, best }; fishHud.style.display = ''; fishHud.innerHTML = '🎣 Line is out… wait for the TUG.<br><button id="fh-r" style="margin-top:8px;border:0;border-radius:999px;padding:9px 18px;font:900 15px Poppins,Arial;background:#16a34a;color:#fff;cursor:pointer">REEL!</button> <button id="fh-x" style="margin-top:8px;border:1px solid #cbd5e1;background:#fff;border-radius:999px;padding:9px 12px;cursor:pointer">✕</button>'; fishHud.querySelector('#fh-x').onclick = () => { fishing = null; fishHud.style.display = 'none'; }; fishHud.querySelector('#fh-r').onclick = () => { if (!fishing) return; if (fishing.phase === 'bite') { const sp = SP[Math.floor(Math.random() * SP.length)]; const lb = (1 + Math.random() * (sp[0] === 'Pike' ? 12 : 6)).toFixed(1); fishing.caught++; app.celebrate && app.celebrate('🐟'); fishHud.innerHTML = `🐟 You caught a <b>${sp[0]}</b> · ${lb} lb! (${fishing.caught} today)<br><button id="fh-a" style="margin-top:8px;border:0;border-radius:999px;padding:9px 18px;font:900 15px Poppins,Arial;background:#0ea5e9;color:#fff;cursor:pointer">Cast again</button> <button id="fh-x" style="margin-top:8px;border:1px solid #cbd5e1;background:#fff;border-radius:999px;padding:9px 12px;cursor:pointer">Done</button>`; const c2 = fishing.caught; fishing = null; if (c2 > best) localStorage.setItem('aou_fish_best', c2); fishHud.querySelector('#fh-a').onclick = () => { fishHud.style.display = 'none'; castLine(); }; fishHud.querySelector('#fh-x').onclick = () => { fishHud.style.display = 'none'; }; } else { fishHud.firstChild.textContent = '🎣 Too early! It swam off. Wait for the TUG…'; fishing.t = 0; fishing.bite = 3 + Math.random() * 6; fishing.phase = 'wait'; } }; };
  app.onUpdate((dt) => { if (!fishing) return; fishing.t += dt; if (fishing.phase === 'wait' && fishing.t > fishing.bite) { fishing.phase = 'bite'; fishing.t = 0; fishHud.firstChild.textContent = '🎣 TUG TUG TUG! REEL NOW!'; app.buzz && app.buzz(120); } if (fishing.phase === 'bite' && fishing.t > 1.6) { fishing.phase = 'wait'; fishing.t = 0; fishing.bite = 3 + Math.random() * 6; fishHud.firstChild.textContent = '🎣 Missed it. Line is out again…'; } });
  app.addInteractable && app.addInteractable(DX + Math.sin(dock.rotation.y) * 3, DZ + Math.cos(dock.rotation.y) * 3, 3.2, '🎣 Go fishing from the dock', castLine);
  app.onUpdate((dt, t) => { const P = app.player.position; if (Math.hypot(P.x - FX, P.z - FZ) > 80) return; flames.forEach((f, i) => { const k = 0.85 + Math.sin(t * (5 + i * 2.3) + i) * 0.16; f.scale.set(1 + Math.sin(t * 7 + i) * 0.08, k, 1); f.position.y = 0.45 + f.userData.h * k / 2; }); fglow.material.opacity = 0.4 + Math.sin(t * 6) * 0.12; for (let i = 0; i < EN; i++) { es[i] = (es[i] + dt * (0.25 + (i % 5) * 0.06)) % 1; const k = es[i]; ep[i * 3] = Math.sin(i * 2.4 + k * 5) * (0.2 + k * 0.9); ep[i * 3 + 1] = 0.8 + k * 5; ep[i * 3 + 2] = Math.cos(i * 1.7 + k * 4) * (0.2 + k * 0.9); } eg.attributes.position.needsUpdate = true; });
  // selfie studio booth on the beach
  const BX2 = beachX - 6, BZ2 = beachZ + 9; const booth = new T.Group(); booth.position.set(BX2, gy(BX2, BZ2), BZ2); S.add(booth); box(2.2, 2.6, 0.3, M(0xffffff), 0, 1.3, 0, booth); box(2.0, 1.3, 0.05, glow(0xff4fd8, 1.2), 0, 1.5, 0.17, booth); const bt = makeSprite('📸 Selfie studio · backgrounds, stickers, draw, download', { scale: 3.4, accent: '#ff4fd8' }); bt.position.y = 3.6; booth.add(bt); app.addObstacle && app.addObstacle(BX2, BZ2, 1.3); app.addInteractable && app.addInteractable(BX2, BZ2 + 1.6, 2.8, '📸 Selfie studio', () => selfieStudio(app)); app.addHotspot && app.addHotspot(booth, { fn: () => selfieStudio(app) });
  app.addPlace && app.addPlace({ id: mine ? 'lake-dillon' : 'lake-unity', name: mine ? "🏖️ Zach's Lake Dillon · swim, dive, fish, fire" : '🏞️ Lake Unity · Como-shaped', icon: mine ? '🏖️' : '🏞️', x: SX, z: SZ + 3, cat: 'Fun', top: true, keys: 'lake dillon unity swim dive fish fishing picnic beach fire firepit powwow jukebox selfie prize visa', say: mine ? 'Open to the world. The sign tells you everything.' : 'Lake Unity, out in the quiet.' });
  return { startGame, sitFire, openJuke };
}

/* 📸 the Selfie Studio: grab the 3D view, swap the background, add stickers, draw, download */
export function selfieStudio(app) { if (document.getElementById('aou-selfie')) return; let shot = null; try { app.renderer.render(app.scene, app.camera); shot = app.renderer.domElement.toDataURL('image/png'); } catch (e) { } app.paused = true;
  const o = document.createElement('div'); o.id = 'aou-selfie'; o.style.cssText = 'position:fixed;inset:0;z-index:99987;background:rgba(2,6,23,.75);display:flex;align-items:center;justify-content:center;padding:10px;font-family:Poppins,Arial'; o.innerHTML = `<div style="background:#fff;border-radius:20px;width:min(1100px,100%);max-height:96vh;overflow:auto;padding:12px 14px;color:#0f172a"><div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><b style="font:900 16px Poppins,Arial">📸 Selfie studio</b><span style="flex:1;color:#475569;font-size:13px">Your view is the photo. Swap the background, add stickers, draw, download.</span><button id="ss-x" style="border:1px solid #e2e8f0;background:#fff;border-radius:10px;width:36px;height:36px;cursor:pointer">✕</button></div>
    <div style="display:grid;grid-template-columns:1fr 280px;gap:10px;margin-top:10px" id="ss-grid"><canvas id="ss-c" width="1280" height="800" style="width:100%;height:auto;border-radius:12px;background:#111;touch-action:none;cursor:crosshair"></canvas><div style="display:flex;flex-direction:column;gap:8px">
    <b style="font-size:12px;color:#475569">BACKGROUND</b><div style="display:flex;flex-wrap:wrap;gap:6px">${[['view', '🧊 My view'], ['lake', '🏖️ Lake'], ['mall', '🏬 Mall'], ['world', '🌍 World'], ['zach', '😎 With Zach'], ['space', '🌌 Space'], ['neon', '🪩 Neon']].map(([k, n]) => `<button data-bg="${k}" style="border:1px solid #cbd5e1;background:#fff;border-radius:999px;padding:6px 10px;font:700 12px Poppins,Arial;cursor:pointer">${n}</button>`).join('')}</div>
    <b style="font-size:12px;color:#475569">STICKERS (tap canvas to place)</b><div style="display:flex;flex-wrap:wrap;gap:6px">${['✌️', '😎', '🔥', '🌈', '🐟', '🎢', '❤️', '🏔️', '👑', '🫧'].map(e => `<button data-st="${e}" style="border:1px solid #e2e8f0;background:#fff;border-radius:10px;width:40px;height:40px;font-size:20px;cursor:pointer">${e}</button>`).join('')}</div>
    <b style="font-size:12px;color:#475569">DRAW</b><div style="display:flex;flex-wrap:wrap;gap:6px">${['#ff4f79', '#ffd23f', '#38f0ff', '#7cff6b', '#ffffff', '#111111'].map(c => `<button data-c="${c}" style="width:30px;height:30px;border-radius:50%;border:2px solid #fff;box-shadow:0 0 0 1px #cbd5e1;background:${c};cursor:pointer"></button>`).join('')}<button data-c="rainbow" style="width:30px;height:30px;border-radius:50%;border:2px solid #fff;box-shadow:0 0 0 1px #cbd5e1;background:conic-gradient(red,orange,yellow,lime,cyan,blue,magenta,red);cursor:pointer"></button></div>
    <label style="font-size:12px;font-weight:800;color:#475569">Caption<input id="ss-cap" maxlength="60" placeholder="Living my best VR life" style="width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:10px;padding:8px;font:700 13px Poppins,Arial;margin-top:4px"></label>
    <button id="ss-dl" style="border:0;border-radius:999px;padding:11px 16px;font:900 14px Poppins,Arial;background:linear-gradient(135deg,#0ea5e9,#6366f1 55%,#a855f7);color:#fff;cursor:pointer">⬇️ Download selfie</button><button id="ss-post" style="border:1px solid #cbd5e1;border-radius:999px;padding:10px 16px;font:800 13px Poppins,Arial;background:#fff;cursor:pointer">📰 Download + post to my feed</button></div></div></div>`; document.body.appendChild(o); if (innerWidth < 760) o.querySelector('#ss-grid').style.gridTemplateColumns = '1fr';
  const cv = o.querySelector('#ss-c'), g = cv.getContext('2d'); let bg = 'view', col = '#ff4f79', hue = 0, sticker = null, drawing = false, last = null; const strokes = []; const stickers = []; const img = new Image(); if (shot) img.src = shot;
  const BGS = { lake: ['#38bdf8', '#0369a1', '🏔️🏖️🌊'], mall: ['#a855f7', '#1e1b4b', '🏬🎢🛍️'], world: ['#7cff6b', '#0f766e', '🌍✌️🌳'], zach: ['#0ea5e9', '#1e3a8a', ''], space: ['#1e1b4b', '#000000', '🌌🚀✨'], neon: ['#ff4fd8', '#38f0ff', '🪩🎶💜'] };
  const zimg = new Image(); zimg.src = '/images/zach-face-shades.webp';
  const paint = () => { g.clearRect(0, 0, 1280, 800); if (bg === 'view' && shot && img.complete) { const r = Math.max(1280 / img.width, 800 / img.height); g.drawImage(img, (1280 - img.width * r) / 2, (800 - img.height * r) / 2, img.width * r, img.height * r); } else if (bg === 'view') { g.fillStyle = '#0b1230'; g.fillRect(0, 0, 1280, 800); } else { const [a, b, em] = BGS[bg]; const gr = g.createLinearGradient(0, 0, 1280, 800); gr.addColorStop(0, a); gr.addColorStop(1, b); g.fillStyle = gr; g.fillRect(0, 0, 1280, 800); g.font = '140px serif'; g.globalAlpha = 0.25; g.textAlign = 'center'; g.fillText(em, 640, 500); g.globalAlpha = 1; if (shot && img.complete) { const w = 520, h = 520 * img.height / img.width; g.save(); g.beginPath(); g.roundRect(380, 400 - h / 2, w, h, 24); g.clip(); g.drawImage(img, 380, 400 - h / 2, w, h); g.restore(); g.lineWidth = 8; g.strokeStyle = '#fff'; g.beginPath(); g.roundRect(380, 400 - h / 2, w, h, 24); g.stroke(); } if (bg === 'zach' && zimg.complete) g.drawImage(zimg, 940, 320, 300, 380); }
    for (const st of strokes) { g.strokeStyle = st.c; g.lineWidth = 14; g.lineCap = 'round'; g.lineJoin = 'round'; g.beginPath(); st.p.forEach(([x, y], i) => i ? g.lineTo(x, y) : g.moveTo(x, y)); g.stroke(); } for (const s of stickers) { g.font = '110px serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillText(s.e, s.x, s.y); } const cap = o.querySelector('#ss-cap').value; if (cap) { g.font = '900 54px Poppins, Arial'; g.textAlign = 'center'; g.fillStyle = 'rgba(0,0,0,.45)'; g.fillRect(0, 700, 1280, 100); g.fillStyle = '#fff'; g.fillText(cap, 640, 764); } g.font = '700 26px Poppins, Arial'; g.textAlign = 'right'; g.fillStyle = 'rgba(255,255,255,.85)'; g.fillText('✌️ allofus.one', 1260, 40); };
  img.onload = paint; zimg.onload = paint; paint(); const pos = (e) => { const r = cv.getBoundingClientRect(); return [(e.clientX - r.left) * 1280 / r.width, (e.clientY - r.top) * 800 / r.height]; };
  cv.onpointerdown = (e) => { cv.setPointerCapture(e.pointerId); const [x, y] = pos(e); if (sticker) { stickers.push({ e: sticker, x, y }); paint(); return; } drawing = true; strokes.push({ c: col === 'rainbow' ? `hsl(${(hue += 40) % 360},90%,60%)` : col, p: [[x, y]] }); }; cv.onpointermove = (e) => { if (!drawing) return; strokes[strokes.length - 1].p.push(pos(e)); paint(); }; cv.onpointerup = () => { drawing = false; };
  o.querySelectorAll('[data-bg]').forEach(b => b.onclick = () => { bg = b.dataset.bg; paint(); }); o.querySelectorAll('[data-st]').forEach(b => b.onclick = () => { sticker = sticker === b.dataset.st ? null : b.dataset.st; o.querySelectorAll('[data-st]').forEach(q => q.style.background = q.dataset.st === sticker ? '#fef3c7' : '#fff'); }); o.querySelectorAll('[data-c]').forEach(b => b.onclick = () => { col = b.dataset.c; sticker = null; }); o.querySelector('#ss-cap').oninput = paint;
  const dl = () => { const a = document.createElement('a'); a.href = cv.toDataURL('image/png'); a.download = 'allofus-selfie.png'; a.click(); app.celebrate && app.celebrate('📸'); }; o.querySelector('#ss-dl').onclick = dl; o.querySelector('#ss-post').onclick = () => { dl(); setTimeout(() => { location.href = '/flat/'; }, 600); };
  o.querySelector('#ss-x').onclick = () => { o.remove(); app.paused = false; }; }
