/* ============================================================
   FAMILY + FUN (v2.6)
   - skyLift(): a glass elevator to a viewing deck high above the world (Zach's, Elias's, Ethan's)
   - Elias's House: stacked, offset glass-and-charcoal cubes, cantilevers, rooftop infinity pool, neon game room with
     Zach's 3D games on the wall (thevrgalaxy, anotherdimensionvr, vrflyingsimulator)
   - Ethan's House: stone-and-brick "precinct" with a watch tower, courtyard pool, patrol car, K9 kennel, badge wall
   - The front pool at Zach's: clover-shaped, 10 ft deep, swim in it, chromatherapy colors, adjustable fountain
   - Snowboard: a real run down Mount Cobes with snow, steering, jumps, flips, slalom gates, 2-player
   ============================================================ */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { M, glow, box, cyl, sph, textPlane } from './aou-kit.js';
import { terrainY, addFlat, MTN } from './aou-terrain.js';
const T = THREE; const MOB = isMobile();
const glassM = (c = 0x9fd8ff, o = 0.35) => new T.MeshPhysicalMaterial({ color: c, transparent: true, opacity: o, roughness: 0.05, metalness: 0.1, transmission: 0, side: T.DoubleSide });

/* ---------------- sky elevator ---------------- */
export function skyLift(app, x, z, top, name, color = 0x38f0ff) {
  const S = app.scene; const y0 = terrainY(x, z); const g = new T.Group(); g.position.set(x, y0, z); S.add(g);
  const tube = new T.Mesh(new T.CylinderGeometry(1.6, 1.6, top, 24, 1, true), glassM(color, 0.18)); tube.position.y = top / 2; g.add(tube); for (let i = 0; i <= Math.floor(top / 6); i++) { const r = new T.Mesh(new T.TorusGeometry(1.62, 0.06, 8, 32), glow(color, 1.2)); r.rotation.x = Math.PI / 2; r.position.y = i * 6; g.add(r); }
  const cab = new T.Group(); g.add(cab); const cabG = cyl(1.3, 1.3, 2.6, glassM(0xffffff, 0.3), 0, 1.3, 0, cab, 20); cyl(1.35, 1.35, 0.16, M(0x1e2a4a, { metalness: 0.7, roughness: 0.3 }), 0, 0.08, 0, cab, 20); cyl(1.35, 1.35, 0.1, M(0x1e2a4a), 0, 2.6, 0, cab, 20); sph(0.14, glow(0xfff3b0, 2), 0, 2.4, 0, cab, 8);
  const deck = new T.Group(); deck.position.y = top; g.add(deck); const floor = cyl(8, 8, 0.4, M(0x15213f, { metalness: 0.6, roughness: 0.35 }), 0, 0, 0, deck, 32); const rail = new T.Mesh(new T.TorusGeometry(8, 0.08, 8, 48), glow(color, 1.4)); rail.rotation.x = Math.PI / 2; rail.position.y = 1.1; deck.add(rail); const rail2 = rail.clone(); rail2.position.y = 0.55; deck.add(rail2); const glassWall = new T.Mesh(new T.CylinderGeometry(8, 8, 1.2, 48, 1, true), glassM(color, 0.12)); glassWall.position.y = 0.6; deck.add(glassWall); for (let i = 0; i < 6; i++) { const a = i / 6 * 6.283; const seat = box(1.6, 0.4, 0.5, M(0x6366f1), Math.cos(a) * 6.2, 0.4, Math.sin(a) * 6.2, deck); seat.rotation.y = -a; } const scope = cyl(0.12, 0.16, 1.2, M(0xdfe6f2, { metalness: 0.8 }), 0, 1.3, 5, deck, 8); scope.rotation.x = -0.5; const sign = makeSprite(`🛗 ${name} · sky deck · ${Math.round(top * 3.28)} ft up`, { scale: 5, accent: '#' + color.toString(16).padStart(6, '0') }); sign.position.y = top + 4; g.add(sign);
  app.addObstacle && app.addObstacle(x, z, 1.8);
  const ST = { pos: 'down', busy: false }; const it = { x, z: z + 2.4, r: 3.2, label: `🛗 ${name}: ride the sky elevator up`, fn: () => go() };
  const go = () => { if (ST.busy) return; const up = ST.pos === 'down'; ST.busy = true; const t0 = app.t, dur = 7; const from = up ? 0 : top, to = up ? top : 0; app.toast(up ? '🛗 Going up. Hold on. The whole world from up here.' : '🛗 Coming down.', 2500); app.buzz && app.buzz(30); app.ride = { pos: (t) => { const k = Math.min(1, (t - t0) / dur); const e = k < 0.5 ? 2 * k * k : 1 - Math.pow(-2 * k + 2, 2) / 2; const y = from + (to - from) * e; cab.position.y = y; if (k >= 1 && ST.busy) { ST.busy = false; ST.pos = up ? 'up' : 'down'; it.label = up ? `🛗 ${name}: come back down` : `🛗 ${name}: ride the sky elevator up`; if (up) { app.ride = { pos: () => new T.Vector3(x, y0 + top + 0.2, z + 5), yaw: app.yaw, stand: true, until: 1e12 }; app.targetDist = Math.max(app.targetDist, 9); app.pitch = -0.05; app.toast('🔭 Sky deck. Drag to look around. Tap 🛗 to come down.', 4500); } else { app.ride = null; app.seatClear && app.seatClear(); app.player.position.set(x, y0, z + 2.4); } } return new T.Vector3(x, y0 + y + 0.2, z); }, yaw: app.yaw, stand: true, until: 1e12 }; }; (app.interactables = app.interactables || []).push(it); app.addHotspot && app.addHotspot(cabG, { fn: go });
  return { go, deck };
}

/* ---------------- the two nephew mansions ---------------- */
const ROOF = () => M(0x1e2a4a, { metalness: 0.4, roughness: 0.5 });
function floorFlat(x, z, w, d, y, face) { const cs = Math.cos(face), sn = Math.sin(face); const r = Math.max(w, d) / 2 + 2; addFlat({ x1: x - r, x2: x + r, z1: z - r, z2: z + r, y, soft: 3 }); }
export function buildElias(app, W, X, Z, face = 0) {
  const S = app.scene; const y0 = terrainY(X, Z); addFlat({ x: X, z: Z, r: 34, y: y0, soft: 10 }); const G = new T.Group(); G.position.set(X, y0, Z); G.rotation.y = face; S.add(G); const charcoal = M(0x23262e, { roughness: 0.6, metalness: 0.2 }), neon = (c) => glow(c, 1.6), gl = glassM(0x7fd3ff, 0.32);
  // three offset cubes, each cantilevered a different way
  const cubes = [[0, 0, 0, 16, 5, 14], [-4, 5, 3, 14, 5, 12], [5, 10, -3, 12, 5, 10]]; cubes.forEach(([cx, cy, cz, w, h, d], i) => { box(w, h, d, i % 2 ? gl : charcoal, cx, cy + h / 2, cz, G); const trim = box(w + 0.2, 0.12, d + 0.2, neon([0x38f0ff, 0xff4fd8, 0xb388ff][i]), cx, cy + h, cz, G); const trim2 = box(w + 0.2, 0.12, d + 0.2, neon([0x38f0ff, 0xff4fd8, 0xb388ff][i]), cx, cy + 0.06, cz, G); if (i === 0) for (let k = -1; k <= 1; k++) box(0.3, h, 0.3, M(0xdfe6f2, { metalness: 0.9 }), cx + k * 5, cy + h / 2, cz + d / 2 + 0.2, G); const floorY = y0 + cy + 0.26; floorFlat(X + cx, Z + cz, w, d, floorY, face); });
  box(14, 0.3, 12, charcoal, 5, 15, -3, G); // rooftop slab
  // rooftop infinity pool
  const pool = box(9, 1.2, 6, new T.MeshPhysicalMaterial({ color: 0x1ee0ff, transparent: true, opacity: 0.6, roughness: 0.05 }), 5, 15.6, -3, G); box(9.4, 1.3, 0.3, gl, 5, 15.6, 0.1, G); const poolPts = [[-4.5, -3], [4.5, -3], [4.5, 3], [-4.5, 3]].map(([a, b]) => { const cs = Math.cos(face), sn = Math.sin(face); const lx = 5 + a, lz = -3 + b; return [X + lx * cs + lz * sn, Z - lx * sn + lz * cs]; });
  // interior: game room on the ground floor with the arcade wall + neon
  const room = new T.Group(); G.add(room); box(14, 0.2, 12, M(0x111318), 0, 0.3, 0, room); for (let i = 0; i < 3; i++) { const sc = textPlane([['🪐 THE VR GALAXY', 'thevrgalaxy.com'], ['🌀 ANOTHER DIMENSION', 'anotherdimensionvr.com'], ['✈️ VR FLYING SIM', 'vrflyingsimulator.com']][i], 3.6, 2.1, { bg: '#0b1a3a', fg: '#fff', accent: ['#38f0ff', '#ff4fd8', '#ffd23f'][i] }); sc.position.set(-4.5 + i * 4.5, 2.4, -6.7); room.add(sc); const fr = box(3.9, 2.4, 0.08, neon(['#38f0ff', '#ff4fd8', '#ffd23f'][i].replace('#', '0x') * 1), -4.5 + i * 4.5, 2.4, -6.78, room); } const couch = box(6, 0.8, 1.6, M(0x5b21b6), 0, 0.7, -2, room); box(6, 1.0, 0.4, M(0x4c1d95), 0, 1.3, -1.3, room); const table = cyl(1.0, 1.0, 0.1, gl, 0, 0.9, -4.2, room, 24); for (let i = 0; i < 6; i++) { const p = sph(0.08, neon([0x38f0ff, 0xff4fd8, 0xffd23f][i % 3]), -6 + i * 2.4, 4.7, 5, room, 6); } const bar = box(5, 1.1, 0.8, charcoal, 4, 0.85, 5, room); box(5.2, 0.08, 0.9, neon(0x38f0ff), 4, 1.42, 5, room); const bed = box(2.2, 0.5, 2.6, M(0x1e1b4b), -4, 5.6, 3, G); box(2.2, 0.6, 0.3, M(0xb388ff), -4, 6.1, 1.8, G); const fish = new T.Mesh(new T.BoxGeometry(3, 1.2, 0.7), glassM(0x8fd3ff, 0.35)); fish.position.set(-5.5, 1.3, 2); room.add(fish); for (let i = 0; i < 5; i++) { const f = sph(0.08, M([0xff6a1f, 0xffd23f, 0x38f0ff, 0xff4fd8, 0x7cff6b][i]), -5.5 + Math.cos(i) * 1.2, 1.2 + (i % 2) * 0.3, 2, room, 6); f.scale.set(0.6, 0.5, 1.4); f.userData.swim = i; }
  const sign = makeSprite("🎮 ELIAS'S HOUSE · game room · rooftop pool · sky elevator", { scale: 6, accent: '#38f0ff' }); sign.position.set(0, 20, 0); G.add(sign);
  const L = (lx, lz) => { const cs = Math.cos(face), sn = Math.sin(face); return [X + lx * cs + lz * sn, Z - lx * sn + lz * cs]; };
  app.addObstacle && app.addObstacle(...L(0, 0), 9); app.addWater && app.addWater({ poly: poolPts, y: y0 + 16.2 });
  const [gx, gz] = L(0, 8.5); app.addInteractable && app.addInteractable(gx, gz, 4.5, "🎮 Elias's game room: play the games", () => { const html = `<p>Elias is 21 and games. His wall runs Zach's 3D games for real. Pick one:</p><div class="aou-styles">${[['🪐', 'The VR Galaxy', 'https://thevrgalaxy.com/'], ['🌀', 'Another Dimension VR', 'https://anotherdimensionvr.com/'], ['✈️', 'VR Flying Simulator', 'https://vrflyingsimulator.com/'], ['🕹️', 'Code Snake (arcade)', '/arcade/']].map(([ic, n, u]) => `<button data-g="${u}"><span>${ic}</span><b>${n}</b><small>opens on the wall</small></button>`).join('')}</div>`; const m = W.api && W.api.modal ? W.api.modal("🎮 Elias's game wall", html, { wide: true }) : null; (m || document).querySelectorAll('[data-g]').forEach(b => b.onclick = () => { const u = b.dataset.g; const body = (m || document).querySelector('.aou-body'); if (body) body.innerHTML = `<iframe src="${u}" style="width:100%;height:70vh;border:0;border-radius:14px;background:#000" allow="fullscreen; gamepad; xr-spatial-tracking"></iframe><p class="aou-note">Playing on the wall. <a href="${u}" target="_blank" rel="noopener">Open full screen ↗</a></p>`; }); });
  const [px, pz] = L(5, 2); app.addInteractable && app.addInteractable(px, pz, 4, '🏊 Rooftop infinity pool (take the elevator)', () => app.toast('🏊 Take the 🛗 up to the rooftop and jump in.', 2500));
  const [ex, ez] = L(-10, 8); const lift = skyLift(app, ex, ez, 70, "Elias's", 0x38f0ff); app.addPlace && app.addPlace({ id: 'elias', name: "🎮 Elias's House · game room + rooftop pool", icon: '🎮', x: gx, z: gz + 3, cat: 'Homes', keys: 'elias nephew gaming house mansion', say: 'Three stacked glass cubes, neon trim, a rooftop infinity pool and a wall of real games.' });
  app.onUpdate((dt, t) => { if (Math.hypot(app.player.position.x - X, app.player.position.z - Z) > 160) return; room.children.forEach(c => { if (c.userData.swim !== undefined) c.position.x = -5.5 + Math.cos(t * 0.7 + c.userData.swim) * 1.2; }); });
  return { lift };
}
export function buildEthan(app, W, X, Z, face = 0) {
  const S = app.scene; const y0 = terrainY(X, Z); addFlat({ x: X, z: Z, r: 34, y: y0, soft: 10 }); const G = new T.Group(); G.position.set(X, y0, Z); G.rotation.y = face; S.add(G); const stone = M(0x9aa3ad, { roughness: 0.95 }), brick = M(0x8b3a2f, { roughness: 0.9 }), navy = M(0x1b2a4a), gl = glassM(0xbfe3ff, 0.3);
  // U-shaped precinct around a courtyard pool, with a watch tower on the corner
  box(22, 6, 7, brick, 0, 3, -8, G); box(7, 6, 18, stone, -7.5, 3, 2.5, G); box(7, 6, 18, stone, 7.5, 3, 2.5, G); box(22.4, 0.5, 7.4, navy, 0, 6.2, -8, G); box(7.4, 0.5, 18.4, navy, -7.5, 6.2, 2.5, G); box(7.4, 0.5, 18.4, navy, 7.5, 6.2, 2.5, G); for (let i = -2; i <= 2; i++) { box(1.6, 1.6, 0.1, gl, i * 4, 3.4, -4.4, G); box(1.6, 1.6, 0.1, gl, i * 4, 3.4, -11.6, G); } for (let k = 0; k < 4; k++) { box(0.1, 1.6, 1.6, gl, -3.9, 3.4, -4 + k * 4, G); box(0.1, 1.6, 1.6, gl, 3.9, 3.4, -4 + k * 4, G); }
  floorFlat(X, Z - 8, 22, 7, y0 + 0.3, face); floorFlat(X - 7.5, Z + 2.5, 7, 18, y0 + 0.3, face); floorFlat(X + 7.5, Z + 2.5, 7, 18, y0 + 0.3, face);
  // tower
  const tw = box(5, 14, 5, stone, -7.5, 7, -8, G); box(5.6, 0.6, 5.6, navy, -7.5, 14.3, -8, G); for (let i = 0; i < 4; i++) box(0.6, 1.0, 0.6, stone, -7.5 + [-2.3, 2.3, -2.3, 2.3][i], 15.1, -8 + [-2.3, -2.3, 2.3, 2.3][i], G); const beacon = sph(0.3, glow(0x2f6bff, 2.5), -7.5, 16, -8, G, 10); const beacon2 = sph(0.3, glow(0xff2f4f, 2.5), -7.5, 16, -8, G, 10); beacon2.visible = false;
  // courtyard pool (kidney) + deck + flagpole + badge wall
  const poolM = new T.MeshPhysicalMaterial({ color: 0x19c7ff, transparent: true, opacity: 0.6, roughness: 0.05 }); const pool = new T.Mesh(new T.CylinderGeometry(4.2, 4.2, 1.2, 24), poolM); pool.position.set(1, -0.3, 2); pool.scale.set(1, 1, 0.7); G.add(pool); const pool2 = pool.clone(); pool2.position.set(-1.5, -0.3, 6); pool2.scale.set(0.7, 1, 0.6); G.add(pool2); const poolPts = []; for (let i = 0; i < 16; i++) { const a = i / 16 * 6.283; poolPts.push([1 + Math.cos(a) * 4.2, 2 + Math.sin(a) * 2.9]); } const PP = poolPts.map(([lx, lz]) => { const cs = Math.cos(face), sn = Math.sin(face); return [X + lx * cs + lz * sn, Z - lx * sn + lz * cs]; }); app.addWater && app.addWater({ poly: PP, y: y0 + 0.1 });
  cyl(0.06, 0.06, 9, M(0xdfe6f2, { metalness: 0.9 }), 9, 4.5, 11, G, 8); const flag = new T.Mesh(new T.PlaneGeometry(2.4, 1.4, 8, 3), new T.MeshStandardMaterial({ color: 0x1b2a4a, side: T.DoubleSide, emissive: 0x0b1a3a, emissiveIntensity: 0.4 })); flag.position.set(10.2, 8.2, 11); G.add(flag); const star = makeSprite('⭐', { scale: 1.2, bg: 'rgba(0,0,0,0)' }); star.position.set(10.2, 8.2, 11.02); G.add(star);
  const badge = textPlane(['★ OFFICER ETHAN ★', 'FUTURE POLICE · PROTECT + SERVE', 'Unity Heights Precinct No. 1'], 6, 2.6, { bg: '#1b2a4a', fg: '#ffd23f', accent: '#38f0ff' }); badge.position.set(0, 3.6, -4.3); G.add(badge);
  // patrol car + K9 kennel
  const car = new T.Group(); car.position.set(9, 0, -16); car.rotation.y = 0.2; G.add(car); box(4.6, 0.9, 2.0, M(0xf1f5f9, { metalness: 0.5, roughness: 0.3 }), 0, 0.75, 0, car); box(2.6, 0.8, 1.9, M(0x111318, { metalness: 0.5, roughness: 0.3 }), -0.2, 1.55, 0, car); box(2.2, 0.7, 1.7, glassM(0x1b2a4a, 0.7), -0.2, 1.6, 0, car); box(1.2, 0.25, 0.4, glow(0x2f6bff, 2), -0.6, 2.05, 0, car); const lb = box(1.2, 0.25, 0.4, glow(0xff2f4f, 2), 0.2, 2.05, 0, car); for (const [x, z] of [[-1.5, 1], [1.5, 1], [-1.5, -1], [1.5, -1]]) { const w = cyl(0.42, 0.42, 0.3, M(0x111318), x, 0.42, z, car, 14); w.rotation.x = Math.PI / 2; } const pl = textPlane(['POLICE'], 2.4, 0.5, { bg: '#f1f5f9', fg: '#1b2a4a', accent: '#1b2a4a', font: 'bold 120px Poppins, Arial' }); pl.position.set(0, 0.8, 1.02); car.add(pl); const pl2 = pl.clone(); pl2.position.z = -1.02; pl2.rotation.y = Math.PI; car.add(pl2);
  const kennel = new T.Group(); kennel.position.set(-13, 0, 10); G.add(kennel); box(2.4, 1.6, 2.4, M(0x8a5a2b), 0, 0.8, 0, kennel); box(2.8, 0.2, 2.8, navy, 0, 1.7, 0, kennel); box(0.9, 1.1, 0.1, M(0x111318), 0, 0.55, 1.22, kennel); const k9 = makeSprite('🐕‍🦺 K9 UNIT · Rex', { scale: 2.4, accent: '#ffd23f' }); k9.position.set(0, 2.6, 0); kennel.add(k9); const rex = new T.Group(); rex.position.set(1.6, 0, 1.2); kennel.add(rex); const bb = sph(0.3, M(0x5d4037), 0, 0.5, 0, rex, 10); bb.scale.set(0.8, 0.7, 1.4); sph(0.2, M(0x5d4037), 0, 0.75, 0.5, rex, 8); cyl(0.05, 0.05, 0.4, M(0x5d4037), 0, 0.2, 0.3, rex, 5); cyl(0.05, 0.05, 0.4, M(0x5d4037), 0, 0.2, -0.3, rex, 5);
  // interior basics + gym
  const room = new T.Group(); G.add(room); box(20, 0.2, 5.5, M(0x1e293b), 0, 0.3, -8, room); box(3, 0.9, 1.2, M(0x334155), -6, 0.75, -8, room); box(2.2, 0.08, 1, M(0x0f172a), -6, 1.24, -8, room); for (let i = 0; i < 3; i++) { const sc = textPlane([['📺 PRECINCT CAM 0' + (i + 1)]][0], 1.6, 1.0, { bg: '#0b1a3a', fg: '#7cf8ff', accent: '#38f0ff' }); sc.position.set(-7.5 + i * 1.7, 2.0, -11.2); room.add(sc); } const rack = box(2, 0.1, 0.6, M(0x334155), 5, 1.2, -8, room); for (let i = 0; i < 4; i++) cyl(0.18, 0.18, 0.1, M(0x111318), 4.3 + i * 0.45, 1.3, -8, room, 12); const bench = box(1.6, 0.3, 0.5, M(0x1b2a4a), 7.5, 0.6, -6, room); box(0.08, 0.08, 1.4, M(0x6b7280), 7.5, 1.4, -6, room);
  const L = (lx, lz) => { const cs = Math.cos(face), sn = Math.sin(face); return [X + lx * cs + lz * sn, Z - lx * sn + lz * cs]; }; const sign = makeSprite("👮 ETHAN'S HOUSE · precinct · tower · courtyard pool · K9", { scale: 6, accent: '#ffd23f' }); sign.position.set(0, 19, 0); G.add(sign);
  app.addObstacle && app.addObstacle(...L(0, -8), 6); app.addObstacle && app.addObstacle(...L(-7.5, 2.5), 3.6); app.addObstacle && app.addObstacle(...L(7.5, 2.5), 3.6); app.addObstacle && app.addObstacle(...L(9, -16), 2.4);
  const [cx, cz] = L(9, -13.5); app.addInteractable && app.addInteractable(cx, cz, 3.5, '🚓 Patrol car: lights + siren', () => { ETH.siren = !ETH.siren; app.toast(ETH.siren ? '🚨 Lights on. (Siren is pretend; the neighbors thank you.)' : '🚓 Lights off.', 2000); }); const [bx, bz] = L(0, -2); app.addInteractable && app.addInteractable(bx, bz, 3.5, "⭐ Officer Ethan's badge wall", () => app.toast('⭐ Future officer. Protect and serve. The precinct is his, the K9 is Rex, the pool is for after the shift.', 4000)); const [kx, kz] = L(-11.5, 11); app.addInteractable && app.addInteractable(kx, kz, 3, '🐕‍🦺 Rex the K9: pet', () => { app.toast('🐕‍🦺 Rex sits, stays, then licks your whole face. Trained, mostly.', 2500); app.celebrate && app.celebrate('🐾'); });
  const ETH = { siren: false }; const [ex, ez] = L(13, -2); const lift = skyLift(app, ex, ez, 64, "Ethan's", 0xffd23f); app.addPlace && app.addPlace({ id: 'ethan', name: "👮 Ethan's House · precinct + pool + K9", icon: '👮', x: bx, z: bz + 4, cat: 'Homes', keys: 'ethan nephew police cop house precinct', say: 'A real precinct for a future officer: tower beacon, patrol car, Rex the K9, courtyard pool.' });
  app.onUpdate((dt, t) => { if (Math.hypot(app.player.position.x - X, app.player.position.z - Z) > 160) return; const f = Math.sin(t * 8) > 0; beacon.visible = f; beacon2.visible = !f; if (ETH.siren) { lb.visible = f; car.children.forEach(c => { if (c.material && c.material.emissive && c.material.emissiveIntensity > 1) c.material.emissiveIntensity = f ? 3 : 0.5; }); } const fp = flag.geometry.attributes.position; for (let i = 0; i < fp.count; i++) { const x = fp.getX(i); fp.setZ(i, Math.sin(t * 5 + x * 2) * 0.1 * (x + 1.2) / 2.4); } fp.needsUpdate = true; rex.position.x = 1.6 + Math.sin(t * 0.6) * 1.2; rex.rotation.y = Math.cos(t * 0.6) > 0 ? Math.PI / 2 : -Math.PI / 2; });
  return { lift };
}

/* ---------------- Zach's front pool: clover, 10 ft deep, chromatherapy ---------------- */
export function buildFrontPool(app, W, x, z) {
  const S = app.scene; const y0 = terrainY(x, z); const G = new T.Group(); G.position.set(x, y0, z); S.add(G); addFlat({ x, z, r: 16, y: y0, soft: 6 });
  const lobes = [[0, -5.5], [5.5, 0], [0, 5.5], [-5.5, 0]]; const poly = []; for (let i = 0; i < 40; i++) { const a = i / 40 * 6.283; const r = 6.5 + 2.6 * Math.abs(Math.cos(a * 2)); poly.push([x + Math.cos(a) * r, z + Math.sin(a) * r]); }
  const waterM = new T.MeshPhysicalMaterial({ color: 0x19c7ff, transparent: true, opacity: 0.62, roughness: 0.05, metalness: 0.05, emissive: 0x0b4a66, emissiveIntensity: 0.4 }); const shape = new T.Shape(); poly.forEach(([px, pz], i) => { if (i) shape.lineTo(px - x, pz - z); else shape.moveTo(px - x, pz - z); }); shape.closePath(); const water = new T.Mesh(new T.ShapeGeometry(shape, 1), waterM); water.rotation.x = -Math.PI / 2; water.position.y = 0.05; G.add(water); const basin = new T.Mesh(new T.ExtrudeGeometry(shape, { depth: 0.4, bevelEnabled: false }), M(0xe2e8f0, { roughness: 0.6 })); basin.rotation.x = Math.PI / 2; basin.position.y = 0.06; basin.scale.set(1.06, 1.06, 1); G.add(basin); const rim = new T.Mesh(new T.ExtrudeGeometry(shape, { depth: 0.25, bevelEnabled: false }), glow(0x38f0ff, 1.2)); rim.rotation.x = Math.PI / 2; rim.position.y = 0.3; rim.scale.set(1.09, 1.09, 1); G.add(rim); const rim2 = new T.Mesh(new T.ExtrudeGeometry(shape, { depth: 0.2, bevelEnabled: false }), M(0xe2e8f0)); rim2.rotation.x = Math.PI / 2; rim2.position.y = 0.32; rim2.scale.set(1.0, 1.0, 1); G.add(rim2);
  const cx = cyl(0.9, 1.2, 1.1, M(0xcbd5e1), 0, 0.55, 0, G, 20); const jets = []; for (let i = 0; i < 9; i++) { const j = new T.Mesh(new T.CylinderGeometry(0.08, 0.18, 1, 8, 1, true), new T.MeshStandardMaterial({ color: 0xcfefff, transparent: true, opacity: 0.55 })); j.position.set(i === 0 ? 0 : Math.cos(i * 0.785) * 4.2, 0.6, i === 0 ? 0 : Math.sin(i * 0.785) * 4.2); G.add(j); jets.push(j); } const lights = []; for (let i = 0; i < 8; i++) { const l = sph(0.18, glow(0x38f0ff, 2), Math.cos(i * 0.785) * 7.6, 0.2, Math.sin(i * 0.785) * 7.6, G, 8); lights.push(l); }
  app.addWater && app.addWater({ poly, y: y0 + 0.1 }); const ST = { mode: 'ocean', jet: 1 }; const MODES = { ocean: [0x19c7ff, 'calm'], lavender: [0xb388ff, 'rest'], rose: [0xff6fd8, 'love'], gold: [0xffd23f, 'energy'], emerald: [0x2ee59d, 'balance'], rainbow: [0xffffff, 'party'] };
  const sign = makeSprite("🏊 ZACH'S POOL · swim · chromatherapy · fountain", { scale: 5, accent: '#38f0ff' }); sign.position.y = 6; G.add(sign);
  const control = () => { const html = `<p>Chromatherapy: pick the water color. Jets: pick the height. Then jump in. It is 10 feet deep in the middle.</p><div class="aou-chips">${Object.entries(MODES).map(([k, [c, m]]) => `<button class="lt-btn" data-mode="${k}" style="border-left:6px solid #${c.toString(16).padStart(6, '0')}">${k} · ${m}</button>`).join('')}</div><p class="aou-lbl">Fountain</p><div class="aou-chips">${[['off', 0], ['low', 0.5], ['normal', 1], ['high', 2], ['geyser', 4]].map(([n, v]) => `<button class="lt-btn" data-jet="${v}">${n}</button>`).join('')}</div>`; const m = W.api && W.api.modal ? W.api.modal("🏊 Zach's pool", html) : null; (m || document).querySelectorAll('[data-mode]').forEach(b => b.onclick = () => { ST.mode = b.dataset.mode; app.toast('🎨 ' + b.dataset.mode + ' water.', 1500); }); (m || document).querySelectorAll('[data-jet]').forEach(b => b.onclick = () => { ST.jet = +b.dataset.jet; app.toast(ST.jet ? '⛲ Fountain: ' + b.textContent : '⛲ Fountain off. Just a pool now.', 1500); }); };
  app.addInteractable && app.addInteractable(x, z - 9.5, 3.5, '🏊 Pool controls: color + fountain', control); app.addHotspot && app.addHotspot(cx, { fn: control });
  app.onUpdate((dt, t) => { const P = app.player.position; if (Math.hypot(P.x - x, P.z - z) > 120) return; let col; if (ST.mode === 'rainbow') { col = new T.Color().setHSL((t * 0.15) % 1, 1, 0.55); } else col = new T.Color(MODES[ST.mode][0]); waterM.color.lerp(col, 0.05); waterM.emissive.copy(waterM.color).multiplyScalar(0.35); lights.forEach((l, i) => { l.material.color.lerp(col, 0.05); l.material.emissive.lerp(col, 0.05); l.position.y = 0.2 + Math.sin(t * 2 + i) * 0.05; }); jets.forEach((j, i) => { const h = (i === 0 ? 6 : 2.4) * ST.jet * (0.85 + Math.sin(t * 3 + i) * 0.15); j.visible = ST.jet > 0; j.scale.y = Math.max(0.01, h); j.position.y = 0.6 + h / 2; }); });
  app.addPlace && app.addPlace({ id: 'zach-pool', name: "🏊 Zach's pool · chromatherapy fountain", icon: '🏊', x, z: z - 10, cat: 'Fun', keys: 'pool swim fountain zach chromatherapy', say: 'Clover pool, ten feet deep. Pick a color and jump in.' });
}

/* ---------------- the real snowboard game ---------------- */
export function buildSnowboard(app, W) {
  const S = app.scene; const toast = (m, ms) => app.toast(m, ms); const top = { x: MTN.x + 30, z: MTN.z + 10 }; const START = new T.Vector3(top.x, 0, top.z); const dir = new T.Vector3(0.35, 0, -1).normalize(); const LEN = 300;
  const snowM = new T.MeshStandardMaterial({ color: 0xf4f9ff, roughness: 0.95, metalness: 0 }); const half = 22; const seg = Math.round(LEN / 4); const geo = new T.BufferGeometry(); const pos = [], uv = [], idx = []; const side = new T.Vector3(-dir.z, 0, dir.x); for (let i = 0; i <= seg; i++) { const d = i / seg * LEN; const c = START.clone().addScaledVector(dir, d); for (let k = 0; k <= 10; k++) { const s = (k / 10 - 0.5) * 2 * half; const x = c.x + side.x * s, z = c.z + side.z * s; const bump = Math.sin(d * 0.15) * Math.cos(s * 0.3) * 0.25; pos.push(x, terrainY(x, z) + 0.35 + bump, z); uv.push(k / 10, i / seg); } } for (let i = 0; i < seg; i++) for (let k = 0; k < 10; k++) { const a = i * 11 + k; idx.push(a, a + 1, a + 11, a + 1, a + 12, a + 11); } geo.setAttribute('position', new T.Float32BufferAttribute(pos, 3)); geo.setAttribute('uv', new T.Float32BufferAttribute(uv, 2)); geo.setIndex(idx); geo.computeVertexNormals(); const run = new T.Mesh(geo, snowM); run.receiveShadow = true; run.userData.noCollide = true; S.add(run); const surfY = (x, z) => { const rel = new T.Vector3(x, 0, z).sub(START); const d = rel.dot(dir); const s = rel.dot(side); const c = START.clone().addScaledVector(dir, d); return terrainY(c.x + side.x * s, c.z + side.z * s) + 0.35 + Math.sin(d * 0.15) * Math.cos(s * 0.3) * 0.25; };
  // gates, kickers, trees along the edge
  const gates = []; for (let d = 40; d < LEN - 30; d += 36) { const c = START.clone().addScaledVector(dir, d); const s = Math.sin(d * 0.08) * 10; const gx = c.x + side.x * s, gz = c.z + side.z * s; for (const q of [-1, 1]) { const p = cyl(0.06, 0.06, 2.2, M(q > 0 ? 0xff4f79 : 0x2f6bff), gx + side.x * q * 2.5, surfY(gx + side.x * q * 2.5, gz + side.z * q * 2.5) + 1.1, gz + side.z * q * 2.5, S, 6); const fl = box(0.5, 0.35, 0.03, glow(q > 0 ? 0xff4f79 : 0x2f6bff, 1), gx + side.x * q * 2.5, surfY(gx, gz) + 2, gz + side.z * q * 2.5, S); } gates.push({ d, s }); } const kickers = []; for (const d of [90, 170, 240]) { const c = START.clone().addScaledVector(dir, d); const k = new T.Mesh(new T.BoxGeometry(10, 1.6, 6), snowM); k.position.set(c.x, surfY(c.x, c.z) + 0.4, c.z); k.rotation.x = 0.35; k.lookAt(c.x + dir.x, k.position.y + 0.4, c.z + dir.z); S.add(k); kickers.push(d); } for (let d = 10; d < LEN; d += 18) for (const q of [-1, 1]) { const c = START.clone().addScaledVector(dir, d); const tx = c.x + side.x * q * (half + 3 + (d % 7)), tz = c.z + side.z * q * (half + 3 + (d % 5)); const ty = terrainY(tx, tz); cyl(0.2, 0.3, 2.5, M(0x4a3222), tx, ty + 1.2, tz, S, 6); const cone = new T.Mesh(new T.ConeGeometry(1.8, 5, 8), M(0x2e5f3f)); cone.position.set(tx, ty + 4.5, tz); S.add(cone); const cap = new T.Mesh(new T.ConeGeometry(1.2, 2.2, 8), snowM); cap.position.set(tx, ty + 6.2, tz); S.add(cap); }
  const fin = START.clone().addScaledVector(dir, LEN); const banner = textPlane(['FINISH'], 10, 2, { bg: '#ff4f79', fg: '#fff', accent: '#fff' }); banner.position.set(fin.x, surfY(fin.x, fin.z) + 4.5, fin.z); banner.lookAt(START.x, banner.position.y, START.z); banner.material.side = T.DoubleSide; S.add(banner); for (const q of [-1, 1]) cyl(0.1, 0.1, 5, M(0xdfe6f2), fin.x + side.x * q * 5, surfY(fin.x, fin.z) + 2.5, fin.z + side.z * q * 5, S, 8);
  const sgn = makeSprite('🏂 SNOWBOARD RUN · steer · jump · flip · 2 players', { scale: 6, accent: '#38f0ff' }); sgn.position.set(START.x, surfY(START.x, START.z) + 5, START.z); S.add(sgn);
  const mkBoard = (c) => { const g = new T.Group(); const b = box(0.3, 0.05, 1.6, new T.MeshStandardMaterial({ color: c, metalness: 0.4, roughness: 0.3 }), 0, 0.03, 0, g); return g; };
  const R = []; const mkRider = (i) => { const r = { i, d: 0, s: (i ? 3 : -3), v: 0, air: 0, airV: 0, spin: 0, flip: 0, score: 0, gatesHit: 0, done: false, g: mkBoard(i ? 0xff4f79 : 0x38f0ff), yaw: 0 }; if (i) { const body = cyl(0.25, 0.3, 1.1, M(0xff4f79), 0, 0.85, 0, r.g, 8); sph(0.22, M(0xf1c27d), 0, 1.6, 0, r.g, 10); const hm = sph(0.24, M(0xff4f79), 0, 1.68, 0, r.g, 10); } S.add(r.g); return r; };
  const keys = new Set(); addEventListener('keydown', (e) => { if (!SB.on) return; keys.add(e.key.toLowerCase()); if (e.code === 'Space') { e.preventDefault(); jump(R[0]); } if (e.key === 'Enter' && R[1]) { e.preventDefault(); jump(R[1]); } if (e.key.toLowerCase() === 'q') off(); }); addEventListener('keyup', (e) => keys.delete(e.key.toLowerCase()));
  const hud = document.createElement('div'); hud.style.cssText = 'position:absolute;left:50%;bottom:150px;transform:translateX(-50%);z-index:40;display:none;gap:8px;flex-wrap:wrap;justify-content:center;font-family:Poppins,Arial'; hud.innerHTML = ['⬅', '➡', '🪂 JUMP', '🌀 Flip', '🛑 Quit'].map((t, i) => `<button data-sb="${i}" style="border:0;border-radius:14px;padding:12px 16px;font:900 15px Poppins,Arial;background:${i === 2 ? '#ff4f79' : i === 4 ? '#64748b' : '#0e7490'};color:#fff;touch-action:none">${t}</button>`).join('') + `<div id="sb-score" style="width:100%;text-align:center;color:#fff;font:900 16px Poppins,Arial;text-shadow:0 2px 8px #000"></div>`; document.body.appendChild(hud); let steer = 0; hud.addEventListener('pointerdown', (e) => { const b = e.target.closest('[data-sb]'); if (!b) return; const i = +b.dataset.sb; if (i === 0) steer = -1; if (i === 1) steer = 1; if (i === 2) jump(R[0]); if (i === 3) flip(R[0]); if (i === 4) off(); }); addEventListener('pointerup', () => { steer = 0; });
  const SB = { on: false, two: false, t0: 0 }; const jump = (r) => { if (!r || r.air > 0 || r.done) return; r.airV = 9 + r.v * 0.25; r.air = 0.01; app.buzz && app.buzz(25); }; const flip = (r) => { if (!r || r.air <= 0.3 || r.flip > 0) { if (r && r.air <= 0.3) toast('🌀 Flips need air. Jump first (or hit a kicker).', 1200); return; } r.flip = 6.283; r.score += 250; };
  const start = (two) => { if (SB.on || app.ride) return; SB.on = true; SB.two = !!two; SB.t0 = app.t; R.length = 0; R.push(mkRider(0)); if (two) R.push(mkRider(1)); R.forEach(r => { r.d = 0; r.v = 0; r.score = 0; r.gatesHit = 0; r.done = false; }); hud.style.display = 'flex'; app.seatClip && app.seatClip(R[0].g, 0.9, { tilt: true }); app.targetDist = Math.max(app.targetDist, 9); app.pitch = -0.12; toast(two ? '🏂 TWO PLAYER. P1: A/D steer, Space jump, F flip. P2 (red): ← → steer, Enter jump, / flip. Gates = points. Q quits.' : '🏂 A/D (or ◀ ▶) to steer, Space or 🪂 to jump, F or 🌀 to flip in the air. Hit the gates. Kickers launch you.', 7000);
    app.ride = { pos: () => { const dt = Math.min(0.05, app._sbDt || 0.016); const PR = R[0]; R.forEach((r, i) => { if (r.done) return; const st = i === 0 ? (steer || (keys.has('a') ? -1 : keys.has('d') ? 1 : 0)) : (keys.has('arrowleft') ? -1 : keys.has('arrowright') ? 1 : 0); if (i === 0 && keys.has('f')) flip(r); if (i === 1 && keys.has('/')) flip(r); const slope = Math.max(0.06, (surfY(START.x + dir.x * r.d, START.z + dir.z * r.d) - surfY(START.x + dir.x * (r.d + 4), START.z + dir.z * (r.d + 4))) / 4); r.v = Math.min(26, r.v + (slope * 14 - r.v * 0.08 - Math.abs(st) * 1.2) * dt); r.d += r.v * dt; r.s = Math.max(-half + 1, Math.min(half - 1, r.s + st * dt * (4 + r.v * 0.25))); r.yaw += (st * 0.5 - r.yaw) * Math.min(1, dt * 6); if (r.air > 0 || r.airV > 0) { r.airV -= 22 * dt; r.air = Math.max(0, r.air + r.airV * dt); if (r.air === 0 && r.airV < 0) { r.airV = 0; if (r.flip > 0.8) { r.score -= 100; toast(i ? '🔴 P2 face plant!' : '🤕 Face plant! Land the flip next time.', 1200); r.v *= 0.4; } r.flip = 0; app.buzz && app.buzz(15); } } if (r.flip > 0) { const k = Math.min(r.flip, dt * 7); r.g.rotation.x -= k; r.flip -= k; if (r.flip <= 0) { r.g.rotation.x = 0; r.score += 250; toast(i ? '🔴 P2 FLIP!' : '🌀 FLIP! +250', 900); } } for (const kd of kickers) { if (Math.abs(r.d - kd) < 1.5 && r.air === 0 && r.v > 6 && !r._k) { r._k = kd; r.airV = 10 + r.v * 0.35; r.air = 0.01; toast(i ? '🔴 P2 launches!' : '🪂 KICKER! Flip now!', 900); } } if (r._k && Math.abs(r.d - r._k) > 4) r._k = 0; for (const gt of gates) { if (!gt['hit' + i] && r.d >= gt.d) { gt['hit' + i] = true; if (Math.abs(r.s - gt.s) < 2.6) { r.gatesHit++; r.score += 100; if (i === 0) app.celebrate && app.celebrate('🚩'); } } } const c = START.clone().addScaledVector(dir, r.d); const px = c.x + side.x * r.s, pz = c.z + side.z * r.s; const py = surfY(px, pz) + r.air; r.g.position.set(px, py, pz); r.g.rotation.y = Math.atan2(dir.x, dir.z) + r.yaw + (r.flip > 0 ? 0 : 0); r.g.rotation.z = -st * 0.4; if (r.d >= LEN && !r.done) { r.done = true; const secs = Math.round((app.t - SB.t0) * 10) / 10; const bonus = Math.max(0, 600 - Math.round(secs * 10)); r.score += bonus; toast(`${i ? '🔴 P2' : '🏁 You'} finished: ${secs}s · ${r.gatesHit}/${gates.length} gates · score ${r.score}`, 6000); if (i === 0) { try { const best = +localStorage.getItem('aou_sb_best') || 0; if (r.score > best) { localStorage.setItem('aou_sb_best', String(r.score)); toast('🏆 New personal best!', 3000); } } catch (e) { } app.celebrate && app.celebrate('🏂'); } } }); const sc = document.getElementById('sb-score'); if (sc) sc.textContent = `P1 ${PR.score} · ${Math.round(PR.v * 2.2)} mph · gates ${PR.gatesHit}/${gates.length}` + (R[1] ? ` | P2 ${R[1].score}` : '') + (PR.done ? ' · done (🛑 to exit)' : ''); if (R.every(r => r.done)) { setTimeout(off, 2500); } return new T.Vector3(PR.g.position.x, PR.g.position.y + 0.95, PR.g.position.z); }, yaw: Math.atan2(dir.x, dir.z), stand: false }; };
  const off = () => { if (!SB.on) return; SB.on = false; app.ride = null; app.seatClear && app.seatClear(); hud.style.display = 'none'; const r = R[0]; if (r) { app.player.position.set(r.g.position.x + 2, terrainY(r.g.position.x + 2, r.g.position.z), r.g.position.z); } R.forEach(x => S.remove(x.g)); R.length = 0; };
  app.onUpdate((dt) => { app._sbDt = dt; });
  app.addInteractable && app.addInteractable(START.x, START.z + 3, 4, '🏂 Snowboard run: 1 player', () => start(false)); app.addInteractable && app.addInteractable(START.x + 4, START.z + 3, 4, '🏂🏂 Snowboard run: 2 players (one keyboard)', () => start(true)); app.addPlace && app.addPlace({ id: 'snowboard', name: '🏂 Snowboard run · steer, jump, flip, 2P', icon: '🏂', x: START.x, z: START.z + 4, cat: 'Fun', keys: 'snowboard ski run mountain jump flip two player game', say: 'Top of the run. Pick 1 or 2 players and drop in.' });
}
