/* 🐕 JAMOKE · Zach's gray-and-white dog. Lives at No. 1 Unity Road. Pet him, call him, pick him up, play fetch.
   He wags, licks, slobbers, sits, barks, and follows you around the property. Plus: the cherry-red lifted 4x4
   with spinning rims and fog lights, the jet ski in the bed (tilt, slide, ride), and five jet skis at the lake. */
import { THREE, makeSprite, isMobile } from './aou-engine.js';
import { M, glow, box, cyl, sph } from './aou-kit.js';
import { terrainY } from './aou-terrain.js';
const T = THREE; const MOB = isMobile();
export function buildJamoke(app, W, X, Z) {
  const S = app.scene; const toast = (m, ms) => app.toast(m, ms); const gy = (x, z) => terrainY(x, z);
  const HX = X - 30, HZ = Z + 18; const dog = new T.Group(); dog.position.set(HX, gy(HX, HZ), HZ); S.add(dog);
  const grey = M(0x9aa0a8, { roughness: 0.9 }), white = M(0xf3f4f6, { roughness: 0.9 }), pink = M(0xff8fb1), black = M(0x111111, { roughness: 0.3 });
  const body = sph(0.32, grey, 0, 0.52, 0, dog, 14); body.scale.set(0.8, 0.75, 1.5); const chest = sph(0.2, white, 0, 0.42, 0.3, dog, 10); chest.scale.set(0.9, 0.9, 1.2); const headG = new T.Group(); headG.position.set(0, 0.78, 0.5); dog.add(headG); sph(0.22, grey, 0, 0, 0, headG, 14); const muzzle = sph(0.12, white, 0, -0.06, 0.2, headG, 10); muzzle.scale.set(1, 0.8, 1.2); sph(0.05, black, 0, -0.02, 0.33, headG, 8); for (const sx of [-1, 1]) { sph(0.035, black, sx * 0.09, 0.06, 0.19, headG, 6); const ear = sph(0.09, grey, sx * 0.19, 0.16, -0.02, headG, 8); ear.scale.set(0.6, 1.2, 0.5); ear.rotation.z = sx * -0.5; } const tongue = box(0.06, 0.02, 0.16, pink, 0, -0.14, 0.3, headG); tongue.visible = false; const collar = cyl(0.21, 0.21, 0.05, M(0xff4f79), 0, -0.2, 0, headG, 12); const tag = makeSprite('JAMOKE', { scale: 0.9, accent: '#ffd23f' }); tag.position.set(0, -0.3, 0.2); headG.add(tag);
  const legs = []; for (const [x, z] of [[-0.14, 0.3], [0.14, 0.3], [-0.14, -0.3], [0.14, -0.3]]) { const l = cyl(0.06, 0.05, 0.4, z > 0 ? white : grey, x, 0.2, z, dog, 6); legs.push(l); } const tail = new T.Group(); tail.position.set(0, 0.6, -0.5); dog.add(tail); const tl = cyl(0.04, 0.02, 0.4, grey, 0, 0.15, -0.1, tail, 6); tl.rotation.x = 0.9;
  const drops = []; const nm = makeSprite('🐕 Jamoke · tap to pet · call · fetch', { scale: 2.6, accent: '#ffd23f' }); nm.position.set(0, 1.6, 0); dog.add(nm);
  const D = { mode: 'idle', t0: 0, wag: 0, target: null, held: false, ball: null, happy: 0, bark: 0 }; const face = () => { const P = app.player.position; dog.rotation.y = Math.atan2(P.x - dog.position.x, P.z - dog.position.z); };
  const woof = () => { try { const AC = window.AudioContext || window.webkitAudioContext; const ac = new AC(); const o = ac.createOscillator(), g = ac.createGain(); o.type = 'sawtooth'; o.frequency.setValueAtTime(240, ac.currentTime); o.frequency.exponentialRampToValueAtTime(120, ac.currentTime + 0.12); g.gain.setValueAtTime(0.15, ac.currentTime); g.gain.exponentialRampToValueAtTime(0.001, ac.currentTime + 0.18); o.connect(g); g.connect(ac.destination); o.start(); o.stop(ac.currentTime + 0.2); setTimeout(() => ac.close(), 400); } catch (e) { } };
  const pet = () => { D.happy = 4; D.mode = 'pet'; D.t0 = app.t; tongue.visible = true; face(); toast(['🐕 Jamoke rolls over. Belly rubs accepted.', '🐕 Tail going nuts. He loves you.', '🐕 SLOBBER. You have been licked.', '🐕 Happy wiggles. Good boy Jamoke.'][Math.floor(Math.random() * 4)], 2500); app.celebrate && app.celebrate('🐾'); for (let i = 0; i < 6; i++) { const d = sph(0.03, new T.MeshStandardMaterial({ color: 0xbfefff, transparent: true, opacity: 0.8 }), 0, 0, 0, S, 6); d.position.copy(dog.position).add(new T.Vector3((Math.random() - 0.5) * 0.3, 0.8, 0.6)); d.userData.v = new T.Vector3((Math.random() - 0.5) * 1.5, 1.5 + Math.random(), 0.5 + Math.random()); d.userData.t = 0; drops.push(d); } };
  const call = () => { D.mode = D.mode === 'follow' ? 'home' : 'follow'; woof(); toast(D.mode === 'follow' ? '🐕 Jamoke is coming with you! (call again to send him home)' : '🐕 Jamoke heads home.', 2500); };
  const fetch = () => { if (D.ball) return; const P = app.player.position; const b = sph(0.12, M(0xffd23f, { roughness: 0.4 }), 0, 0, 0, S, 10); b.position.copy(P).add(new T.Vector3(0, 1.2, 0)); const dir = new T.Vector3(-Math.sin(app.yaw), 0, -Math.cos(app.yaw)); b.userData.v = dir.multiplyScalar(11).add(new T.Vector3(0, 6, 0)); b.userData.t = 0; S.add(b); D.ball = b; D.mode = 'fetch'; woof(); toast('🎾 Fetch!', 1200); };
  const hold = () => { D.held = !D.held; if (D.held) { D.mode = 'held'; toast('🐕 You picked up Jamoke. He is heavier than he looks. Tap again to put him down.', 3000); } else { D.mode = 'follow'; dog.position.copy(app.player.position).add(new T.Vector3(0.8, 0, 0.8)); dog.position.y = gy(dog.position.x, dog.position.z); toast('🐕 Down he goes. Zoomies incoming.', 2000); } };
  app.addHotspot && app.addHotspot(dog, { title: '🐕 Jamoke', html: '<p>Zach\'s dog. Gray and white, zero chill, all love. Lives at No. 1 Unity Road.</p>', actions: [{ label: '🖐️ Pet him', fn: pet }, { label: '📣 Call him / send home', fn: call }, { label: '🎾 Play fetch', fn: fetch }, { label: '🫳 Pick up / put down', fn: hold }] });
  app.addInteractable && app.addInteractable(HX, HZ + 2, 3.2, '🐕 Jamoke: pet, call, fetch', () => { pet(); });
  app.addPlace && app.addPlace({ id: 'jamoke', name: '🐕 Jamoke · Zach\'s dog', icon: '🐕', x: HX, z: HZ + 3, cat: 'Fun', keys: 'dog jamoke pet fetch puppy', say: 'Tap him. He will do the rest.' });
  app.onUpdate((dt, t) => { const P = app.player.position; const d = Math.hypot(P.x - dog.position.x, P.z - dog.position.z); if (d > 200 && D.mode !== 'follow' && !D.held) return;
    D.wag = D.happy > 0 || D.mode === 'follow' || d < 4 ? 1 : 0.3; tail.rotation.y = Math.sin(t * (D.wag > 0.5 ? 18 : 4)) * 0.8 * D.wag; if (D.happy > 0) { D.happy -= dt; headG.rotation.z = Math.sin(t * 9) * 0.25; dog.position.y = gy(dog.position.x, dog.position.z) + Math.abs(Math.sin(t * 10)) * 0.08; if (D.happy <= 0) { tongue.visible = false; headG.rotation.z = 0; } }
    for (const dr of drops) { dr.userData.t += dt; dr.userData.v.y -= 9.8 * dt; dr.position.addScaledVector(dr.userData.v, dt); if (dr.userData.t > 1) S.remove(dr); } for (let i = drops.length - 1; i >= 0; i--) if (drops[i].userData.t > 1) drops.splice(i, 1);
    if (D.held) { dog.position.copy(P).add(new T.Vector3(-Math.sin(app.yaw) * 0.5, 1.0, -Math.cos(app.yaw) * 0.5)); dog.rotation.y = app.yaw + Math.PI; headG.rotation.z = Math.sin(t * 6) * 0.15; return; }
    let goal = null; if (D.mode === 'follow' && d > 2.4) goal = P; if (D.mode === 'home') { goal = new T.Vector3(HX, 0, HZ); if (Math.hypot(HX - dog.position.x, HZ - dog.position.z) < 1) D.mode = 'idle'; }
    if (D.mode === 'fetch' && D.ball) { const b = D.ball; if (!b.userData.rest) { b.userData.v.y -= 9.8 * dt; b.position.addScaledVector(b.userData.v, dt); const g0 = gy(b.position.x, b.position.z) + 0.12; if (b.position.y < g0) { b.position.y = g0; b.userData.v.y *= -0.45; b.userData.v.x *= 0.7; b.userData.v.z *= 0.7; if (Math.abs(b.userData.v.y) < 0.5) b.userData.rest = true; } } const db = Math.hypot(b.position.x - dog.position.x, b.position.z - dog.position.z); if (!b.userData.got) { goal = b.position; if (db < 0.8 && b.userData.rest) { b.userData.got = true; toast('🐕 Got it! Bringing it back.', 1200); } } else { b.position.copy(dog.position).add(new T.Vector3(0, 0.6, 0.6)); goal = P; if (d < 1.6) { S.remove(b); D.ball = null; D.mode = 'follow'; D.happy = 3; tongue.visible = true; toast('🐕 Jamoke drops it at your feet. Again? (He says again.)', 2500); app.celebate && app.celebrate('🎾'); } } }
    if (goal) { const dx = goal.x - dog.position.x, dz = goal.z - dog.position.z, dist = Math.hypot(dx, dz); if (dist > 0.6) { const sp = Math.min(dist, 6.5 * dt); dog.position.x += dx / dist * sp; dog.position.z += dz / dist * sp; dog.rotation.y = Math.atan2(dx, dz); legs.forEach((l, i) => l.rotation.x = Math.sin(t * 16 + i * 1.57) * 0.7); dog.position.y = gy(dog.position.x, dog.position.z) + Math.abs(Math.sin(t * 16)) * 0.06; } else legs.forEach(l => l.rotation.x = 0); } else if (d < 6) { face(); legs.forEach(l => l.rotation.x = 0); if (D.happy <= 0) dog.position.y = gy(dog.position.x, dog.position.z); if (Math.random() < dt * 0.08) { woof(); } } });
  /* ---- the cherry-red lifted 4x4 + jet ski in the bed; five jet skis at the lake ---- */
  const TX = X - 34, TZ = Z + 28; const truck = new T.Group(); truck.position.set(TX, gy(TX, TZ) + 1.1, TZ); truck.rotation.y = 0.4; S.add(truck); const red = new T.MeshStandardMaterial({ color: 0xd1001c, metalness: 0.75, roughness: 0.2 }); const chrome = M(0xe6edf7, { metalness: 1, roughness: 0.08 }); const dark = M(0x111318, { roughness: 0.5 });
  box(2.4, 0.5, 5.6, dark, 0, 0.3, 0, truck); box(2.5, 0.9, 2.6, red, 0, 1.0, 1.3, truck); box(2.3, 0.85, 1.9, new T.MeshPhysicalMaterial({ color: 0x1b2a4a, metalness: 0.4, roughness: 0.1, transparent: true, opacity: 0.85 }), 0, 1.85, 1.0, truck); box(2.5, 0.6, 2.9, red, 0, 0.85, -1.4, truck); for (const sx of [-1.1, 1.1]) box(0.3, 0.6, 2.9, red, sx, 1.15, -1.4, truck); box(2.5, 0.2, 0.2, chrome, 0, 0.75, 2.7, truck); for (const sx of [-0.8, 0.8]) { const fog = sph(0.14, glow(0xfff3b0, 2.2), sx, 0.95, 2.78, truck, 10); cyl(0.07, 0.07, 0.2, chrome, sx * 0.5, 2.35, 1.6, truck, 8); sph(0.1, glow(0xffffff, 2), sx * 0.5, 2.38, 1.75, truck, 8); } box(2.0, 0.08, 0.5, chrome, 0, 2.3, 1.7, truck);
  const wheels = []; for (const [x, z] of [[-1.35, 1.8], [1.35, 1.8], [-1.35, -1.8], [1.35, -1.8]]) { const sp = cyl(0.14, 0.14, 1.0, chrome, x, 0.0, z, truck, 10); sp.rotation.z = Math.PI / 2; sp.position.y = 0.2; for (let k = 0; k < 4; k++) { const c = cyl(0.12, 0.16, 0.5, chrome, x, 0.2 + Math.sin(k * 1.57) * 0.55, z + Math.cos(k * 1.57) * 0.55, truck, 8); c.rotation.z = Math.PI / 2; } const tire = new T.Mesh(new T.TorusGeometry(0.62, 0.3, 10, 24), dark); tire.rotation.y = Math.PI / 2; tire.position.set(x, 0.2, z); truck.add(tire); const rim = new T.Mesh(new T.TorusGeometry(0.42, 0.08, 8, 24), chrome); rim.rotation.y = Math.PI / 2; rim.position.set(x, 0.2, z); truck.add(rim); const spokes = new T.Group(); spokes.position.set(x, 0.2, z); for (let k = 0; k < 6; k++) { const s2 = box(0.08, 0.7, 0.08, chrome, 0, 0, 0, spokes); s2.rotation.x = k * Math.PI / 3; } truck.add(spokes); wheels.push({ spokes, rim }); const spring = new T.Mesh(new T.TorusKnotGeometry(0.18, 0.05, 40, 8, 1, 7), chrome); spring.position.set(x * 0.7, 0.45, z); spring.scale.set(1, 1.6, 1); truck.add(spring); }
  const sign = makeSprite("🛻 ZACH'S 4x4 · jet ski in the bed · tap to tilt + slide", { scale: 4, accent: '#ff4f79' }); sign.position.set(0, 4.2, 0); truck.add(sign); app.addObstacle && app.addObstacle(TX, TZ, 3.4);
  const mkJetski = (col) => { const j = new T.Group(); const hull = new T.Mesh(new T.CapsuleGeometry(0.42, 1.6, 6, 12), new T.MeshStandardMaterial({ color: col, metalness: 0.5, roughness: 0.25 })); hull.rotation.x = Math.PI / 2; hull.scale.set(1, 0.6, 1); hull.position.y = 0.3; j.add(hull); box(0.5, 0.25, 0.9, dark, 0, 0.62, -0.2, j); const bars = cyl(0.03, 0.03, 0.7, chrome, 0, 0.85, 0.55, j, 6); bars.rotation.z = Math.PI / 2; cyl(0.04, 0.04, 0.5, chrome, 0, 0.7, 0.55, j, 6); box(0.3, 0.1, 0.5, glow(0x38f0ff, 1.4), 0, 0.42, 1.1, j); return j; };
  const bedSki = mkJetski(0x38f0ff); bedSki.position.set(0, 1.25, -1.4); bedSki.scale.setScalar(0.85); truck.add(bedSki); let tilt = 0, tiltOn = false; const tiltIt = () => { tiltOn = !tiltOn; toast(tiltOn ? '🛻 Bed tilting… jet ski sliding out. Take it to the lake!' : '🛻 Bed back down.', 2500); };
  app.addInteractable && app.addInteractable(TX, TZ + 3.8, 3.2, '🛻 Tilt the bed (jet ski slides out)', tiltIt); app.addHotspot && app.addHotspot(truck, { fn: tiltIt });
  const LAKE = { x: X + 86 - 20, z: Z + 12 + 44 }; const skis = []; for (let i = 0; i < 5; i++) { const j = mkJetski([0xff4f79, 0xffd23f, 0x7cff6b, 0xb388ff, 0xff8a3d][i]); const sx = LAKE.x + i * 3.2 - 6, sz = LAKE.z + 2; j.position.set(sx, gy(sx, sz) + 0.3, sz); j.rotation.y = Math.PI; S.add(j); skis.push(j); app.addInteractable && app.addInteractable(sx, sz, 2.2, '🚤 Ride jet ski #' + (i + 1), () => ride(j)); app.addHotspot && app.addHotspot(j, { fn: () => ride(j) }); }
  const rsg = makeSprite('🚤 JET SKIS · anyone can ride · spin, jump, flip', { scale: 4.2, accent: '#38f0ff' }); rsg.position.set(LAKE.x, gy(LAKE.x, LAKE.z) + 4, LAKE.z + 2); S.add(rsg);
  const JS = { on: false, j: null, v: 0, yaw: 0, air: 0, airV: 0, spin: 0, flip: 0, tricks: 0 }; const keys = new Set(); addEventListener('keydown', (e) => { if (JS.on) keys.add(e.key.toLowerCase()); if (JS.on && e.code === 'Space') { e.preventDefault(); jump(); } }); addEventListener('keyup', (e) => keys.delete(e.key.toLowerCase()));
  const hud = document.createElement('div'); hud.style.cssText = 'position:absolute;left:50%;bottom:150px;transform:translateX(-50%);z-index:40;display:none;gap:8px;flex-wrap:wrap;justify-content:center;font-family:Poppins,Arial'; hud.innerHTML = ['⬅ Left', '➡ Right', '⚡ Gas', '🪂 JUMP 20 ft', '🌀 Spin out', '🤸 Flip', '🛑 Off'].map((t, i) => `<button data-js="${i}" style="border:0;border-radius:14px;padding:10px 12px;font:900 13px Poppins,Arial;background:${i === 3 ? '#ff4f79' : i === 6 ? '#64748b' : '#0e7490'};color:#fff;touch-action:none">${t}</button>`).join(''); (document.getElementById('wvm-hud') || document.body).appendChild(hud); let steer = 0, gas = 0; hud.addEventListener('pointerdown', (e) => { const b = e.target.closest('[data-js]'); if (!b) return; const i = +b.dataset.js; if (i === 0) steer = -1; if (i === 1) steer = 1; if (i === 2) gas = 1; if (i === 3) jump(); if (i === 4) { JS.spin = 6.28 * 2; JS.tricks++; } if (i === 5) { if (JS.air > 0.5) { JS.flip = 6.28; JS.tricks += 2; } else toast('🤸 Flips need air. Jump first!', 1200); } if (i === 6) off(); }); addEventListener('pointerup', () => { steer = 0; gas = 0; });
  const wake = []; const jump = () => { if (!JS.on || JS.air > 0) return; JS.airV = 14; JS.air = 0.01; toast('🪂 AIR!', 700); app.buzz && app.buzz(40); };
  const ride = (j) => { if (JS.on || app.ride) return; JS.on = true; JS.j = j; JS.v = 0; JS.yaw = j.rotation.y; app.seatClip && app.seatClip(j, 0.75, { tilt: true }); hud.style.display = 'flex'; app.targetDist = Math.max(app.targetDist, 7); toast('🚤 A/D or ◀ ▶ to steer, W or ⚡ for gas, Space or 🪂 to JUMP, 🌀 spin, 🤸 flip in the air. Make waves.', 6000); const prev = app.ride; app.ride = { pos: () => { const dt = Math.min(0.05, app._skiDt || 0.016); const s = steer || (keys.has('a') || keys.has('arrowleft') ? -1 : keys.has('d') || keys.has('arrowright') ? 1 : 0); const g = gas || (keys.has('w') || keys.has('arrowup') ? 1 : 0); JS.v = Math.max(0, Math.min(18, JS.v + (g ? 9 : -5) * dt)); JS.yaw -= s * dt * (1.2 + JS.v * 0.06); if (JS.spin > 0) { const d = Math.min(JS.spin, dt * 9); JS.yaw += d; JS.spin -= d; } const nx = j.position.x - Math.sin(JS.yaw) * JS.v * dt, nz = j.position.z - Math.cos(JS.yaw) * JS.v * dt; const inWater = app._waterAt && app._waterAt(nx, nz) !== null; if (inWater || JS.air > 0) { j.position.x = nx; j.position.z = nz; } else { JS.v *= 0.3; } if (JS.air > 0 || JS.airV > 0) { JS.airV -= 24 * dt; JS.air = Math.max(0, JS.air + JS.airV * dt); if (JS.air === 0 && JS.airV < 0) { JS.airV = 0; splash(j.position, 2); app.buzz && app.buzz(60); if (JS.flip > 0.3) { toast('🤸 Not quite! Belly flop.', 1200); } JS.flip = 0; } } if (JS.flip > 0) { const d = Math.min(JS.flip, dt * 7); j.rotation.x -= d; JS.flip -= d; if (JS.flip <= 0) { j.rotation.x = 0; toast('🤸 FLIP! +2 tricks', 1200); app.celebrate && app.celebrate('🤸'); } } else j.rotation.x = -JS.v * 0.02 + (JS.airV > 0 ? -0.3 : 0); const wy = (app._waterAt && app._waterAt(j.position.x, j.position.z)) ?? gy(j.position.x, j.position.z); j.position.y = (wy !== null ? wy : gy(j.position.x, j.position.z)) + 0.1 + JS.air + Math.sin(app.t * 6) * 0.05 * (JS.v / 18); j.rotation.y = JS.yaw; j.rotation.z = -s * 0.35; if (JS.v > 4 && JS.air === 0 && Math.random() < dt * 20) splash(j.position, 0.4); app.ride.yaw = JS.yaw; return new T.Vector3(j.position.x, j.position.y + 0.45, j.position.z); }, yaw: JS.yaw, stand: false }; };
  const off = () => { if (!JS.on) return; JS.on = false; app.ride = null; app.seatClear && app.seatClear(); hud.style.display = 'none'; const j = JS.j; const P = app.player.position; P.set(j.position.x + 1.5, gy(j.position.x + 1.5, j.position.z), j.position.z); toast('🚤 Off the ski. ' + JS.tricks + ' tricks this ride.', 2500); JS.tricks = 0; };
  const splash = (p, k) => { for (let i = 0; i < (MOB ? 4 : 8) * k; i++) { const d = sph(0.06 + Math.random() * 0.08 * k, new T.MeshStandardMaterial({ color: 0xcfefff, transparent: true, opacity: 0.85 }), 0, 0, 0, S, 6); d.position.copy(p).add(new T.Vector3((Math.random() - 0.5) * 1.2, 0.1, (Math.random() - 0.5) * 1.2)); d.userData.v = new T.Vector3((Math.random() - 0.5) * 3 * k, 2 + Math.random() * 3 * k, (Math.random() - 0.5) * 3 * k); d.userData.t = 0; wake.push(d); } };
  app.onUpdate((dt, t) => { app._skiDt = dt; for (const w of wheels) { if (Math.hypot(app.player.position.x - TX, app.player.position.z - TZ) < 60) w.spokes.rotation.x += dt * 2.2; } const want = tiltOn ? 0.55 : 0; tilt += (want - tilt) * Math.min(1, dt * 2); truck.children.forEach(c => { if (c === bedSki) { c.rotation.x = tilt; c.position.z = -1.4 - tilt * 3.2; c.position.y = 1.25 - tilt * 1.2; } }); for (const d of wake) { d.userData.t += dt; d.userData.v.y -= 9.8 * dt; d.position.addScaledVector(d.userData.v, dt); d.material.opacity = Math.max(0, 0.85 - d.userData.t); if (d.userData.t > 1) S.remove(d); } for (let i = wake.length - 1; i >= 0; i--) if (wake[i].userData.t > 1) wake.splice(i, 1); });
  // palm tree out front
  const PX = X - 30, PZ = Z - 14; const palm = new T.Group(); palm.position.set(PX, gy(PX, PZ), PZ); S.add(palm); const trunkPts = []; for (let i = 0; i <= 8; i++) trunkPts.push(new T.Vector3(Math.sin(i * 0.3) * 0.6, i * 1.1, 0)); const trunk = new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(trunkPts), 16, 0.28, 8, false), M(0x8a6a3c, { roughness: 1 })); palm.add(trunk); for (let i = 0; i < 9; i++) { const a = i / 9 * 6.283; const frond = new T.Mesh(new T.PlaneGeometry(0.7, 4.2, 1, 6), M(0x2f8f3a, { side: T.DoubleSide, roughness: 0.9 })); frond.position.set(Math.sin(8 * 0.3) * 0.6 + Math.cos(a) * 1.2, 8.8 + Math.sin(i) * 0.3, Math.sin(a) * 1.2); frond.rotation.set(0.9 * Math.cos(a), -a, 0.9 * Math.sin(a)); frond.rotation.order = 'YXZ'; frond.rotation.y = -a; frond.rotation.x = 1.1; frond.userData.a = a; palm.add(frond); } for (let i = 0; i < 4; i++) sph(0.18, M(0x6b4a2a), Math.sin(8 * 0.3) * 0.6 + Math.cos(i * 1.6) * 0.4, 8.5, Math.sin(i * 1.6) * 0.4, palm, 8); app.addObstacle && app.addObstacle(PX, PZ, 0.7); app.onUpdate((dt, t) => { palm.children.forEach(c => { if (c.userData.a !== undefined) c.rotation.z = Math.sin(t * 1.5 + c.userData.a) * 0.08; }); });
  return { pet, call, fetch, hold };
}
